Repository hengband/hengband, pull requests merged in 2021-11, with the labels that each got.

#1848 [Refactor] spell_type 列挙体に enum をつけ SpellProcessType に改名
  src/cmd-action/cmd-hissatsu.cpp
  src/cmd-action/cmd-spell.cpp
  src/io-dump/special-class-dump.cpp
  src/knowledge/knowledge-experiences.cpp
  src/player/player-status.cpp
  src/realm/realm-arcane.cpp
  src/realm/realm-arcane.h
  src/realm/realm-chaos.cpp
  src/realm/realm-chaos.h
  src/realm/realm-craft.cpp
  src/realm/realm-craft.h
  src/realm/realm-crusade.cpp
  src/realm/realm-crusade.h
  src/realm/realm-death.cpp
  src/realm/realm-death.h
  src/realm/realm-demon.cpp
  src/realm/realm-demon.h
  src/realm/realm-hex.cpp
  src/realm/realm-hex.h
  src/realm/realm-hissatsu.cpp
  src/realm/realm-hissatsu.h
  src/realm/realm-life.cpp
  src/realm/realm-life.h
  src/realm/realm-nature.cpp
  src/realm/realm-nature.h
  src/realm/realm-song.cpp
  src/realm/realm-song.h
  src/realm/realm-sorcery.cpp
  src/realm/realm-sorcery.h
  src/realm/realm-trump.cpp
  src/realm/realm-trump.h
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-song.cpp
  src/spell/spell-info.cpp
  src/spell/spells-execution.cpp
  src/spell/spells-execution.h
  src/spell/spells-util.h
  src/window/display-sub-window-spells.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor

#1849 [Feature] 継続自傷ダメージ装備の導入
  lib/edit/a_info.txt
  src/flavor/flag-inscriptions-table.cpp
  src/hpmp/hp-mp-processor.cpp
  src/info-reader/kind-info-tokens-table.cpp
  src/object-enchant/smith-tables.cpp
  src/object-enchant/tr-types.h
  src/perception/identification.cpp
  src/player-info/body-improvement-info.cpp
  src/player/player-status-flags.cpp
  src/view/display-characteristic.cpp
Labels: enhancement

#1855 [Feature] MonsterDamageProseccorに複合属性渡しを許可する
  src/combat/shoot.cpp
  src/combat/slaying.cpp
  src/combat/slaying.h
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-death.h
  src/monster-floor/special-death-switcher.cpp
  src/monster-floor/special-death-switcher.h
  src/monster/monster-damage.cpp
  src/monster/monster-damage.h
  src/object-use/throw-execution.cpp
  src/player-attack/player-attack-util.h
  src/player-attack/player-attack.cpp
  src/spell/spell-types.h
Labels: enhancement

#1857 [Implement] 『手負いの熊』に適用された生成時初期HPを CURHP_* フラグで％指定できるように汎用化。
  lib/edit/r_info.txt
  src/info-reader/race-reader.cpp
  src/monster-floor/one-monster-placer.cpp
  src/system/monster-race-definition.h
Labels: enhancement

#1863 [Fix} 誰得の巻物で固定アーティファクトが生成されない
  src/spell/spells-object.cpp
Labels: enhancement

#1865 [Release] 3.0.0Alpha46
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: enhancement

#1875 [Fix] 自傷フラグの自動生成スポイラー対応
  src/wizard/spoiler-table.cpp
  src/wizard/spoiler-table.h
Labels: bug, enhancement

#1876 [Add] ランダム発動に加速(50+d50)を追加。
  src/artifact/random-art-effects.h
  src/object-activation/activation-switcher.cpp
  src/object-enchant/activation-info-table.cpp
  src/object-enchant/object-boost.cpp
Labels: enhancement

#1878 発動追加：ヒーロー＋祝福 #1693 d25+25で追加する
  src/artifact/random-art-effects.h
  src/object-activation/activation-switcher.cpp
  src/object-enchant/activation-info-table.cpp
Labels: enhancement

#1877 改めて★ダイアナの長弓の追加
  lib/edit/a_info.txt
  src/artifact/random-art-effects.h
  src/object-activation/activation-others.cpp
  src/object-activation/activation-others.h
  src/object-activation/activation-switcher.cpp
  src/object-enchant/activation-info-table.cpp
Labels: enhancement

#1872 [Refactor] モンスター闘技場のモンスター種族評価値を calc_monrace_power() に分離して、monster-race.cpp/h へ移動。
  src/market/arena.cpp
  src/monster-race/monster-race.cpp
  src/monster-race/monster-race.h
Labels: refactor

#1873 [Implement] 執拗な呪いの実装
  src/cmd-item/cmd-equipment.cpp
  src/info-reader/kind-info-tokens-table.cpp
  src/inventory/inventory-curse.cpp
  src/mind/mind-priest.cpp
  src/object-enchant/smith-tables.cpp
  src/object-enchant/tr-types.h
  src/object-enchant/trc-types.h
  src/object/object-value-calc.cpp
  src/perception/identification.cpp
  src/player/player-status-flags.cpp
  src/view/display-characteristic.cpp
  src/wizard/spoiler-table.cpp
  src/wizard/spoiler-table.h
Labels: enhancement

#1874 謎の*勝利*タイトル条件の削除と、真*勝利者*の条件を PlayerType のメソッド化。
  src/player/process-death.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/window/main-window-left-frame.cpp
Labels: enhancement

#1885 [Fix] 地震による落盤で死ぬと死因が0feetになる #1883
  src/spell-kind/earthquake.cpp
Labels: bug

#1881 ★ダイアナの長弓の調整
  lib/edit/a_info.txt
Labels: enhancement

#1884 [Implement] 呪力弱点の導入
  src/flavor/flag-inscriptions-table.cpp
  src/info-reader/kind-info-tokens-table.cpp
  src/inventory/inventory-curse.cpp
  src/object-enchant/smith-tables.cpp
  src/object-enchant/tr-types.h
  src/object-enchant/trc-types.h
  src/object/object-value-calc.cpp
  src/perception/identification.cpp
  src/player/player-status-flags.cpp
  src/player/player-status-flags.h
  src/player/player-status.cpp
  src/view/display-characteristic.cpp
  src/wizard/artifact-analyzer.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/spoiler-table.cpp
  src/wizard/spoiler-table.h
  src/wizard/spoiler-util.h
Labels: enhancement

#1886 [Implement] アヌビス神のカタナを原作仕様に近づける
  lib/edit/a_info.txt
  src/artifact/fixed-art-types.h
  src/cmd-item/cmd-equipment.cpp
  src/info-reader/kind-info-tokens-table.cpp
  src/inventory/inventory-curse.cpp
  src/object-enchant/smith-tables.cpp
  src/object-enchant/tr-types.h
  src/perception/identification.cpp
  src/player-status/player-speed.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/player/player-status.h
  src/view/display-characteristic.cpp
  src/wizard/spoiler-table.cpp
Labels: enhancement

#1889 [Refactor] rbm_type を enum class 化しつつ RaceBlowMethodType に改名。
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/lore/combat-types-setter.cpp
  src/lore/lore-store.cpp
  src/lore/lore-util.h
  src/melee/melee-switcher.cpp
  src/melee/melee-util.h
  src/melee/monster-attack-monster.cpp
  src/monster-attack/monster-attack-describer.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-attack/monster-attack-types.h
  src/monster-attack/monster-attack-util.h
  src/monster-floor/monster-death.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster/monster-damage.cpp
  src/monster/monster-list.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/mspell/summon-checker.cpp
  src/object/warning.cpp
  src/system/monster-race-definition.h
  src/view/display-lore-attacks.cpp
  src/view/display-lore.cpp
Labels: refactor

#1892 [Release] 3.0.0Alpha47
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1880 Feature/refactor player effect type
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/effect/effect-player-curse.cpp
  src/effect/effect-player-curse.h
  src/effect/effect-player-oldies.cpp
  src/effect/effect-player-oldies.h
  src/effect/effect-player-resist-hurt.cpp
  src/effect/effect-player-resist-hurt.h
  src/effect/effect-player-spirit.cpp
  src/effect/effect-player-spirit.h
  src/effect/effect-player-switcher.cpp
  src/effect/effect-player-switcher.h
  src/effect/effect-player-util.h
  src/effect/effect-player.cpp
  src/effect/effect-player.h
  src/effect/effect-processor.h
Labels: refactor

#1894 [Fix] アヌビス-チャリオッツでACが二重に下がる
  src/cmd-item/cmd-equipment.cpp
Labels: bug
