Repository hengband/hengband, pull requests merged in 2021-08, with the labels that each got.

#1296 コンパイル警告/エラーの解消
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/main-win.cpp
Labels: refactor

#1300 [Refactor] Windowsの音再生に関わるコンパイル警告の除去
  src/main-win/main-win-sound.cpp
  src/main-win/wav-reader.h
Labels: refactor

#1306 【再プルリク】デバッグのモンスター生成についてコメント側を合わせる
  src/monster-floor/one-monster-placer.cpp
  src/wizard/wizard-spells.cpp
Labels: bug, refactor

#1311 フラグ管理のリファクタリング(one-monster-placer.cpp)
  src/monster-floor/one-monster-placer.cpp
  src/wizard/wizard-spells.cpp
Labels: refactor

#1299 不要な型エイリアスの削減
  src/combat/attack-accuracy.cpp
  src/combat/attack-accuracy.h
  src/market/building-craft-weapon.cpp
  src/mind/mind-force-trainer.cpp
  src/mind/mind-force-trainer.h
  src/mind/mind-magic-eater.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-song.cpp
  src/spell-realm/spells-song.cpp
  src/spell-realm/spells-song.h
  src/system/h-type.h
  src/system/object-type-definition.h
  src/system/player-type-definition.h
Labels: refactor

#1294 Feature/adjust monsters alpha33
  lib/edit/a_info.txt
  lib/edit/misc.txt
  lib/edit/r_info.txt
  src/artifact/random-art-effects.h
  src/lore/lore-util.h
  src/monster-attack/monster-attack-status.cpp
  src/monster-floor/monster-summon.cpp
  src/monster-floor/special-death-switcher.cpp
  src/monster-race/race-indice-types.h
  src/mspell/mspell-floor.cpp
  src/object-activation/activation-others.cpp
  src/object-activation/activation-others.h
  src/object-activation/activation-switcher.cpp
  src/object-enchant/activation-info-table.cpp
  src/object-enchant/activation-info-table.h
  src/view/display-lore-magics.cpp
  src/view/display-lore.cpp
  src/wizard/monster-info-spoiler.cpp
Labels: enhancement

#1313 monster-sweep-grid.cpp/h のクラス化/メソッド分割
  src/monster-floor/monster-direction.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
Labels: refactor

#1320 [Release] 3.0.0Alpha33
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1329 モンスターが下に走る現象の修正と関数名の変更
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
Labels: bug, refactor

#1326 Feature/fix endless dec status
  src/spell-kind/blood-curse.cpp
  src/spell-kind/spells-random.cpp
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
Labels: bug

#1331 Release/3.0.0 alpha34
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1330 [Release] 3.0.0Alpha34
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1334 [Release] 3.0.0Alpha35
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: bug, release

#1333 Release/3.0.0 alpha35
  doxygen/Hengband.doxyfile
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
  src/spell-kind/blood-curse.cpp
  src/spell-kind/spells-random.cpp
  src/system/angband-version.h
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
Labels: bug, release

#1322 Fix monster/monster-damage.cpp compilation when world score disabled
  src/monster/monster-damage.cpp
Labels: bug

#1338 [Fix] HPが再計算された時に体力ランクを不明にする
  src/spell/spells-status.cpp
Labels: bug

#1337 鼠小僧の黒装束の性能調整
  lib/edit/a_info.txt
Labels: bug, enhancement

#1323 Fix Debian Buster compilation for std::function
  src/hpmp/hp-mp-processor.cpp
  src/info-reader/general-parser.h
  src/target/grid-selector.cpp
Labels: bug

#1342 Feature/refactor recall random quest failure
  src/floor/pattern-walk.cpp
  src/floor/pattern-walk.h
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
  src/world/world-movement-processor.cpp
  src/world/world-movement-processor.h
Labels: bug, refactor

#1341 [Fix] ヨグ＝ソトートの落とし子の日本語版の通常monspeakが死に際になっていたのを修正．
  lib/file/monspeak_j.txt
Labels: bug

#1351 [Fix] 武器祝福で簡易鑑定状態がリセットされない
  src/mind/mind-priest.cpp
Labels: bug

#1353 [Refactor] ビットフラグ操作マクロ群を関数に変更
  src/load/load.cpp
  src/player/player-class.h
  src/player/player-status.cpp
  src/system/player-type-definition.h
  src/util/bit-flags-calculator.h
Labels: refactor

#1357 空腹進行殴りを追加し、第三の乗り手『フェミン』のEAT_FOODを空腹進行に変更
  lib/edit/r_info.txt
  src/info-reader/race-info-tokens-table.cpp
  src/io/gf-descriptions.cpp
  src/io/gf-descriptions.h
  src/lore/combat-types-setter.cpp
  src/melee/melee-switcher.cpp
  src/monster-attack/monster-attack-effect.h
  src/monster-attack/monster-attack-switcher.cpp
  src/monster-attack/monster-attack-types.cpp
  src/monster-attack/monster-eating.cpp
  src/monster-attack/monster-eating.h
  src/spell/spell-types.h
Labels: enhancement

#1364 Change whitespace and capitalization in English armor enchantment message
  src/object-enchant/apply-magic-armor.cpp
Labels: bug, translation

#1359 Fix some verbs in English death messages
  src/monster/monster-damage.cpp
Labels: bug, translation

#1360 Change English description for HUNGRY blows
  src/lore/combat-types-setter.cpp
Labels: bug, translation

#1365 [Refactor] autopick内の関数コメントをDoxygen向けに整形．
  src/autopick/autopick-command-menu.cpp
  src/autopick/autopick-describer.cpp
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick-drawer.cpp
  src/autopick/autopick-editor-command.cpp
  src/autopick/autopick-editor-util.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-finder.cpp
  src/autopick/autopick-initializer.cpp
  src/autopick/autopick-inserter-killer.cpp
  src/autopick/autopick-matcher.cpp
  src/autopick/autopick-pref-processor.cpp
  src/autopick/autopick-reader-writer.cpp
  src/autopick/autopick-registry.cpp
  src/autopick/autopick-util.cpp
  src/autopick/autopick.cpp
Labels: documentation, refactor

#1345 [Add] cfm_type をDoxygenコメントに置換し、確認調整．
  src/floor/floor-mode-changer.h
Labels: refactor

#1380 cmd-throw.cpp に定義されていたit_type関連の処理をthrow-util.cpp/h に移した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/mutation-execution.cpp
  src/action/throw-util.cpp
  src/action/throw-util.h
  src/cmd-item/cmd-throw.cpp
  src/cmd-item/cmd-throw.h
  src/io/input-key-processor.cpp
  src/mind/mind-ninja.cpp
  src/object-use/throw-execution.cpp
  src/object-use/throw-execution.h
  src/realm/realm-hissatsu.cpp
  src/system/h-type.h
Labels: refactor

#1386 mind_kind_type を enum class 化して各型を矯正.
  src/cmd-action/cmd-mind.cpp
  src/mind/mind-explanations-table.cpp
  src/mind/mind-explanations-table.h
  src/mind/mind-info.cpp
  src/mind/mind-info.h
  src/mind/mind-power-getter.cpp
  src/mind/mind-power-getter.h
  src/mind/mind-types.h
  src/window/display-sub-window-spells.cpp
Labels: refactor

#1388 [Fix] ブラックマーケットが複数生成されないようにするコードが機能していない
  src/room/rooms-city.cpp
Labels: bug

#1391 [Feature]スナイパーの火炎/冷気の矢が弱点の敵に対して更に高倍率に
  src/mind/mind-sniper.cpp
Labels: enhancement

#1399 monster_race からr_xtra2 を削除し、r_xtra1 をr_can_evolve に改名した
  src/load/lore-loader.cpp
  src/lore/lore-store.cpp
  src/monster/monster-status.cpp
  src/save/monster-writer.cpp
  src/system/angband-version.h
  src/system/monster-race-definition.h
  src/view/display-lore-status.cpp
Labels: refactor

#1402 [Release] 3.0.0Alpha36
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1406 #1404 列挙型の値を基底型の整数値に変換する関数の導入
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/birth-select-race.cpp
  src/birth/birth-wizard.cpp
  src/birth/character-builder.cpp
  src/birth/inventory-initializer.cpp
  src/birth/quick-start.cpp
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-action/cmd-mind.cpp
  src/core/scores.cpp
  src/grid/feature-flag-types.h
  src/grid/grid.cpp
  src/io-dump/character-dump.cpp
  src/io-dump/special-class-dump.cpp
  src/knowledge/knowledge-self.cpp
  src/load/load-v1-5-0.cpp
  src/load/load.cpp
  src/load/monster-loader.cpp
  src/main-win.cpp
  src/market/building-service.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-power-getter.cpp
  src/mspell/assign-monster-spell.cpp
  src/mspell/mspell-selector.cpp
  src/object-enchant/object-curse.cpp
  src/object-hook/hook-magic.cpp
  src/player-status/player-basic-statistics.cpp
  src/player-status/player-infravision.cpp
  src/player-status/player-stealth.cpp
  src/player/player-race-types.h
  src/player/player-race.cpp
  src/player/player-status.cpp
  src/racial/mutation-racial-selector.cpp
  src/racial/racial-util.cpp
  src/status/shape-changer.cpp
  src/store/pricing.cpp
  src/store/purchase-order.cpp
  src/util/enum-converter.h
  src/view/display-store.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spells.cpp
Labels: refactor

#1425 report_score() の型リファクタリング
  src/core/scores.cpp
  src/io/report.cpp
  src/io/report.h
Labels: refactor

#1427 [Fix] #1426 サブウィンドウのアイテム欄の記号が表示されない
  src/core/window-redrawer.cpp
  src/window/display-sub-windows.cpp
  src/window/display-sub-windows.h
Labels: bug

#1430 サブウィンドウでのアイテム選択記号の絞り込みを復活させる
  src/core/window-redrawer.cpp
  src/floor/floor-object.cpp
  src/object/item-tester-hooker.h
  src/window/display-sub-windows.cpp
  src/window/display-sub-windows.h
Labels: bug, refactor

#1407 アイテム破損関数のクラス化
  src/effect/effect-item.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/inventory/inventory-damage.cpp
  src/inventory/inventory-damage.h
  src/object/object-broken.cpp
  src/object/object-broken.h
  src/player/player-damage.cpp
Labels: refactor

#1438 [Refactor] ItemTester の clone() メンバ関数をCRTPで共通化
  src/object/item-tester-hooker.h
Labels: refactor
