Repository hengband/hengband, pull requests merged in 2021-06, with the labels that each got.

#1179 [Fix] 弓が重すぎて運搬中になると命中率が上がる #1133
  src/player/player-status.cpp
  src/player/player-status.h
Labels: bug

#1184 両手持ちボーナスを得られる条件がおそらく意図せず変わっている #1134
  lib/edit/a_info.txt
  src/player/player-status-flags.cpp
Labels: bug

#1185 [Feature] 戦士/狂戦士の両手持ちボーナスを強化
  src/player/player-status.cpp
Labels: enhancement

#1186 [Fix] 【バグ】 運搬中状態のヘヴィ・クロスボウで射撃すると異常終了 #1182
  src/player/player-status.cpp
Labels: bug

#1192 Feature/3.0.0 alpha26
  doxygen/Hengband.doxyfile
  lib/edit/a_info.txt
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/player/player-status.h
  src/system/angband-version.h
Labels: release

#1191 [Release] 3.0.0Alpha26
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1195 [Fix] ピット/ネストが生成されない #1189
  src/info-reader/dungeon-reader.cpp
Labels: bug

#1199 [Feature] Windows版の効果音再生をwaveOut APIへ移行
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/main-win.cpp
  src/main-win/main-win-sound.cpp
  src/main-win/main-win-sound.h
  src/main-win/wav-reader.cpp
  src/main-win/wav-reader.h
Labels: enhancement

#1206 [Release] 3.0.0Alpha27
  src/system/angband-version.h
Labels: release

#1207 Release/3.0.0 alpha27
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/info-reader/dungeon-reader.cpp
  src/main-win.cpp
  src/main-win/main-win-sound.cpp
  src/main-win/main-win-sound.h
  src/main-win/main-win-utils.h
  src/main-win/wav-reader.cpp
  src/main-win/wav-reader.h
  src/system/angband-version.h
Labels: enhancement

#1209 [Fix] ダンプに過去に使えた領域が記録されない #1205
  src/io-dump/character-dump.cpp
Labels: bug

#1216 [Fix] EASY_SPELL の表記ゆれ
  src/view/display-characteristic.cpp
Labels: bug

#1215 [Fix] 呪いの一時効果の狂戦士化の説明文が*鑑定*時に出ない #1059
  src/perception/identification.cpp
Labels: bug

#1208 [Fix] フェーズアウト状態(カジノ闘技場観戦)時にプレイヤーがテレポートアウェイ効果の影響そのものを受けないよう修正．
  src/spell-kind/spells-teleport.cpp
Labels: bug

#1217 [Fix] 数の指定で受け付けない入力値がある
  src/core/asking-player.cpp
Labels: bug

#1214 [Feature] 効果音の追加v3.0.0 α28
  lib/xtra/sound/sound.cfg
  src/cmd-item/cmd-equipment.cpp
  src/main/sound-definitions-table.cpp
  src/main/sound-definitions-table.h
  src/mspell/mspell-bolt.cpp
  src/spell/spells-status.cpp
Labels: enhancement

#1221 [Release] 3.0.0Alpha28
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1223 3.0.0Alpha28再マージ
  doxygen/Hengband.doxyfile
  lib/xtra/sound/sound.cfg
  src/cmd-item/cmd-equipment.cpp
  src/core/asking-player.cpp
  src/hpmp/hp-mp-regenerator.cpp
  src/io-dump/character-dump.cpp
  src/main/sound-definitions-table.cpp
  src/main/sound-definitions-table.h
  src/mspell/mspell-bolt.cpp
  src/perception/identification.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell/spells-status.cpp
  src/system/angband-version.h
  src/view/display-characteristic.cpp
Labels: release

#1230 [Implement] NO_QUESTモンスターフラグ実装。
  src/dungeon/quest.cpp
  src/floor/fixed-map-generator.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/place-monster-types.h
  src/monster-race/race-flags8.h
Labels: enhancement

#1202 [Fix]　固定護衛生成数を可能な限り最低数保証できるよう生成処理をある程度改善。
  src/monster-floor/monster-generator.cpp
Labels: bug, enhancement

#1226 [Fix] ラッキーマンが変異を他に持たない状態でも突然変異一覧に表示できるよう修正.
  src/io/mutations-dump.cpp
  src/view/display-player.cpp
Labels: bug

#1234 Release/3.0.0 alpha29
  doxygen/Hengband.doxyfile
  src/dungeon/quest.cpp
  src/floor/fixed-map-generator.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/io/mutations-dump.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/place-monster-types.h
  src/monster-race/race-flags8.h
  src/system/angband-version.h
  src/view/display-player.cpp
Labels: enhancement

#1233 [Release] 3.0.0Alpha29
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: enhancement
