Repository hengband/hengband, pull requests merged in 2021-05, with the labels that each got.

#991 [Fix] 文字2倍幅表示のときにMMマップを表示するとクラッシュ #990
  src/window/main-window-util.cpp
Labels: bug

#972 [Refactor] スタックしたアイテムデータをstd::listで管理する
  src/action/open-close-execution.cpp
  src/action/open-util.cpp
  src/action/run-execution.cpp
  src/autopick/autopick.cpp
  src/cmd-item/cmd-smith.cpp
  src/combat/shoot.cpp
  src/core/object-compressor.cpp
  src/dungeon/quest-completion-checker.cpp
  src/effect/effect-item.cpp
  src/floor/cave.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/floor/object-allocator.cpp
  src/floor/object-scanner.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/grid/object-placer.cpp
  src/grid/stair.cpp
  src/inventory/floor-item-getter.cpp
  src/inventory/inventory-object.cpp
  src/inventory/item-getter.cpp
  src/inventory/item-selection-util.cpp
  src/inventory/item-selection-util.h
  src/inventory/player-inventory.cpp
  src/knowledge/knowledge-items.cpp
  src/load/floor-loader.cpp
  src/load/load-v1-5-0.cpp
  src/monster-attack/monster-eating.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-object.cpp
  src/monster-floor/monster-remover.cpp
  src/monster/monster-compaction.cpp
  src/mspell/mspell-checker.cpp
  src/player-attack/attack-chaos-effect.cpp
  src/player/player-move.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/room/vault-builder.cpp
  src/spell-kind/spells-enchant.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-polymorph.cpp
  src/system/monster-type-definition.h
  src/system/object-type-definition.h
  src/target/target-describer.cpp
  src/target/target-preparation.cpp
  src/util/sort.cpp
  src/view/display-map.cpp
  src/window/display-sub-windows.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: enhancement, refactor

#998 [Fix] cheat_know + Wizardモードで2重にモンスター種族IDが表示
  src/view/display-lore.cpp
Labels: bug

#994 [Feature] Win版にコマンドラインオプション追加（デバッグ用コンソール表示）
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/main-win.cpp
  src/main-win/commandline-win.cpp
  src/main-win/commandline-win.h
Labels: enhancement

#1000 [Feature] clangでのビルドテストではプリコンパイルヘッダを使用しない
  .github/workflows/buildtest-on-linux.yml
Labels: enhancement

#1005 [Fix] 力の杖のレアリティ設定のtypoを修正
  lib/edit/k_info.txt
Labels: bug

#993 [Fix/Feature] 種族の食料タイプを設定 #820
  src/cmd-item/cmd-eat.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/object-hook/hook-expendable.cpp
  src/object-use/quaff-execution.cpp
  src/player/mimic-info-table.cpp
  src/player/player-race.cpp
  src/player/player-race.h
  src/player/race-info-table.cpp
Labels: bug, enhancement

#1006 モンスター情報の詳細化/修正
  src/main-win.cpp
  src/main.cpp
  src/view/display-lore-drops.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/monster-info-spoiler.cpp
  src/wizard/spoiler-util.h
  src/wizard/wizard-spoiler.cpp
Labels: bug, refactor

#1011 [Add] main-win.cにDoxygenフォーマット追加． doxyfileのデフォルトに 必要なPREDEFINED追加
  doxygen/Hengband.doxyfile
  src/main-win.cpp
Labels: documentation

#988 v3.0.0 Alpha21 モンスター＆特殊ドロップ実装
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  lib/edit/misc.txt
  lib/edit/r_info.txt
  lib/file/mondeath.txt
  lib/file/mondeath_j.txt
  lib/file/monfear.txt
  lib/file/monfear_j.txt
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
  src/Makefile.am
  src/birth/inventory-initializer.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-object.cpp
  src/market/bounty.cpp
  src/market/building-enchanter.cpp
  src/mind/mind-archer.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/monster-race/race-indice-types.h
  src/mspell/mspell-summon.cpp
  src/mspell/specified-summon.cpp
  src/object-enchant/apply-magic-accessory.cpp
  src/object-enchant/apply-magic-accessory.h
  src/object-enchant/apply-magic-amulet.cpp
  src/object-enchant/apply-magic-amulet.h
  src/object-enchant/apply-magic-ring.cpp
  src/object-enchant/apply-magic-ring.h
  src/object-enchant/apply-magic.cpp
  src/object-enchant/apply-magic.h
  src/object-enchant/enchanter-base.h
  src/object/object-kind-hook.cpp
  src/object/object-kind-hook.h
  src/spell-realm/spells-craft.cpp
  src/spell/spells-object.cpp
  src/spell/spells-object.h
  src/store/store-util.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: enhancement

#999 [Fix] 【バグ】 足元のアイテムを複数拾おうとした時にサブウィンドウ：あなたの足元のアイテム一覧が更新されない #995
  src/floor/floor-object.cpp
Labels: bug

#1014 [Release] 3.0.0Alpha21
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1018 [Fix] Cコマンドで永久光源欄の@列に . を表示し忘れている
  src/view/display-characteristic.cpp
Labels: bug

#1027 [Fix] メッセージ履歴が正しく保存されない
  src/save/save.cpp
Labels: bug

#1019 [Fix] 固定部屋で床が . ではなく空白になっているのを修正
  lib/edit/v_info.txt
Labels: bug

#1025 [Fix] ウィザードモードでのpval99999入力ハングの修正
  src/flavor/flavor-util.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: enhancement

#1032 [Implement] NO_ROOM ダンジョンフラグ実装。
  src/dungeon/dungeon-flag-types.h
  src/floor/cave-generator.cpp
  src/info-reader/dungeon-info-tokens-table.cpp
Labels: enhancement

#1038 [Refactor] ダンジョンフラグをFlagGroup化
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/action-limited.cpp
  src/cmd-action/cmd-attack.cpp
  src/dungeon/dungeon-flag-mask.h
  src/dungeon/dungeon-flag-types.h
  src/dungeon/dungeon.h
  src/effect/effect-feature.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-events.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-streams.cpp
  src/floor/wild.cpp
  src/grid/door.cpp
  src/grid/feature-generator.cpp
  src/grid/feature.cpp
  src/grid/grid.cpp
  src/info-reader/dungeon-info-tokens-table.cpp
  src/info-reader/dungeon-info-tokens-table.h
  src/info-reader/dungeon-reader.cpp
  src/io/input-key-processor.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/melee/melee-spell-util.cpp
  src/melee/monster-attack-monster.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-attack/monster-attack-processor.cpp
  src/monster-floor/monster-lite.cpp
  src/monster-floor/monster-summon.cpp
  src/monster/monster-list.cpp
  src/monster/monster-status.cpp
  src/monster/monster-update.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-attack.cpp
  src/mspell/mspell-lite.cpp
  src/object/warning.cpp
  src/player/player-move.cpp
  src/racial/racial-vampire.cpp
  src/realm/realm-hissatsu.cpp
  src/room/cave-filler.cpp
  src/room/room-generator.cpp
  src/room/rooms-builder.cpp
  src/room/rooms-fractal.cpp
  src/room/rooms-maze-vault.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-special.cpp
  src/room/rooms-trap.cpp
  src/room/rooms-vault.cpp
  src/room/space-finder.cpp
  src/specific-object/torch.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-lite.cpp
  src/world/world-object.cpp
Labels: refactor

#1028 message_add 関数をC++機能でリファクタリングする #1026
  src/main/game-data-initializer.cpp
  src/view/display-messages.cpp
  src/view/display-messages.h
Labels: enhancement, refactor

#1046 [Feature] 目的地に居る場合にトラベル継続確認を行わない
  src/cmd-action/cmd-travel.cpp
Labels: enhancement

#1048 [Fix] 祝福による魔法防御上昇の誤り #1047
  src/player/player-status.cpp
Labels: bug

#1045 [Fix] 轟音のブレスにより魔力復活の薬が割れた際にクラッシュ #1041
  src/effect/effect-item.cpp
Labels: bug

#1051 [Refactor] GINOU_* を改名して enum 化．
  src/cmd-action/cmd-attack.cpp
  src/cmd-action/cmd-pet.cpp
  src/combat/shoot.cpp
  src/core/player-processor.cpp
  src/knowledge/knowledge-experiences.cpp
  src/load/load-zangband.cpp
  src/mind/mind-cavalry.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster/monster-processor.cpp
  src/pet/pet-fall-off.cpp
  src/player-attack/player-attack.cpp
  src/player-status/player-speed.cpp
  src/player/player-skill.h
  src/player/player-status.cpp
  src/spell/spell-info.cpp
Labels: enhancement

#1044 [Fix] 床上のアイテム一覧サブウィンドウでモンスターを感知できる #1030
  src/window/display-sub-windows.cpp
Labels: bug

#1056 [Fix] ユニーククローンを倒したときに本物の撃破時間を上書きしてしまう #1055
  src/monster-floor/monster-death.cpp
Labels: bug

#1001 [Feature] 床上のアイテムリストのスタック順を保持する #992
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/combat/shoot.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/floor/floor-util.cpp
  src/grid/grid.h
  src/grid/object-placer.cpp
  src/inventory/floor-item-getter.cpp
  src/load/floor-loader.cpp
  src/load/item-loader.cpp
  src/load/load-v1-5-0.cpp
  src/load/savedata-flag-types.h
  src/monster-attack/monster-eating.cpp
  src/monster-floor/monster-object.cpp
  src/object/object-index-list.cpp
  src/object/object-index-list.h
  src/save/item-writer.cpp
  src/spell-kind/spells-fetcher.cpp
  src/stdafx.h
  src/system/monster-type-definition.h
  src/system/object-type-definition.h
  src/target/target-describer.cpp
Labels: enhancement

#1052 [Refactor] curse_flags の FlagGroup化
  src/artifact/fixed-art-generator.cpp
  src/artifact/random-art-characteristics.cpp
  src/cmd-item/cmd-equipment.cpp
  src/cmd-item/cmd-smith.cpp
  src/hpmp/hp-mp-processor.cpp
  src/inventory/inventory-curse.cpp
  src/load/item-loader.cpp
  src/load/load-v1-5-0.cpp
  src/mind/mind-priest.cpp
  src/object-enchant/apply-magic-amulet.cpp
  src/object-enchant/apply-magic-armor.cpp
  src/object-enchant/apply-magic-others.cpp
  src/object-enchant/apply-magic-ring.cpp
  src/object-enchant/apply-magic-weapon.cpp
  src/object-enchant/apply-magic.cpp
  src/object-enchant/object-curse.cpp
  src/object-enchant/object-curse.h
  src/object-enchant/object-ego.cpp
  src/object-enchant/trc-types.h
  src/object-hook/hook-checker.cpp
  src/object/object-value-calc.cpp
  src/perception/identification.cpp
  src/player-info/self-info.cpp
  src/player/digestion-processor.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/racial/racial-android.cpp
  src/realm/realm-hex.cpp
  src/save/item-writer.cpp
  src/spell-kind/spells-curse-removal.cpp
  src/spell/spells-object.cpp
  src/system/angband-version.h
  src/system/object-type-definition.cpp
  src/system/object-type-definition.h
  src/system/player-type-definition.h
  src/view/display-characteristic.cpp
  src/wizard/artifact-analyzer.cpp
Labels: enhancement, refactor

#1057 [Fix] 見えないときにモンスターの無敵発動時のメッセージが表示される #1034
  src/mspell/mspell-status.cpp
Labels: bug

#1064 [Fix] Mac版Clangで display-messages.cpp のコンパイルエラー
  src/view/display-messages.cpp
Labels: bug, refactor

#1063 [Feature] FlagGroup のメンバに nodiscard 属性を付与する
  src/util/flag-group.h
Labels: enhancement

#1066 [Fix] 武器匠での会心ダメージやステータス画面上の平均ダメージに強撃の効果が反映されない #897
  src/combat/attack-criticality.cpp
  src/combat/attack-criticality.h
  src/combat/shoot.cpp
  src/combat/shoot.h
  src/market/building-craft-weapon.cpp
  src/view/status-first-page.cpp
Labels: bug, enhancement

#1068 [Release] 3.0.0Alpha22
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1062 [Feature] Windows版をUnicode文字セット(UTF-16)へ移行
  Hengband/Hengband/Hengband.vcxproj
  src/main-win.cpp
  src/main-win/main-win-cfg-reader.cpp
  src/main-win/main-win-file-utils.cpp
  src/main-win/main-win-mci.cpp
  src/main-win/main-win-mci.h
  src/main-win/main-win-music.cpp
  src/main-win/main-win-sound.cpp
  src/main-win/main-win-utils.cpp
  src/main-win/main-win-utils.h
Labels: enhancement

#1072 [Fix] 両手の空いたマーシャルアーツで利き手でない方の指に追加攻撃の指輪を付けても攻撃回数が増えない #1071
  src/player/player-status-flags.cpp
Labels: bug

#909 [Refactor] 各パーサをstd::string系の処理を利用して書き直し
  src/flavor/object-flavor.cpp
  src/grid/feature-flag-types.h
  src/info-reader/artifact-reader.cpp
  src/info-reader/artifact-reader.h
  src/info-reader/dungeon-reader.cpp
  src/info-reader/dungeon-reader.h
  src/info-reader/ego-reader.cpp
  src/info-reader/ego-reader.h
  src/info-reader/feature-info-tokens-table.cpp
  src/info-reader/feature-info-tokens-table.h
  src/info-reader/feature-reader.cpp
  src/info-reader/feature-reader.h
  src/info-reader/general-parser.cpp
  src/info-reader/general-parser.h
  src/info-reader/info-reader-util.cpp
  src/info-reader/info-reader-util.h
  src/info-reader/kind-info-tokens-table.cpp
  src/info-reader/kind-info-tokens-table.h
  src/info-reader/kind-reader.cpp
  src/info-reader/kind-reader.h
  src/info-reader/magic-reader.cpp
  src/info-reader/magic-reader.h
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/info-reader/race-reader.h
  src/info-reader/skill-reader.cpp
  src/info-reader/skill-reader.h
  src/info-reader/vault-reader.cpp
  src/info-reader/vault-reader.h
  src/main/angband-headers.h
  src/main/info-initializer.cpp
  src/monster-race/race-flags8.h
  src/util/string-processor.cpp
  src/util/string-processor.h
Labels: refactor

#1095 [Fix] r_info.txtのモンスターの呪文フラグで書式によってうまく読めない #1091
  src/info-reader/race-reader.cpp
Labels: bug

#1089 [Fix] モンスターの思い出の射撃ダイス表示がダイス数と目で逆。
  src/view/display-lore.cpp
Labels: enhancement

#1096 [English] In angband_fgets() replace nonprintables with '?' rather than strip them
  src/util/angband-files.cpp
Labels: bug

#1092 モンスター追加/調整 α23版
  lib/edit/misc.txt
  lib/edit/r_info.txt
  lib/file/monfear.txt
  lib/file/monfear_j.txt
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
  src/monster-race/race-indice-types.h
  src/mspell/mspell-summon.cpp
  src/mspell/specified-summon.cpp
  src/mspell/specified-summon.h
  src/mspell/summon-checker.cpp
  src/spell/summon-types.h
Labels: enhancement

#1106 [Release] 3.0.0Alpha23
  src/system/angband-version.h
Labels: release

#1114 [MISC] music.cfgに個別BGMのコメント追加
  lib/xtra/music/music.cfg
Labels: documentation

#1117 [Feature] ワイド文字列版APIへ移行（PlaySound, GetFileAttributes, mciSendCommand）
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/main-win/main-win-cfg-reader.cpp
  src/main-win/main-win-file-utils.cpp
  src/main-win/main-win-mci.cpp
  src/main-win/main-win-mci.h
  src/main-win/main-win-mmsystem.h
  src/main-win/main-win-music.cpp
  src/main-win/main-win-sound.cpp
  src/main-win/main-win-windows.h
Labels: enhancement

#1122 [Fix] m_info.txt の xtra フラグが正しく読めていない
  src/info-reader/info-reader-util.h
  src/info-reader/magic-reader.cpp
Labels: bug

#1127 [Feature] 固定アーティファクト『ドラゴンころし』の追加
  lib/edit/a_info.txt
  lib/edit/misc.txt
  lib/edit/t0000001.txt
  lib/edit/t_lite.txt
Labels: enhancement

#1136 [Feature] 効果音の追加。空腹時、会心の一撃、切れ味
  lib/xtra/sound/sound.cfg
  src/combat/attack-criticality.cpp
  src/combat/attack-criticality.h
  src/main/sound-definitions-table.cpp
  src/main/sound-definitions-table.h
  src/object-enchant/vorpal-weapon.cpp
  src/player/digestion-processor.cpp
Labels: enhancement

#1129 [Fix] グラフィクスモードの初期化をTERM_XTRA_REACTに依存せず起動時に行う
  src/main-win.cpp
Labels: enhancement

#1131 [Fix] #1130 存在しないダンジョンID及び階層を指定したら再入力を促すようにした
  src/dungeon/dungeon.h
  src/wizard/wizard-special-process.cpp
Labels: bug

#1080 [Refactor] トラップの種別をenum化.
  src/grid/trap.cpp
  src/grid/trap.h
Labels: refactor

#1140 v3.0.0 α24 モンスター調整＋追加
  lib/edit/misc.txt
  lib/edit/r_info.txt
  lib/file/mondeath.txt
  lib/file/mondeath_j.txt
  lib/file/monfear.txt
  lib/file/monfear_j.txt
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
  src/monster-floor/special-death-switcher.cpp
  src/monster-race/race-indice-types.h
  src/mspell/mspell-summon.cpp
  src/mspell/specified-summon.cpp
  src/mspell/specified-summon.h
  src/mspell/summon-checker.cpp
Labels: enhancement

#1115 mind-power-getter.cpp の分割
  src/cmd-action/cmd-mind.cpp
  src/mind/mind-power-getter.cpp
  src/mind/mind-power-getter.h
Labels: refactor

#1124 [Fix] 店で購入したアイテムに対する自動刻み関連の修正
  src/autopick/autopick-util.cpp
  src/store/purchase-order.cpp
Labels: bug

#1145 [Release] 3.0.0Alpha24
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1146 Release/3.0.0 alpha24
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  doxygen/Hengband.doxyfile
  lib/edit/a_info.txt
  lib/edit/misc.txt
  lib/edit/r_info.txt
  lib/edit/t0000001.txt
  lib/edit/t_lite.txt
  lib/file/mondeath.txt
  lib/file/mondeath_j.txt
  lib/file/monfear.txt
  lib/file/monfear_j.txt
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
  lib/xtra/music/music.cfg
  lib/xtra/sound/Makefile.am
  lib/xtra/sound/sound.cfg
  src/Makefile.am
  src/autopick/autopick-util.cpp
  src/cmd-action/cmd-mind.cpp
  src/cmd-io/cmd-dump.cpp
  src/cmd-io/cmd-macro.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/combat/attack-criticality.cpp
  src/combat/attack-criticality.h
  src/dungeon/dungeon.h
  src/grid/trap.cpp
  src/grid/trap.h
  src/info-reader/info-reader-util.h
  src/info-reader/magic-reader.cpp
  src/io/read-pref-file.cpp
  src/io/read-pref-file.h
  src/main-win.cpp
  src/main-win/main-win-cfg-reader.cpp
  src/main-win/main-win-file-utils.cpp
  src/main-win/main-win-mci.cpp
  src/main-win/main-win-mci.h
  src/main-win/main-win-mmsystem.h
  src/main-win/main-win-music.cpp
  src/main-win/main-win-sound.cpp
  src/main-win/main-win-windows.h
  src/main/sound-definitions-table.cpp
  src/main/sound-definitions-table.h
  src/mind/mind-power-getter.cpp
  src/mind/mind-power-getter.h
  src/monster-floor/special-death-switcher.cpp
  src/monster-race/race-indice-types.h
  src/mspell/mspell-summon.cpp
  src/mspell/specified-summon.cpp
  src/mspell/specified-summon.h
  src/mspell/summon-checker.cpp
  src/object-enchant/vorpal-weapon.cpp
  src/player/digestion-processor.cpp
  src/store/purchase-order.cpp
  src/system/angband-version.h
  src/wizard/wizard-special-process.cpp
Labels: enhancement

#1132 [Feature] Windows版の描画にダブルバッファリング導入
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/main-win.cpp
  src/main-win/main-win-term.cpp
  src/main-win/main-win-term.h
Labels: enhancement

#1159 [Fix] モンスターがテレポート追尾しない #1157
  src/spell-kind/spells-teleport.cpp
Labels: bug

#1142 [Feature] 射撃命中音の効果音対応
  lib/xtra/sound/sound.cfg
  src/combat/shoot.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/main/sound-definitions-table.cpp
  src/main/sound-definitions-table.h
  src/mspell/mspell-bolt.cpp
Labels: enhancement

#1162 v3.0.0 α25 アイテム調整
  lib/edit/a_info.txt
  lib/edit/misc.txt
  src/action/racial-execution.cpp
  src/artifact/fixed-art-types.h
  src/cmd-action/cmd-mane.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/player/player-status.cpp
Labels: enhancement

#1171 [Fix] #1156 足元のアイテムを表示する時に見かけのモンスターを表示するようにした
  src/window/display-sub-windows.cpp
Labels: bug

#1163 world-turn-processor.cpp/h の分割
  src/core/player-processor.cpp
  src/core/window-redrawer.cpp
  src/dungeon/dungeon-processor.cpp
  src/world/world-turn-processor.cpp
  src/world/world-turn-processor.h
Labels: refactor

#1175 [Release] 3.0.0Alpha25
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release
