Repository hengband/hengband, pull requests merged in 2021-03, with the labels that each got.

#359 [Fix] 「回避の彫像」「守りのルーン」の表記ブレの統一 #357
  lib/edit/f_info.txt
  lib/edit/k_info.txt
  lib/help/dungeon.txt
  lib/pref/graf-ibm.prf
  lib/pref/graf-ne2.prf
  lib/pref/graf-new.prf
  lib/pref/graf-xxx.prf
  lib/pref/spell-xx.prf
  src/effect/effect-feature.c
  src/effect/effect-player.c
  src/floor/floor-leaver.c
  src/grid/feature-flag-types.h
  src/grid/feature.c
  src/grid/feature.h
  src/grid/grid.c
  src/grid/grid.h
  src/info-reader/feature-info-tokens-table.c
  src/info-reader/feature-reader.c
  src/io/gf-descriptions.c
  src/load/load-v1-5-0.c
  src/load/old-feature-types.h
  src/mind/mind-explanations-table.c
  src/mind/mind-ninja.c
  src/mind/mind-numbers.h
  src/monster-floor/monster-move.c
  src/monster-floor/one-monster-placer.c
  src/object-activation/activation-others.c
  src/object-use/read-execution.c
  src/racial/racial-switcher.c
  src/realm/realm-life.c
  src/realm/realm-song.c
  src/realm/realm-sorcery.c
  src/spell-kind/earthquake.c
  src/spell-kind/spells-grid.c
  src/spell-kind/spells-grid.h
  src/spell-kind/spells-neighbor.c
  src/spell-kind/spells-neighbor.h
  src/spell/spell-types.h
  src/system/gamevalue.h
  src/term/gameterm.c
  src/wizard/wizard-special-process.c
Labels: bug

#368 [Refactor] BIT演算マクロへの置換を進める。mutation-investor-remover.c
  src/mutation/mutation-investor-remover.c
Labels: refactor

#373 [Refactor] BIT演算マクロへの置換を進める。mutation-investor-remover.c後半。
  src/mutation/mutation-investor-remover.c
Labels: refactor

#370 [Feature]α10に向けたアーティファクトの調整
  lib/edit/a_info.txt
Labels: enhancement

#376 [Fix] セクシースペルマスターの初期武器
  src/birth/inventory-initializer.c
  src/core/game-play.c
Labels: bug

#378 [Fix] ★デサンクの発動を酸から電撃のボールと耐性に修正
  lib/edit/a_info.txt
Labels: bug

#375 [Refactor] BIT演算マクロへの置換を進める。display-player-stat-info.c
  src/view/display-player-stat-info.c
Labels: refactor

#362 [Refactor] tim_player_flags()の整理
  src/object-enchant/tr-types.h
  src/player/player-status-flags.c
  src/player/player-status-flags.h
  src/player/temporary-resistances.c
Labels: refactor

#379 [Refactor] BIT演算マクロへの置換を進める。monster-info-spoiler.c
  src/wizard/monster-info-spoiler.c
Labels: refactor

#377 [Feature] マーフォークの初期武器及び武器熟練度
  src/birth/inventory-initializer.c
  src/core/game-play.c
Labels: enhancement

#381 English: edit descriptions for some of the new 3.0.0 monsters
  lib/edit/r_info.txt
Labels: translation

#383 [Fix] ジェノサイバーの思い出表現がおかしかったのを修正
  lib/edit/r_info.txt
Labels: bug

#384 Feature/improve release package build script
  Build-Windows-Release-Package.ps1
  lib/delete.me
  lib/xtra/delete.me
Labels: enhancement

#361 [Fix] 同じBGMタイプのエリアに移動するとBGMが鳴りなおす #264
  src/main-win.c
Labels: bug, enhancement

#385 [Refactor] BIT演算マクロへの置換を進める。mutation-info.c
  src/player-info/mutation-info.c
Labels: refactor

#389 [Fix] 自己分析メッセージ中のコスト表示不一致 #388
  src/player-info/class-ability-info.c
Labels: bug

#380 [Refactor] flag_cause列挙子の修正 #287
  src/player-attack/player-attack.c
  src/player/permanent-resistances.c
  src/player/player-status-flags.c
  src/player/player-status-flags.h
  src/player/player-status-resist.c
  src/player/temporary-resistances.c
Labels: refactor

#386 [Fix] 店や家でサブウィンドウのキャラ情報が更新されない #259
  src/cmd-item/cmd-equipment.c
  src/inventory/inventory-object.c
  src/store/purchase-order.c
  src/store/sell-order.c
Labels: bug, enhancement

#391 [Feature] モンスターの思い出で打撃を手段や効果で色分けする
  src/lore/combat-types-setter.c
  src/lore/lore-util.h
  src/lore/monster-lore.c
  src/view/display-lore-attacks.c
  src/view/display-lore-attacks.h
Labels: enhancement

#394 [Refactor] BIT演算処理を整理する player-status-flags.c #393
  src/player/player-status-flags.c
Labels: refactor

#390 [Refactor] BIT演算マクロへの置換を進める。racial-switcher.c
  src/racial/racial-switcher.c
Labels: refactor

#397 [Refactor] get_player_flags()を整理
  src/player/player-status-flags.c
  src/player/temporary-resistances.c
Labels: refactor

#398 [Fix] BGM未定義のシチュエーションで街のBGMが鳴る
  src/main-win.c
  src/main/sound-of-music.c
Labels: bug

#402 [Refactor] calc_speed()関数を分解・整理し速度増減の由来を取得可能とする
  src/player/player-status-flags.c
  src/player/player-status-flags.h
  src/player/player-status.c
  src/player/player-status.h
  src/player/temporary-resistances.c
Labels: refactor

#395 [refactor] repair_monstersフラグの削除
  src/core/player-processor.c
  src/dungeon/dungeon-processor.c
  src/floor/floor-changer.c
  src/floor/floor-save-util.c
  src/floor/floor-save-util.h
  src/monster-floor/one-monster-placer.c
  src/spell-kind/spells-detection.c
Labels: refactor

#403 Feature/remove gcc overflow warning
  .github/workflows/buildtest-on-linux.yml
  src/autopick/autopick-entry.c
  src/birth/auto-roller.c
  src/cmd-action/cmd-mane.c
  src/cmd-io/cmd-dump.c
  src/cmd-io/cmd-lore.c
  src/cmd-item/cmd-smith.c
  src/core/show-file.c
  src/floor/floor-save.c
  src/info-reader/dungeon-reader.c
  src/inventory/floor-item-getter.c
  src/inventory/item-getter.c
  src/inventory/item-selection-util.h
  src/io/files-util.c
  src/io/record-play-movie.c
  src/knowledge/knowledge-quests.c
  src/load/floor-loader.c
  src/lore/lore-calculator.c
  src/main/angband-initializer.c
  src/market/bounty.c
  src/market/building-monster.c
  src/object/object-info.c
  src/save/floor-writer.c
  src/status/shape-changer.c
  src/window/display-sub-window-spells.c
  src/wizard/fixed-artifacts-spoiler.c
  src/wizard/wizard-messages.c
Labels: refactor

#406 SUPPORTIVEフラグを適用して＊鑑定＊表示にも出るように追加
  lib/edit/a_info.txt
  lib/edit/k_info.txt
  src/info-reader/kind-info-tokens-table.c
  src/info-reader/kind-info-tokens-table.h
  src/object-enchant/tr-types.h
  src/perception/identification.c
  src/player/player-status-flags.c
  src/player/player-status.c
Labels: enhancement

#413 [Fix] 耐酸、耐火、耐電の盾の発動の効果属性の記述の間違い #411
  lib/help/jdefend.txt
Labels: documentation

#409 [Fix] 両手持ちの修正計算時に利き手のみを把持対象としていた #407
  src/player/player-status.c
Labels: bug

#421 [Fix] DUN_ROOMS_MAX のコメント修正． / Fix comment of DUN_ROOMS_MAX.
  src/room/door-definition.h
Labels: refactor

#408 [Refactor] calc_stealthの分解・整理し隠密修正の成分取得を可能とする
  src/player/player-status-flags.c
  src/player/player-status.c
  src/player/player-status.h
Labels: refactor

#420 店舗の常時陳列商品を設定
  src/cmd-building/cmd-store.c
  src/market/articles-on-sale.c
  src/market/articles-on-sale.h
  src/market/building-initializer.c
  src/store/purchase-order.c
  src/store/service-checker.c
  src/store/store-util.c
  src/store/store-util.h
  src/store/store.c
  src/store/store.h
Labels: enhancement

#371 [feature] 視界内のモンスター一覧からアイテムに擬態するモンスターを除く #89
  src/monster-race/race-indice-types.h
  src/monster/monster-flag-types.h
  src/monster/monster-info.c
  src/monster/monster-info.h
  src/monster/monster-update.c
  src/target/target-preparation.c
Labels: enhancement

#423 [Fix] Artifact自動生成スポイラーの一部フラグが欠損
  src/wizard/spoiler-table.c
  src/wizard/spoiler-table.h
Labels: bug

#427 [Fix] 毒の沼で耐毒があると毒状態におかされる
  src/core/hp-mp-processor.c
Labels: bug

#429 [Fix] モンスターの思い出の経験値表示でクラッシュ (英語版)
  src/term/z-form.c
  src/view/display-lore.c
Labels: bug

#433 [Fix] .editorconfigにcppを追加
  .editorconfig
Labels: bug

#435 ウィザードコマンドに種族変更を追加。
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-special-process.h
Labels: bug, enhancement

#434 【バグ】 自己分析の種族特殊能力メッセージの誤り
  src/player-info/race-ability-info.cpp
Labels: bug

#438 [Version]3.0.0Alpha10
  src/system/angband-version.h
Labels: enhancement

#441 剣術家の技「幻惑」の説明と実際の効果が異なる
  src/effect/effect-monster-switcher.cpp
  src/realm/realm-hissatsu.cpp
Labels: bug

#447 [Fix] 現在の知識コマンドの鑑定済みの装備の耐性のヘッダ #444
  src/knowledge/knowledge-inventory.cpp
Labels: bug, enhancement

#448 [Fix] GF_HOLY_FIREが善良なモンスターに有効 #446
  src/effect/effect-monster-resist-hurt.cpp
Labels: bug

#442 [Feature] デバグコマンドの整理と拡張
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-game-modifier.h
  src/wizard/wizard-player-modifier.cpp
  src/wizard/wizard-player-modifier.h
Labels: enhancement

#451 [Feature] doxyfileを1.9.1で更新してバージョン表記も3.0.0Alpha10に変更．
  doxygen/Hengband.doxyfile
Labels: documentation

#454 [Fix] ローカルスコアの種族と性格がおかしい
  src/core/scores.cpp
Labels: bug

#455 [update] clang-formatの設定を更新
  .clang-format
Labels: enhancement, refactor

#457 [Fix] 呪術の呪力吸収の説明文 #453
  src/realm/realm-hex.cpp
Labels: bug

#449 [Refactor] PlayerStatusBase、PlayerSpeedクラスの導入
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/player-status/player-speed.cpp
  src/player-status/player-speed.h
  src/player-status/player-status-base.cpp
  src/player-status/player-status-base.h
  src/player/player-status-flags.cpp
  src/player/player-status-flags.h
  src/player/player-status.cpp
  src/player/player-status.h
Labels: refactor

#459 [Feature] 騎乗時にランス、ヘヴィ・ランスのダイス追加を明示する。
  src/flavor/flavor-describer.cpp
Labels: enhancement, refactor

#452 [Feature] 足元/床上のアイテム一覧ウィンドウフラグ (from 東方勝手版)
  src/artifact/random-art-generator.cpp
  src/autopick/autopick.cpp
  src/birth/inventory-initializer.cpp
  src/cmd-io/cmd-floor.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-item/cmd-equipment.cpp
  src/cmd-item/cmd-item.cpp
  src/cmd-item/cmd-throw.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/cmd-item/cmd-zaprod.cpp
  src/cmd-item/cmd-zapwand.cpp
  src/core/game-play.cpp
  src/core/window-redrawer.cpp
  src/core/window-redrawer.h
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/inventory/inventory-object.cpp
  src/mind/mind-mindcrafter.cpp
  src/mind/mind-priest.cpp
  src/player/player-move.cpp
  src/spell-kind/spells-enchant.cpp
  src/spell-kind/spells-perception.cpp
  src/spell/spells-object.cpp
  src/status/base-status.cpp
  src/target/target-setter.cpp
  src/term/gameterm.cpp
  src/window/display-sub-windows.cpp
  src/window/display-sub-windows.h
  src/wizard/wizard-item-modifier.cpp
Labels: enhancement

#464 [Feature] ベースアイテムの調整(α10→α11) #300
  lib/edit/k_info.txt
  src/object-enchant/apply-magic-accessory.cpp
Labels: enhancement

#437 [Feature] キャラ作成画面に追加の能力値表示 #436
  src/birth/birth-select-class.cpp
  src/birth/birth-select-personality.cpp
  src/birth/birth-select-race.cpp
  src/birth/birth-select-realm.cpp
  src/birth/birth-wizard.cpp
Labels: enhancement

#471 [feature] セーブファイルの仕様バージョンを本体のバージョンと分離する #470
  src/load/dummy-loader.cpp
  src/load/floor-loader.cpp
  src/load/info-loader.cpp
  src/load/load-util.cpp
  src/load/load-util.h
  src/save/save.cpp
  src/spell/spells-util.h
  src/system/angband-version.h
Labels: enhancement

#424 [English documentation] align the contents of defend.txt with jdefend.txt
  lib/help/defend.txt
Labels: bug, documentation

#461 [Refactor] プレイヤーがダンジョンに居るかの判定をis_in_dungeon()関数に置換．
  src/action/action-limited.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-building/cmd-store.cpp
  src/cmd-io/cmd-dump.cpp
  src/core/hp-mp-processor.cpp
  src/core/player-processor.cpp
  src/floor/floor-leaver.cpp
  src/grid/grid.cpp
  src/io/write-diary.cpp
  src/load/player-info-loader.cpp
  src/monster-race/monster-race-hook.cpp
  src/mutation/mutation-processor.cpp
  src/player/player-damage.cpp
  src/player/player-status.cpp
  src/player/player-status.h
  src/spell-kind/spells-world.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor

#479 [Feature] 知識情報配列のロードの改修
  src/load/item-loader.cpp
  src/load/lore-loader.cpp
Labels: enhancement

#477 [Refactor] PlayerBasicStatisticsクラスの導入
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/open-close-execution.cpp
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-action/cmd-mind.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/cmd-item/cmd-throw.cpp
  src/combat/shoot.cpp
  src/core/hp-mp-regenerator.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/flavor/flavor-describer.cpp
  src/inventory/inventory-describer.cpp
  src/mind/mind-blue-mage.cpp
  src/mind/mind-power-getter.cpp
  src/monster-attack/monster-eating.cpp
  src/player-status/player-basic-statistics.cpp
  src/player-status/player-basic-statistics.h
  src/player-status/player-charisma.cpp
  src/player-status/player-charisma.h
  src/player-status/player-constitution.cpp
  src/player-status/player-constitution.h
  src/player-status/player-dextarity.cpp
  src/player-status/player-dextarity.h
  src/player-status/player-intelligence.cpp
  src/player-status/player-intelligence.h
  src/player-status/player-status-base.h
  src/player-status/player-strength.cpp
  src/player-status/player-strength.h
  src/player-status/player-wisdom.cpp
  src/player-status/player-wisdom.h
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/player/player-status.h
  src/spell/spell-info.cpp
  src/spell/spells-diceroll.cpp
  src/store/pricing.cpp
  src/view/display-player-middle.cpp
  src/window/display-sub-window-spells.cpp
Labels: refactor

#482 [refactor] モンスター一覧の表示
  src/target/target-preparation.cpp
  src/target/target-preparation.h
  src/window/display-sub-windows.cpp
  src/window/display-sub-windows.h
Labels: refactor

#488 [feature] FlagGroupクラス
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/util/flag-group.h
Labels: enhancement, refactor

#487 [Fix] 消費魔力減少の指輪のレア度設定
  lib/edit/k_info.txt
Labels: bug

#480 [Fix] GF_PSI及びGF_PSI_DRAINの反射判定の不具合を修正 #472
  src/effect/effect-monster-psi.cpp
Labels: bug

#485 [Fix] 乗馬した状態で足元をターゲットに魔法棒等を放っても何の効果も発生しない #467
  src/effect/effect-monster.cpp
Labels: bug

#489 [Refactor] gen_flagsをFlagGroup<TRG>クラスに変更
  src/artifact/fixed-art-generator.cpp
  src/dungeon/quest.cpp
  src/flavor/tval-description-switcher.cpp
  src/floor/fixed-map-generator.cpp
  src/info-reader/artifact-reader.cpp
  src/info-reader/ego-reader.cpp
  src/info-reader/general-parser.cpp
  src/info-reader/kind-info-tokens-table.cpp
  src/info-reader/kind-info-tokens-table.h
  src/info-reader/kind-reader.cpp
  src/load/load-v1-5-0.cpp
  src/load/quest-loader.cpp
  src/object-enchant/apply-magic.cpp
  src/object-enchant/object-ego.h
  src/object-enchant/trg-types.h
  src/object-hook/hook-quest.cpp
  src/object/object-generator.cpp
  src/object/object-kind.h
  src/perception/object-perception.cpp
  src/racial/racial-android.cpp
  src/spell/spells-object.cpp
  src/system/artifact-type-definition.h
  src/util/flag-group.h
  src/wizard/artifact-analyzer.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/wizard-special-process.cpp
Labels: enhancement

#483 [Feature] 通常エゴと呪いエゴの選出ルーチンを変更
  src/object-enchant/apply-magic-armor.cpp
  src/object-enchant/apply-magic-weapon.cpp
  src/object-enchant/apply-magic.cpp
  src/object-enchant/object-ego.cpp
Labels: enhancement

#481 [Feature/Fix] 地獄、時間、水属性の追加実装と不具合の修正 #473 #474 #476
  src/effect/effect-player-resist-hurt.cpp
  src/flavor/flag-inscriptions-table.cpp
  src/flavor/flag-inscriptions-table.h
  src/flavor/flavor-util.cpp
  src/object-enchant/object-boost.cpp
  src/object/object-value-calc.cpp
  src/perception/identification.cpp
  src/player/permanent-resistances.cpp
  src/player/player-status-flags.cpp
  src/player/player-status-resist.cpp
  src/player/player-status-resist.h
Labels: bug, enhancement, refactor

#491 [Feature] 武蔵セットの強化
  lib/edit/a_info.txt
  src/artifact/fixed-art-generator.cpp
  src/player/player-status.cpp
  src/wizard/artifact-analyzer.cpp
  src/wizard/spoiler-table.cpp
  src/wizard/spoiler-table.h
Labels: enhancement

#493 [fix] FlagGroupの定数定義をクラス定義の冒頭に移動する
  src/util/flag-group.h
Labels: bug

#486 [Feature] アーティファクト性能の調整 α11
  lib/edit/a_info.txt
  lib/edit/q0000004.txt
Labels: enhancement

#501 [Version] 3.0.0Alpha11
  src/system/angband-version.h
Labels: release

#506 [Fix] モンスター自爆効果が無限連鎖する #505
  src/effect/effect-monster.cpp
Labels: bug

#508 [add] 自動更新スポイラーdeploy用Workflowにautoconf-archive追加
  .github/workflows/publish-spoiler-page.yml
Labels: bug

#516 [Fix] 隠密計算に職業の基礎値が足されていない #515
  src/player-status/player-stealth.cpp
  src/player-status/player-stealth.h
Labels: bug

#514 [Fix] どのビーム魔法でも足元のペットに効果がない旨が表示される #510
  src/effect/effect-monster.cpp
Labels: bug

#513 [Fix] 足元にお金か未発見アイテムだけになると床上のアイテム一覧が無限ループ #512
  src/window/display-sub-windows.cpp
Labels: bug

#519 Release/3.0.0 alpha12
  .github/workflows/publish-spoiler-page.yml
  src/effect/effect-monster.cpp
  src/player-status/player-stealth.cpp
  src/player-status/player-stealth.h
  src/system/angband-version.h
  src/window/display-sub-windows.cpp
Labels: release

#518 [Version] 3.0.0Alpha12
  src/system/angband-version.h
Labels: release

#503 [Fix] 狂戦士が狂戦士化の薬を飲んだときにメッセージが出る #499
  src/status/buff-setter.cpp
Labels: bug

#529 [Fix/Refactor] 吸血鬼が普通に食事していた/食事の処理の整理 #526
  src/cmd-item/cmd-eat.cpp
Labels: bug, refactor

#509 [fix/refactor] clangのWarning対策
  src/artifact/random-art-characteristics.cpp
  src/maid-x11.cpp
  src/store/rumor.cpp
  src/system/system-variables.cpp
Labels: bug, refactor

#524 [Fix] get_check()でauto_more使用時にプロンプト用の文字列を破棄してしまってから一時バッファにコピーしている #523
  src/core/asking-player.cpp
Labels: bug

#535 [Feature] マーフォークの固定徳を「然」に指定．
  src/player-info/avatar.cpp
Labels: bug, enhancement

#537 [Fix] 毒の沼のダメージ計算式バグを修正
  src/core/hp-mp-processor.cpp
Labels: bug

#522 [Feature] 自動スポイラー作成に騎乗可能モンスター一覧を追加
  src/wizard/monster-info-spoiler.cpp
  src/wizard/monster-info-spoiler.h
  src/wizard/wizard-spoiler.cpp
Labels: enhancement

#500 [Feature] 思い出にユニーク/ナズグル系の生存情報を表示する
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/lore/monster-lore.cpp
  src/view/display-lore-attacks.cpp
  src/view/display-lore-drops.cpp
  src/view/display-lore-magics.cpp
  src/view/display-lore-status.cpp
  src/view/display-lore.cpp
Labels: enhancement

#226 [Refactor] グローバル変数 tmp_pos を消去
  src/floor/floor-generator.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/monster-floor/monster-lite.cpp
  src/player/player-view.cpp
  src/room/cave-filler.cpp
  src/specific-object/torch.cpp
  src/spell-kind/spells-lite.cpp
  src/target/grid-selector.cpp
  src/target/target-preparation.cpp
  src/target/target-preparation.h
  src/target/target-setter.cpp
Labels: refactor

#542 [Feature] doxyfile　のバージョン更新、cppを解析対象に．
  doxygen/Hengband.doxyfile
Labels: documentation

#541 [Feature] Windowsの高DPI環境での表示改善
  src/main-win.cpp
Labels: enhancement

#544 [Fix] 日が変わっても日替わり賞金首の知識を更新していなかった #536
  src/cmd-building/cmd-building.cpp
  src/cmd-building/cmd-building.h
  src/load/world-loader.cpp
  src/market/bounty.cpp
  src/monster-floor/monster-death.cpp
  src/object-hook/hook-quest.cpp
  src/player/player-status.h
  src/save/player-writer.cpp
  src/world/world.h
Labels: bug

#520 [feature] 確率テーブルクラス
  src/Makefile.am
  src/main/game-data-initializer.cpp
  src/monster/monster-list.cpp
  src/object-enchant/object-ego.cpp
  src/room/room-generator.cpp
  src/room/rooms-pit-nest.cpp
  src/system/alloc-entry-definition.h
  src/util/probability-table.h
  src/world/world-object.cpp
Labels: enhancement, refactor

#543 [Fix] *.rawの更新がされず齟齬が生じる可能性がある / TRGフラグのクラス化で番号の付け違い
  src/info-reader/general-parser.cpp
  src/io-dump/character-dump.cpp
  src/main/angband-headers.h
  src/main/info-initializer.cpp
  src/object-enchant/trg-types.h
Labels: bug

#540 [feature] Linux/UNIX環境におけるビルド/ビルドチェックWorkflowの改善
  .github/workflows/buildtest-on-linux.yml
  configure.ac
  src/Makefile.am
  src/artifact/random-art-generator.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-building/cmd-inn.cpp
  src/cmd-item/cmd-equipment.cpp
  src/combat/shoot.cpp
  src/combat/slaying.cpp
  src/flavor/flavor-describer.cpp
  src/flavor/object-flavor.cpp
  src/floor/floor-object.cpp
  src/io/uid-checker.cpp
  src/lore/combat-types-setter.cpp
  src/maid-x11.cpp
  src/market/building-recharger.cpp
  src/melee/melee-switcher.cpp
  src/mind/mind-mindcrafter.cpp
  src/mind/mind-weaponsmith.cpp
  src/monster-attack/monster-attack-describer.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/object-enchant/apply-magic-accessory.cpp
  src/object-enchant/apply-magic-armor.cpp
  src/object-enchant/apply-magic-others.cpp
  src/object-enchant/apply-magic-weapon.cpp
  src/object-hook/hook-bow.cpp
  src/object-hook/hook-weapon.cpp
  src/object/object-broken.cpp
  src/object/object-info.cpp
  src/object/object-value.cpp
  src/object/warning.cpp
  src/perception/identification.cpp
  src/perception/simple-perception.cpp
  src/player-info/avatar.cpp
  src/player-info/class-ability-info.cpp
  src/player/eldritch-horror.cpp
  src/player/player-status-flags.cpp
  src/player/player-status-resist.cpp
  src/player/player-status.cpp
  src/racial/racial-draconian.cpp
  src/realm/realm-hex.cpp
  src/util/object-sort.cpp
  src/window/display-sub-windows.cpp
  src/wizard/wizard-spoiler.cpp
Labels: enhancement

#549 [Fix] ブロンズ・クロスを発動で脱ぐと裸にtimeoutが設定される #547
  src/action/activation-execution.cpp
  src/object-activation/activation-switcher.cpp
  src/object-activation/activation-switcher.h
  src/spell/spells-status.cpp
  src/spell/spells-status.h
Labels: bug

#551 [Refactor] メンバ関数の命名規則の統一
  src/player-status/player-basic-statistics.cpp
  src/player-status/player-basic-statistics.h
  src/player-status/player-charisma.cpp
  src/player-status/player-charisma.h
  src/player-status/player-status-base.cpp
  src/player-status/player-status-base.h
  src/player-status/player-stealth.cpp
  src/player-status/player-stealth.h
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
Labels: refactor

#552 [Feature] 元素使いをXAngbandから移植実装
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  lib/edit/m_info.txt
  lib/edit/s_info.txt
  lib/edit/t0000001.txt
  src/Makefile.am
  src/artifact/random-art-generator.cpp
  src/birth/birth-explanations-table.cpp
  src/birth/birth-select-realm.cpp
  src/birth/initial-equipments-table.cpp
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-monster.cpp
  src/io/input-key-processor.cpp
  src/io/store-key-processor.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-elementalist.h
  src/mind/mind-types.h
  src/perception/simple-perception.cpp
  src/player-info/avatar.cpp
  src/player-info/class-ability-info.cpp
  src/player/permanent-resistances.cpp
  src/player/player-class.cpp
  src/player/player-classes-types.h
  src/player/player-realm.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/player/race-info-table.cpp
  src/racial/class-racial-switcher.cpp
  src/racial/racial-draconian.cpp
  src/racial/racial-switcher.cpp
  src/spell/spell-types.h
  src/spell/spells-staff-only.cpp
  src/view/display-player.cpp
  src/window/display-sub-window-spells.cpp
Labels: enhancement

#563 [fix] キャラクタ作成時のメモリリークの可能性
  src/birth/game-play-initializer.cpp
  src/load/inventory-loader.cpp
Labels: bug

#559 [Fix] 自殺時もゲームオーバーBGMを鳴らすように修正．
  src/cmd-action/cmd-others.cpp
Labels: bug

#561 [Feature] 願いコマンドをwizardモード用に実装
  src/util/string-processor.cpp
  src/util/string-processor.h
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-item-modifier.h
Labels: enhancement

#548 [Fix] 自分をターゲットとしない範囲魔法に巻き込まれたときラーニングできない #533
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/blue-magic/blue-magic-checker.cpp
  src/blue-magic/blue-magic-checker.h
  src/effect/effect-player.cpp
  src/effect/effect-player.h
  src/effect/effect-processor.cpp
  src/effect/effect-processor.h
  src/melee/melee-spell.cpp
  src/monster-floor/quantum-effect.cpp
  src/mspell/assign-monster-spell.cpp
  src/mspell/assign-monster-spell.h
  src/mspell/mspell-attack.cpp
  src/mspell/mspell-ball.cpp
  src/mspell/mspell-ball.h
  src/mspell/mspell-bolt.cpp
  src/mspell/mspell-bolt.h
  src/mspell/mspell-breath.cpp
  src/mspell/mspell-breath.h
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-checker.h
  src/mspell/mspell-curse.cpp
  src/mspell/mspell-curse.h
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-dispel.h
  src/mspell/mspell-floor.cpp
  src/mspell/mspell-floor.h
  src/mspell/mspell-particularity.cpp
  src/mspell/mspell-particularity.h
  src/mspell/mspell-special.cpp
  src/mspell/mspell-special.h
  src/mspell/mspell-status.cpp
  src/mspell/mspell-status.h
  src/mspell/mspell-summon.cpp
  src/mspell/mspell-summon.h
  src/mspell/mspell.h
  src/spell-kind/spells-launcher.cpp
  src/spell-kind/spells-neighbor.cpp
  src/spell-kind/spells-sight.cpp
Labels: bug

#568 [Fix] 乗馬中探索モードに入ると右下表記がおかしくなる #565
  src/player-status/player-speed.cpp
  src/window/main-window-stat-poster.cpp
Labels: bug

#567 [Fix] モンスターメッセージ中の「サンダー・・ボール」を「サンダー・ボール」に修正. / Fix Japanese lighting …
  src/mspell/mspell-ball.cpp
Labels: bug

#569 [feature] 各種構造体のPOD型としての扱いをやめる #564
  src/autopick/autopick-util.cpp
  src/main/game-data-initializer.cpp
  src/main/info-initializer.cpp
  src/term/z-virt.h
Labels: enhancement

#562 [Fix] キャラクタメイク時の経験値修正に職業の修正が入っていない #554
  src/birth/birth-stat.cpp
  src/birth/birth-stat.h
  src/birth/birth-wizard.cpp
Labels: bug

#557 [Feature] 元素使いの調整
  src/birth/inventory-initializer.cpp
  src/io/read-pref-file.cpp
  src/io/report.cpp
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-self.cpp
  src/mind/mind-elementalist.cpp
  src/object-hook/hook-magic.cpp
Labels: enhancement

#572 [Refactor] main-win.cppの分割
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/main-win.cpp
  src/main-win/main-win-bg.cpp
  src/main-win/main-win-bg.h
  src/main-win/main-win-define.h
  src/main-win/main-win-file-utils.cpp
  src/main-win/main-win-file-utils.h
  src/main-win/main-win-mci.cpp
  src/main-win/main-win-mci.h
  src/main-win/main-win-mmsystem.h
  src/main-win/main-win-music.cpp
  src/main-win/main-win-music.h
  src/main-win/main-win-sound.cpp
  src/main-win/main-win-sound.h
  src/main-win/main-win-tokenizer.cpp
  src/main-win/main-win-tokenizer.h
  src/main-win/main-win-windows.h
Labels: refactor

#574 [Fix] ドラゴンピットの多色化問題
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/monster-race/monster-race-hook.cpp
  src/room/pit-nest-kinds-table.cpp
  src/room/pit-nest-kinds-table.h
  src/room/rooms-pit-nest.cpp
  src/room/rooms-pit-nest.h
Labels: bug, enhancement

#534 [Fix] apply-magic-armor.cppの無限ループになる可能性のある場所を解消．
  src/object-enchant/apply-magic-armor.cpp
Labels: enhancement

#576 [Fix] ドラゴンピットの多色化(再修正) #574
  src/monster-race/monster-race-hook.cpp
Labels: bug

#571 [fix] 構造体のゼロクリアの条件
  src/term/z-virt.h
Labels: bug

#579 [Fix] Wizardモードのモンスター闘技場のHP/MP表示 #577
  src/window/main-window-left-frame.cpp
Labels: bug

#581 [Fix] 元素使いの領域選択でシンボルキーで選択した場合の挙動
  src/mind/mind-elementalist.cpp
Labels: bug

#582 [Fix] #574のリファクタリングでファイルが消えていなかった
  src/room/pit-nest-kinds-table.cpp
  src/room/pit-nest-kinds-table.h
  src/room/rooms-pit-nest.cpp
Labels: bug

#586 [Fix/Feature] VisualStudioでプリコンパイルヘッダ導入
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  Hengband/Hengband/stdafx.cpp
  Hengband/Hengband/stdafx.h
Labels: bug, enhancement

#575 [Fix] Windows英語版でメニューバーが日本語 #573
  Hengband/Hengband/Hengband.vcxproj
  src/ang_eng.rc
  src/ang_jp.rc
  src/angband.rc
Labels: bug

#583 [Linux/Unix] include src/main-win/* in the files packaged with "make dist"
  src/Makefile.am
Labels: bug

#578 [Fix] キー定義のないマクロ定義を読み込んで誤爆登録する #418
  src/cmd-io/macro-util.cpp
  src/io/interpret-pref-file.cpp
Labels: bug

#570 [Refactor] ralloc(), rnfree(), rpanic() の削除
  src/autopick/autopick-editor-util.cpp
  src/main-win.cpp
  src/term/z-virt.cpp
  src/term/z-virt.h
Labels: refactor

#590 [Fix] 元素使いのレベルによる耐性のチェックで職業を加味していない
  src/mind/mind-elementalist.cpp
Labels: bug

#591 [Fix] 元素使いのダンプで免疫の表示がおかしい(+になる)
  src/player/permanent-resistances.cpp
  src/player/race-resistances.cpp
Labels: bug

#592 [Fix] 元素魔法の説明と実際の属性の食い違い
  src/mind/mind-elementalist.cpp
  src/player/patron-valar.cpp
  src/player/patron-valar.h
Labels: bug

#593 fix: いらないファイルをaddしてしまった
  src/player/patron-valar.cpp
  src/player/patron-valar.h
Labels: refactor

#594 [Version] 3.0.0Alpha13
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#597 [Fix] fresh_onceオプション使用時、マクロ使用直後にサブウィンドウが更新されない
  src/io/input-key-acceptor.cpp
  src/io/input-key-acceptor.h
  src/term/z-term.cpp
  src/term/z-term.h
Labels: bug

#600 [feature] Linux/UNIX環境でのビルドにプリコンパイルヘッダを導入
  .gitignore
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/stdafx.cpp
  src/stdafx.h
Labels: enhancement

#609 [Fix] ナズグル系ではないモンスターの思い出にXX体生きていると表示 #608
  src/view/display-lore.cpp
Labels: bug

#615 [Fix] 吸血鬼が食料やキノコを食べても数が減らない #614
  src/cmd-item/cmd-eat.cpp
Labels: bug

#612 [FIx] 未鑑定の罠感知のロッド等を使用して罠が感知されたときに未感知エリアにならない #611
  src/spell-kind/spells-detection.cpp
Labels: bug

#613 [fix] playrecordに未判明アイテムの識別が記録されない #610
  src/perception/object-perception.cpp
Labels: bug

#620 [refactor] VSが出力する警告に対処
  src/load/load-v1-5-0.cpp
  src/load/monster-loader.cpp
  src/monster-race/race-flags4.h
  src/player-status/player-basic-statistics.cpp
  src/player/player-view.cpp
  src/target/target-preparation.cpp
Labels: refactor

#622 [Refactor] main-win系処理のVS警告への対処
  src/main-win/main-win-bg.cpp
  src/main-win/main-win-music.cpp
Labels: refactor

#624 [Fix] 元素使いで魔法を失敗し魔力が氾濫したときにMPが更新されない #623
  src/mind/mind-elementalist.cpp
Labels: bug

#621 [fix] sanity_blast時にモンスターの表示位置がずれる #330
  src/core/player-processor.cpp
  src/monster/monster-flag-types.h
  src/monster/monster-update.cpp
Labels: bug

#598 [Feature/Fix] 元素使いの修正や調整
  lib/edit/t0000001.txt
  lib/edit/t_lite.txt
  lib/pref/spell-xx.prf
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/effect/effect-feature.cpp
  src/effect/effect-item.cpp
  src/effect/effect-monster-resist-hurt.cpp
  src/effect/effect-monster-resist-hurt.h
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/io/gf-descriptions.cpp
  src/io/gf-descriptions.h
  src/io/input-key-processor.cpp
  src/mind/mind-elementalist.cpp
  src/object/object-info.cpp
  src/player/player-status-flags.cpp
  src/player/player-status-resist.cpp
  src/player/player-status-resist.h
  src/player/race-info-table.cpp
  src/spell/spell-types.h
  src/view/object-describer.cpp
Labels: bug, enhancement, refactor

#628 [Feature] トラベルコマンド等で、建物(+)と店(0-9)の位置を文字入力で指定できる #627
  src/target/grid-selector.cpp
Labels: enhancement

#630 [Fix/Feature] 飛行モンスターが深い穴を超えられない現象を解消 #177
  src/floor/floor-generator.cpp
  src/floor/floor-util.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/target/target-describer.cpp
Labels: bug, enhancement, refactor

#632 [Fix] モンスターがモンスターに対して撃った暗闇が常にライトエリア #631
  src/mspell/mspell-floor.cpp
Labels: bug

#629 [Refactor] ZAngbandバージョンの廃止
  src/load/angband-version-comparer.cpp
  src/load/angband-version-comparer.h
  src/load/birth-loader.cpp
  src/load/extra-loader.cpp
  src/load/info-loader.cpp
  src/load/load-v1-5-0.cpp
  src/load/load-zangband.cpp
  src/load/load-zangband.h
  src/load/load.cpp
  src/load/option-loader.cpp
  src/load/player-attack-loader.cpp
  src/load/player-info-loader.cpp
  src/load/quest-loader.cpp
  src/load/store-loader.cpp
  src/load/world-loader.cpp
  src/system/angband-version.h
  src/world/world.h
Labels: refactor

#633 [Refactor] BGM選曲のリファクタリング
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/main-win.cpp
  src/main-win/main-win-music.cpp
  src/main-win/main-win-music.h
  src/main/scene-table.cpp
  src/main/scene-table.h
  src/main/sound-of-music.cpp
  src/term/z-term.h
Labels: enhancement, refactor

#638 [Fix] ソースコード内 typo の修正
  src/info-reader/parse-error-types.h
  src/info-reader/race-reader.cpp
  src/main.cpp
Labels: refactor

#641 [Feature] ワーグクエスト系のクエストを放棄できるように変更 #607
  lib/edit/q_warg.txt
  lib/edit/t0000001.txt
  src/market/building-quest.cpp
Labels: enhancement

#645 [Version] 3.0.0Alpha14
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#648 [Fix] ワーグクエストの報酬が報酬時と成功後次クエスト移行時の2回報酬を落としていた
  lib/edit/t0000001.txt
Labels: bug

#650 [Fix] セーブバージョン1の旧友好/ペットフラグを読んで移行してから新友好/ペットフラグをクリアしている
  src/load/monster-loader.cpp
Labels: bug

#654 [Version] 3.0.0Alpha15.
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#655 Release/3.0.0 alpha15
  doxygen/Hengband.doxyfile
  lib/edit/t0000001.txt
  src/load/monster-loader.cpp
  src/system/angband-version.h
Labels: release

#658 [fix] obj-desc.txtの出力がおかしい #657
  src/wizard/items-spoiler.cpp
Labels: bug

#659 [fix] C_WIPEで先頭の要素しかクリアされていない
  src/term/z-virt.h
Labels: bug

#651 [Fix] 天然生成のアーティファクトでXTRA_DICEが無効になる
  src/artifact/fixed-art-generator.cpp
  src/artifact/fixed-art-generator.h
  src/object-enchant/apply-magic.cpp
Labels: bug

#660 [Feature] 啓蒙/周辺感知で壁の中の壁も感知する / 壁に囲まれた壁を表示するオプション #643
  src/game-option/map-screen-options.cpp
  src/game-option/map-screen-options.h
  src/game-option/option-types-table.cpp
  src/game-option/option-types-table.h
  src/spell-kind/spells-floor.cpp
  src/view/display-map.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-util.cpp
Labels: enhancement

#663 [Add] 日本語版ヘルプに「危険な地形」追加． / Add "Dangerous Terrain" to Japanese help file.
  lib/help/jdungeon.hlp
  lib/help/jdungeon.txt
Labels: documentation
