Repository hengband/hengband, pull requests merged in 2021-04, with the labels that each got.

#671 [Refactor] 地形によるダメージの耐性計算をcalc_*_damage_rate()で行う #664
  src/core/hp-mp-processor.cpp
Labels: refactor

#681 [fix] 探索モード中に探索コマンドを実行するとその場に留まるより損をする #680
  src/cmd-action/cmd-others.cpp
Labels: bug

#684 [Refactor] Point構造体の定義を一箇所にまとめる
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/grid/grid.cpp
  src/monster-floor/monster-lite.cpp
  src/player/player-view.cpp
  src/room/cave-filler.cpp
  src/specific-object/torch.cpp
  src/spell-kind/spells-lite.cpp
  src/util/point-2d.h
Labels: refactor

#676 [Feature] キャラメイク時にキャラ名を変えてもロードしたセーブファイルのままスタートするオプション #126
  src/game-option/birth-options.cpp
  src/game-option/birth-options.h
  src/game-option/option-types-table.cpp
  src/game-option/option-types-table.h
  src/player/process-name.cpp
Labels: enhancement

#688 [Fix/refactor] MPがある職にもかかわらず知識の石の発動でMPを消費しない #685
  src/spell/spells-object.cpp
Labels: bug, refactor

#674 [Fix] ものまね師が攻撃魔法のダメージを記憶できなかったので修正 #548 #673
  src/melee/melee-spell.cpp
  src/mspell/mspell-attack-util.cpp
  src/mspell/mspell-attack.cpp
  src/mspell/mspell-ball.cpp
  src/mspell/mspell-bolt.cpp
  src/mspell/mspell-breath.cpp
  src/mspell/mspell-curse.cpp
  src/mspell/mspell-particularity.cpp
  src/mspell/mspell-status.cpp
  src/mspell/mspell.h
Labels: bug

#691 [Feature] サブウィンドウフラグを't'でトグルする #686 / [Fix] 1つのサブウィンドウに複数のフラグがセットできる
  src/cmd-io/cmd-gameoption.cpp
Labels: enhancement, refactor

#693 [Fix] INSTA_ARTの追加耐性と能力が2回追加される(#651のエンバグ)
  src/artifact/fixed-art-generator.cpp
Labels: bug

#696 [Fix] 装備してない欄の(なし)の表記が(なし) {未判明}などになる #695
  src/birth/game-play-initializer.cpp
  src/flavor/flavor-describer.cpp
Labels: bug

#683 [documentation] align the contents of dungeon.txt with jdungeon.txt
  lib/help/dungeon.hlp
  lib/help/dungeon.txt
Labels: documentation

#698 [Add] ウィザードモードのyコマンド解説を追記 / Add description wizard 'y' command.
  src/wizard/cmd-wizard.cpp
Labels: enhancement

#706 [fix] msg_printでredraw_stuffを呼ばないようにする #704
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-action/cmd-move.cpp
  src/core/game-play.cpp
  src/core/output-updater.cpp
  src/core/output-updater.h
  src/view/display-messages.cpp
Labels: bug

#701 [Fix] ペットを捕まえた直後にペット維持が更新されない #699
  src/effect/effect-monster-charm.cpp
  src/specific-object/monster-ball.cpp
Labels: bug

#711 [Fix] 呪文選択で大文字選択のときの確認で属性が表示されない(%sのまま) #703
  src/mind/mind-elementalist.cpp
Labels: bug

#702 [Feature] α16に向けたアーティファクト、エゴ、モンスターの追加及び調整
  lib/edit/a_info.txt
  lib/edit/e_info.txt
  lib/edit/misc.txt
  lib/edit/r_info.txt
  src/mspell/mspell-breath.cpp
  src/object-enchant/apply-magic.cpp
Labels: bug

#713 [Fix] デバグコマンドの数字の入力に関する修正 / [Feature] 領域変更の追加
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-player-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-special-process.h
Labels: bug, enhancement

#715 [Version] 3.0.0Alpha16
  src/system/angband-version.h
Labels: release

#656 [Fix] アイテム選択時にアルファベットのタグを選択すると!*の確認が無視される #642
  src/inventory/floor-item-getter.cpp
  src/inventory/item-getter.cpp
Labels: bug, refactor

#717 [refactor] 未使用MenuItem関連のデッドコードを削除
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/ang_eng.rc
  src/ang_jp.rc
  src/main-win.cpp
  src/main-win/main-win-menuitem.h
Labels: refactor

#726 [Fix] 死を欺くオプション後状態異常が回復しなかった / Not restored bad statuses after cheat death.
  src/spell/spells-status.cpp
  src/wizard/wizard-special-process.cpp
Labels: bug

#724 [Feature] 技能値の実値表示オプションで徳の善悪属性の実値も表示する #720
  src/game-option/birth-options.cpp
  src/game-option/option-types-table.cpp
  src/game-option/text-display-options.cpp
  src/player-info/avatar.cpp
  src/player/player-status.cpp
Labels: enhancement

#728 [Fix] 床上のアイテムを選択する場合にタグがないとクラッシュ
  src/inventory/floor-item-getter.cpp
Labels: bug

#723 [Feature] 店舗商品入れ替え処理の向上
  src/io/store-key-processor.cpp
  src/load/store-loader.cpp
  src/market/building-initializer.cpp
  src/store/store-util.cpp
  src/store/store-util.h
  src/store/store.cpp
  src/store/store.h
Labels: bug, enhancement

#719 [Add] 不滅チートオプション実装．　/ Implement cheat_immortal.
  src/birth/game-play-initializer.cpp
  src/core/game-play.cpp
  src/core/player-processor.cpp
  src/dungeon/dungeon-processor.cpp
  src/game-option/cheat-options.cpp
  src/game-option/cheat-options.h
  src/game-option/option-types-table.cpp
  src/game-option/option-types-table.h
  src/io/signal-handlers.cpp
  src/load/option-loader.cpp
  src/player/player-damage.cpp
  src/save/info-writer.cpp
Labels: enhancement

#733 [Feature] 一部アイテムのベース名表示で#が残らないように変更
  src/flavor/object-flavor.cpp
Labels: bug, enhancement

#732 [Fix] モンスターボールがHPの低すぎるモンスターを捕まえられない #731
  src/effect/effect-monster-charm.cpp
Labels: bug, refactor

#734 [Feature] 罠未感知エリアの壁の中に囲まれた壁を表示するオプション #643
  src/game-option/map-screen-options.cpp
  src/game-option/map-screen-options.h
  src/game-option/option-types-table.cpp
  src/game-option/option-types-table.h
  src/view/display-map.cpp
Labels: enhancement

#740 [Fix] Linx/Mac版で徳の実値表示がおかしい
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-self.cpp
  src/player-info/avatar.cpp
  src/player/player-status.cpp
  src/player/player-status.h
  src/view/display-player.cpp
  src/view/display-self-info.cpp
Labels: bug

#744 [Refactor] 固定アーティファクト生成ルーチンの統一 #694
  src/artifact/fixed-art-generator.cpp
Labels: bug, refactor

#748 [Feature/Refactor] ハードコーディングされているエゴ生成フラグをe_info.txtで定義できる
  lib/edit/e_info.txt
  src/info-reader/ego-reader.cpp
  src/object-enchant/apply-magic-armor.cpp
  src/object-enchant/apply-magic-weapon.cpp
  src/object-enchant/apply-magic.cpp
  src/object-enchant/object-ego.cpp
  src/object-enchant/object-ego.h
  src/wizard/wizard-item-modifier.cpp
Labels: enhancement, refactor

#749 [Fix] スペルマスターが全ての武器を得意武器として自動拾いする #736
  src/object-hook/hook-weapon.cpp
Labels: bug

#751 [MISC] autopick.txtの変数説明に新種族と新職業を追加
  autopick.txt
  autopick_eng.txt
Labels: documentation

#753 [Refactor] LOW_MAGICをHARD_SPELLに改名 / [Fix] DOWN_SAVINGの説明の表示がおかしい
  src/cmd-item/cmd-smith.cpp
  src/info-reader/kind-info-tokens-table.cpp
  src/inventory/inventory-curse.cpp
  src/object-enchant/tr-types.h
  src/object-enchant/trc-types.h
  src/object/object-value-calc.cpp
  src/perception/identification.cpp
  src/player-info/self-info.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
Labels: bug, refactor

#750 [Fix] 元素使い系統を第一領域と共有したことによる不具合
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/birth/birth-select-realm.cpp
  src/birth/quick-start.cpp
  src/birth/quick-start.h
  src/io/read-pref-file.cpp
  src/io/report.cpp
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-self.cpp
  src/load/player-info-loader.cpp
  src/mind/mind-elementalist.cpp
  src/object-hook/hook-magic.cpp
  src/object/object-info.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.h
  src/racial/racial-draconian.cpp
  src/save/player-writer.cpp
  src/view/display-player.cpp
  src/view/object-describer.cpp
Labels: bug, refactor

#745 [Feature] 文字列操作ユーティリティ関数
  src/util/string-processor.cpp
  src/util/string-processor.h
Labels: enhancement

#737 [Refactor] 店舗関係のコードをstore/以下に集約
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/io/input-key-processor.cpp
  src/market/building-initializer.cpp
  src/store/articles-on-sale.cpp
  src/store/articles-on-sale.h
  src/store/cmd-store.cpp
  src/store/cmd-store.h
  src/store/gold-magnification-table.cpp
  src/store/gold-magnification-table.h
  src/store/pricing.cpp
  src/store/store-key-processor.cpp
  src/store/store-key-processor.h
Labels: refactor

#754 [Fix] 【バグ】fresh_onceを入れてマクロでターゲッティングするとモンスターの思い出サブウィンドウが更新されない #742
  src/io/input-key-acceptor.cpp
  src/io/input-key-requester.cpp
Labels: bug

#739 [Fix] savefile_baseが更新されず、一時ファイルとplayrecord.txtのファイル名がおかしい #738
  src/birth/quick-start.cpp
  src/cmd-visual/cmd-draw.cpp
  src/core/game-play.cpp
  src/player/process-name.cpp
  src/player/process-name.h
Labels: bug, refactor

#759 [Fix] ダークエルフの種族レイシャルパワーが表示されない #758
  src/term/z-form.cpp
Labels: bug

#761 [Fix] ターゲッティング等の入力待ちでカーソル位置がおかしい #760
  src/io/input-key-acceptor.cpp
Labels: bug

#757 [Feature] 店舗での価格交渉を削除
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  lib/pref/pref-opt.prf
  src/Makefile.am
  src/game-option/birth-options.cpp
  src/game-option/birth-options.h
  src/game-option/option-types-table.cpp
  src/store/owner-insults.cpp
  src/store/owner-insults.h
  src/store/pricing.cpp
  src/store/pricing.h
  src/store/purchase-order.cpp
  src/store/say-comments.cpp
  src/store/say-comments.h
  src/store/sell-order.cpp
  src/store/store-owner-comments.cpp
  src/store/store-owner-comments.h
  src/store/store-owners.cpp
  src/store/store-owners.h
  src/store/store-util.h
  src/view/display-store.cpp
Labels: enhancement, refactor

#727 [Feature] モンスター遭遇時にBGMを再生する
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  lib/xtra/music/music.cfg
  src/Makefile.am
  src/core/window-redrawer.cpp
  src/main-win.cpp
  src/main-win/main-win-cfg-reader.cpp
  src/main-win/main-win-cfg-reader.h
  src/main-win/main-win-music.cpp
  src/main-win/main-win-music.h
  src/main/music-definitions-table.cpp
  src/main/music-definitions-table.h
  src/main/scene-table-floor.cpp
  src/main/scene-table-floor.h
  src/main/scene-table-monster.cpp
  src/main/scene-table-monster.h
  src/main/scene-table.cpp
  src/main/scene-table.h
  src/main/sound-of-music.cpp
  src/main/sound-of-music.h
  src/term/z-term.h
  src/window/display-sub-windows.cpp
Labels: enhancement

#764 [Version] 3.0.0Alpha17
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#770 [Fix] 能力値実値併記オプションで武器/魔法/技能の経験値を表示しない #768
  src/knowledge/knowledge-experiences.cpp
Labels: bug, enhancement

#779 [Fix] プリーストが生命と破邪を選べない
  src/birth/birth-select-realm.cpp
Labels: bug

#780 [Feature] Win版メニューのオプションをタイトル画面やキャラメイク中も切り替え可能にする
  src/main-win.cpp
Labels: enhancement

#777 [Fix] 見えていないモンスターのダメージメッセージが不自然に流れる。 / Unnatural message by damage of unseen monsters.
  src/effect/effect-monster.cpp
  src/monster/monster-describer.cpp
Labels: bug

#789 [Fix] 指定した時だけキー入力待ち時の再描画を行う
  src/io/input-key-acceptor.cpp
  src/io/input-key-acceptor.h
  src/io/input-key-requester.cpp
Labels: bug

#788 [FIx] 刻んだ銘タグでアイテムを選ぶとき大文字で警告が出る #786
  src/inventory/floor-item-getter.cpp
  src/inventory/item-getter.cpp
Labels: bug

#798 Release/3.0.0 alpha18
  doxygen/Hengband.doxyfile
  src/birth/birth-select-realm.cpp
  src/core/window-redrawer.cpp
  src/effect/effect-monster.cpp
  src/inventory/floor-item-getter.cpp
  src/inventory/item-getter.cpp
  src/io/input-key-acceptor.cpp
  src/io/input-key-acceptor.h
  src/io/input-key-requester.cpp
  src/knowledge/knowledge-experiences.cpp
  src/main-win.cpp
  src/main/scene-table.cpp
  src/monster/monster-describer.cpp
  src/system/angband-version.h
Labels: release

#797 [Version] 3.0.0Alpha18
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#801 [Fix] Linux/MacOSX版で元素使いで新規開始及びクイックスタートができなくなっていた
  src/birth/birth-select-realm.cpp
  src/load/player-info-loader.cpp
Labels: bug

#803 [Refactor] 意味もなく引き回しているprocess_autopick_file_command引数の削除
  src/autopick/autopick-reader-writer.cpp
  src/birth/birth-wizard.cpp
  src/birth/birth-wizard.h
  src/birth/character-builder.cpp
  src/birth/character-builder.h
  src/birth/history-editor.cpp
  src/birth/history-editor.h
  src/cmd-io/cmd-autopick.cpp
  src/cmd-io/cmd-dump.cpp
  src/cmd-io/cmd-dump.h
  src/cmd-io/cmd-macro.cpp
  src/cmd-io/cmd-macro.h
  src/cmd-io/cmd-process-screen.cpp
  src/cmd-io/cmd-process-screen.h
  src/cmd-visual/cmd-visuals.cpp
  src/cmd-visual/cmd-visuals.h
  src/core/game-play.cpp
  src/core/visuals-reseter.cpp
  src/core/visuals-reseter.h
  src/io/input-key-processor.cpp
  src/io/read-pref-file.cpp
  src/io/read-pref-file.h
  src/io/report.cpp
  src/io/report.h
  src/main-win.cpp
  src/main.cpp
  src/main/angband-initializer.cpp
  src/main/angband-initializer.h
  src/monster/monster-status.cpp
  src/player/player-damage.cpp
  src/store/store-key-processor.cpp
Labels: refactor

#805 [MISC] 不要なincludeの削除、未参照パラメーター警告の抑制、参照型の代入修正
  src/main-win.cpp
  src/main-win/main-win-music.cpp
Labels: refactor

#806 [Fix] ワーグタイプ以外のクエストが放棄できるのを修正 / 放棄時間が記録されないのを修正
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/market/building-quest.cpp
Labels: bug

#769 [Feature] α19に向けたアイテムの能力追加及び調整
  lib/edit/a_info.txt
  lib/edit/e_info.txt
  lib/edit/k_info.txt
  lib/edit/misc.txt
  src/artifact/artifact-info.cpp
  src/artifact/random-art-effects.h
  src/artifact/random-art-misc.cpp
  src/artifact/random-art-slay.cpp
  src/cmd-item/cmd-smith.cpp
  src/combat/attack-criticality.cpp
  src/combat/attack-criticality.h
  src/combat/shoot.cpp
  src/flavor/flag-inscriptions-table.cpp
  src/info-reader/artifact-reader.cpp
  src/info-reader/ego-reader.cpp
  src/info-reader/kind-info-tokens-table.cpp
  src/info-reader/kind-info-tokens-table.h
  src/info-reader/kind-reader.cpp
  src/inventory/inventory-curse.cpp
  src/market/building-craft-weapon.cpp
  src/monster-floor/monster-object.cpp
  src/object-activation/activation-others.cpp
  src/object-activation/activation-others.h
  src/object-enchant/activation-info-table.cpp
  src/object-enchant/activation-info-table.h
  src/object-enchant/apply-magic-armor.cpp
  src/object-enchant/apply-magic-weapon.cpp
  src/object-enchant/object-boost.cpp
  src/object-enchant/object-boost.h
  src/object-enchant/object-ego.cpp
  src/object-enchant/object-ego.h
  src/object-enchant/tr-types.h
  src/object-enchant/trc-types.h
  src/object-enchant/trg-types.h
  src/object/object-flags.cpp
  src/object/object-value-calc.cpp
  src/perception/identification.cpp
  src/player-attack/attack-chaos-effect.cpp
  src/player-attack/player-attack-util.h
  src/player-attack/player-attack.cpp
  src/player-info/body-improvement-info.cpp
  src/player-info/self-info.cpp
  src/player-info/weapon-effect-info.cpp
  src/player/player-status-flags.cpp
  src/player/player-status-flags.h
  src/player/player-status.cpp
  src/player/player-status.h
  src/spell-kind/spells-sight.cpp
  src/spell-kind/spells-sight.h
  src/view/display-characteristic.cpp
  src/wizard/cmd-wizard.cpp
  src/wizard/spoiler-table.cpp
  src/wizard/spoiler-table.h
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-item-modifier.h
Labels: enhancement, refactor

#808 [Add] cheat_sightに座標表示 / Coordinate display on cheat_sight.
  src/target/target-setter.cpp
Labels: enhancement

#811 [Refactor] feat_state()がplayer_typeを必要とせず、floor_typeのみで事足りたので引数掃き出し。
  src/action/open-close-execution.cpp
  src/floor/floor-changer.cpp
  src/floor/object-allocator.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/monster-floor/monster-move.cpp
  src/spell-kind/spells-grid.cpp
  src/spell-realm/spells-chaos.cpp
Labels: refactor

#814 [translation] For English prompts with get_check(), insert space, if it wasn't …
  src/cmd-action/cmd-travel.cpp
  src/cmd-item/cmd-equipment.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/market/building-quest.cpp
  src/specific-object/muramasa.cpp
  src/store/purchase-order.cpp
  src/store/sell-order.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#818 [Fix] マジックベーンの発動呼び出しが抜けている
  src/object-activation/activation-switcher.cpp
Labels: bug

#813 [Feature] キャラクタダンプの出力ページを拡張
  src/cmd-visual/cmd-draw.cpp
  src/io-dump/player-status-dump.cpp
  src/view/display-characteristic.cpp
  src/view/display-characteristic.h
  src/view/display-player.cpp
Labels: enhancement

#783 [Feature] キャラメイク時BGM対応
  lib/xtra/music/music.cfg
  src/birth/character-builder.cpp
  src/main-win.cpp
  src/main/music-definitions-table.cpp
  src/main/music-definitions-table.h
Labels: enhancement

#810 [Feature] Win版にアクティブ時のみBGM再生オプション追加
  src/ang_eng.rc
  src/ang_jp.rc
  src/main-win.cpp
  src/main-win/main-win-menuitem.h
  src/main-win/main-win-music.cpp
  src/main-win/main-win-music.h
Labels: enhancement

#823 [Fix] シンボルエディタで右端の移動がおかしい
  src/io-dump/dump-util.cpp
  src/knowledge/knowledge-features.cpp
Labels: bug

#822 [Feature] オプションのデフォルト値を変更
  lib/pref/pref-opt.prf
  src/game-option/option-types-table.cpp
Labels: enhancement

#827 [Fix] 魔法を防ぐクロークのsvalがクロークと同じだった
  lib/edit/k_info.txt
Labels: bug

#828 [Fix] プレイ記録で元素の系統とカオスパトロンを出力 #825
  src/birth/character-builder.cpp
Labels: bug, enhancement

#819 [Refactor] cmd-mind.cpp の cm_type に関する Doxygen コメント追加.
  src/cmd-action/cmd-mind.cpp
Labels: documentation

#835 [Version] 3.0.0Alpha19
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#837 [Refactor] main-win.cppから"lib/xtra/font/*.fon"関連を削除する
  Build-Windows-Release-Package.ps1
  src/main-win.cpp
Labels: refactor

#832 [Feature] サブウィンドウの装備/持ち物一覧でシンボルを表示する #829
  src/view/display-inventory.cpp
  src/window/display-sub-windows.cpp
Labels: enhancement

#841 [Fix] サブウィンドウサイズの高さが足りない場合に装備/持ち物一覧で落ちる #840
  src/view/display-inventory.cpp
  src/window/display-sub-windows.cpp
Labels: bug

#843 [Feature] easy_floor有効時にも財宝($)を拾う時にSOUND_SELL効果音を鳴らす
  src/inventory/player-inventory.cpp
Labels: enhancement

#834 [Feature] 呪文設定一覧を出力するダンプコマンド #342
  src/wizard/spoiler-util.cpp
  src/wizard/wizard-spoiler.cpp
Labels: enhancement

#821 [Refactor] monster_spell_type と RF_ABILITY を統合する
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  lib/edit/r_info.txt
  src/Makefile.am
  src/blue-magic/blue-magic-ball-bolt.cpp
  src/blue-magic/blue-magic-breath.cpp
  src/blue-magic/blue-magic-caster.cpp
  src/blue-magic/blue-magic-caster.h
  src/blue-magic/blue-magic-spirit-curse.cpp
  src/blue-magic/learnt-info.cpp
  src/blue-magic/learnt-info.h
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-mane.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/lore/lore-calculator.cpp
  src/lore/lore-calculator.h
  src/lore/magic-types-setter.cpp
  src/mind/mind-blue-mage.cpp
  src/monster-race/race-ability-flags.h
  src/monster-race/race-ability-mask.cpp
  src/mspell/assign-monster-spell.cpp
  src/mspell/mspell-attack.cpp
  src/mspell/mspell-ball.cpp
  src/mspell/mspell-bolt.cpp
  src/mspell/mspell-breath.cpp
  src/mspell/mspell-curse.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/mspell/mspell-damage-calculator.h
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-floor.cpp
  src/mspell/mspell-particularity.cpp
  src/mspell/mspell-status.cpp
  src/mspell/mspell-type.h
  src/object/warning.cpp
  src/view/display-lore.cpp
Labels: refactor

#845 [modify] GCCのバグを回避するため初期化リストの型を明示
  src/cmd-action/cmd-attack.cpp
Labels: enhancement

#847 [Fix] α19新規追加要素の修正(善良スレイ説明文、価格設定) #846
  lib/edit/k_info.txt
  src/perception/identification.cpp
Labels: bug

#850 [Refactor] 青魔法のソースファイルに関するDoxygenコメント追加．
  src/blue-magic/blue-magic-ball-bolt.cpp
  src/blue-magic/blue-magic-ball-bolt.h
  src/blue-magic/blue-magic-breath.cpp
  src/blue-magic/blue-magic-breath.h
  src/blue-magic/blue-magic-caster.cpp
  src/blue-magic/blue-magic-caster.h
  src/blue-magic/blue-magic-checker.cpp
  src/blue-magic/blue-magic-checker.h
  src/blue-magic/blue-magic-spirit-curse.cpp
  src/blue-magic/blue-magic-spirit-curse.h
  src/blue-magic/blue-magic-status.cpp
  src/blue-magic/blue-magic-status.h
  src/blue-magic/blue-magic-summon.cpp
  src/blue-magic/blue-magic-summon.h
  src/blue-magic/blue-magic-util.cpp
  src/blue-magic/blue-magic-util.h
  src/blue-magic/learnt-info.cpp
  src/blue-magic/learnt-info.h
  src/blue-magic/learnt-power-getter.cpp
  src/blue-magic/learnt-power-getter.h
Labels: enhancement

#852 [Feature] オートローラの初期設定を職業に合わせて設定する
  src/birth/auto-roller.cpp
Labels: enhancement

#839 [Refactor] Windowsのフォント周りの整理及びlib/xtra/fontの整理
  configure.ac
  lib/pref/Makefile.am
  lib/pref/font-ami.prf
  lib/pref/font-dos.prf
  lib/pref/font-ibm.prf
  lib/pref/font-win.prf
  lib/pref/font.prf
  lib/pref/graf-ami.prf
  lib/pref/graf-dos.prf
  lib/pref/graf-ibm.prf
  lib/pref/graf.prf
  lib/pref/pref-acn.prf
  lib/pref/pref-ami.prf
  lib/pref/pref-emx.prf
  lib/pref/pref.prf
  lib/pref/user.prf
  lib/pref/xtra-new.prf
  lib/pref/xtra-xxx.prf
  lib/xtra/Makefile.am
  lib/xtra/font/10X20.FON
  lib/xtra/font/12X24.FON
  lib/xtra/font/5X8.FON
  lib/xtra/font/6X10.FON
  lib/xtra/font/6X12.FON
  lib/xtra/font/6X13.FON
  lib/xtra/font/6X13B.FON
  lib/xtra/font/6X9.FON
  lib/xtra/font/7X13.FON
  lib/xtra/font/7X13B.FON
  lib/xtra/font/8X13.FON
  lib/xtra/font/8X13B.FON
  lib/xtra/font/9X15.FON
  lib/xtra/font/9X15B.FON
  lib/xtra/font/Makefile.am
  lib/xtra/font/xm10x17.fnt
  lib/xtra/font/xm10x17b.fnt
  lib/xtra/font/xm12x20.fnt
  lib/xtra/font/xm12x20b.fnt
  lib/xtra/font/xm16x25.fnt
  lib/xtra/font/xm16x25b.fnt
  lib/xtra/font/xm4x6.fnt
  lib/xtra/font/xm5x8.fnt
  lib/xtra/font/xm6x12.fnt
  lib/xtra/font/xm6x12b.fnt
  lib/xtra/font/xm8x13.fnt
  lib/xtra/font/xm8x13b.fnt
  lib/xtra/font/xm8x16.fnt
  lib/xtra/font/xm8x16b.fnt
  src/ang_eng.rc
  src/ang_jp.rc
  src/main-win.cpp
  src/main-win/main-win-menuitem.h
  src/system/h-config.h
Labels: refactor

#857 [Fix] @param と @details の綴りミス置換.
  src/birth/birth-wizard.cpp
  src/core/hp-mp-processor.cpp
  src/effect/effect-monster-psi.cpp
  src/effect/effect-monster-resist-hurt.cpp
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/load/angband-version-comparer.cpp
  src/mind/mind-elementalist.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/monster-floor/monster-summon.cpp
  src/player-info/race-ability-info.cpp
  src/player-status/player-basic-statistics.cpp
  src/player-status/player-charisma.cpp
  src/player-status/player-status-base.cpp
  src/player/player-status-flags.cpp
  src/room/rooms-pit-nest.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-realm/spells-chaos.cpp
  src/spell/spells-status.cpp
  src/store/articles-on-sale.cpp
  src/target/grid-selector.cpp
  src/util/string-processor.cpp
  src/view/display-lore.cpp
  src/view/display-messages.cpp
  src/wizard/cmd-wizard.cpp
Labels: bug, documentation

#863 [Refactor] #860 Deleted make files for Borland C++ Builder
  src/Makefile.am
  src/makefile.bcc
  src/makefile.std
Labels: refactor

#858 [feature] FlagGroupクラスを従来のenum型でも使えるようにする #856
  src/blue-magic/blue-magic-checker.cpp
  src/blue-magic/blue-magic-checker.h
  src/blue-magic/learnt-power-getter.cpp
  src/dungeon/dungeon.h
  src/info-reader/artifact-reader.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/ego-reader.cpp
  src/info-reader/kind-reader.cpp
  src/info-reader/race-reader.cpp
  src/io-dump/special-class-dump.cpp
  src/lore/lore-util.h
  src/melee/melee-spell-flags-checker.cpp
  src/melee/melee-spell-util.h
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster-race/race-ability-mask.cpp
  src/monster-race/race-ability-mask.h
  src/monster/monster-processor-util.h
  src/mspell/improper-mspell-remover.cpp
  src/mspell/improper-mspell-remover.h
  src/mspell/mspell-attack-util.h
  src/mspell/mspell-attack.cpp
  src/mspell/smart-mspell-util.cpp
  src/mspell/smart-mspell-util.h
  src/object-enchant/object-ego.cpp
  src/object-enchant/object-ego.h
  src/object/object-kind.h
  src/player/player-status.h
  src/system/artifact-type-definition.h
  src/system/monster-race-definition.h
  src/system/monster-type-definition.h
  src/util/flag-group.h
  src/wizard/wizard-spells.cpp
Labels: enhancement

#867 [Refactor] 壁紙メニューを別階層に分ける
  src/ang_eng.rc
  src/ang_jp.rc
  src/main-win.cpp
  src/main-win/main-win-bg.cpp
  src/main-win/main-win-bg.h
  src/main-win/main-win-menuitem.h
Labels: refactor

#873 [Refactor] 16色画面用の処理を削除し、256色以下の画面では起動しないようにする
  src/main-win.cpp
Labels: refactor

#861 [Feature] レイシャルパワーの説明文を表示できるようにする #625
  src/cmd-action/cmd-racial.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-action/cmd-spell.h
  src/mind/mind-elementalist.cpp
  src/racial/class-racial-switcher.cpp
  src/racial/class-racial-switcher.h
  src/racial/mutation-racial-selector.cpp
  src/racial/race-racial-command-setter.cpp
  src/racial/racial-util.cpp
  src/racial/racial-util.h
  src/realm/realm-sorcery.cpp
Labels: enhancement, refactor

#830 [Feature] 勝利済み職業とユニークを倒した時間を記録する #784 #18
  src/birth/birth-select-class.cpp
  src/cmd-action/cmd-others.cpp
  src/cmd-visual/cmd-draw.cpp
  src/core/game-closer.cpp
  src/core/game-play.cpp
  src/core/scores.cpp
  src/core/scores.h
  src/io-dump/character-dump.cpp
  src/io-dump/character-dump.h
  src/io/files-util.cpp
  src/io/files-util.h
  src/io/report.cpp
  src/io/report.h
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-self.cpp
  src/knowledge/knowledge-uniques.cpp
  src/load/load.cpp
  src/load/lore-loader.cpp
  src/monster-floor/monster-death-util.h
  src/monster-floor/monster-death.cpp
  src/mspell/mspell-attack-util.h
  src/mspell/smart-mspell-util.h
  src/player/player-damage.cpp
  src/player/process-death.cpp
  src/player/process-death.h
  src/save/monster-writer.cpp
  src/save/save.cpp
  src/system/angband-version.h
  src/system/monster-race-definition.h
  src/system/monster-type-definition.h
  src/world/world.cpp
  src/world/world.h
Labels: enhancement

#876 [Refactor] #625 レイシャルパワーの説明文のコードをわかりやすく整理
  src/cmd-action/cmd-racial.cpp
  src/mind/mind-elementalist.cpp
  src/racial/class-racial-switcher.cpp
  src/racial/mutation-racial-selector.cpp
  src/racial/race-racial-command-setter.cpp
  src/racial/racial-util.cpp
  src/racial/racial-util.h
Labels: refactor

#872 [Fix] 宝物庫の報酬がクエスト受注元でメッセージを出すたびに変わる
  src/market/building-quest.cpp
Labels: bug

#875 [Refactor] 256色画面用の処理を削除する
  src/main-win.cpp
Labels: refactor

#868 [Add] mainディレクトリ以下のファイルにDoxygenコメント追加.
  src/main/angband-headers.cpp
  src/main/angband-headers.h
  src/main/angband-initializer.cpp
  src/main/angband-initializer.h
  src/main/game-data-initializer.cpp
  src/main/game-data-initializer.h
  src/main/info-initializer.cpp
  src/main/info-initializer.h
  src/main/init-error-messages-table.cpp
  src/main/init-error-messages-table.h
  src/main/music-definitions-table.cpp
  src/main/music-definitions-table.h
  src/main/scene-table-floor.cpp
  src/main/scene-table-floor.h
  src/main/scene-table-monster.cpp
  src/main/scene-table-monster.h
  src/main/scene-table.cpp
  src/main/scene-table.h
  src/main/sound-definitions-table.cpp
  src/main/sound-definitions-table.h
  src/main/sound-of-music.cpp
  src/main/sound-of-music.h
  src/main/x11-gamma-builder.cpp
  src/main/x11-gamma-builder.h
  src/main/x11-type-string.cpp
  src/main/x11-type-string.h
Labels: documentation

#883 [Fix] アリーナで呪術の薬物吸入ができない #882
  src/cmd-item/cmd-quaff.cpp
Labels: bug

#881 [Fix] クラスパワーでtextをinfoに代入していた(鏡使い分)
  src/cmd-action/cmd-racial.cpp
  src/racial/class-racial-switcher.cpp
Labels: bug

#884 [Fix] 射撃術の爆発の矢を無傷球中の敵に撃つと爆発のダメージが0 #848
  src/combat/shoot.cpp
Labels: bug

#887 [Add] actionファイル以下にDoxygenのファイル説明追加.
  src/action/action-limited.cpp
  src/action/action-limited.h
  src/action/activation-execution.cpp
  src/action/activation-execution.h
  src/action/movement-execution.cpp
  src/action/movement-execution.h
  src/action/mutation-execution.cpp
  src/action/mutation-execution.h
  src/action/open-close-execution.cpp
  src/action/open-close-execution.h
  src/action/open-util.cpp
  src/action/open-util.h
  src/action/racial-execution.cpp
  src/action/racial-execution.h
  src/action/run-execution.cpp
  src/action/run-execution.h
  src/action/throw-util.cpp
  src/action/throw-util.h
  src/action/travel-execution.cpp
  src/action/travel-execution.h
  src/action/tunnel-execution.cpp
  src/action/tunnel-execution.h
  src/action/weapon-shield.cpp
  src/action/weapon-shield.h
Labels: documentation, enhancement

#888 [Add] collect_monsters() のDoxygenコメント整理.
  src/knowledge/knowledge-monsters.cpp
Labels: documentation

#877 [fix] レイシャルパワーの一覧表示/非表示の切り替え
  src/cmd-action/cmd-racial.cpp
Labels: bug

#893 [Refactor] readdib.cpp/hを削除し、タイルの読込をGDI+処理に置き換える
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/main-win.cpp
  src/main-win/main-win-bg.cpp
  src/main-win/read-graphics.cpp
  src/main-win/read-graphics.h
  src/main-win/tile-info.h
  src/term/readdib.cpp
  src/term/readdib.h
Labels: refactor

#899 [Feature] MessageBox,GetSaveFileName APIをワイド文字列版へ移行
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/main-win.cpp
  src/main-win/string-win.h
Labels: enhancement

#879 [Feature] α20に向けたエゴ関係の機能の改変や調整 (＋ステータス表示画面の改善)
  lib/edit/e_info.txt
  src/flavor/flag-inscriptions-table.cpp
  src/flavor/flag-inscriptions-table.h
  src/flavor/flavor-util.cpp
  src/info-reader/ego-reader.cpp
  src/info-reader/ego-reader.h
  src/info-reader/kind-info-tokens-table.cpp
  src/object-enchant/apply-magic-armor.cpp
  src/object-enchant/apply-magic-weapon.cpp
  src/object-enchant/object-ego.cpp
  src/object-enchant/object-ego.h
  src/object-enchant/trg-types.h
  src/perception/identification.cpp
  src/player/player-status-flags.cpp
  src/view/display-characteristic.cpp
  src/view/display-characteristic.h
Labels: enhancement, refactor

#902 [Refactor] z-term.cpp をC++の機能で書き換える
  src/main-win.cpp
  src/term/z-term.cpp
  src/term/z-term.h
Labels: refactor

#903 [Fix] 既知のモンスターで1体も既知ではない場合の配列外アクセス
  src/knowledge/knowledge-monsters.cpp
Labels: bug

#900 モンスター案の実装 (OSDNの旧チケット＋α)
  lib/edit/misc.txt
  lib/edit/r_info.txt
  lib/file/mondeath.txt
  lib/file/mondeath_j.txt
  lib/file/monfear.txt
  lib/file/monfear_j.txt
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
  src/effect/effect-monster.cpp
  src/monster-floor/special-death-switcher.cpp
  src/monster-race/race-indice-types.h
  src/monster/monster-status-setter.cpp
  src/monster/monster-status-setter.h
  src/monster/monster-status.cpp
  src/mspell/mspell-floor.cpp
  src/mspell/mspell-status.cpp
  src/mspell/mspell-summon.cpp
  src/mspell/specified-summon.cpp
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-spells.cpp
Labels: enhancement

#901 [Fix] fresh_once時にMコマンドを含めたマクロを実行するとサブウィンドウが更新されない #898
  src/cmd-visual/cmd-map.cpp
Labels: bug

#912 Include vector in z-term.h to avoid compiler errors if not using precompiled headers
  src/term/z-term.h
Labels: bug

#907 [Fix] 赤魔導士の連続魔で1回目でキャンセルできない、また2回目できちんとターゲット指定できない #905 #906
  src/cmd-action/cmd-spell.cpp
  src/cmd-action/cmd-spell.h
  src/io/input-key-processor.cpp
  src/racial/racial-switcher.cpp
Labels: bug

#915 [Implement] #914 イェンダーの魔法使いにおける特殊な救援召喚を実装した / Implemented special S_K…
  lib/edit/r_info.txt
  src/monster-floor/special-death-switcher.cpp
  src/monster-race/race-indice-types.h
  src/mspell/mspell-summon.cpp
  src/mspell/specified-summon.cpp
  src/mspell/specified-summon.h
Labels: enhancement

#931 [Release] 3.0.0Alpha20
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#934 [Add] artifact ディレクトリ以下のファイルに Doxygen コメントを追加.　/ Add Doxygen comments…
  src/artifact/artifact-info.cpp
  src/artifact/artifact-info.h
  src/artifact/fixed-art-generator.cpp
  src/artifact/fixed-art-generator.h
  src/artifact/fixed-art-types.h
  src/artifact/random-art-activation.cpp
  src/artifact/random-art-activation.h
  src/artifact/random-art-bias-types.h
  src/artifact/random-art-characteristics.cpp
  src/artifact/random-art-characteristics.h
  src/artifact/random-art-effects.h
  src/artifact/random-art-generator.cpp
  src/artifact/random-art-generator.h
  src/artifact/random-art-misc.cpp
  src/artifact/random-art-misc.h
  src/artifact/random-art-pval-investor.cpp
  src/artifact/random-art-pval-investor.h
  src/artifact/random-art-resistance.cpp
  src/artifact/random-art-resistance.h
  src/artifact/random-art-slay.cpp
  src/artifact/random-art-slay.h
Labels: documentation

#936 [Fix] Win版のタイル/壁紙/効果音切り替えバグを修正
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/main-win.cpp
  src/main-win/graphics-win.cpp
  src/main-win/graphics-win.h
  src/main-win/main-win-bg.cpp
  src/main-win/main-win-bg.h
  src/main-win/read-graphics.h
  src/main-win/tile-info.h
Labels: enhancement

#940 [Add] Doxygen用のメインページをangband.hに追加．
  src/system/angband.h
Labels: enhancement

#938 [Refactor] 赤外線視力管理クラス PlayerInfravisionの導入
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/player-status/player-infravision.cpp
  src/player-status/player-infravision.h
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
Labels: refactor

#911 [Feature] screen_save()/screen_load()で多重に画面を保存する #891
  src/stdafx.h
  src/term/screen-processor.cpp
  src/term/screen-processor.h
  src/term/z-term.cpp
  src/term/z-term.h
Labels: enhancement

#948 [Fix] 生い立ちエディタの文字化け #946
  src/term/z-form.cpp
Labels: bug

#956 デバッグコマンドのSとvが逆になっている不具合の修正
  src/wizard/cmd-wizard.cpp
Labels: bug

#951 [Fix] オートローラーで最大値が出ない #949
  src/birth/auto-roller.cpp
Labels: bug

#952 [Fix] デバグのインベントリ内全*鑑定*でawareしない #913
  src/wizard/wizard-item-modifier.cpp
Labels: bug

#961 [Add] ディレクトリに関するDoxygenコメントをいくらか追加.
  src/system/angband.h
Labels: bug, documentation

#971 [Fix] #964 Resolved the typo; abillity to ability
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/info-reader/magic-reader.cpp
  src/info-reader/race-reader.cpp
  src/load/birth-loader.cpp
  src/lore/monster-lore.cpp
  src/mspell/monster-power-table.cpp
  src/object-enchant/object-boost.cpp
  src/player-ability/player-ability-types.h
  src/player-status/player-basic-statistics.h
  src/player/player-race.h
  src/player/player-status-table.h
  src/save/info-writer.cpp
  src/system/player-type-definition.h
Labels: bug

#965 [Feature] 矢弾生成のレイシャルパワーを繰り返しコマンドに対応
  src/mind/mind-archer.cpp
Labels: bug, enhancement

#975 [Refactor] 吟遊詩人の一部の歌名を実情に合わせて改名
  src/realm/realm-song.cpp
Labels: refactor

#947 [Feature] BGM、効果音の設定フォルダを開くメニューを追加
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  readme.md
  src/Makefile.am
  src/ang_eng.rc
  src/ang_jp.rc
  src/main-win.cpp
  src/main-win/main-win-menuitem.h
  src/main-win/main-win-utils.cpp
  src/main-win/main-win-utils.h
Labels: documentation, enhancement

#977 [Feature] 各種テスト用にデバグコマンドの拡張α21
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-item-modifier.h
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
Labels: enhancement, refactor

#979 [Refactor] main-win.cpp分割（タイル初期化処理をgraphics-win.cppへ移動）
  src/main-win.cpp
  src/main-win/graphics-win.cpp
  src/main-win/graphics-win.h
Labels: refactor

#984 [feature] cheat_knowオン時にモンスターの種族IDを表示する
  src/view/display-lore.cpp
Labels: enhancement

#986 v3.0.0 Alpha21 アイテム追加リクエストへの対応
  lib/edit/k_info.txt
  lib/edit/misc.txt
  src/object-use/quaff-execution.cpp
  src/object/object-broken.cpp
  src/sv-definition/sv-potion-types.h
Labels: enhancement
