Repository hengband/hengband, pull requests merged in 2021-02, with the labels that each got.

#9 Feature/implement skip more
  src/game-option/input-options.c
  src/game-option/input-options.h
  src/game-option/option-types-table.c
  src/game-option/option-types-table.h
  src/view/display-messages.c
Labels: enhancement

#13 WORLD_SCOREの定義によるスコア送信機能の切り替えが機能するようにする
  Hengband/Hengband/Hengband.vcxproj
  src/cmd-io/cmd-gameoption.c
  src/cmd-io/cmd-gameoption.h
  src/game-option/game-play-options.c
  src/game-option/game-play-options.h
  src/game-option/option-types-table.c
  src/io/report.c
  src/player/player-damage.c
  src/save/save.c
  src/system/game-option-types.h
  src/system/h-config.h
Labels: wontfix

#62 [update] #1 ビルドテストを並列実行する
  .github/workflows/buildtest-on-linux.yml
Labels: enhancement

#40 [Fix] 英語版 rumor.txt に有用な噂追加. / Add useful rumors to English version.
  lib/file/rumors.txt
Labels: enhancement

#67 [Fix] 視界内のモンスター表示中、center_playerの描写がおかしくなる #66
  src/target/target-setter.c
Labels: bug

#71 [Refactor] FORCE_SLEEPという不適切なフラグ名称 #30
  lib/edit/r_info.txt
  src/core/player-processor.c
  src/floor/floor-changer.c
  src/info-reader/race-info-tokens-table.c
  src/monster-floor/one-monster-placer.c
  src/monster-race/race-flags1.h
  src/monster/monster-flag-types.h
  src/monster/monster-processor.c
  src/mspell/mspell-attack.c
Labels: refactor

#70 [fix] #65 未初期化の変数を参照している
  src/floor/floor-object.c
  src/inventory/inventory-slot-types.h
Labels: bug

#87 [fix] 横幅をめちゃくちゃ広くすると、インベントリの表示などが乱れる #86
  src/term/z-term.c
Labels: bug

#90 [update] 大きなサイズのマップもスコアサーバへ送信できるようにしたい #43
  src/load/load.c
  src/system/system-variables.h
Labels: enhancement

#97 [fix] モンスター一覧を表示すると画面がちらつく#96
  src/window/display-sub-windows.c
Labels: enhancement

#104 [fix] pkg-config のチェックを追加 #12
  configure.ac
Labels: bug

#102 [Fix] セーブファイルを指定して起動した時にpath指定がおかしくて起動しない #101
  src/main-win.c
Labels: bug

#116 [Fix] 青魔導士のファイア・ボルトがMP消費ターン消費なし #115
  src/blue-magic/blue-magic-caster.c
Labels: bug

#103 [Fix] 床置きアイテム自動破壊時にメッセージウインドウが遅れる #92
  src/core/window-redrawer.c
  src/io/input-key-requester.c
  src/window/display-sub-windows.c
  src/window/display-sub-windows.h
Labels: bug

#132 Feature/refactor monster alpha6
  lib/edit/r_info.txt
Labels: enhancement

#137 [Fix] アイテム選択時にクラッシュ #117
  src/inventory/floor-item-getter.c
Labels: bug

#113 [Fix] mbe_info の配列外参照を修正
  src/info-reader/race-info-tokens-table.c
  src/info-reader/race-info-tokens-table.h
  src/monster-attack/monster-attack-effect.h
  src/monster-attack/monster-attack-types.c
  src/monster-attack/monster-attack-types.h
Labels: bug

#139 [Feature] mon-info.txtの出力情報を現在のプレイヤー情報に依存させない
  src/view/display-lore.c
  src/view/display-lore.h
  src/wizard/monster-info-spoiler.c
Labels: enhancement

#143 [Fix] artifact.txtにEASY_SPELLが出力されていない #54
  src/wizard/spoiler-table.c
  src/wizard/spoiler-table.h
Labels: enhancement

#144 [Feature] Spoiler File出力関数のplayer_type依存解消
  src/autopick/autopick-matcher.c
  src/flavor/flavor-describer.c
  src/flavor/object-flavor-types.h
  src/main-win.c
  src/object-hook/hook-quest.c
  src/object-hook/hook-quest.h
  src/wizard/artifact-analyzer.c
  src/wizard/cmd-wizard.c
  src/wizard/fixed-artifacts-spoiler.c
  src/wizard/fixed-artifacts-spoiler.h
  src/wizard/items-spoiler.c
  src/wizard/items-spoiler.h
  src/wizard/monster-info-spoiler.c
  src/wizard/monster-info-spoiler.h
  src/wizard/wizard-spoiler.c
  src/wizard/wizard-spoiler.h
Labels: enhancement

#146 [Fix] Artifact Spoiler出力の射撃回数計算がおかしい
  src/flavor/flavor-describer.c
Labels: bug

#108 [Fix] ビットテスト用の左シフトの左辺を全て符号なしにする
  src/autopick/autopick-entry.c
  src/autopick/autopick-key-flag-process.h
  src/birth/birth-select-class.c
  src/birth/birth-select-realm.c
  src/blue-magic/learnt-power-getter.c
  src/cmd-action/cmd-hissatsu.c
  src/cmd-action/cmd-spell.c
  src/cmd-io/cmd-gameoption.c
  src/floor/wild.c
  src/info-reader/general-parser.c
  src/info-reader/info-reader-util.c
  src/io-dump/character-dump.c
  src/io-dump/special-class-dump.c
  src/io/interpret-pref-file.c
  src/load/load-zangband.c
  src/load/option-loader.c
  src/lore/lore-store.c
  src/main/game-data-initializer.c
  src/melee/melee-spell-flags-checker.c
  src/melee/melee-spell.c
  src/monster/monster-status.c
  src/mspell/mspell-attack.c
  src/object-enchant/object-curse.c
  src/object-hook/hook-magic.c
  src/player/player-status-flags.c
  src/player/player-status-resist.c
  src/player/player-status.c
  src/realm/realm-hex.c
  src/room/rooms-pit-nest.c
  src/save/info-writer.c
  src/spell-kind/spells-world.c
  src/spell-realm/spells-hex.c
  src/spell/spell-info.c
  src/status/shape-changer.c
  src/store/rumor.c
  src/term/z-util.c
  src/util/bit-flags-calculator.h
  src/view/object-describer.c
  src/window/display-sub-window-spells.c
  src/window/main-window-stat-poster.c
  src/wizard/spoiler-table.h
  src/wizard/wizard-spells.c
Labels: refactor

#145 [Refactor] Spoiler File作成時のメッセージを分離
  src/cmd-io/cmd-lore.c
  src/view/display-lore.h
  src/wizard/fixed-artifacts-spoiler.c
  src/wizard/fixed-artifacts-spoiler.h
  src/wizard/items-spoiler.c
  src/wizard/items-spoiler.h
  src/wizard/monster-info-spoiler.c
  src/wizard/monster-info-spoiler.h
  src/wizard/spoiler-util.h
  src/wizard/wizard-spoiler.c
Labels: refactor

#148 [Fix] artifact.txtにガラドリエルのスリングが出力される
  src/wizard/fixed-artifacts-spoiler.c
Labels: bug

#149 Correct typo in one of the activation_info table's English labels
  src/object-enchant/activation-info-table.c
Labels: translation

#153 [Feature] Debugセーブのメッセージログを40行に制限
  src/save/save.c
Labels: enhancement

#156 [feature] ゲーム画面無しでゲームデータ初期化を行うスイッチ
  src/main-win.c
  src/main.c
  src/main/angband-initializer.c
  src/main/angband-initializer.h
Labels: enhancement

#167 [Fix] X11 ドライバで視界内モンスターリストウィンドウがリサイズ時に再描画されていなかった
  src/core/window-redrawer.c
  src/core/window-redrawer.h
Labels: bug

#166 [feature] モンスター一覧表示用のターゲット準備処理 #159
  src/target/grid-selector.c
  src/target/target-preparation.c
  src/target/target-preparation.h
  src/target/target-setter.c
  src/target/target-setter.h
  src/util/sort.c
  src/util/sort.h
  src/window/display-sub-windows.c
  src/window/display-sub-windows.h
Labels: enhancement

#152 [Implement] Windows環境で--output-spoilersオプションの実装
  src/main-win.c
  src/wizard/wizard-spoiler.c
  src/wizard/wizard-spoiler.h
Labels: enhancement

#179 [fix] X11版でXFTを有効にすると、フォントのサイズによって描画が崩れる #178
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/locale/japanese.c
  src/locale/utf-8.c
  src/locale/utf-8.h
  src/main-x11.c
Labels: bug

#175 Feature/fix priest realm
  src/birth/birth-select-realm.c
  src/player/player-realm.c
  src/player/player-realm.h
Labels: bug

#176 [Fix] #174 プリーストの相応しい武器の判定がおかしかったのを修正した / Resolved the issue that the…
  src/player/player-status-flags.c
Labels: bug

#191 [Fix] 青魔道師の一貫性のないラーニング判定を修正
  src/blue-magic/blue-magic-checker.c
  src/blue-magic/blue-magic-checker.h
  src/effect/effect-player-curse.c
  src/effect/effect-player-resist-hurt.c
  src/effect/effect-player-spirit.c
  src/mspell/mspell-attack.c
  src/mspell/mspell-checker.c
  src/mspell/mspell-dispel.c
  src/mspell/mspell-floor.c
  src/mspell/mspell-learn-checker.c
  src/mspell/mspell-status.c
  src/player/player-damage.c
Labels: bug

#203 [fix] アリーナで友好的な敵が出現 #202
  src/monster-floor/one-monster-placer.c
Labels: bug

#204 [Fix] 水辺に出てくる敵の出現率が低下 #197
  src/monster-race/monster-race-hook.c
  src/util/bit-flags-calculator.h
Labels: bug

#189 [feature] UNIX系環境用のスポイラーを出力するオプション
  src/main.c
Labels: enhancement

#206 [Refactor] player-statusのBIT_FLAGS処理をマクロを用いて表記
  src/player/player-status.c
  src/util/bit-flags-calculator.h
Labels: refactor

#205 Feature/fix do get mon num prep
  src/monster/monster-util.c
Labels: refactor

#209 [Implement] 荒野に出現するモンスター一覧のスポイラー出力
  src/wizard/monster-info-spoiler.c
  src/wizard/monster-info-spoiler.h
  src/wizard/wizard-spoiler.c
Labels: enhancement

#199 [Feature] fresh_afterコマンドの分割
  src/cmd-action/cmd-move.c
  src/cmd-action/cmd-pet.c
  src/core/player-processor.c
  src/dungeon/dungeon-processor.c
  src/effect/effect-processor.c
  src/game-option/map-screen-options.c
  src/game-option/map-screen-options.h
  src/game-option/option-types-table.c
  src/game-option/option-types-table.h
  src/io/input-key-requester.c
  src/mind/mind-mirror-master.c
  src/spell-kind/spells-genocide.c
  src/spell-kind/spells-sight.c
  src/term/z-term.c
  src/term/z-term.h
  src/view/display-messages.c
Labels: enhancement

#213 Feature/implement shoot slaying
  src/combat/shoot.c
Labels: bug

#223 Feature/refactor monsters alpha7
  lib/edit/r_info.txt
Labels: enhancement

#224 [feature] 自動生成スポイラーのサイトをpublishするWorkflow
  .github/workflows/publish-spoiler-page.yml
Labels: documentation, enhancement

#230 [Version] 3.0.0Alpha7
  src/system/angband-version.h
Labels: release

#222 Feature/fix get artifact index
  lib/edit/r_info.txt
  src/monster-floor/monster-death.c
Labels: bug

#236 [Fix] fresh_onceオプションをセーブできない
  src/game-option/option-types-table.c
Labels: bug

#227 Add: 3 artifacts from XAngband. #225
  lib/edit/a_info.txt
  lib/edit/misc.txt
  src/artifact/fixed-art-types.h
  src/player/player-status.c
Labels: enhancement

#238 [Fix] スペルマスター、プリーストが盾装備時ふさわしくない武器判定される
  src/player/player-status-flags.c
Labels: bug

#245 [Version] 3.0.0Alpha8
  src/system/angband-version.h
Labels: bug, release

#246 Release/3.0.0 alpha8
  lib/edit/a_info.txt
  lib/edit/misc.txt
  lib/edit/r_info.txt
  src/artifact/fixed-art-types.h
  src/game-option/option-types-table.c
  src/monster-floor/monster-death.c
  src/player/player-status-flags.c
  src/player/player-status.c
  src/system/angband-version.h
Labels: bug, release

#247 [Implement] アプリを切り替えてもサブウィンドウが消えないオプションが欲しい #14
  src/game-option/game-play-options.c
  src/game-option/game-play-options.h
  src/game-option/option-types-table.c
  src/game-option/option-types-table.h
  src/main-win.c
Labels: enhancement

#252 [Fix] drawing sniper rushing arrow's moving points #251
  src/combat/shoot.c
Labels: bug

#240 [Fix] ロード時に latest_visit_mark を復元
  src/load/dungeon-loader.c
Labels: bug

#262 [fix] 思い出の改行位置がおかしい #17
  src/term/screen-processor.c
Labels: bug

#261 [Feature] hengband.iniに刻まれるセーブファイルのpathをexeからの相対pathにして欲しい #181
  src/main-win.c
Labels: enhancement

#266 [Fix] #247のサブウィンドウ関連オプションをウィンドウズのメニュー処理に移行
  src/angband.rc
  src/game-option/game-play-options.c
  src/game-option/game-play-options.h
  src/game-option/option-types-table.c
  src/game-option/option-types-table.h
  src/main-win.c
Labels: bug

#269 [Fix] 魔法の鎧使用時、実際には浮遊していない
  src/player/player-status-flags.c
Labels: bug

#271 [Fix] snprintfの第二引数を訂正 #267
  src/main-win.c
Labels: bug

#270 [Feature] Draw line with different colors in show_file()'s keyword finding. #211
  src/core/show-file.c
Labels: enhancement

#272 [feature] 敵を一撃で倒すデバッグコマンド #234
  src/wizard/cmd-wizard.c
  src/wizard/wizard-spells.c
  src/wizard/wizard-spells.h
Labels: enhancement

#268 [Fix] Aquatic monsters appear in moutain or volcano dungeons. #51
  src/monster-race/monster-race-hook.c
Labels: bug, enhancement

#277 [Fix] 自動生成スポイラーに魔法・ブレスの威力を表示
  src/knowledge/knowledge-monsters.c
  src/lore/lore-calculator.c
  src/lore/lore-calculator.h
  src/lore/magic-types-setter.c
  src/view/display-lore-status.c
  src/view/display-lore.c
Labels: enhancement

#275 [fix] テレポートレベル巻物で下の階へ移動してから階段を登ると巻物を読んだ場所に出ることがある #192
  src/floor/floor-leaver.c
Labels: bug

#248 [Refacotr] resistance-checkerのBIT_FLAGS演算をマクロで置換
  src/mspell/element-resistance-checker.c
  src/mspell/high-resistance-checker.c
Labels: refactor

#282 [Fix] #280 player-status-flags.c 内で論理和計算すべきところを即値代入しているミスを修正．
  src/player/player-status-flags.c
Labels: bug

#290 Fix: display reverse imitation status. #289
  src/window/main-window-stat-poster.c
Labels: bug

#281 [Fix] X11 ドライバで画面コピーに失敗するのを修正 #215
  src/main-x11.c
Labels: bug

#288 [Feature] 騎乗時の浮遊処理の仕様を修正 #285
  src/player/permanent-resistances.c
  src/player/permanent-resistances.h
  src/player/player-status-flags.c
  src/player/player-status-flags.h
  src/view/display-characteristic.c
Labels: enhancement

#292 ﻿[Add] .editorconfig を追加
  .editorconfig
Labels: enhancement, refactor

#296 [Fix] 特性フラグ一覧表示の2ページ目がランダムに緑や赤になる #295
  src/view/display-characteristic.c
Labels: bug

#301 [Fix] 地震を起こす武器で地震が起こらない #286
  src/player-attack/player-attack.c
Labels: bug

#297 [Feature] r_info.txt において、DROP_GOOD または DROP_GREAT を指定したら自動的にONLY_ITE…
  src/monster-floor/monster-death-util.c
Labels: enhancement

#305 [refactor] UTF-8 ↔ EUC-JPの変換処理を共通化
  src/locale/japanese.c
  src/locale/japanese.h
  src/main-gcu.c
  src/main-x11.c
Labels: refactor

#291 [refactor] プレイヤーのステータス更新処理のリファクタリング
  src/player/player-status-flags.c
  src/player/player-status-flags.h
  src/player/player-status.c
  src/specific-object/torch.c
  src/specific-object/torch.h
Labels: refactor

#273 [Refactor] tim_player_flagsから二重実装になっている判定を排除
  src/player/player-status-flags.c
  src/player/temporary-resistances.c
Labels: bug, refactor

#308 ﻿[Fix] アリーナ外周の上辺と左辺が永久壁でなく花崗岩になる #294
  src/grid/grid.c
Labels: bug

#315 [Fix] 剣術の技のダイス倍率増加が適用されない #313
  src/mind/mind-samurai.c
Labels: bug

#309 [fix] ペットが召喚したペットが消えない #302
  src/monster-floor/monster-remover.c
  src/monster/monster-processor.c
Labels: bug

#312 [Refactor] ビットテスト/ビット操作マクロの再整理案 #283
  src/combat/shoot.c
  src/knowledge/knowledge-monsters.c
  src/monster-floor/monster-death-util.c
  src/monster-race/monster-race-hook.c
  src/mspell/element-resistance-checker.c
  src/mspell/high-resistance-checker.c
  src/player-attack/player-attack.c
  src/player/permanent-resistances.c
  src/player/player-status.c
  src/player/temporary-resistances.c
  src/util/bit-flags-calculator.h
  src/wizard/monster-info-spoiler.c
Labels: enhancement

#316 Feature/readme md
  readme-eng.md
  readme.md
  readme.txt
  readme_eng.txt
Labels: documentation

#327 Fix: 既知の★一覧でID256以上の★の表示がおかしい #326
  src/knowledge/knowledge-items.c
Labels: bug

#332 [fix] カオスパトロンの報酬の召喚で配列外アクセス #331
  src/monster-floor/monster-summon.c
Labels: bug

#339 [Fix] '%'キーの画面表示の設定項目が減っている #335
  src/knowledge/knowledge-monsters.c
  src/lore/lore-util.h
Labels: bug

#317 [Feature] 帰還できるダンジョンがないのに帰還してしまう #284
  src/cmd-action/cmd-move.c
  src/floor/floor-leaver.c
  src/player/player-move.c
Labels: bug

#336 [Feature]赤魔導士の一部呪文を開放、秘術の調整
  lib/edit/m_info.txt
Labels: enhancement

#343 [Fix] 自然領域のブリザードのコストを調整
  lib/edit/m_info.txt
Labels: bug, enhancement

#345 [Fix] 赤魔道師の説明を修正
  src/birth/birth-explanations-table.c
Labels: enhancement

#344 [feature] mon-desc.txt の折返し表示
  src/wizard/monster-info-spoiler.c
Labels: enhancement

#334 [Fix] 設定ファイルがBOM付で保存される #333
  .editorconfig
Labels: bug, enhancement

#350 [feature] Create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, enhancement

#307 [refactor] 正式なbool型の導入
  src/cmd-building/cmd-building.c
  src/main-gcu.c
  src/mspell/mspell-attack-util.h
  src/system/h-type.h
  src/term/screen-processor.c
  src/term/z-term.c
Labels: refactor

#341 [Fix] 大鷲系モンスターの挙動がおかしい
  src/monster-floor/monster-summon.c
  src/mspell/mspell-special.c
Labels: bug

#352 アーティファクト装備の能力等を調整 (α9)
  lib/edit/a_info.txt
Labels: enhancement

#355 [fix] character_icky の型変更による不具合
  src/cmd-building/cmd-building.c
  src/cmd-building/cmd-store.c
  src/core/game-closer.c
  src/core/game-play.c
  src/core/window-redrawer.c
  src/io/input-key-acceptor.c
  src/player/player-status.c
  src/term/screen-processor.c
  src/world/world.h
Labels: bug

#358 [Feature] 赤魔導師の古い城報酬をサンブレードに変更．
  lib/edit/t0000001.txt
  lib/edit/t_lite.txt
Labels: enhancement

#365 English: edit descriptions for elementary, high, and acting master mystic
  lib/edit/r_info.txt
Labels: translation
