Repository hengband/hengband, pull requests merged in 2021-12, with the labels that each got.

#1904 [Fix] #1901 ウィザードモード廃止による不具合
  lib/help/joption.txt
  lib/help/jversion.txt
  lib/help/option.txt
  lib/help/version.txt
  lib/pref/pref-opt.prf
  src/artifact/random-art-generator.cpp
  src/birth/game-play-initializer.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/core/game-play.cpp
  src/floor/floor-object.cpp
  src/floor/pattern-walk.cpp
  src/game-option/game-play-options.cpp
  src/game-option/game-play-options.h
  src/game-option/option-types-table.cpp
  src/io/input-key-processor.cpp
  src/io/input-key-processor.h
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/option-loader.cpp
  src/mind/monk-attack.cpp
  src/monster-floor/monster-death.cpp
  src/monster/monster-damage.cpp
  src/realm/realm-hex.cpp
  src/save/info-writer.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-kind/spells-world.cpp
  src/spell/spell-info.cpp
  src/target/target-describer.cpp
  src/view/display-lore.cpp
  src/window/main-window-left-frame.cpp
  src/window/main-window-stat-poster.cpp
  src/wizard/wizard-item-modifier.cpp
  src/world/world.h
Labels: bug

#1906 [Release] 3.0.0Alpha48
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1907 Release/3.0.0 alpha48
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  doxygen/Hengband.doxyfile
  lib/help/joption.txt
  lib/help/jversion.txt
  lib/help/option.txt
  lib/help/version.txt
  lib/pref/pref-opt.prf
  src/Makefile.am
  src/artifact/random-art-generator.cpp
  src/birth/game-play-initializer.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-io/cmd-macro.cpp
  src/cmd-item/cmd-equipment.cpp
  src/core/game-play.cpp
  src/effect/effect-player-curse.cpp
  src/effect/effect-player-curse.h
  src/effect/effect-player-oldies.cpp
  src/effect/effect-player-oldies.h
  src/effect/effect-player-resist-hurt.cpp
  src/effect/effect-player-resist-hurt.h
  src/effect/effect-player-spirit.cpp
  src/effect/effect-player-spirit.h
  src/effect/effect-player-switcher.cpp
  src/effect/effect-player-switcher.h
  src/effect/effect-player-util.h
  src/effect/effect-player.cpp
  src/effect/effect-player.h
  src/effect/effect-processor.h
  src/floor/floor-object.cpp
  src/floor/pattern-walk.cpp
  src/game-option/game-play-options.cpp
  src/game-option/game-play-options.h
  src/game-option/option-types-table.cpp
  src/io/input-key-processor.cpp
  src/io/input-key-processor.h
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/option-loader.cpp
  src/mind/monk-attack.cpp
  src/monster-floor/monster-death.cpp
  src/monster/monster-damage.cpp
  src/player/player-skill.cpp
  src/realm/realm-hex.cpp
  src/save/info-writer.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-kind/spells-world.cpp
  src/spell/spell-info.cpp
  src/system/angband-version.h
  src/target/target-describer.cpp
  src/view/display-lore.cpp
  src/window/main-window-left-frame.cpp
  src/window/main-window-stat-poster.cpp
  src/wizard/wizard-item-modifier.cpp
  src/world/world.h
Labels: release

#1911 [Fix] アーティファクトスポイラーの善良スレイ表記がおかしい
  src/wizard/spoiler-table.cpp
Labels: bug

#1895 [Add] アイテムの発動に魔力消去追加。
  src/artifact/random-art-effects.h
  src/object-activation/activation-others.cpp
  src/object-activation/activation-others.h
  src/object-activation/activation-switcher.cpp
  src/object-enchant/activation-info-table.cpp
Labels: enhancement

#1912 [Fix] モンスターの色/文字を正常にprfファイルに保存できない
  src/cmd-visual/cmd-visuals.cpp
Labels: bug

#1913 [Fix] 同一のセーブファイルでゲームを開始するオプションに不要なアスタリスク
  src/game-option/option-types-table.cpp
Labels: bug

#1917 [Fix] PlayerType クラスのメンバに武器スキルの最大値を持たせる
  src/birth/birth-stat.cpp
  src/core/game-play.cpp
  src/knowledge/knowledge-experiences.cpp
  src/object-hook/hook-weapon.cpp
  src/player/player-skill.cpp
  src/player/player-skill.h
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/system/player-type-definition.h
  src/wizard/wizard-special-process.cpp
Labels: bug

#1921 [Feature] AC低下と狂戦士化の特性を自動生成スポイラーに記載する
  src/wizard/spoiler-table.cpp
  src/wizard/spoiler-table.h
Labels: enhancement

#1919 [Refactor] 通常トラップリストのstd::vecor化。
  src/grid/trap.cpp
  src/grid/trap.h
Labels: refactor

#1932 [Fix] #1931 職業選択時、ランダムをカーソル＋Enterで選択すると強制終了する
  src/birth/birth-select-class.cpp
Labels: bug

#1928 mspell.h をmspell-result.h に改名した
  Hengband/Hengband.sln
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/melee/melee-spell.cpp
  src/monster-floor/quantum-effect.cpp
  src/mspell/assign-monster-spell.cpp
  src/mspell/mspell-attack.cpp
  src/mspell/mspell-ball.cpp
  src/mspell/mspell-bolt.cpp
  src/mspell/mspell-breath.cpp
  src/mspell/mspell-curse.cpp
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-floor.cpp
  src/mspell/mspell-particularity.cpp
  src/mspell/mspell-result.h
  src/mspell/mspell-special.cpp
  src/mspell/mspell-status.cpp
  src/mspell/mspell-summon.cpp
Labels: refactor

#1922 [Refactor] enum trap_type を enum clas TrapType にリファクタリング。
  src/grid/trap.cpp
  src/grid/trap.h
  src/player/player-move.cpp
Labels: refactor

#1939 [Fix] #1938 モンスターの思い出にオーラの情報が表示されない
  src/lore/lore-util.cpp
Labels: bug

#1937 [Refactor] MAX_STORESを constexpr int 置換の上、StoreSaleType::MAX を参照。
  src/store/store-owners.cpp
  src/store/store-owners.h
  src/store/store-util.h
Labels: refactor

#1929 [Fix] #1924 異なる鍛冶効果を付与したアイテムが重なってしまう
  src/object/object-stack.cpp
Labels: bug

#1945 Release/3.0.0 alpha49
  Hengband/Hengband.sln
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  doxygen/Hengband.doxyfile
  src/Makefile.am
  src/artifact/random-art-effects.h
  src/autopick/autopick-describer.cpp
  src/birth/birth-select-class.cpp
  src/birth/birth-stat.cpp
  src/cmd-item/cmd-item.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/game-play.cpp
  src/flavor/flavor-util.cpp
  src/game-option/option-types-table.cpp
  src/grid/trap.cpp
  src/grid/trap.h
  src/knowledge/knowledge-experiences.cpp
  src/lore/lore-util.cpp
  src/melee/melee-spell.cpp
  src/monster-floor/quantum-effect.cpp
  src/mspell/assign-monster-spell.cpp
  src/mspell/mspell-attack.cpp
  src/mspell/mspell-ball.cpp
  src/mspell/mspell-bolt.cpp
  src/mspell/mspell-breath.cpp
  src/mspell/mspell-curse.cpp
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-floor.cpp
  src/mspell/mspell-particularity.cpp
  src/mspell/mspell-result.h
  src/mspell/mspell-special.cpp
  src/mspell/mspell-status.cpp
  src/mspell/mspell-summon.cpp
  src/object-activation/activation-others.cpp
  src/object-activation/activation-others.h
  src/object-activation/activation-switcher.cpp
  src/object-enchant/activation-info-table.cpp
  src/object-hook/hook-weapon.cpp
  src/object/object-stack.cpp
  src/player/player-move.cpp
  src/player/player-skill.cpp
  src/player/player-skill.h
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/store/store-owners.cpp
  src/store/store-owners.h
  src/store/store-util.h
  src/system/angband-version.h
  src/system/h-type.h
  src/system/player-type-definition.h
  src/window/display-sub-window-items.cpp
  src/wizard/spoiler-table.cpp
  src/wizard/spoiler-table.h
  src/wizard/wizard-special-process.cpp
Labels: release

#1926 [Feature] モンスターの召喚魔法によるプレイヤー連続行動阻害の条件を統一
  src/mspell/mspell-summon.cpp
Labels: enhancement

#1927 [Feature] モンスターの特殊な行動、回復について連続行動阻害の要件を整理
  src/mspell/mspell-special.cpp
  src/mspell/mspell-status.cpp
Labels: enhancement

#1944 [Release] 3.0.0Alpha49
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1933 Feature/refctor monster knowledge count
  src/knowledge/knowledge-monsters.cpp
Labels: enhancement, refactor
