Repository hengband/hengband, pull requests merged in 2021-10, with the labels that each got.

#1689 青魔法関連のリファクタリング
  src/blue-magic/blue-magic-checker.cpp
  src/blue-magic/learnt-power-getter.cpp
  src/blue-magic/learnt-power-getter.h
  src/cmd-action/cmd-mane.cpp
  src/io-dump/special-class-dump.cpp
  src/mind/mind-blue-mage.cpp
  src/mspell/monster-power-table.cpp
  src/mspell/monster-power-table.h
Labels: refactor

#1686 初心者用簡単モードを削除した
  lib/help/joption.txt
  lib/help/option.txt
  lib/pref/pref-opt.prf
  src/cmd-io/cmd-gameoption.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/core/scores.cpp
  src/game-option/birth-options.cpp
  src/game-option/birth-options.h
  src/game-option/option-types-table.cpp
  src/game-option/option-types-table.h
  src/load/option-loader.cpp
  src/mspell/mspell-summon.cpp
  src/player/player-damage.cpp
  src/player/player-status.cpp
  src/spell/spells-summon.cpp
  src/term/term-color-types.h
Labels: refactor

#1691 effect-player.cpp の整形
  src/effect/effect-player.cpp
Labels: refactor

#1697 [Refactor] ASCII文字↔整数の変換マクロ群を関数化する
  src/util/int-char-converter.h
Labels: refactor

#1703 [Refactor] スポイラー出力に使用するアイテムのカテゴリ分けテーブル
  src/io-dump/random-art-info-dumper.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/spoiler-table.cpp
  src/wizard/spoiler-table.h
Labels: refactor

#1699 忍者以外でも変わり身で攻撃を回避する場合がある不具合を解消した
  src/effect/effect-player.cpp
  src/mind/mind-ninja.cpp
  src/monster-attack/monster-attack-player.cpp
Labels: bug

#1706 [Feature] #83 ウェイト値をmsecで0から1000へ選択可能に。
  src/cmd-io/cmd-gameoption.cpp
  src/combat/shoot.cpp
  src/effect/effect-processor.cpp
  src/game-option/special-options.cpp
  src/game-option/special-options.h
  src/load/option-loader.cpp
  src/mind/mind-mirror-master.cpp
  src/object-use/throw-execution.cpp
  src/save/info-writer.cpp
  src/spell-kind/spells-genocide.cpp
Labels: enhancement

#1705 [Feature] デバッグコマンドの固定アーティファクト生成をリストで選択する
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-special-process.h
Labels: enhancement

#1698 activation_info を配列からvectorに差し替えた
  src/action/activation-execution.cpp
  src/artifact/artifact-info.cpp
  src/artifact/artifact-info.h
  src/artifact/random-art-effects.h
  src/object-enchant/activation-info-table.cpp
  src/object-enchant/activation-info-table.h
  src/object/object-info.cpp
  src/object/object-value-calc.cpp
Labels: refactor

#1707 [Refactor] 剣術家の型を職業固有データに移動する
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-action/cmd-attack.cpp
  src/cmd-action/cmd-hissatsu.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-others.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-action/cmd-racial.cpp
  src/cmd-action/cmd-shoot.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-action/cmd-tunnel.cpp
  src/cmd-item/cmd-destroy.cpp
  src/cmd-item/cmd-eat.cpp
  src/cmd-item/cmd-equipment.cpp
  src/cmd-item/cmd-item.cpp
  src/cmd-item/cmd-quaff.cpp
  src/cmd-item/cmd-read.cpp
  src/cmd-item/cmd-refill.cpp
  src/cmd-item/cmd-throw.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/cmd-item/cmd-zaprod.cpp
  src/cmd-item/cmd-zapwand.cpp
  src/core/player-processor.cpp
  src/effect/effect-player.cpp
  src/hpmp/hp-mp-processor.cpp
  src/hpmp/hp-mp-regenerator.cpp
  src/io/input-key-processor.cpp
  src/load/player-attack-loader.cpp
  src/load/player-class-specific-data-loader.cpp
  src/load/player-class-specific-data-loader.h
  src/mind/mind-samurai.cpp
  src/mind/stances-table.cpp
  src/mind/stances-table.h
  src/monster-attack/monster-attack-player.cpp
  src/monster/monster-update.cpp
  src/player-ability/player-charisma.cpp
  src/player-ability/player-constitution.cpp
  src/player-ability/player-dexterity.cpp
  src/player-ability/player-intelligence.cpp
  src/player-ability/player-strength.cpp
  src/player-ability/player-wisdom.cpp
  src/player-base/player-class.cpp
  src/player-base/player-class.h
  src/player-info/class-specific-data.h
  src/player-info/samurai-data-type.h
  src/player/digestion-processor.cpp
  src/player/permanent-resistances.cpp
  src/player/player-damage.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/player/race-resistances.cpp
  src/player/special-defense-types.h
  src/save/player-class-specific-data-writer.cpp
  src/save/player-class-specific-data-writer.h
  src/status/action-setter.cpp
  src/status/bad-status-setter.cpp
  src/status/element-resistance.cpp
  src/window/main-window-stat-poster.cpp
Labels: refactor

#1715 alloc-entry-definition.h を alloc-entries.h に吸収合併した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/system/alloc-entries.h
  src/system/alloc-entry-definition.h
Labels: refactor

#1709 random-art-activation-type をenum classに置換した
  src/action/activation-execution.cpp
  src/artifact/artifact-info.cpp
  src/artifact/artifact-info.h
  src/artifact/fixed-art-generator.cpp
  src/artifact/random-art-activation.cpp
  src/artifact/random-art-effects.h
  src/artifact/random-art-generator.cpp
  src/info-reader/artifact-reader.cpp
  src/info-reader/ego-reader.cpp
  src/info-reader/info-reader-util.cpp
  src/info-reader/info-reader-util.h
  src/info-reader/kind-reader.cpp
  src/load/item-loader.cpp
  src/load/load-v1-5-0.cpp
  src/load/savedata-flag-types.h
  src/market/building-craft-fix.cpp
  src/object-activation/activation-switcher.cpp
  src/object-enchant/activation-info-table.cpp
  src/object-enchant/activation-info-table.h
  src/object-enchant/object-boost.cpp
  src/object-enchant/object-ego.cpp
  src/object-enchant/object-ego.h
  src/object-enchant/object-smith.cpp
  src/object-enchant/object-smith.h
  src/object-enchant/smith-info.cpp
  src/object-enchant/smith-info.h
  src/object-enchant/smith-tables.cpp
  src/object/object-info.cpp
  src/object/object-kind.h
  src/save/item-writer.cpp
  src/system/artifact-type-definition.h
  src/system/object-type-definition.cpp
  src/system/object-type-definition.h
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#1712 quest-completion-checker.cpp/h をクラス化した
  src/birth/game-play-initializer.cpp
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-move.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest-completion-checker.cpp
  src/dungeon/quest-completion-checker.h
  src/dungeon/quest-monster-placer.cpp
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/effect/effect-monster-charm.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-events.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-util.cpp
  src/floor/wild.cpp
  src/info-reader/fixed-map-parser.cpp
  src/io/write-diary.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/load.cpp
  src/load/quest-loader.cpp
  src/main/game-data-initializer.cpp
  src/market/building-quest.cpp
  src/melee/melee-spell-util.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-runaway.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-status-setter.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-attack.cpp
  src/player-status/player-speed.cpp
  src/player/player-damage.cpp
  src/player/player-move.cpp
  src/save/save.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-grid.cpp
  src/spell-kind/spells-world.cpp
  src/spell-realm/spells-chaos.cpp
  src/view/display-player.cpp
  src/wizard/wizard-game-modifier.cpp
  src/world/world-movement-processor.cpp
Labels: refactor

#1728 [Fix] 詐欺オプションでカーソルが動かない
  src/cmd-io/cmd-gameoption.cpp
Labels: bug

#1730 [Feature] 鍛冶で岩石溶解の発動付加のエッセンス消費量を増やす
  src/object-enchant/smith-tables.cpp
Labels: enhancement

#1726 [Refactor] 忍者のデータを職業固有データに移動する
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-action/cmd-move.cpp
  src/dungeon/dungeon-processor.cpp
  src/effect/effect-feature.cpp
  src/floor/floor-events.cpp
  src/floor/floor-leaver.cpp
  src/grid/feature.cpp
  src/load/player-class-specific-data-loader.cpp
  src/load/player-class-specific-data-loader.h
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-lite.cpp
  src/monster/monster-damage.cpp
  src/monster/monster-processor.cpp
  src/player-base/player-class.cpp
  src/player-info/class-specific-data.h
  src/player-info/ninja-data-type.h
  src/player/special-defense-types.h
  src/save/player-class-specific-data-writer.cpp
  src/save/player-class-specific-data-writer.h
  src/specific-object/torch.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-lite.cpp
  src/window/main-window-stat-poster.cpp
Labels: refactor

#1733 [Modify] Windows版アイコンを斑多氏案に変更。
  src/angband.ico
Labels: enhancement

#1732 呪術のおかしな挙動の修正
  src/realm/realm-hex.cpp
  src/status/action-setter.cpp
Labels: bug

#1734 忍者の変わり身が意図せず発動する事象を修正した
  src/effect/effect-player.cpp
Labels: bug

#1735 塔のクエストがクリア状態にならない不具合を解消した
  src/cmd-action/cmd-move.cpp
Labels: bug

#1725 QuestCompletionCheckerクラスの分割
  src/dungeon/quest-completion-checker.cpp
  src/dungeon/quest-completion-checker.h
Labels: refactor

#1736 ランダムクエスト報酬を改善した
  src/dungeon/quest-completion-checker.cpp
  src/dungeon/quest-completion-checker.h
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/grid/object-placer.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/specific-object/chest.cpp
  src/spell/spells-object.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: enhancement

#1738 [Release] 3.0.0Alpha40
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1741 make_object() の引数rq_level をデフォルト引数にし、型もintからstd::optional<int>に変更した
  src/dungeon/quest-completion-checker.cpp
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/grid/object-placer.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/specific-object/chest.cpp
  src/spell/spells-object.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#1749 '? true : false' 形式の判定を適切に差し替えた
  src/artifact/fixed-art-generator.cpp
  src/info-reader/fixed-map-parser.cpp
  src/load/item-loader.cpp
  src/load/option-loader.cpp
  src/lore/lore-calculator.cpp
  src/main-win.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/pet/pet-util.cpp
  src/player/player-damage.cpp
  src/player/player-move.cpp
  src/player/player-status.cpp
  src/realm/realm-arcane.cpp
  src/realm/realm-chaos.cpp
  src/realm/realm-craft.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-death.cpp
  src/realm/realm-demon.cpp
  src/realm/realm-hissatsu.cpp
  src/realm/realm-names-table.h
  src/realm/realm-nature.cpp
  src/realm/realm-song.cpp
  src/realm/realm-sorcery.cpp
  src/realm/realm-trump.cpp
  src/spell-kind/spells-polymorph.cpp
  src/store/cmd-store.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#1759 乱数生成に STL を使用する
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/flavor/object-flavor.cpp
  src/floor/wild.cpp
  src/load/info-loader.cpp
  src/monster-floor/special-death-switcher.cpp
  src/mspell/specified-summon.cpp
  src/object-enchant/apply-magic-ring.cpp
  src/save/info-writer.cpp
  src/term/z-rand.cpp
  src/term/z-rand.h
  src/util/rng-xoshiro.cpp
  src/util/rng-xoshiro.h
  src/world/world.h
Labels: refactor

#1764 arena-type構造体をbuilding-type-definition.h から arena-info-table.h に移した
  src/market/arena-info-table.cpp
  src/market/arena-info-table.h
  src/system/building-type-definition.h
Labels: refactor

#1768 [Feature] 英語版のフレーバーテキストを良い感じに連結する
  src/info-reader/artifact-reader.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/info-reader-util.cpp
  src/info-reader/info-reader-util.h
  src/info-reader/kind-reader.cpp
  src/info-reader/race-reader.cpp
Labels: enhancement

#1784 MAX() のマクロ関数をstd::max() に差し替えた
  src/autopick/autopick-drawer.cpp
  src/autopick/autopick-editor-command.cpp
  src/autopick/autopick-editor-util.cpp
  src/avatar/avatar.cpp
  src/birth/auto-roller.cpp
  src/cmd-action/cmd-mind.cpp
  src/cmd-item/cmd-eat.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/cmd-item/cmd-zapwand.cpp
  src/cmd-visual/cmd-draw.cpp
  src/combat/attack-criticality.cpp
  src/combat/attack-power-table.cpp
  src/combat/slaying.cpp
  src/effect/effect-monster-charm.cpp
  src/effect/effect-player-spirit.cpp
  src/floor/floor-events.cpp
  src/floor/object-scanner.cpp
  src/io-dump/dump-util.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/market/arena.cpp
  src/market/bounty.cpp
  src/market/building-craft-fix.cpp
  src/market/building-recharger.cpp
  src/melee/melee-switcher.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-samurai.cpp
  src/mind/monk-attack.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/monster-floor/monster-move.cpp
  src/monster/monster-list.cpp
  src/object-enchant/object-boost.cpp
  src/object-enchant/object-ego.cpp
  src/object-use/quaff-execution.cpp
  src/object/warning.cpp
  src/player/player-damage.cpp
  src/player/player-status.cpp
  src/racial/racial-android.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-nature.cpp
  src/room/rooms-city.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-kind/spells-world.cpp
  src/spell/spell-info.cpp
  src/store/store.cpp
  src/system/h-define.h
  src/target/target-preparation.cpp
  src/view/display-lore-drops.cpp
  src/view/display-self-info.cpp
  src/view/status-first-page.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#1783 [Refactor] セーブファイルから整数値を読み込む関数のインターフェース
  src/load/birth-loader.cpp
  src/load/dummy-loader.cpp
  src/load/dungeon-loader.cpp
  src/load/extra-loader.cpp
  src/load/floor-loader.cpp
  src/load/info-loader.cpp
  src/load/inventory-loader.cpp
  src/load/item-loader.cpp
  src/load/load-util.cpp
  src/load/load-util.h
  src/load/load-v1-5-0.cpp
  src/load/load-v1-7-0.cpp
  src/load/load-zangband.cpp
  src/load/load.cpp
  src/load/lore-loader.cpp
  src/load/monster-loader.cpp
  src/load/option-loader.cpp
  src/load/player-attack-loader.cpp
  src/load/player-class-specific-data-loader.cpp
  src/load/player-info-loader.cpp
  src/load/quest-loader.cpp
  src/load/store-loader.cpp
  src/load/world-loader.cpp
  src/util/flag-group.h
Labels: refactor

#1779 [Implement] get_value()が参照代入値ポインタの入力前値をデフォルト値にするよう仕様追加。
  src/core/asking-player.cpp
  src/wizard/wizard-spells.cpp
Labels: enhancement

#1791 モンスターのオーラ情報をflag2/3 からaura_flags へ分離した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/movement-execution.cpp
  src/hpmp/hp-mp-processor.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/load/item-loader.cpp
  src/load/load.cpp
  src/load/lore-loader.cpp
  src/load/lore-loader.h
  src/load/savedata-old-flag-types.h
  src/lore/lore-calculator.cpp
  src/lore/lore-util.h
  src/melee/monster-attack-monster.cpp
  src/monster-race/monster-aura-types.h
  src/monster-race/monster-race-hook.cpp
  src/monster-race/race-flags2.h
  src/monster-race/race-flags3.h
  src/monster/monster-info.cpp
  src/monster/monster-update.cpp
  src/player/player-damage.cpp
  src/save/monster-writer.cpp
  src/system/angband-version.h
  src/system/monster-race-definition.h
  src/view/display-lore.cpp
Labels: refactor

#1795 秩序の指輪が他より重かった不具合を修正した
  lib/edit/k_info.txt
Labels: bug

#1797 [Fix] おじゃまぷよの英文フレーバーが余計だった（爆発は別にしない）ので修正。
  lib/edit/r_info.txt
Labels: bug

#1794 deleteしているだけのデフォルトコンストラクタを消した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/avatar/avatar-changer.h
  src/monster-floor/monster-sweep-grid.h
  src/monster/monster-damage.h
  src/mspell/mspell.h
  src/object-enchant/abstract-protector-enchanter.h
  src/object-enchant/apply-magic-amulet.h
  src/object-enchant/apply-magic-armor.h
  src/object-enchant/apply-magic-boots.h
  src/object-enchant/apply-magic-cloak.h
  src/object-enchant/apply-magic-crown.h
  src/object-enchant/apply-magic-gloves.h
  src/object-enchant/apply-magic-helm.h
  src/object-enchant/apply-magic-ring.h
  src/object-enchant/apply-magic-shield.h
  src/object/object-broken.h
  src/player-ability/player-charisma.cpp
  src/player-ability/player-charisma.h
  src/player-ability/player-constitution.cpp
  src/player-ability/player-constitution.h
  src/player-ability/player-dexterity.cpp
  src/player-ability/player-dexterity.h
  src/player-ability/player-intelligence.cpp
  src/player-ability/player-intelligence.h
  src/player-ability/player-strength.cpp
  src/player-ability/player-strength.h
  src/player-ability/player-wisdom.cpp
  src/player-ability/player-wisdom.h
  src/player-base/player-class.h
  src/player-base/player-race.h
  src/player-info/alignment.h
  src/player-status/player-basic-statistics.cpp
  src/player-status/player-basic-statistics.h
  src/player-status/player-energy.h
  src/player-status/player-infravision.cpp
  src/player-status/player-infravision.h
  src/player-status/player-speed.cpp
  src/player-status/player-speed.h
  src/player-status/player-status-base.cpp
  src/player-status/player-status-base.h
  src/player-status/player-stealth.cpp
  src/player-status/player-stealth.h
  src/player/player-status.cpp
  src/spell-realm/spells-hex.h
Labels: refactor

#1798 item-loader.cpp/h をクラス化し、ファクトリクラスで処理を分割した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/load/dummy-loader.cpp
  src/load/dungeon-loader.cpp
  src/load/floor-loader.cpp
  src/load/inventory-loader.cpp
  src/load/item-loader.h
  src/load/item/item-loader-base.cpp
  src/load/item/item-loader-base.h
  src/load/item/item-loader-factory.cpp
  src/load/item/item-loader-factory.h
  src/load/item/item-loader-version-types.h
  src/load/load.cpp
  src/load/lore-loader.cpp
  src/load/old/item-flag-types-savefile10.h
  src/load/old/item-loader-savefile10.cpp
  src/load/old/item-loader-savefile10.h
  src/load/old/load-v1-5-0.cpp
  src/load/old/load-v1-5-0.h
  src/load/old/load-v1-7-0.cpp
  src/load/old/load-v1-7-0.h
  src/load/old/monster-flag-types-savefile10.h
  src/load/old/monster-loader-savefile10.cpp
  src/load/old/monster-loader-savefile10.h
  src/load/player-info-loader.cpp
  src/load/store-loader.cpp
  src/load/store-loader.h
  src/main-win.cpp
  src/save/item-writer.cpp
  src/save/monster-writer.cpp
Labels: refactor

#1801 monster-loader.cpp/h をクラス化し、ファクトリクラスで処理を分割した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/load/dummy-loader.cpp
  src/load/floor-loader.cpp
  src/load/monster/monster-loader-base.h
  src/load/monster/monster-loader-factory.cpp
  src/load/monster/monster-loader-factory.h
  src/load/monster/monster-loader-version-types.h
  src/load/old/load-v1-5-0.cpp
  src/load/old/monster-loader-savefile10.cpp
  src/load/old/monster-loader-savefile10.h
Labels: refactor

#1810 [Fix] 敵がファイア・ボールを唱えた時にクラッシュする
  src/mspell/mspell-ball.cpp
Labels: bug

#1817 [Fix] キャラメイクの職業選択時におかしな挙動が発生する
  src/birth/birth-select-class.cpp
Labels: bug

#1820 [Release] 3.0.0Alpha43
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1806 [Feature] 天上のクロークに浮遊能力を追加
  lib/edit/k_info.txt
Labels: enhancement

#1804 [Refactor] 魔法の熟練度処理を PlayerSkill クラスに移設
  src/cmd-action/cmd-spell.cpp
  src/knowledge/knowledge-experiences.cpp
  src/player/player-skill.cpp
  src/player/player-skill.h
  src/player/player-status.cpp
  src/player/player-status.h
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-hex.h
  src/spell-realm/spells-song.cpp
  src/spell/spell-info.cpp
  src/spell/spell-info.h
Labels: refactor

#1755 [Add] 『カルバノグの殺人兎』/ The Killer Rabbit of Caerbannog
  lib/edit/r_info.txt
Labels: enhancement

#1836 [Refactor] 熟練度レベルの定数を enum class にする
  src/birth/birth-stat.cpp
  src/cmd-action/cmd-spell.cpp
  src/combat/shoot.cpp
  src/core/game-play.cpp
  src/info-reader/skill-reader.cpp
  src/knowledge/knowledge-experiences.cpp
  src/load/player-info-loader.cpp
  src/object-hook/hook-weapon.cpp
  src/player/player-skill.cpp
  src/player/player-skill.h
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/spell/spell-info.cpp
  src/view/display-player-middle.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor

#1838 [Refactor] モンスターの限界最大HP(30000)がマジックナンバーになっていたのを const int に変更
  src/effect/effect-monster-oldies.cpp
  src/load/old/load-v1-5-0.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-list.cpp
  src/monster/monster-status.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/system/monster-type-definition.h
  src/view/display-lore-status.cpp
Labels: refactor

#1846 [Release] 3.0.0Alpha45
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release
