Repository hengband/hengband, pull requests merged in 2021-09, with the labels that each got.

#1443 乗馬中に「乗馬にふさわしくない武器」を判定するルーチンの修正
  src/cmd-action/cmd-mind.cpp
  src/combat/attack-criticality.cpp
  src/flavor/flavor-describer.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-ninja.cpp
  src/mind/mind-power-getter.cpp
  src/perception/identification.cpp
  src/player/permanent-resistances.cpp
  src/player/player-status-flags.cpp
  src/player/player-status-flags.h
  src/player/player-status.cpp
  src/spell/spell-info.cpp
  src/system/object-type-definition.cpp
  src/system/object-type-definition.h
  src/system/player-type-definition.h
Labels: bug

#1428 Windowsとそれ以外で使用するプリプロを分ける
  src/system/h-config.h
Labels: refactor

#1445 ランダムアーティファクトの銘を選択するルーチンが冗長だったので簡略化した
  src/artifact/random-art-characteristics.cpp
Labels: refactor

#1453 上位耐性のランダム付与とランダムアーティファクトに 3.0.0Alpha で新しく追加された耐性が付与されるようにする
  src/artifact/random-art-resistance.cpp
  src/object-enchant/object-boost.cpp
Labels: enhancement

#1456 object_type::is_offerable() のコンパイル警告修正
  src/system/object-type-definition.cpp
Labels: refactor

#1457 SGN() の削除 他 jump_floors() の微修正
  src/floor/floor-leaver.cpp
  src/system/h-define.h
Labels: refactor

#1421 [Refactor] io-dump ディレクトリ内のコメントを Doxygen 向けに整理．
  src/io-dump/dump-util.cpp
Labels: refactor

#1408 [Refactor] avatar ディレクトリ以下のコメントをDoxygen向けに追加、整理．
  src/avatar/avatar-changer.cpp
Labels: documentation, refactor

#1416 もう使われていないプリプロの削除＠h-system.h
  src/main-cap.cpp
  src/main-gcu.cpp
  src/system/h-system.h
Labels: refactor

#1467 grid-type.cpp/h のリファクタリング＆メソッド移動
  src/grid/feature.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/target/grid-selector.cpp
Labels: refactor

#1470 [Release] 3.0.0Alpha37
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1463 [Fix] X11版インターフェースのリソースリーク
  src/main-x11.cpp
Labels: bug

#1481 [Fix] すべてのソースファイルにBOMを付与する
  src/autopick/autopick-methods-table.h
  src/dungeon/dungeon-flag-mask.h
  src/market/building-initializer.h
  src/monster-floor/monster-dist-offsets.h
  src/player-info/self-info-util.h
Labels: bug

#1483 [Implement] 地形や毒等のダメージ発生時の効果音を追加
  lib/xtra/sound/sound.cfg
  src/hpmp/hp-mp-processor.cpp
  src/main/sound-definitions-table.cpp
  src/main/sound-definitions-table.h
Labels: enhancement

#1484 [Refactor] ビットフラグをFlagGroupに移行するコードに共通関数を使用する
  src/load/item-loader.cpp
  src/load/load-util.h
  src/load/load-v1-5-0.cpp
  src/load/lore-loader.cpp
  src/load/monster-loader.cpp
  src/load/player-info-loader.cpp
Labels: refactor

#1482 spells-hex.cpp/h のクラス化＆メソッド分割
  src/action/activation-execution.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-item/cmd-eat.cpp
  src/cmd-item/cmd-quaff.cpp
  src/combat/aura-counterattack.cpp
  src/combat/slaying.cpp
  src/core/player-processor.cpp
  src/effect/effect-player.cpp
  src/floor/wild.cpp
  src/market/building-craft-weapon.cpp
  src/melee/melee-spell.cpp
  src/melee/monster-attack-monster.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster/monster-processor.cpp
  src/mspell/mspell-attack.cpp
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-floor.cpp
  src/mutation/mutation-processor.cpp
  src/object-activation/activation-breath.cpp
  src/object-activation/activation-others.cpp
  src/object-use/quaff-execution.cpp
  src/object-use/read-execution.cpp
  src/player-ability/player-constitution.cpp
  src/player-ability/player-dexterity.cpp
  src/player-ability/player-strength.cpp
  src/player-attack/attack-chaos-effect.cpp
  src/player-attack/blood-sucking-processor.cpp
  src/player-attack/player-attack.cpp
  src/player-status/player-speed.cpp
  src/player-status/player-stealth.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/racial/racial-switcher.cpp
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-hex.h
  src/status/action-setter.cpp
  src/status/bad-status-setter.cpp
  src/window/main-window-stat-poster.cpp
Labels: refactor

#1494 [Feature] 鍛冶師のエッセンスの所持数と必要数の表記位置を入れ替える
  src/cmd-item/cmd-smith.cpp
Labels: enhancement

#1486 monster-attack-player.cpp に定義されていた呪術関係の処理をspells-hex.cpp/h へ移した
  src/monster-attack/monster-attack-player.cpp
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-hex.h
Labels: refactor

#1502 [Feature] clang-format の設定の ColumnLimit を 0 にする
  .clang-format
Labels: enhancement, refactor

#1497 鍛冶師リファクタリング
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/artifact/artifact-info.cpp
  src/artifact/random-art-effects.h
  src/cmd-item/cmd-smith.cpp
  src/cmd-item/cmd-smith.h
  src/flavor/flavor-describer.cpp
  src/flavor/object-flavor.cpp
  src/io-dump/special-class-dump.cpp
  src/io/input-key-processor.cpp
  src/load/load-v1-5-0.cpp
  src/load/load.cpp
  src/mind/mind-weaponsmith.cpp
  src/mind/mind-weaponsmith.h
  src/object-enchant/object-smith.cpp
  src/object-enchant/object-smith.h
  src/object-enchant/smith-tables.cpp
  src/object-enchant/smith-tables.h
  src/object-enchant/smith-types.h
  src/object/object-flags.cpp
  src/store/store-key-processor.cpp
  src/system/angband-version.h
  src/system/object-type-definition.cpp
Labels: refactor

#1503 型エイリアスの削除 Alpha38
  src/grid/feature.h
  src/store/service-checker.cpp
  src/system/h-type.h
  src/system/object-type-definition.h
Labels: refactor

#1510 [Refactor] 鍛冶効果情報をカスタマイズしやすく再設計
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/object-enchant/object-smith.cpp
  src/object-enchant/object-smith.h
  src/object-enchant/smith-info.cpp
  src/object-enchant/smith-info.h
  src/object-enchant/smith-tables.cpp
  src/object-enchant/smith-tables.h
Labels: enhancement, refactor

#1516 [Feature] 鍛冶師のエッセンスを全て最大所持量にするデバッグコマンド
  src/object-enchant/object-smith.cpp
  src/object-enchant/object-smith.h
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
Labels: enhancement

#1515 鍛冶コマンドの複数ページ対応/いくつかの鍛冶効果を追加
  src/mind/mind-weaponsmith.cpp
  src/object-enchant/object-smith.cpp
  src/object-enchant/smith-info.cpp
  src/object-enchant/smith-info.h
  src/object-enchant/smith-tables.cpp
  src/object-enchant/smith-types.h
Labels: enhancement

#1525 [Fix] +2以上の追加攻撃の鍛冶ができてしまう
  src/mind/mind-weaponsmith.cpp
Labels: bug

#1519 新規鍛冶効果の追加
  src/load/load-v1-3-0.cpp
  src/market/building-craft-fix.cpp
  src/object-enchant/object-smith.cpp
  src/object-enchant/smith-info.cpp
  src/object-enchant/smith-tables.cpp
  src/object-enchant/smith-types.h
  src/object-enchant/tr-types.h
  src/player/player-status-flags.cpp
Labels: enhancement

#1531 [Fix] 矢弾に効果の無いエッセンスが付与できてしまう
  src/object-enchant/smith-info.cpp
Labels: bug

#1526 arg_fiddleを常時真として削除した
  src/game-option/runtime-arguments.cpp
  src/game-option/runtime-arguments.h
  src/load/info-loader.cpp
  src/load/item-loader.cpp
  src/load/load.cpp
  src/load/lore-loader.cpp
  src/main.cpp
Labels: refactor

#1518 spells-hex.h に定義された関数マクロの除去
  src/action/activation-execution.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-item/cmd-eat.cpp
  src/cmd-item/cmd-quaff.cpp
  src/combat/aura-counterattack.cpp
  src/combat/slaying.cpp
  src/core/player-processor.cpp
  src/effect/effect-player.cpp
  src/floor/wild.cpp
  src/market/building-craft-weapon.cpp
  src/melee/melee-spell.cpp
  src/melee/monster-attack-monster.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster/monster-processor.cpp
  src/mspell/mspell-attack.cpp
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-floor.cpp
  src/mutation/mutation-processor.cpp
  src/object-activation/activation-breath.cpp
  src/object-activation/activation-others.cpp
  src/object-use/quaff-execution.cpp
  src/object-use/read-execution.cpp
  src/player-ability/player-constitution.cpp
  src/player-ability/player-dexterity.cpp
  src/player-ability/player-strength.cpp
  src/player-attack/attack-chaos-effect.cpp
  src/player-attack/blood-sucking-processor.cpp
  src/player-attack/player-attack.cpp
  src/player-status/player-speed.cpp
  src/player-status/player-stealth.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/racial/racial-switcher.cpp
  src/realm/realm-arcane.cpp
  src/realm/realm-chaos.cpp
  src/realm/realm-craft.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-death.cpp
  src/realm/realm-demon.cpp
  src/realm/realm-hex-numbers.h
  src/realm/realm-hex.cpp
  src/realm/realm-hex.h
  src/realm/realm-hissatsu.cpp
  src/realm/realm-life.cpp
  src/realm/realm-nature.cpp
  src/realm/realm-song.cpp
  src/realm/realm-sorcery.cpp
  src/realm/realm-trump.cpp
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-hex.h
  src/spell-realm/spells-song.cpp
  src/spell/spells-execution.cpp
  src/spell/spells-util.h
  src/status/action-setter.cpp
  src/status/bad-status-setter.cpp
  src/system/player-type-definition.h
  src/window/main-window-stat-poster.cpp
Labels: refactor

#1530 arg_wizardを常時偽として削除した
  src/core/game-play.cpp
  src/game-option/runtime-arguments.cpp
  src/game-option/runtime-arguments.h
  src/io/input-key-processor.cpp
  src/load/load.cpp
  src/main.cpp
Labels: refactor

#1533 [Refactor] 関数テンプレート i2enum を導入
  src/birth/birth-select-class.cpp
  src/birth/birth-select-race.cpp
  src/birth/birth-wizard.cpp
  src/birth/inventory-initializer.cpp
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-mind.cpp
  src/cmd-action/cmd-racial.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-monster.cpp
  src/flavor/flavor-util.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/wild.cpp
  src/info-reader/general-parser.cpp
  src/io-dump/special-class-dump.cpp
  src/knowledge/knowledge-inventory.cpp
  src/knowledge/knowledge-self.cpp
  src/load/birth-loader.cpp
  src/load/load-v1-5-0.cpp
  src/load/monster-loader.cpp
  src/load/player-info-loader.cpp
  src/load/store-loader.cpp
  src/market/building-craft-fix.cpp
  src/market/building-initializer.cpp
  src/market/building-quest.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-blue-mage.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-weaponsmith.cpp
  src/mspell/mspell-special.cpp
  src/mutation/mutation-processor.cpp
  src/object-enchant/object-curse.cpp
  src/object-enchant/object-smith.cpp
  src/object-use/quaff-execution.cpp
  src/player-status/player-status-base.cpp
  src/player/player-status-flags.cpp
  src/player/temporary-resistances.cpp
  src/specific-object/bloody-moon.cpp
  src/spell-kind/spells-random.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-trump.cpp
  src/spell/spells-execution.cpp
  src/target/target-setter.cpp
  src/util/enum-converter.h
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-player-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spells.cpp
Labels: refactor

#1541 [Fix] 矢弾に装備品用のエッセンスを付与できる
  src/object-enchant/smith-info.cpp
Labels: bug

#1542 [Fix] #1138 あてどなくふらつく商人の説明文に誤訳、「魅力のアミュレット」ではなく「装飾のアミュレット」に修正した
  lib/edit/r_info.txt
Labels: bug, documentation, translation

#1527 鍛冶師の発動効果の追加と仕様変更
  src/artifact/artifact-info.cpp
  src/load/item-loader.cpp
  src/load/savedata-flag-types.h
  src/mind/mind-weaponsmith.cpp
  src/object-enchant/object-smith.cpp
  src/object-enchant/object-smith.h
  src/object-enchant/smith-info.cpp
  src/object-enchant/smith-info.h
  src/object-enchant/smith-tables.cpp
  src/object-enchant/smith-types.h
  src/object/object-flags.cpp
  src/save/item-writer.cpp
  src/system/object-type-definition.cpp
  src/system/object-type-definition.h
Labels: enhancement

#1546 モンスターが直接攻撃をしない事象を修正した
  src/monster-attack/monster-attack-player.cpp
Labels: bug

#1539 [Refactor] モンスター進化のスポイラー生成ルーチン
  src/util/sort.cpp
  src/util/sort.h
  src/wizard/wizard-spoiler.cpp
Labels: enhancement, refactor

#1540 [Fix] メニューコマンドでエッセンス付与する時の挙動
  src/mind/mind-weaponsmith.cpp
Labels: bug

#1548 player_type から時限ステータスを分離した (朦朧のみ)
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/action-limited.cpp
  src/action/movement-execution.cpp
  src/action/racial-execution.cpp
  src/blue-magic/blue-magic-checker.cpp
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-attack.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-action/cmd-mind.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-action/cmd-shoot.cpp
  src/cmd-building/cmd-inn.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/core/player-processor.cpp
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-psi.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/floor/pattern-walk.cpp
  src/load/item-loader.cpp
  src/load/player-info-loader.cpp
  src/mind/mind-blue-mage.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-ninja.cpp
  src/mind/mind-power-getter.cpp
  src/mind/mind-samurai.cpp
  src/mind/monk-attack.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-attack/monster-attack-status.cpp
  src/object-use/quaff-execution.cpp
  src/player-info/self-info.cpp
  src/player/player-status.cpp
  src/save/player-writer.cpp
  src/specific-object/chest.cpp
  src/spell-kind/earthquake.cpp
  src/spell/spell-info.cpp
  src/status/bad-status-setter.cpp
  src/status/buff-setter.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/timed-effect/player-stun.cpp
  src/timed-effect/player-stun.h
  src/timed-effect/timed-effects.cpp
  src/timed-effect/timed-effects.h
  src/window/display-sub-window-spells.cpp
  src/window/main-window-stat-poster.cpp
Labels: refactor

#1547 モンスター調整(＋一部追加) Alpha38
  lib/edit/misc.txt
  lib/edit/r_info.txt
  lib/file/mondeath.txt
  lib/file/monfear.txt
Labels: enhancement

#1552 アイテム調整＋追加 Alpha38
  lib/edit/k_info.txt
  lib/edit/misc.txt
  lib/file/w_low_j.txt
  src/object-enchant/apply-magic-ring.cpp
  src/sv-definition/sv-ring-types.h
Labels: refactor

#1550 投稿頂いたユニークモンスターの実装 兼 今後のためのコミットサンプル
  lib/edit/misc.txt
  lib/edit/r_info.txt
  lib/file/mondeath.txt
  lib/file/mondeath_j.txt
  lib/file/monfear.txt
  lib/file/monfear_j.txt
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
Labels: enhancement

#1554 [Implement] #1167 新規モンスターの追加 Alpha38用
  lib/edit/misc.txt
  lib/edit/r_info.txt
  lib/file/monfear.txt
  lib/file/monfear_j.txt
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
Labels: enhancement

#1555 [Fix] #1537 ファルメル・ウォーモンガーの進化経験値が未設定なバグを200000経験値に設定することで解消
  lib/edit/r_info.txt
Labels: bug

#1556 [Release] 3.0.0Alpha38
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1560 ピカチャウ(ルルイエのすがた) の警戒度と進化経験値を取り違えていたので修正した
  lib/edit/r_info.txt
Labels: bug

#1549 [Feature] *_info 配列の要素のメンバに自身のindexを持たせる
  src/dungeon/dungeon.h
  src/grid/feature.h
  src/info-reader/artifact-reader.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/ego-reader.cpp
  src/info-reader/feature-reader.cpp
  src/info-reader/kind-reader.cpp
  src/info-reader/race-reader.cpp
  src/info-reader/vault-reader.cpp
  src/object-enchant/object-ego.h
  src/object/object-kind.h
  src/room/rooms-vault.h
  src/system/artifact-type-definition.h
  src/system/monster-race-definition.h
Labels: enhancement, refactor

#1561 [Fix] 鍛冶で遠隔武器や矢弾の命中/ダメージ修正を強化できない
  src/object-enchant/smith-info.cpp
Labels: bug

#1565 Release/3.0.0 alpha39
  doxygen/Hengband.doxyfile
  lib/edit/r_info.txt
  src/dungeon/dungeon.h
  src/grid/feature.h
  src/info-reader/artifact-reader.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/ego-reader.cpp
  src/info-reader/feature-reader.cpp
  src/info-reader/kind-reader.cpp
  src/info-reader/race-reader.cpp
  src/info-reader/vault-reader.cpp
  src/object-enchant/object-ego.h
  src/object-enchant/smith-info.cpp
  src/object/object-kind.h
  src/room/rooms-vault.h
  src/system/angband-version.h
  src/system/artifact-type-definition.h
  src/system/monster-race-definition.h
Labels: release

#1564 [Release] 3.0.0Alpha39
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1566 *_info 配列に対するループを range-based for に置き換える
  src/artifact/fixed-art-generator.cpp
  src/birth/game-play-initializer.cpp
  src/cmd-io/cmd-lore.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/visuals-reseter.cpp
  src/dungeon/dungeon.cpp
  src/flavor/object-flavor.cpp
  src/floor/floor-generator.cpp
  src/floor/wild.cpp
  src/io-dump/character-dump.cpp
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-uniques.cpp
  src/load/quest-loader.cpp
  src/main/angband-initializer.cpp
  src/main/game-data-initializer.cpp
  src/market/arena.cpp
  src/market/bounty.cpp
  src/market/building-craft-fix.cpp
  src/market/building-monster.cpp
  src/monster-floor/monster-remover.cpp
  src/object-enchant/object-ego.cpp
  src/object/object-kind-hook.cpp
  src/player/player-status.cpp
  src/room/rooms-city.cpp
  src/spell/spells-object.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/monster-info-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spoiler.cpp
  src/world/world-turn-processor.cpp
Labels: refactor

#1568 [Fix] Visual Studio の警告に対処
  src/info-reader/artifact-reader.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/ego-reader.cpp
  src/info-reader/feature-reader.cpp
  src/info-reader/kind-reader.cpp
  src/info-reader/race-reader.cpp
  src/info-reader/vault-reader.cpp
  src/knowledge/knowledge-items.cpp
  src/object-enchant/object-smith.h
  src/object-enchant/smith-info.h
  src/object-enchant/smith-types.h
  src/system/object-type-definition.h
Labels: refactor

#1570 [Refactor] C_MAKEによる一時的バッファをstd::vectorで置き換える
  src/action/activation-execution.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-io/cmd-lore.cpp
  src/dungeon/dungeon.cpp
  src/flavor/object-flavor.cpp
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-quests.cpp
  src/knowledge/knowledge-uniques.cpp
  src/load/floor-loader.cpp
  src/load/load.cpp
  src/locale/japanese.cpp
  src/main/game-data-initializer.cpp
  src/market/building-monster.cpp
  src/room/rooms-city.cpp
  src/room/rooms-maze-vault.cpp
  src/room/rooms-vault.cpp
  src/save/floor-writer.cpp
  src/term/z-form.cpp
  src/wizard/monster-info-spoiler.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor

#1582 Include <vector> in z-form.cpp so it compiles when precompiled headers…
  src/term/z-form.cpp
Labels: bug

#1583 [Fix] エッセンス抽出で割引率が消去される
  src/object-enchant/object-smith.cpp
Labels: bug

#1584 [Fix] 鍛冶で矢弾を強化する時エッセンス数が足りているのに不足していると判定される
  src/mind/mind-weaponsmith.cpp
  src/object-enchant/object-smith.cpp
  src/object-enchant/object-smith.h
Labels: bug

#1586 [Refactor] floor_typeの配列的に扱うメンバ、荒野、クエスト、ダンジョン探索深度に std::vector を使用する
  src/dungeon/dungeon.cpp
  src/dungeon/dungeon.h
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/floor/floor-generator.cpp
  src/floor/floor-object.cpp
  src/floor/wild.cpp
  src/floor/wild.h
  src/main/game-data-initializer.cpp
  src/monster/monster-status.cpp
  src/system/floor-type-definition.h
  src/window/display-sub-windows.cpp
Labels: refactor

#1585 [Refactor] player_type::inventory_list の型を shared_ptr<object_type[]> に変更
  src/birth/game-play-initializer.cpp
  src/load/inventory-loader.cpp
  src/system/player-type-definition.h
Labels: refactor

#1587 [Refactor] 街・店舗・店舗のアイテム情報を std::vector もしくは std::unique_ptr にする
  src/floor/floor-town.cpp
  src/floor/floor-town.h
  src/market/building-initializer.cpp
  src/store/store-util.h
Labels: refactor

#1589 [Refactor] マクロ関連の配列変数をstd::vectorにする
  src/cmd-io/cmd-macro.cpp
  src/cmd-io/macro-util.cpp
  src/cmd-io/macro-util.h
  src/io/input-key-acceptor.cpp
  src/io/interpret-pref-file.cpp
  src/main/game-data-initializer.cpp
  src/term/z-util.cpp
  src/term/z-util.h
  src/util/string-processor.cpp
  src/util/string-processor.h
Labels: refactor

#1588 [Refactor] ファイル読み書き用のバッファを std::vector にする
  src/io/read-pref-file.cpp
  src/main/angband-initializer.cpp
  src/util/angband-files.cpp
  src/util/angband-files.h
Labels: refactor

#1590 [Refactor] quark関連のコード
  src/util/quarks.cpp
  src/util/quarks.h
Labels: refactor

#1592 [Refactor] 自動拾い関連の配列変数を std::vector にする
  src/autopick/autopick-describer.cpp
  src/autopick/autopick-drawer.cpp
  src/autopick/autopick-editor-util.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-finder.cpp
  src/autopick/autopick-initializer.cpp
  src/autopick/autopick-matcher.cpp
  src/autopick/autopick-pref-processor.cpp
  src/autopick/autopick-reader-writer.cpp
  src/autopick/autopick-reader-writer.h
  src/autopick/autopick-registry.cpp
  src/autopick/autopick-util.cpp
  src/autopick/autopick-util.h
  src/cmd-io/cmd-autopick.cpp
  src/cmd-visual/cmd-map.cpp
  src/knowledge/knowledge-autopick.cpp
Labels: refactor

#1593 [Refactor] to_wchar と to_multibyte の内部バッファを std::vector にする
  src/main-win/main-win-utils.h
Labels: refactor

#1595 [Fix] Windows版でマウスドラッグ時にメモリリーク
  src/main-win.cpp
Labels: bug

#1596 [Fix] string_make で確保した領域に C_KILL している
  src/autopick/autopick-drawer.cpp
Labels: bug

#1597 [Refactor] X11版のメモリ領域確保の方法を変更
  src/maid-x11.cpp
  src/main-x11.cpp
Labels: refactor

#1601 [Delete] メモリ確保/解放関連のマクロを削除
  src/term/z-virt.h
Labels: refactor

#1603 [Fix] 維持のない能力値アップが明るい緑でなく深い緑で表示される
  src/view/display-player-stat-info.cpp
Labels: bug

#1605 quark_add() においてコンパイル警告が出るのを修正した
  src/util/quarks.cpp
Labels: refactor

#1606 [Refactor] デバッグコマンドのメニューテーブルの型
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-player-modifier.cpp
Labels: refactor

#1608 [Feature] 鍛冶：階のユニークモンスターを表示する発動
  src/object-enchant/smith-tables.cpp
  src/object-enchant/smith-types.h
Labels: enhancement

#1612 [Implement] 階段の昇降時効果音を追加
  lib/xtra/sound/sound.cfg
  src/cmd-action/cmd-move.cpp
  src/main/sound-definitions-table.cpp
  src/main/sound-definitions-table.h
Labels: enhancement

#1604 WIPE/C_WIPE/COPY マクロを削除する
  src/autopick/autopick-destroyer.cpp
  src/birth/game-play-initializer.cpp
  src/birth/quick-start.cpp
  src/blue-magic/learnt-power-getter.cpp
  src/core/scores.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-leaver.cpp
  src/knowledge/knowledge-features.cpp
  src/load/load.cpp
  src/main-win.cpp
  src/main-x11.cpp
  src/monster-floor/monster-remover.cpp
  src/monster/monster-compaction.cpp
  src/monster/monster-damage.cpp
  src/room/rooms-city.cpp
  src/system/object-type-definition.cpp
  src/term/z-virt.h
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#1620 [Fix] 誤ってterm_dataへのポインタを初期化している
  src/main-win.cpp
Labels: bug

#1619 [Refactor] max_*_idx を廃止する
  lib/edit/misc.txt
  src/cmd-visual/cmd-visuals.cpp
  src/floor/fixed-map-generator.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/artifact-reader.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/ego-reader.cpp
  src/info-reader/feature-reader.cpp
  src/info-reader/kind-reader.cpp
  src/info-reader/race-reader.cpp
  src/info-reader/vault-reader.cpp
  src/io/interpret-pref-file.cpp
  src/load/item-loader.cpp
  src/load/lore-loader.cpp
  src/load/world-loader.cpp
  src/main-win/main-win-music.cpp
  src/main/game-data-initializer.cpp
  src/main/info-initializer.cpp
  src/monster-floor/monster-summon.cpp
  src/monster-race/monster-race.cpp
  src/monster-race/monster-race.h
  src/monster/monster-describer.cpp
  src/monster/monster-status.cpp
  src/object-enchant/apply-magic-others.cpp
  src/object-enchant/object-ego.cpp
  src/object-enchant/object-ego.h
  src/object/object-kind.cpp
  src/object/object-kind.h
  src/room/rooms-vault.cpp
  src/room/rooms-vault.h
  src/save/player-writer.cpp
  src/save/save.cpp
  src/spell/spells-object.cpp
  src/store/rumor.cpp
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/view/display-map.cpp
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/world/world.h
Labels: refactor

#1609 PlayerCutクラスを作成して切り傷処理を移管した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-action/cmd-move.cpp
  src/cmd-building/cmd-inn.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/core/player-processor.cpp
  src/effect/effect-player-curse.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/floor/pattern-walk.cpp
  src/grid/trap.cpp
  src/hpmp/hp-mp-processor.cpp
  src/load/player-info-loader.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-samurai.cpp
  src/monster-attack/monster-attack-player.cpp
  src/object-use/quaff-execution.cpp
  src/player-attack/player-attack.cpp
  src/player-base/player-class.cpp
  src/player-base/player-class.h
  src/player-base/player-race.cpp
  src/player-base/player-race.h
  src/player-info/self-info.cpp
  src/realm/realm-hissatsu.cpp
  src/save/player-writer.cpp
  src/specific-object/chest.cpp
  src/spell/spells-status.cpp
  src/status/bad-status-setter.cpp
  src/status/bad-status-setter.h
  src/status/buff-setter.cpp
  src/status/shape-changer.cpp
  src/system/player-type-definition.h
  src/timed-effect/player-cut.cpp
  src/timed-effect/player-cut.h
  src/timed-effect/timed-effects.cpp
  src/timed-effect/timed-effects.h
  src/window/main-window-stat-poster.cpp
Labels: refactor

#1615 [Fix] ウィザードモードのID指定モンスター生成(N/n)が回数指定の事前入力のみを想定した仕様で手動指定が足りなかった
  src/core/asking-player.cpp
  src/core/asking-player.h
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spells.cpp
Labels: bug, enhancement

#1617 [Feature] 職業固有のデータを持てるようにするシステムの導入
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/birth-wizard.cpp
  src/birth/quick-start.cpp
  src/load/player-class-specific-data-loader.cpp
  src/load/player-class-specific-data-loader.h
  src/load/player-info-loader.cpp
  src/mind/mind-force-trainer.cpp
  src/object-enchant/object-smith.cpp
  src/object-enchant/object-smith.h
  src/object-enchant/smith-info.h
  src/object-enchant/smith-tables.h
  src/object-enchant/smith-types.h
  src/player-base/player-class.cpp
  src/player-base/player-class.h
  src/player-info/bluemage-data-type.h
  src/player-info/class-specific-data.h
  src/player-info/force-trainer-data-type.h
  src/player-info/smith-data-type.h
  src/player-info/spell-hex-data-type.h
  src/realm/realm-hex-numbers.h
  src/realm/realm-hex.cpp
  src/save/player-class-specific-data-writer.cpp
  src/save/player-class-specific-data-writer.h
  src/save/player-writer.cpp
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-hex.h
  src/system/angband-version.h
  src/system/player-type-definition.h
  src/wizard/wizard-spells.cpp
Labels: enhancement, refactor

#1625 BadStatusSetterクラスに mod_hoge() メソッドを定義した
  src/action/open-close-execution.cpp
  src/cmd-action/cmd-mind.cpp
  src/cmd-action/cmd-shoot.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-item/cmd-eat.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-psi.cpp
  src/effect/effect-player-curse.cpp
  src/effect/effect-player-oldies.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/effect/effect-player-spirit.cpp
  src/grid/trap.cpp
  src/hpmp/hp-mp-processor.cpp
  src/inventory/inventory-curse.cpp
  src/mind/mind-blue-mage.cpp
  src/mind/mind-elementalist.cpp
  src/monster-attack/monster-attack-lose.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-attack/monster-attack-status.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/mspell/mspell-status.cpp
  src/mutation/mutation-processor.cpp
  src/object-use/quaff-execution.cpp
  src/object-use/read-execution.cpp
  src/player/digestion-processor.cpp
  src/player/eldritch-horror.cpp
  src/specific-object/chest.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-random.cpp
  src/spell/spells-object.cpp
  src/spell/spells-status.cpp
  src/spell/spells-summon.cpp
  src/status/bad-status-setter.cpp
  src/status/bad-status-setter.h
  src/status/shape-changer.cpp
Labels: refactor

#1623 デバッグ時のアイテム選択を日本語化した
  lib/edit/k_info.txt
  src/wizard/tval-descriptions-table.cpp
  src/wizard/tval-descriptions-table.h
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-special-process.h
Labels: bug, refactor

#1622 game-data-initializer.cpph/h に定義されているメソッドの無意味な返り値をvoidに変更した
  src/main/angband-initializer.cpp
  src/main/game-data-initializer.cpp
  src/main/game-data-initializer.h
Labels: refactor

#1626 calc_monster_critical() を廃止してPlayerCut/PlayerStun::get_accumulation()/get_accumulation_rank() に個別定義した
  src/combat/attack-criticality.cpp
  src/combat/attack-criticality.h
  src/monster-attack/monster-attack-player.cpp
  src/timed-effect/player-cut.cpp
  src/timed-effect/player-cut.h
  src/timed-effect/player-stun.cpp
  src/timed-effect/player-stun.h
Labels: refactor

#1628 [Refactor] 青魔道士の固有データを magic_num から分離
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/blue-magic/blue-magic-checker.cpp
  src/blue-magic/blue-magic-checker.h
  src/blue-magic/learnt-power-getter.cpp
  src/io-dump/special-class-dump.cpp
  src/load/player-class-specific-data-loader.cpp
  src/load/player-class-specific-data-loader.h
  src/mind/mind-blue-mage.h
  src/mspell/assign-monster-spell.cpp
  src/player-base/player-class.cpp
  src/player-info/class-specific-data.h
  src/save/player-class-specific-data-writer.cpp
  src/save/player-class-specific-data-writer.h
  src/wizard/wizard-spells.cpp
Labels: refactor

#1630 [Refactor] 青魔法のタイプを enum から enum class にする
  src/blue-magic/blue-magic-checker.cpp
  src/blue-magic/blue-magic-checker.h
  src/blue-magic/learnt-power-getter.cpp
  src/io-dump/special-class-dump.cpp
  src/mind/mind-blue-mage.h
Labels: refactor

#1634 [Refactor] 魔道具術師の固有データを magic_num から分離する
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-building/cmd-inn.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/cmd-item/cmd-magiceat.h
  src/hpmp/hp-mp-regenerator.cpp
  src/io-dump/special-class-dump.cpp
  src/load/player-class-specific-data-loader.cpp
  src/load/player-class-specific-data-loader.h
  src/mind/mind-magic-eater.cpp
  src/player-base/player-class.cpp
  src/player-info/bluemage-data-type.h
  src/player-info/class-specific-data.h
  src/player-info/force-trainer-data-type.h
  src/player-info/magic-eater-data-type.cpp
  src/player-info/magic-eater-data-type.h
  src/player-info/smith-data-type.h
  src/player-info/spell-hex-data-type.h
  src/save/player-class-specific-data-writer.cpp
  src/save/player-class-specific-data-writer.h
  src/spell/spells-status.cpp
  src/sv-definition/sv-rod-types.h
  src/sv-definition/sv-staff-types.h
  src/sv-definition/sv-wand-types.h
Labels: refactor

#1638 [Fix] 呪術の処理から吟遊詩人の処理を呼んでいる
  src/realm/realm-hex.cpp
Labels: bug

#1637 [Fix] 呪術ハイメイジで詠唱一時中断後に詠唱を再開しなくなっている
  src/mspell/mspell-dispel.cpp
  src/player-info/spell-hex-data-type.h
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-hex.h
Labels: bug

#1639 [Refactor] 吟遊詩人の固有データを magic_num から分離する
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/load/player-class-specific-data-loader.cpp
  src/load/player-class-specific-data-loader.h
  src/player-base/player-class.cpp
  src/player-info/bard-data-type.h
  src/player-info/class-specific-data.h
  src/realm/realm-song-numbers.h
  src/save/player-class-specific-data-writer.cpp
  src/save/player-class-specific-data-writer.h
  src/spell-realm/spells-song.cpp
  src/spell-realm/spells-song.h
Labels: refactor

#1640 [Refactor] 不要になった magic_num1/2 を player_type から削除
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/game-play-initializer.cpp
  src/load/load-v1-3-0.cpp
  src/load/load-v1-3-0.h
  src/load/load-zangband.cpp
  src/load/load-zangband.h
  src/load/player-class-specific-data-loader.cpp
  src/load/player-class-specific-data-loader.h
  src/load/player-info-loader.cpp
  src/mind/mind-mirror-master.cpp
  src/object-enchant/smith-types.h
  src/player-attack/player-attack.cpp
  src/realm/realm-hex.cpp
  src/save/player-writer.cpp
  src/spell-realm/spells-hex.h
  src/system/player-type-definition.h
  src/system/system-variables.h
Labels: refactor

#1641 [Refactor/Fix] 職業専用データのメンバに初期化子をつける
  src/player-info/bard-data-type.h
  src/player-info/bluemage-data-type.h
  src/player-info/force-trainer-data-type.h
  src/player-info/magic-eater-data-type.h
  src/player-info/smith-data-type.h
  src/player-info/spell-hex-data-type.h
Labels: bug, refactor

#1645 [Refactor] ものまね師の専用データを職業固有データに移動する
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/game-play-initializer.cpp
  src/blue-magic/blue-magic-checker.cpp
  src/cmd-action/cmd-mane.cpp
  src/core/player-processor.cpp
  src/load/player-class-specific-data-loader.cpp
  src/load/player-class-specific-data-loader.h
  src/load/player-info-loader.cpp
  src/melee/melee-spell.cpp
  src/mspell/mspell-attack.cpp
  src/player-base/player-class.cpp
  src/player-info/bluemage-data-type.h
  src/player-info/class-specific-data.h
  src/player-info/mane-data-type.h
  src/save/player-class-specific-data-writer.cpp
  src/save/player-class-specific-data-writer.h
  src/save/player-writer.cpp
  src/status/action-setter.cpp
  src/status/bad-status-setter.cpp
  src/system/player-type-definition.h
  src/window/main-window-stat-poster.cpp
Labels: refactor

#1627 perilous_secrets() をspells-object.cpp/h からspecific-object/stone-of-lore.cpp/h へ移動させた
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/object-activation/activation-switcher.cpp
  src/specific-object/stone-of-lore.cpp
  src/specific-object/stone-of-lore.h
  src/spell/spells-object.cpp
  src/spell/spells-object.h
Labels: refactor

#1534 ウィザードモードを廃止してデバッグモードに統一した
  lib/help/joption.txt
  lib/help/jversion.txt
  lib/help/option.txt
  lib/help/version.txt
  lib/pref/pref-opt.prf
  src/artifact/random-art-generator.cpp
  src/birth/game-play-initializer.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/core/game-play.cpp
  src/floor/floor-object.cpp
  src/floor/pattern-walk.cpp
  src/game-option/game-play-options.cpp
  src/game-option/game-play-options.h
  src/game-option/option-types-table.cpp
  src/io/input-key-processor.cpp
  src/io/input-key-processor.h
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/option-loader.cpp
  src/mind/monk-attack.cpp
  src/monster-floor/monster-death.cpp
  src/monster/monster-damage.cpp
  src/realm/realm-hex.cpp
  src/save/info-writer.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-kind/spells-world.cpp
  src/spell/spell-info.cpp
  src/target/target-describer.cpp
  src/view/display-lore.cpp
  src/window/main-window-left-frame.cpp
  src/window/main-window-stat-poster.cpp
  src/wizard/wizard-item-modifier.cpp
  src/world/world.h
Labels: refactor

#1652 [Add] プリコンパイルヘッダをいくつか追加
  src/stdafx.h
Labels: enhancement

#1656 体重をフレーバーの表示以外に使わなくした
  lib/help/birth.txt
  lib/help/jbirth.txt
  src/player-status/player-speed.cpp
Labels: enhancement, refactor

#1650 [Refactor] スナイパーの専用データを職業固有データに移動する
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-action/cmd-shoot.cpp
  src/combat/shoot.cpp
  src/core/player-processor.cpp
  src/flavor/flavor-describer.cpp
  src/io/input-key-processor.cpp
  src/load/player-class-specific-data-loader.cpp
  src/load/player-class-specific-data-loader.h
  src/load/player-info-loader.cpp
  src/mind/mind-sniper.cpp
  src/monster/monster-update.cpp
  src/player-base/player-class.cpp
  src/player-info/class-specific-data.h
  src/player-info/sniper-data-type.h
  src/player/player-status.cpp
  src/save/player-class-specific-data-writer.cpp
  src/save/player-class-specific-data-writer.h
  src/save/player-writer.cpp
  src/status/bad-status-setter.cpp
  src/system/player-type-definition.h
  src/window/main-window-stat-poster.cpp
Labels: refactor

#1657 seikaku をpersonality に改名した (スコアサーバのパラメータを除く)
  src/artifact/fixed-art-generator.cpp
  src/birth/birth-body-spec.cpp
  src/birth/birth-select-personality.cpp
  src/birth/birth-stat.cpp
  src/birth/birth-wizard.cpp
  src/birth/character-builder.cpp
  src/birth/inventory-initializer.cpp
  src/birth/quick-start.cpp
  src/birth/quick-start.h
  src/cmd-building/cmd-building.cpp
  src/cmd-item/cmd-equipment.cpp
  src/combat/attack-accuracy.cpp
  src/combat/shoot.cpp
  src/core/game-play.cpp
  src/core/scores.cpp
  src/floor/floor-changer.cpp
  src/grid/trap.cpp
  src/inventory/player-inventory.cpp
  src/io/files-util.cpp
  src/io/report.cpp
  src/knowledge/knowledge-self.cpp
  src/load/birth-loader.cpp
  src/load/load.cpp
  src/load/player-info-loader.cpp
  src/monster-floor/special-death-switcher.cpp
  src/mutation/gain-mutation-switcher.cpp
  src/mutation/lose-mutation-switcher.cpp
  src/mutation/mutation-calculator.cpp
  src/object-enchant/apply-magic.cpp
  src/player-status/player-basic-statistics.cpp
  src/player-status/player-speed.cpp
  src/player-status/player-stealth.cpp
  src/player/permanent-resistances.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/racial/racial-android.cpp
  src/save/info-writer.cpp
  src/save/player-writer.cpp
  src/system/player-type-definition.h
Labels: refactor

#1649 [Refactor] 馬鹿馬鹿よりカオスパトロンのクラス化移行を移植．
  src/birth/character-builder.cpp
  src/monster-floor/monster-death.cpp
  src/player-ability/player-ability-types.h
  src/player/patron.cpp
  src/player/patron.h
  src/player/player-status.cpp
  src/view/display-player.cpp
  src/wizard/cmd-wizard.cpp
Labels: refactor

#1659 [Add]　追加されたBGM/効果音プリセットの提供元のまとめ。
  lib/xtra/readme.md
  lib/xtra/sound/readme.txt
Labels: documentation, enhancement

#1663 Remove readme.txt from output of "make dist" in lib/xtra/sound
  lib/xtra/sound/Makefile.am
Labels: bug, documentation

#1665 Adjust the Makefile.am files so xtra/readme.md and all the sound and …
  lib/xtra/Makefile.am
  lib/xtra/music/Makefile.am
  lib/xtra/sound/Makefile.am
Labels: bug

#1669 [Fix] 魔法をキャンセルしたのにMPが消費される
  src/cmd-action/cmd-spell.cpp
Labels: bug

#1660 SourceTrailの解析 (clangベース)でエラーが出た箇所を修正した
  src/knowledge/knowledge-experiences.cpp
  src/view/display-util.cpp
Labels: refactor

#1672 [Feature] FlagGroup::first() を実装
  src/util/flag-group.h
Labels: enhancement

#1668 [Feature] モンスター・ボールを武器と交換できるようにする
  src/cmd-item/cmd-equipment.cpp
Labels: enhancement

#1629 chest.cpp/h のクラス化 w/ ChestTrapTypeの定義
  src/action/open-close-execution.cpp
  src/action/open-util.cpp
  src/cmd-action/cmd-open-close.cpp
  src/flavor/flavor-describer.cpp
  src/grid/trap.cpp
  src/grid/trap.h
  src/player/player-move.cpp
  src/specific-object/chest.cpp
  src/specific-object/chest.h
Labels: refactor

#1673 [Style] clang-format の整形ルールの調整
  .clang-format
Labels: refactor

#1674 職業由来の特性フラグの処理のリファクタリング
  src/player-base/player-class.cpp
  src/player-base/player-class.h
  src/player/permanent-resistances.cpp
  src/player/player-status-flags.cpp
Labels: refactor

#1676 痛恨の一撃を食らった時に朦朧値が正しく蓄積しない不具合を修正した
  src/monster-attack/monster-attack-switcher.cpp
Labels: refactor

#1678 [Feature] 究極の耐性と無双の型に新規耐性を追加
  src/player/player-status-flags.cpp
Labels: enhancement

#1648 アイテムの使用に関する exe_hoge() 関数をhoge-execution.cpp/h に移しクラス化した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-action/cmd-mind.cpp
  src/cmd-item/cmd-item.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/cmd-item/cmd-quaff.cpp
  src/cmd-item/cmd-read.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/cmd-item/cmd-usestaff.h
  src/cmd-item/cmd-zaprod.cpp
  src/cmd-item/cmd-zaprod.h
  src/cmd-item/cmd-zapwand.cpp
  src/cmd-item/cmd-zapwand.h
  src/mind/mind-blue-mage.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-power-getter.cpp
  src/object-use/item-use-checker.cpp
  src/object-use/item-use-checker.h
  src/object-use/quaff-execution.cpp
  src/object-use/quaff-execution.h
  src/object-use/read-execution.cpp
  src/object-use/read-execution.h
  src/object-use/use-execution.cpp
  src/object-use/use-execution.h
  src/object-use/zaprod-execution.cpp
  src/object-use/zaprod-execution.h
  src/object-use/zapwand-execution.cpp
  src/object-use/zapwand-execution.h
  src/spell/spell-info.cpp
  src/timed-effect/player-stun.cpp
  src/timed-effect/player-stun.h
  src/window/display-sub-window-spells.cpp
Labels: refactor

#1684 [Fix] デバッグコマンド実行時に職業固有データを更新する
  src/wizard/wizard-special-process.cpp
Labels: refactor

#1687 Windows(Visual Studio)用の必要ヘッダファイルの調整
  src/blue-magic/learnt-power-getter.cpp
  src/io-dump/special-class-dump.cpp
  src/main-win/main-win-cfg-reader.h
  src/main-win/main-win-sound.cpp
  src/main-win/main-win-utils.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mspell/mspell-attack.cpp
  src/spell-realm/spells-hex.cpp
  src/system/h-system.h
  src/wizard/wizard-spoiler.cpp
Labels: enhancement

#1682 新しい朦朧の仕様を実装した
  src/core/player-processor.cpp
  src/monster-attack/monster-attack-player.cpp
  src/status/bad-status-setter.cpp
  src/status/bad-status-setter.h
  src/timed-effect/player-stun.cpp
  src/timed-effect/player-stun.h
Labels: enhancement

#1667 [Refactor] 青魔法の選択処理
  src/blue-magic/learnt-power-getter.cpp
Labels: refactor
