Repository hengband/hengband, pull requests merged in 2021-07, with the labels that each got.

#1237 [Refactor] ステータス修正以外のチャージマン判定を is_chargeman() に集約.
  src/dungeon/quest.cpp
  src/grid/trap.cpp
  src/inventory/inventory-damage.cpp
  src/monster-floor/one-monster-placer.cpp
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-floor.cpp
  src/player/player-status.cpp
  src/player/player-status.h
  src/status/bad-status-setter.cpp
Labels: enhancement

#1242 [Fix] 値切りシステム廃止後の売買のメッセージ統一を推進．
  src/store/purchase-order.cpp
  src/store/sell-order.cpp
Labels: bug

#1247 [Feature] 危ない水着の生成率をアップ(A:30/20:50/8で天上のクロークよりまだ見かけない程度)
  lib/edit/k_info.txt
Labels: enhancement

#1249 Release/3.0.0 alpha30
  doxygen/Hengband.doxyfile
  lib/edit/k_info.txt
  src/dungeon/quest.cpp
  src/grid/trap.cpp
  src/inventory/inventory-damage.cpp
  src/main-win/main-win-sound.cpp
  src/monster-floor/one-monster-placer.cpp
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-floor.cpp
  src/player/player-status.cpp
  src/player/player-status.h
  src/status/bad-status-setter.cpp
  src/store/purchase-order.cpp
  src/store/sell-order.cpp
  src/system/angband-version.h
Labels: release

#1248 [Release] 3.0.0Alpha30
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1250 [Fix] 種族アンドロイドで店舗でのアイテム強化した時の処理
  src/market/building-enchanter.cpp
  src/spell/spells-object.cpp
Labels: bug

#1244 [Fix] ウィザードモードのクエスト突入機能が正しく動作するよう修正＆リファクタリング．
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/floor/fixed-map-generator.cpp
  src/system/system-variables.cpp
  src/wizard/wizard-game-modifier.cpp
Labels: enhancement

#1253 [Fix] is_echizen()がTRUE(セリフがアレの状態)の時、地上に戻る際の帰還残り時間がリセットされない不具合を修正.
  src/cmd-action/cmd-move.cpp
Labels: enhancement

#1254 [Fix] r_info.txt の英語名がロードされていない
  src/info-reader/race-reader.cpp
Labels: bug

#1256 [Fix] ペットに巻き込むなって言ってるのに巻き込む #1255
  src/melee/melee-spell-flags-checker.cpp
Labels: bug

#1258 店舗の価格交渉削除後に残っている問題の修正
  src/object-enchant/special-object-flags.h
  src/store/pricing.cpp
  src/store/purchase-order.cpp
  src/store/sell-order.cpp
  src/store/store.cpp
  src/view/display-store.cpp
Labels: bug

#1260 [Release] 3.0.0Alpha31
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: enhancement

#1261 Feature/release 3.0.0 alpha31
  doxygen/Hengband.doxyfile
  src/cmd-action/cmd-move.cpp
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/floor/fixed-map-generator.cpp
  src/info-reader/race-reader.cpp
  src/market/building-enchanter.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/object-enchant/special-object-flags.h
  src/spell/spells-object.cpp
  src/store/pricing.cpp
  src/store/purchase-order.cpp
  src/store/sell-order.cpp
  src/store/store.cpp
  src/system/angband-version.h
  src/system/system-variables.cpp
  src/view/display-store.cpp
  src/wizard/wizard-game-modifier.cpp
Labels: enhancement

#1269 [Fix] 静水のMP回復量表示の誤り #1266
  src/racial/class-racial-switcher.cpp
Labels: bug

#1271 [Add] 魔法を防ぐクローク、ミスリル及びアダマン製の防具をRARE対象に。
  src/object-hook/hook-enchant.cpp
  src/sv-definition/sv-protector-types.h
Labels: enhancement

#1272 Feature/fix speed dump display
  src/player-status/player-speed.cpp
  src/view/display-player-middle.cpp
Labels: enhancement

#1246 Feature/refactor floor warp fix
  src/floor/floor-leaver.cpp
  src/floor/floor-leaver.h
  src/wizard/wizard-special-process.cpp
Labels: enhancement, refactor

#1280 Release/3.0.0 alpha32
  configure.ac
  doxygen/Hengband.doxyfile
  lib/edit/a_info.txt
  lib/edit/r_info.txt
  src/floor/floor-leaver.cpp
  src/floor/floor-leaver.h
  src/object-hook/hook-enchant.cpp
  src/player-status/player-speed.cpp
  src/racial/class-racial-switcher.cpp
  src/sv-definition/sv-protector-types.h
  src/system/angband-version.h
  src/view/display-player-middle.cpp
  src/wizard/wizard-special-process.cpp
Labels: enhancement

#1279 [Add] 3.0.0Alpha32
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: enhancement

#1285 [Fix] 床上のアイテムのエッセンスを抽出するとスタック順が変わる
  src/system/object-type-definition.cpp
Labels: bug

#1268 敵対モンスターの友好モンスター召喚時のバグについて
  src/monster-floor/one-monster-placer.cpp
Labels: bug
