Repository hengband/hengband, pull requests merged in 2022-07, with the labels that each got.

#2556 [Delete] 効果音をhengband.xtra管轄で管理するため削除。
  lib/xtra/sound/apple1-r.wav
  lib/xtra/sound/decision25r.wav
  lib/xtra/sound/drop1.wav
  lib/xtra/sound/enemy-advent1-r.wav
  lib/xtra/sound/readme.txt
  lib/xtra/sound/se_maoudamashii_battle07.wav
  lib/xtra/sound/se_maoudamashii_retro22.wav
  lib/xtra/sound/se_maoudamashii_se_drink01.wav
  lib/xtra/sound/se_maoudamashii_voice_monster01.wav
  lib/xtra/sound/sea-lion2-r.wav
  lib/xtra/sound/sound.cfg
  lib/xtra/sound/sword-clash1-r.wav
  lib/xtra/sound/sword-gesture3-r.wav
  lib/xtra/sound/sword-slash3-r.wav
Labels: enhancement

#2559 Release/3.0.0 alpha63
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  doxygen/Hengband.doxyfile
  lib/xtra/sound/apple1-r.wav
  lib/xtra/sound/decision25r.wav
  lib/xtra/sound/drop1.wav
  lib/xtra/sound/enemy-advent1-r.wav
  lib/xtra/sound/readme.txt
  lib/xtra/sound/se_maoudamashii_battle07.wav
  lib/xtra/sound/se_maoudamashii_retro22.wav
  lib/xtra/sound/se_maoudamashii_se_drink01.wav
  lib/xtra/sound/se_maoudamashii_voice_monster01.wav
  lib/xtra/sound/sea-lion2-r.wav
  lib/xtra/sound/sound.cfg
  lib/xtra/sound/sword-clash1-r.wav
  lib/xtra/sound/sword-gesture3-r.wav
  lib/xtra/sound/sword-slash3-r.wav
  src/Makefile.am
  src/blue-magic/blue-magic-caster.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/cmd-item/cmd-zaprod.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/effect/effect-player-oldies.cpp
  src/load/player-info-loader.cpp
  src/locale/english.cpp
  src/main-gcu.cpp
  src/mind/mind-mindcrafter.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/mspell/mspell-dispel.cpp
  src/mutation/mutation-processor.cpp
  src/object-activation/activation-switcher.cpp
  src/object-use/quaff/quaff-effects.cpp
  src/player/player-status.cpp
  src/realm/realm-craft.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-death.cpp
  src/realm/realm-life.cpp
  src/realm/realm-song.cpp
  src/realm/realm-sorcery.cpp
  src/save/player-writer.cpp
  src/spell/spells-status.cpp
  src/status/buff-setter.cpp
  src/status/buff-setter.h
  src/system/angband-version.h
  src/system/player-type-definition.h
  src/timed-effect/player-acceleration.cpp
  src/timed-effect/player-acceleration.h
  src/timed-effect/timed-effects.cpp
  src/timed-effect/timed-effects.h
Labels: release

#2560 [Release] 3.0.0Alpha63
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#2562 Fix lib/xtra/sound/Makefile.am so "make distcheck" works after recent…
  lib/xtra/sound/Makefile.am
Labels: bug

#2564 [Fix] 英語版でキャラクタダンプ出力時にクラッシュする
  src/io-dump/character-dump.cpp
Labels: bug

#2566 モンスターの出現数フラグをFlagGroup化
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/game-play-initializer.cpp
  src/dungeon/dungeon.h
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-oldies.cpp
  src/effect/effect-monster.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-leaver.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/market/bounty.cpp
  src/melee/melee-postprocess.cpp
  src/monster-floor/monster-runaway.cpp
  src/monster-floor/monster-summon.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/race-population-flags.h
  src/monster/monster-damage.cpp
  src/monster/monster-list.cpp
  src/monster/monster-processor.cpp
  src/monster/monster-util.cpp
  src/spell/spells-diceroll.cpp
  src/system/monster-race-definition.h
  src/view/display-lore.cpp
  src/wizard/monster-info-spoiler.cpp
  src/wizard/wizard-game-modifier.cpp
Labels: refactor, Priority:MIDDLE

#2568 SPEAK系フラグを新設
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  lib/edit/r_info.txt
  src/Makefile.am
  src/dungeon/dungeon.h
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-runaway.cpp
  src/monster-race/race-speak-flags.h
  src/monster/monster-damage.cpp
  src/monster/monster-util.cpp
  src/system/monster-race-definition.h
Labels: refactor

#2565 Add mode, OD_BASE_NAME, for describe_flavor() which omits artifact, …
  src/action/activation-execution.cpp
  src/flavor/named-item-describer.cpp
  src/flavor/object-flavor-types.h
Labels: bug

#2570 VS2022環境でstd::array<T, N> 型の変数宣言でコンパイル警告が出ていたのを解消した
  src/mind/mind-blue-mage.h
  src/mind/mind-elementalist.cpp
  src/object-enchant/tr-types.h
  src/player/player-skill.cpp
  src/util/rng-xoshiro.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor

#2573 死亡時メッセージだけが定義されているモンスターについて、ハードコードではなくmondeath.txt からの定義文を参照するようにした
  lib/edit/r_info.txt
  lib/file/mondeath.txt
  lib/file/mondeath_j.txt
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-runaway.cpp
  src/monster-floor/special-death-switcher.cpp
  src/monster-race/race-indice-types.h
  src/monster/monster-damage.cpp
  src/target/projection-path-calculator.h
Labels: enhancement

#2572 wizard-spoiler.cpp の調整
  src/main-win.cpp
  src/main.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/monster-info-spoiler.cpp
  src/wizard/spoiler-util.h
  src/wizard/wizard-spoiler.cpp
  src/wizard/wizard-spoiler.h
Labels: refactor

#2574 [Release] 3.0.0Alpha64
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#2575 Release/3.0.0 alpha64
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  doxygen/Hengband.doxyfile
  lib/edit/r_info.txt
  lib/file/mondeath.txt
  lib/file/mondeath_j.txt
  lib/xtra/sound/Makefile.am
  src/Makefile.am
  src/action/activation-execution.cpp
  src/birth/game-play-initializer.cpp
  src/dungeon/dungeon.h
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-oldies.cpp
  src/effect/effect-monster.cpp
  src/flavor/named-item-describer.cpp
  src/flavor/object-flavor-types.h
  src/floor/fixed-map-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-leaver.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/io-dump/character-dump.cpp
  src/main-win.cpp
  src/main.cpp
  src/market/bounty.cpp
  src/melee/melee-postprocess.cpp
  src/mind/mind-blue-mage.h
  src/mind/mind-elementalist.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-runaway.cpp
  src/monster-floor/monster-summon.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-floor/special-death-switcher.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/race-indice-types.h
  src/monster-race/race-population-flags.h
  src/monster-race/race-speak-flags.h
  src/monster/monster-damage.cpp
  src/monster/monster-list.cpp
  src/monster/monster-processor.cpp
  src/monster/monster-util.cpp
  src/object-enchant/tr-types.h
  src/player/player-skill.cpp
  src/spell/spells-diceroll.cpp
  src/system/angband-version.h
  src/system/monster-race-definition.h
  src/target/projection-path-calculator.h
  src/util/rng-xoshiro.cpp
  src/view/display-lore.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/monster-info-spoiler.cpp
  src/wizard/spoiler-util.h
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-spoiler.cpp
  src/wizard/wizard-spoiler.h
Labels: release
