Repository hengband/hengband, pull requests merged in 2022-11, with the labels that each got.

#2755 噂を聞く時に欠番の固定アーティファクトIDを指定されるとクラッシュする不具合を修正した
  src/store/rumor.cpp
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
Labels: refactor, Priority:MIDDLE

#2764 [Fix] to_multibyte クラスの存在しないメソッド data() を呼んでいる
  src/main-win.cpp
  src/main-win/commandline-win.cpp
  src/main-win/main-win-utils.cpp
Labels: bug

#2762 gamevalue.h にあるべきでない定数群を適切な場所に移し、その他はconstexpr で再定義した
  src/action/mutation-execution.cpp
  src/artifact/random-art-characteristics.cpp
  src/artifact/random-art-generator.cpp
  src/artifact/random-art-resistance.cpp
  src/cmd-building/cmd-inn.cpp
  src/cmd-item/cmd-zaprod.cpp
  src/cmd-item/cmd-zapwand.cpp
  src/effect/effect-monster-util.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-object.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-town.h
  src/floor/wild.cpp
  src/floor/wild.h
  src/grid/feature-generator.cpp
  src/inventory/inventory-curse.cpp
  src/melee/melee-postprocess.cpp
  src/melee/melee-util.cpp
  src/melee/monster-attack-monster.cpp
  src/mind/mind-elementalist.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-lite.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-move.h
  src/monster-floor/monster-sweep-grid.cpp
  src/monster/monster-list.cpp
  src/monster/monster-processor.cpp
  src/monster/monster-status.cpp
  src/monster/monster-update.cpp
  src/mspell/mspell-floor.cpp
  src/mspell/mspell-util.cpp
  src/player-attack/player-attack.cpp
  src/player/player-damage.cpp
  src/player/player-skill.h
  src/player/player-view.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-hissatsu.cpp
  src/realm/realm-life.cpp
  src/room/rooms-city.cpp
  src/room/rooms-vault.cpp
  src/spell-kind/spells-genocide.cpp
  src/spell-kind/spells-sight.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-kind/spells-world.cpp
  src/spell-realm/spells-hex.cpp
  src/store/cmd-store.cpp
  src/store/rumor.cpp
  src/system/gamevalue.h
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/world/world-object.cpp
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#2770 [Fix] #2765 OSに渡すミューテックス文字列が正しく初期化されず毎回異なる値となってアプリの多重起動を許してしまう事象を修正した
  src/main-win/main-win-utils.cpp
Labels: bug, Priority:MIDDLE

#2757 ヘルプやニュース類の古すぎる情報を変更、削除
  lib/file/news.txt
  lib/file/news_j.txt
  lib/help/faq.txt
  lib/help/general.txt
  lib/help/jgeneral.txt
  readme.md
Labels: enhancement

#2771 ベースアイテムのtval/sval を一意に特定できるクラスを作った
  src/market/building-initializer.cpp
  src/object/object-kind-hook.cpp
  src/object/object-kind-hook.h
  src/store/articles-on-sale.cpp
  src/store/articles-on-sale.h
  src/system/baseitem-info-definition.cpp
  src/system/baseitem-info-definition.h
Labels: refactor, Priority:MIDDLE

#2772 [Feature] GCU版のウインドウ数を最大8個表示できるようにする
  src/main-gcu.cpp
Labels: enhancement

#2782 [Feature] BGMと効果音の音量設定機能
  src/ang_eng.rc
  src/ang_jp.rc
  src/game-option/runtime-arguments.cpp
  src/game-option/runtime-arguments.h
  src/main-win.cpp
  src/main-win/main-win-menuitem.h
  src/main-win/main-win-music.cpp
  src/main-win/main-win-music.h
  src/main-win/main-win-sound.cpp
  src/main-win/main-win-sound.h
Labels: enhancement

#2780 SV_ANY を廃止し、lookup_kind() をBaseitemKeyを受け取るように全て差し替え、svalがnulloptだった時の動作を最適化した
  src/artifact/fixed-art-generator.cpp
  src/artifact/random-art-generator.cpp
  src/birth/inventory-initializer.cpp
  src/cmd-item/cmd-eat.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/effect/effect-monster.cpp
  src/floor/fixed-map-generator.cpp
  src/info-reader/general-parser.cpp
  src/io-dump/special-class-dump.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/old/load-v1-5-0.cpp
  src/market/arena-info-table.cpp
  src/market/arena-info-table.h
  src/market/bounty-prize-table.cpp
  src/market/bounty-prize-table.h
  src/market/bounty.cpp
  src/market/building-craft-fix.cpp
  src/market/building-initializer.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-chaos-warrior.cpp
  src/mind/mind-hobbit.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object-enchant/protector/apply-magic-soft-armor.cpp
  src/object/object-kind-hook.cpp
  src/object/object-kind-hook.h
  src/realm/realm-nature.cpp
  src/spell/spells-object.cpp
  src/spell/spells-status.cpp
  src/store/articles-on-sale.cpp
  src/store/rumor.cpp
  src/sv-definition/sv-other-types.h
  src/system/baseitem-info-definition.cpp
  src/system/baseitem-info-definition.h
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#2791 exe_lookup() の引数をtval/sval からBaseitemKey に差し替えた
  src/object/object-kind-hook.cpp
Labels: refactor, Priority:MIDDLE

#2729 効果音設定の追加要望に対応
  src/action/tunnel-execution.cpp
  src/cmd-action/cmd-attack.cpp
  src/main/sound-definitions-table.cpp
  src/main/sound-definitions-table.h
  src/monster-attack/monster-attack-describer.cpp
  src/player-attack/player-attack.cpp
Labels: enhancement

#2787 [Feature] 魔法書の先頭にLv値を表示するようにした
  src/flavor/named-item-describer.cpp
  src/system/object-type-definition.cpp
  src/system/object-type-definition.h
Labels: enhancement, Priority:MIDDLE

#2792 規定で無効化されているコンパイル警告C5264 (定数不使用)を抑制した
  Hengband/Hengband/Hengband.vcxproj
Labels: refactor, Priority:MIDDLE

#2801 ArtifactType のtval/sval をBaseitemKey に差し替えた
  src/artifact/fixed-art-generator.cpp
  src/info-reader/artifact-reader.cpp
  src/info-reader/general-parser.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-quests.cpp
  src/object-hook/hook-quest.cpp
  src/spell/spells-object.cpp
  src/store/rumor.cpp
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/util/sort.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#2804 BaseitemInfo::tval/sval をBaseitemKey に差し替えた
  src/artifact/random-art-generator.cpp
  src/flavor/flavor-util.h
  src/flavor/object-flavor.cpp
  src/info-reader/baseitem-reader.cpp
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-items.cpp
  src/load/item/item-loader-base.cpp
  src/load/old/item-loader-savefile50.cpp
  src/market/building-craft-fix.cpp
  src/market/building-recharger.cpp
  src/mind/mind-mage.cpp
  src/monster-attack/monster-eating.cpp
  src/object-enchant/protector/apply-magic-armor.cpp
  src/object-enchant/protector/apply-magic-soft-armor.cpp
  src/object/object-broken.cpp
  src/object/object-kind-hook.cpp
  src/object/object-kind-hook.h
  src/spell-kind/magic-item-recharger.cpp
  src/spell/spells-object.cpp
  src/system/baseitem-info-definition.cpp
  src/system/baseitem-info-definition.h
  src/system/object-type-definition.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/world/world-object.cpp
Labels: refactor, Priority:MIDDLE

#2806 [Fix] 意図したフォールスルーに [[fallthrough]] 属性を使用する
  src/autopick/autopick-finder.cpp
  src/birth/birth-body-spec.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/core/asking-player.cpp
  src/flavor/flavor-util.cpp
  src/info-reader/general-parser.cpp
  src/inventory/floor-item-getter.cpp
  src/inventory/item-getter.cpp
  src/knowledge/knowledge-features.cpp
  src/main-win.cpp
  src/melee/melee-switcher.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/player-info/class-ability-info.cpp
  src/player/player-status.cpp
  src/racial/class-racial-switcher.cpp
  src/racial/racial-switcher.cpp
  src/room/rooms-builder.cpp
  src/spell-kind/blood-curse.cpp
  src/spell-kind/spells-random.cpp
  src/store/service-checker.cpp
  src/target/target-setter.cpp
  src/term/gameterm.cpp
Labels: bug, refactor

#2812 Fix lib/edit/Makefile.am for renamed file. Resolves …
  lib/edit/Makefile.am
Labels: bug

#2813 bow_tval_ammo() をBaseitemKeyに繰り込んだ
  Hengband/Hengband/Hengband.vcxproj
  src/Makefile.am
  src/flavor/flavor-describer.cpp
  src/player/player-status.cpp
  src/specific-object/bow.cpp
  src/specific-object/bow.h
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
Labels: refactor, Priority:MIDDLE

#2817 ItemEntity::tval/sval をBaseitemKey に差し替えるための準備をした
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-item/cmd-destroy.cpp
  src/flavor/named-item-describer.cpp
  src/knowledge/knowledge-items.cpp
  src/object-hook/hook-magic.cpp
  src/object-hook/hook-magic.h
  src/object/object-info.cpp
  src/object/object-info.h
  src/object/object-kind-hook.cpp
  src/player/player-status.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: refactor, Priority:MIDDLE

#2821 [Feature] FlagGroup を固定バイト長でセーブファイルに読み書きする関数
  src/action/run-execution.cpp
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick.cpp
  src/cmd-item/cmd-equipment.cpp
  src/combat/shoot.cpp
  src/effect/effect-item.cpp
  src/floor/floor-events.cpp
  src/floor/object-scanner.cpp
  src/grid/grid.cpp
  src/inventory/inventory-object.cpp
  src/inventory/item-getter.cpp
  src/inventory/player-inventory.cpp
  src/load/inventory-loader.cpp
  src/load/old/item-loader-savefile50.cpp
  src/load/old/load-v1-5-0.cpp
  src/mind/mind-mindcrafter.cpp
  src/monster-attack/monster-eating.cpp
  src/monster-floor/monster-object.cpp
  src/object/object-mark-types.h
  src/player-attack/attack-chaos-effect.cpp
  src/player/player-status.cpp
  src/save/item-writer.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-enchant.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-perception.cpp
  src/system/item-entity.h
  src/target/target-describer.cpp
  src/target/target-preparation.cpp
  src/util/flag-group.h
  src/view/display-map.cpp
  src/window/display-sub-windows.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: enhancement, refactor

#2827 ItemEntity::tval/sval をBaseitemKey に差し替えるための準備をした その2
  src/artifact/random-art-pval-investor.cpp
  src/cmd-item/cmd-eat.cpp
  src/object-enchant/weapon/abstract-weapon-enchanter.cpp
  src/object-hook/hook-weapon.cpp
  src/object-use/use-execution.cpp
  src/object-use/zapwand-execution.cpp
  src/object/tval-types.h
  src/perception/object-perception.cpp
  src/player/player-status.cpp
  src/smith/object-smith.cpp
  src/spell-kind/spells-detection.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/util/object-sort.cpp
  src/view/object-describer.cpp
  src/view/object-describer.h
Labels: refactor, Priority:MIDDLE

#2831 [Refactor] tag_sort() の削除
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/main/game-data-initializer.cpp
  src/system/alloc-entries.h
  src/util/tag-sorter.cpp
  src/util/tag-sorter.h
Labels: refactor

#2833 [Add] C++の言語標準バージョンをチェックする autoconf マクロ
  .github/workflows/build-with-autotools.yml
  .github/workflows/publish-spoiler-page.yml
  bootstrap
  configure.ac
  m4/ax_cxx_compile_stdcxx.m4
Labels: enhancement

#2829 ItemEntity::tval/sval をBaseitemKey に差し替えるための準備をした その3
  src/artifact/random-art-generator.cpp
  src/artifact/random-art-misc.cpp
  src/artifact/random-art-resistance.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-building/cmd-building.cpp
  src/cmd-item/cmd-eat.cpp
  src/combat/aura-counterattack.cpp
  src/flavor/flavor-describer.cpp
  src/floor/floor-object.cpp
  src/knowledge/knowledge-inventory.cpp
  src/market/building-recharger.cpp
  src/mind/mind-mage.cpp
  src/mind/mind-magic-eater.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-attack/monster-eating.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object-enchant/object-curse.cpp
  src/object-hook/hook-expendable.cpp
  src/object/object-stack.cpp
  src/object/tval-types.h
  src/player/player-damage.cpp
  src/player/player-status.cpp
  src/realm/realm-hex.cpp
  src/smith/smith-info.cpp
  src/spell-kind/magic-item-recharger.cpp
  src/spell-realm/spells-nature.cpp
  src/spell/spells-object.cpp
  src/store/purchase-order.cpp
  src/store/sell-order.cpp
  src/store/service-checker.cpp
  src/store/store-util.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/view/object-describer.cpp
Labels: refactor, Priority:MIDDLE

#2834 ItemEntity::tval/sval をBaseitemKey に差し替えるための準備をした その4
  src/combat/shoot.cpp
  src/combat/shoot.h
  src/flavor/flavor-describer.cpp
  src/object/tval-types.h
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/view/display-player-middle.cpp
  src/view/status-first-page.cpp
Labels: refactor, Priority:MIDDLE

#2837 ItemEntity::tval/sval をBaseitemKey に差し替えるための準備をした その5
  src/cmd-item/cmd-eat.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/object-use/zaprod-execution.cpp
  src/object/object-flags.cpp
  src/realm/realm-hex.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: refactor, Priority:MIDDLE

#2840 ItemEntity::tval/sval をBaseitemKey に差し替えるための準備 その6
  src/cmd-action/cmd-hissatsu.cpp
  src/cmd-action/cmd-shoot.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-item/cmd-item.cpp
  src/mind/mind-mage.cpp
  src/realm/realm-hex.cpp
  src/spell-realm/spells-craft.cpp
Labels: refactor, Priority:MIDDLE

#2843 parse_artifacts_info() からbuf へ直接依存している読み込みルーチンを排除した
  src/info-reader/artifact-reader.cpp
Labels: refactor, Priority:MIDDLE

#2853 サブディレクトリとデフォルトmp3の追加に合わせたWindows用ビルドスクリプトを修正。
  Build-Windows-Release-Package.ps1
Labels: bug

#2855 [Release] 3.0.0Alpha72
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#2857 [Fix] github.io の自動生成スポイラーページの更新に失敗する
  .github/workflows/publish-spoiler-page.yml
Labels: bug

#2864 矢弾のダメージが表記されない不具合を修正した
  src/flavor/flavor-describer.cpp
  src/system/baseitem-info.cpp
Labels: refactor, Priority:MIDDLE

#2863 [Fix] GCC 12 でビルドすると info-initializer.cpp でコンパイルエラーが発生する
  src/main/info-initializer.cpp
Labels: bug
