Repository hengband/hengband, pull requests merged in 2022-05, with the labels that each got.

#2505 [Fix] モンスターの復元数変数が初期化されていなかった不具合を修正。
  src/wizard/wizard-game-modifier.cpp
Labels: bug

#2514 libcurl4のインストールに失敗し、GitHub Actionsが正常に動作しない事象を修正した
  .github/workflows/build-with-autotools.yml
Labels: bug, Priority:HIGH

#2510 #2497 長柄/斧と鈍器に殺戮修正が付与されない事象を暫定的に修正した
  src/object-enchant/weapon/apply-magic-hafted.cpp
  src/object-enchant/weapon/apply-magic-polearm.cpp
Labels: bug, Priority:HIGH

#2511 [Fix] デバッグモードoコマンドの表示が崩れていたので行指定変数を正しく修正。
  src/wizard/wizard-item-modifier.cpp
Labels: bug

#2516 Release/3.0.0 alpha60
  .github/workflows/build-with-autotools.yml
  doxygen/Hengband.doxyfile
  src/birth/birth-wizard.cpp
  src/object-enchant/weapon/apply-magic-hafted.cpp
  src/object-enchant/weapon/apply-magic-polearm.cpp
  src/spell-realm/spells-chaos.cpp
  src/system/angband-version.h
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: release

#2515 [Release] 3.0.0Alpha60
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#2519 English: fix typo in message about the version of the savefile being…
  src/load/info-loader.cpp
Labels: bug

#2528 [Fix] クエスト、モンサルヴァト城への侵攻にて町への帰還後の位置が永久岩の壁になっていたので修正。
  lib/edit/t0000002.txt
Labels: bug
