Repository hengband/hengband, pull requests merged in 2022-01, with the labels that each got.

#1949 DOOMからのモンスターを3体追加+モンスターの性能調整
  lib/edit/r_info.txt
Labels: enhancement

#1950 追加したモンスターの番号ミスを修正
  lib/edit/r_info.txt
Labels: bug

#1955 [Fix] モンスターがモンスターを殴る際の地形条件の統一
  src/monster-attack/monster-attack-processor.cpp
Labels: bug

#1961 [Fix] デバッグモードのプレイヤー種族、職業、領域変更の範囲外選択をget_value()リファクタリングで抑止。
  src/wizard/wizard-special-process.cpp
Labels: bug

#1973 Release/3.0.0 alpha50
  doxygen/Hengband.doxyfile
  lib/edit/r_info.txt
  src/knowledge/knowledge-monsters.cpp
  src/monster-attack/monster-attack-processor.cpp
  src/mspell/mspell-special.cpp
  src/mspell/mspell-status.cpp
  src/mspell/mspell-summon.cpp
  src/system/angband-version.h
  src/wizard/wizard-special-process.cpp
Labels: release

#1972 [Release] 3.0.0Alpha50
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1969 [Implement] 店舗ごとにアイテムの生成レベルを指定できる仕様を追加。
  src/store/store-owners.cpp
  src/store/store-owners.h
  src/store/store-util.cpp
  src/store/store-util.h
Labels: enhancement

#1968 [Fix] #1965 長い名前のモンスターに殺されるとダンプが見切れる事象を解決した
  src/birth/birth-wizard.cpp
  src/birth/history-editor.cpp
  src/cmd-visual/cmd-draw.cpp
  src/core/game-closer.cpp
  src/core/game-play.cpp
  src/core/scores.cpp
  src/core/scores.h
  src/io-dump/character-dump.cpp
  src/io-dump/character-dump.h
  src/io-dump/player-status-dump.cpp
  src/io-dump/player-status-dump.h
  src/io/files-util.cpp
  src/io/files-util.h
  src/io/report.cpp
  src/io/report.h
  src/player/process-death.cpp
  src/player/process-death.h
  src/view/display-player.cpp
  src/view/display-player.h
  src/window/display-sub-windows.cpp
Labels: bug

#1976 Fix compilation error if WORLD_SCORE not set.
  src/core/scores.cpp
Labels: bug

#1979 カコデーモンとアラクノトロンの説明文を修正
  lib/edit/r_info.txt
Labels: documentation, translation

#1980 [Implement] モンスターの近接攻撃/射撃の属性を定義する
  lib/pref/spell-xx.prf
  src/blue-magic/blue-magic-caster.cpp
  src/cmd-action/cmd-attack.cpp
  src/cmd-action/cmd-mane.cpp
  src/combat/aura-counterattack.cpp
  src/effect/attribute-types.h
  src/effect/effect-feature.cpp
  src/effect/effect-item.cpp
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-monster.cpp
  src/effect/effect-player-switcher.cpp
  src/floor/object-allocator.cpp
  src/floor/object-allocator.h
  src/grid/trap.cpp
  src/io/gf-descriptions.cpp
  src/io/gf-descriptions.h
  src/melee/melee-spell-flags-checker.cpp
  src/melee/monster-attack-monster.cpp
  src/mind/mind-elementalist.cpp
  src/monster-attack/monster-attack-types.cpp
  src/mspell/assign-monster-spell.cpp
  src/mspell/mspell-bolt.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-particularity.cpp
  src/mspell/specified-summon.cpp
  src/object-activation/activation-bolt-ball.cpp
  src/object-use/read-execution.cpp
  src/object/warning.cpp
  src/player/patron.cpp
  src/racial/racial-switcher.cpp
  src/realm/realm-death.cpp
  src/realm/realm-song.cpp
  src/room/room-generator.cpp
  src/room/room-info-table.cpp
  src/room/room-info-table.h
  src/spell-kind/spells-launcher.cpp
  src/spell-kind/spells-random.cpp
  src/spell-realm/spells-hex.cpp
  src/spell/spells-summon.cpp
  src/system/h-type.h
  src/term/gameterm.cpp
  src/wizard/wizard-spells.h
Labels: enhancement

#1998 [Refactor] floor-base-definitions.h 内定数の constexpr int 化。
  src/floor/floor-base-definitions.h
Labels: refactor

#1999 [Fix] #1993 「既知のモンスター」を開いた際に落ちる
  src/knowledge/knowledge-monsters.cpp
Labels: bug

#2004 80F-100Fユニークモンスターのバランス調整
  lib/edit/r_info.txt
Labels: enhancement

#2005 [Fix] ドワーフ『ナル』のフレーバーが多方面にひどすぎるので直してみた。
  lib/edit/r_info.txt
Labels: documentation

#2010 [Fix] 死亡時召喚でクローンフラグが維持されない
  src/monster-floor/one-monster-placer.cpp
  src/monster-floor/place-monster-types.h
  src/monster-floor/special-death-switcher.cpp
Labels: bug

#2008 [Feature] クエスト「塔」のバランス調整
  lib/edit/q0000005.txt
  lib/edit/q0000006.txt
  lib/edit/q0000007.txt
Labels: enhancement

#2009 [Feature] クエスト『宝物庫』のバランス調整
  lib/edit/q0000004.txt
Labels: enhancement

#1977 Resolve _POSIX_SAVED_IDS issues on Debian
  src/birth/game-play-initializer.cpp
  src/io/uid-checker.cpp
  src/system/h-config.h
Labels: bug

#2012 [Release] 3.0.0Alpha51
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#1982 (Refactor)　ウィザードモードの任意地形変更におけるID指定処理をget_valueに置換。
  src/wizard/wizard-special-process.cpp
Labels: refactor

#2021 [Fix] アングマールの魔王のテキスト送り仮名ミス修正。
  lib/edit/r_info.txt
Labels: bug

#2031 種族や職業に依存する割引が動作していない事象を修正した
  src/info-reader/general-parser.cpp
Labels: bug, 優先度:中

#2022 [Fix] 英語バージョンでスコア送信機能を無効にする
  configure.ac
Labels: enhancement, 優先度:中

#1991 uid-checker.cpp のコンパイルエラーを解消した＋ログ出力を追加した
  src/io/uid-checker.cpp
Labels: bug

#1940 [Refactor] room_typeをenumクラス化し、ループ処理を適時整理。
  src/room/room-generator.cpp
  src/room/room-info-table.cpp
  src/room/room-info-table.h
  src/room/room-types.h
Labels: refactor, 優先度:低
