Repository hengband/hengband, pull requests merged in 2022-09, with the labels that each got.

#2601 clang-format によるソースコード整形チェックが機能していない問題を修正
  .github/scripts/check-format.sh
  src/mutation/mutation-processor.cpp
  src/status/bad-status-setter.cpp
Labels: bug

#2598 誰得の巻物を使うとINSTA_ART指定のベースアイテムが生成される場合がある事象を修正した
  src/object-use/read/scroll-read-executor.cpp
  src/spell/spells-object.cpp
  src/spell/spells-object.h
Labels: bug, Priority:MIDDLE

#2609 artifact_type のmax_num を廃止し、cur_num をbool型にしてis_generated に改名した
  src/artifact/fixed-art-generator.cpp
  src/birth/game-play-initializer.cpp
  src/combat/shoot.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-object.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/grid/object-placer.cpp
  src/knowledge/knowledge-items.cpp
  src/load/item/item-loader-base.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object-enchant/item-magic-applier.cpp
  src/save/save.cpp
  src/spell-kind/spells-floor.cpp
  src/spell/spells-object.cpp
  src/system/artifact-type-definition.h
  src/wizard/wizard-item-modifier.cpp
Labels: refactor, Priority:MIDDLE

#2611 店主の日英情報を統合した
  src/store/store-owners.cpp
  src/store/store-owners.h
Labels: refactor, Priority:MIDDLE

#2612 特性表示記号テーブル定義のリファクタリング
  src/flavor/flag-inscriptions-table.cpp
  src/flavor/flag-inscriptions-table.h
  src/flavor/flavor-util.cpp
Labels: refactor

#2614 [Fix] flag_insc_table のコンストラクタ引数 except_flag をconst参照にする
  src/flavor/flag-inscriptions-table.h
Labels: refactor

#2623 cpp側に定義されたextern 宣言を削除した
  src/player/player-status-table.cpp
  src/util/angband-files.cpp
Labels: refactor, Priority:MIDDLE

#2629 [Fix] #2577 松明の燃料残量が異様に大きな数値になる
  src/specific-object/torch.cpp
Labels: bug

#2630 [Fix] #2535 武器を構えた手が誤って表示されることがある
  src/action/weapon-shield.cpp
Labels: bug

#2626 a_info をvector からmap に差し替えた
  src/action/activation-execution.cpp
  src/artifact/artifact-info.cpp
  src/artifact/fixed-art-generator.cpp
  src/artifact/fixed-art-generator.h
  src/birth/game-play-initializer.cpp
  src/combat/shoot.cpp
  src/dungeon/quest.cpp
  src/flavor/flavor-util.cpp
  src/flavor/named-item-describer.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-object.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/grid/object-placer.cpp
  src/info-reader/artifact-reader.cpp
  src/info-reader/general-parser.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/item/item-loader-base.cpp
  src/load/old/load-v1-5-0.cpp
  src/load/quest-loader.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object-enchant/item-magic-applier.cpp
  src/object-hook/hook-quest.cpp
  src/object/object-flags.cpp
  src/object/object-value-calc.cpp
  src/object/object-value.cpp
  src/perception/identification.cpp
  src/racial/racial-android.cpp
  src/save/save.cpp
  src/specific-object/bloody-moon.cpp
  src/spell-kind/spells-floor.cpp
  src/spell/spells-object.cpp
  src/store/rumor.cpp
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/util/sort.cpp
  src/wizard/artifact-analyzer.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#2634 create_named_art() の中でArtifactType::is_generated をtrueにするよう設計を変えた
  src/artifact/fixed-art-generator.cpp
  src/floor/fixed-map-generator.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#2633 [Fix] 必殺剣「ブーメラン」で何でも投げられてしまう
  src/object-use/throw-execution.cpp
  src/object-use/throw-execution.h
Labels: bug

#2638 [Refactor] 既知のアーティファクト抽出処理
  src/knowledge/knowledge-items.cpp
Labels: refactor

#2641 object_char() をObjectType::get_symbol() に、object_attr() をObjectType::get_color() に変えた
  src/combat/shoot.cpp
  src/object-use/throw-execution.cpp
  src/object/object-info.cpp
  src/object/object-info.h
  src/object/object-kind.cpp
  src/object/object-kind.h
  src/system/object-type-definition.cpp
  src/system/object-type-definition.h
  src/view/display-inventory.cpp
  src/view/display-map.cpp
  src/view/display-player.cpp
  src/view/display-store.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-equipments.cpp
Labels: refactor, Priority:MIDDLE

#2639 固定アーティファクトドロップ処理の改善
  src/monster-floor/monster-death.cpp
Labels: refactor, Priority:MIDDLE

#2643 object_kind 構造体をクラス化するための準備として、まずはヘッダ依存性を減らした
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-util.cpp
  src/flavor/tval-description-switcher.cpp
  src/floor/floor-events.cpp
  src/inventory/recharge-processor.cpp
  src/load/old/item-loader-savefile50.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/object-hook/hook-expendable.cpp
  src/object/object-broken.cpp
  src/object/object-kind.h
  src/object/object-stack.cpp
  src/object/object-value.cpp
  src/racial/racial-android.cpp
  src/store/store-util.cpp
  src/system/object-type-definition.cpp
Labels: refactor, Priority:MIDDLE

#2646 strip_name() のシグネチャを変えた
  src/cmd-visual/cmd-visuals.cpp
  src/flavor/object-flavor.cpp
  src/flavor/object-flavor.h
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-items.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#2657 [Release] 3.0.0Alpha66
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: documentation

#2660 アイテムから発動IDを取ろうとする処理で落ちることがある
  src/artifact/artifact-info.cpp
  src/system/angband-version.h
Labels: bug, Priority:Critical

#2662 アイテムから発動IDを取ろうとする処理で落ちることがある
  src/artifact/artifact-info.cpp
  src/system/angband-version.h
Labels: bug, Priority:Critical

#2664 [Fix] d_info.txtのWブロック表記解説がおかしかったので修正。
  lib/edit/d_info.txt
Labels: documentation

#2669 [Fix] モンスターが魔法を使用する時にクラッシュする
  src/melee/melee-spell-flags-checker.cpp
Labels: bug, Priority:Critical

#2670 [Fix] 暗黒・盲目耐性なしで暗黒属性攻撃を受けても盲目にならない
  src/effect/effect-player-resist-hurt.cpp
Labels: bug

#2671 [Fix] #2667 自身をターゲットにスーパーレイを打つとクラッシュする
  src/spell-class/spells-mirror-master.cpp
Labels: bug

#2673 [Release] 3.0.0Alpha68
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release
