Repository hengband/hengband, pull requests merged in 2022-04, with the labels that each got.

#2463 monster-eating.cpp で出ていたナローキャスティング警告を解消した
  src/monster-attack/monster-eating.cpp
Labels: refactor, Priority:MIDDLE

#2458 シーカーレイが鏡で反射しないことのあるバグを修正
  src/spell-class/spells-mirror-master.cpp
Labels: bug

#2469 [Fix] 油つぼからランタンの燃料補給ができなくなる
  src/load/old/item-loader-savefile50.cpp
Labels: bug

#2462 クエストの配列をシングルトンクラスへ隠蔽化した
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-move.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest-completion-checker.cpp
  src/dungeon/quest-monster-placer.cpp
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/effect/effect-monster-charm.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-events.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-util.cpp
  src/floor/object-allocator.cpp
  src/floor/wild.cpp
  src/info-reader/fixed-map-parser.cpp
  src/info-reader/general-parser.cpp
  src/io-dump/character-dump.cpp
  src/io/write-diary.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/dungeon-loader.cpp
  src/load/load.cpp
  src/load/quest-loader.cpp
  src/main-win/main-win-music.cpp
  src/main/angband-initializer.cpp
  src/main/game-data-initializer.cpp
  src/main/game-data-initializer.h
  src/market/building-quest.cpp
  src/monster-floor/one-monster-placer.cpp
  src/object-hook/hook-quest.cpp
  src/player/player-move.cpp
  src/save/save.cpp
  src/spell-kind/spells-world.cpp
  src/target/target-describer.cpp
  src/util/sort.cpp
  src/view/display-player.cpp
  src/wizard/wizard-game-modifier.cpp
  src/world/world-movement-processor.cpp
Labels: refactor

#2480 モンスターのフラグをまとめる（地形関連動作）
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/movement-execution.cpp
  src/dungeon/dungeon.h
  src/dungeon/quest.cpp
  src/effect/effect-monster-resist-hurt.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/load/lore-loader.cpp
  src/load/savedata-old-flag-types.h
  src/lore/lore-calculator.cpp
  src/lore/lore-store.cpp
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/monster-floor/monster-direction.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/race-feature-flags.h
  src/monster-race/race-feature-mask.cpp
  src/monster-race/race-feature-mask.h
  src/monster/monster-info.cpp
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-update.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-special.cpp
  src/player/player-status-flags.cpp
  src/room/rooms-pit-nest.cpp
  src/save/monster-writer.cpp
  src/spell-kind/earthquake.cpp
  src/system/angband-version.h
  src/system/grid-type-definition.cpp
  src/system/monster-race-definition.h
  src/view/display-lore-status.cpp
Labels: refactor, Priority:MIDDLE

#2473 強化も弱化もしない装備品 (毒針・ダイヤモンドエッジ・死の大鎌)が判定をすり抜けて強化/弱化する不具合を解消した
  src/object-enchant/weapon/abstract-weapon-enchanter.cpp
  src/object-enchant/weapon/abstract-weapon-enchanter.h
  src/object-enchant/weapon/apply-magic-arrow.cpp
  src/object-enchant/weapon/apply-magic-bow.cpp
  src/object-enchant/weapon/apply-magic-digging.cpp
  src/object-enchant/weapon/apply-magic-hafted.cpp
  src/object-enchant/weapon/apply-magic-hafted.h
  src/object-enchant/weapon/apply-magic-polearm.cpp
  src/object-enchant/weapon/apply-magic-polearm.h
  src/object-enchant/weapon/apply-magic-sword.cpp
  src/object-enchant/weapon/apply-magic-sword.h
  src/object-enchant/weapon/melee-weapon-enchanter.h
Labels: bug, Priority:MIDDLE

#2481 load_quest_info() を、「2つのポインタ引数戻り値なし」から「引数なしタプルの戻り値あり」に変更した
  src/load/load.cpp
  src/load/quest-loader.cpp
  src/load/quest-loader.h
Labels: refactor, Priority:MIDDLE

#2488 [Release] 3.0.0Alpha58
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#2492 ブレスの壁貫通バグを修正した
  src/effect/effect-processor.cpp
Labels: bug, Priority:HIGH

#2494 一部ブレスの属性が「不明」になるバグを修正
  src/mspell/mspell-attack/mspell-breath.cpp
Labels: bug

#2499 [Release] 3.0.0Alpha59
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: enhancement

#2498 Release/3.0.0 alpha59
  doxygen/Hengband.doxyfile
  src/effect/effect-processor.cpp
  src/mspell/mspell-attack/mspell-breath.cpp
  src/system/angband-version.h
Labels: release

#2501 [Fix] 壁際の虚無招来による＊破壊＊の効果について、地上か否かの判定が逆になっていた不具合を修正。
  src/spell-realm/spells-chaos.cpp
Labels: bug
