Repository hengband/hengband, pull requests merged in 2022-02, with the labels that each got.

#2028 バリアント名をセーブデータに含めた
  src/core/scores.cpp
  src/core/show-file.cpp
  src/io/report.cpp
  src/load/info-loader.cpp
  src/load/load.cpp
  src/main-win/main-win-utils.cpp
  src/main.cpp
  src/main/angband-initializer.cpp
  src/save/save.cpp
  src/system/angband-version.cpp
  src/system/angband-version.h
Labels: refactor

#2037 GCU版の機能拡張: bigscreen / color / layout customize / cursor flicker fix
  src/main-gcu.cpp
  src/main.cpp
  src/term/z-term.cpp
Labels: enhancement

#2023 Colour patch for 88 and 256 colour terminals
  src/main-gcu.cpp
Labels: enhancement, 優先度:中

#2081 変愚蛮怒以外ではh_older_thanによる互換性確保は作動しないように
  src/load/angband-version-comparer.cpp
  src/system/angband-version.h
Labels: bug, refactor, 優先度:低

#2080 [fix][implement]虚無・深淵属性周りの不具合修正とモンスターの魔法実装
  lib/edit/r_info.txt
  src/blue-magic/blue-magic-ball-bolt.cpp
  src/blue-magic/blue-magic-ball-bolt.h
  src/blue-magic/blue-magic-breath.cpp
  src/blue-magic/blue-magic-breath.h
  src/blue-magic/blue-magic-caster.cpp
  src/blue-magic/learnt-info.cpp
  src/cmd-action/cmd-mane.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/effect/effect-player-resist-hurt.h
  src/effect/effect-player-switcher.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/lore/magic-types-setter.cpp
  src/monster-race/race-ability-flags.h
  src/monster-race/race-ability-mask.cpp
  src/mspell/assign-monster-spell.cpp
  src/mspell/high-resistance-checker.cpp
  src/mspell/monster-power-table.cpp
  src/mspell/mspell-attack.cpp
  src/mspell/mspell-ball.cpp
  src/mspell/mspell-ball.h
  src/mspell/mspell-bolt.cpp
  src/mspell/mspell-bolt.h
  src/mspell/mspell-breath.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/mspell/mspell-selector.cpp
  src/object/warning.cpp
  src/player/player-status-resist.cpp
Labels: enhancement

#2095 モンスター調整 Alpha52
  lib/edit/r_info.txt
Labels: enhancement, refactor

#2109 #2080 で編集したファイルのif文における｛｝の位置をまとめて修正
  src/blue-magic/blue-magic-ball-bolt.cpp
  src/blue-magic/blue-magic-breath.cpp
  src/cmd-action/cmd-mane.cpp
  src/effect/effect-feature.cpp
  src/effect/effect-monster-resist-hurt.cpp
  src/mspell/high-resistance-checker.cpp
  src/mspell/mspell-ball.cpp
  src/mspell/mspell-selector.cpp
  src/object/warning.cpp
Labels: refactor

#2089 monster-attack-util.cpp/h をmonster-attack-player.cpp/h へ吸収合併し、monap_type 構造体をMonsterAttackPlayer クラスへ変更した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/combat/aura-counterattack.cpp
  src/combat/aura-counterattack.h
  src/mind/mind-samurai.cpp
  src/mind/mind-samurai.h
  src/monster-attack/monster-attack-describer.cpp
  src/monster-attack/monster-attack-describer.h
  src/monster-attack/monster-attack-lose.cpp
  src/monster-attack/monster-attack-lose.h
  src/monster-attack/monster-attack-player.cpp
  src/monster-attack/monster-attack-player.h
  src/monster-attack/monster-attack-processor.cpp
  src/monster-attack/monster-attack-status.cpp
  src/monster-attack/monster-attack-status.h
  src/monster-attack/monster-attack-switcher.cpp
  src/monster-attack/monster-attack-switcher.h
  src/monster-attack/monster-attack-util.cpp
  src/monster-attack/monster-attack-util.h
  src/monster-attack/monster-eating.cpp
  src/monster-attack/monster-eating.h
  src/pet/pet-fall-off.cpp
  src/pet/pet-fall-off.h
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-hex.h
Labels: refactor

#2115 薬や魔導書にも上質補正がかかる事象を修正した
  src/object-enchant/apply-magic.cpp
Labels: bug, Priority:Critical

#2113 MSVC環境で出るコンパイル警告を2件解消した
  src/artifact/random-art-characteristics.cpp
  src/inventory/inventory-curse.cpp
Labels: refactor

#2050 盲目時にアンバーの王族召喚を受けた際のメッセージがアンデッド召喚と紛らわしいのを改善(案)
  src/mspell/mspell-summon.cpp
Labels: enhancement

#2099 [Fix] m_bonus()内のrandnorの分散に0が入ってランタイムエラーが発生するのを回避。
  src/term/z-rand.cpp
Labels: enhancement

#2090 モンスターのフラグをまとめる（見た目）
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/core/player-processor.cpp
  src/dungeon/dungeon.h
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/lore/lore-util.h
  src/monster-race/race-visual-flags.h
  src/system/monster-race-definition.h
  src/view/display-map.cpp
  src/wizard/monster-info-spoiler.cpp
Labels: refactor

#2121 [Release] 3.0.0Alpha52
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#2126 不要コメントの削除・必要コメントの追加・変数のコンパイル時定数への変更
  src/load/info-loader.cpp
  src/player/race-resistances.cpp
  src/player/temporary-resistances.cpp
  src/system/angband-version.h
Labels: refactor

#2137 English: avoid "angband" in startup failure messages
  src/main-gcu.cpp
  src/main-win.cpp
Labels: bug, Priority:MIDDLE

#2128 [Adjust] TERM_BLUE to 0x00, 0x80, 0xFF
  lib/pref/colors.prf
  lib/pref/user-win.prf
  src/term/gameterm.cpp
  src/term/term-color-types.h
Labels: enhancement

#2125 object_type::xtra1を消した
  src/load/old/item-loader-savefile50.cpp
  src/load/old/load-v1-5-0.cpp
  src/object/object-stack.cpp
  src/save/item-writer.cpp
  src/store/store-util.cpp
  src/system/object-type-definition.h
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#2136 デバッグ用の装備品強化ルーチンは最初に判定するように修正した
  src/object-enchant/others/apply-magic-amulet.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/object-enchant/others/apply-magic-ring.cpp
  src/object-enchant/protector/apply-magic-armor.cpp
  src/object-enchant/protector/apply-magic-boots.cpp
  src/object-enchant/protector/apply-magic-cloak.cpp
  src/object-enchant/protector/apply-magic-crown.cpp
  src/object-enchant/protector/apply-magic-gloves.cpp
  src/object-enchant/protector/apply-magic-helm.cpp
  src/object-enchant/protector/apply-magic-shield.cpp
  src/object-enchant/weapon/apply-magic-weapon.cpp
Labels: refactor

#2173 重力属性のバグを修正
  src/effect/effect-monster-resist-hurt.cpp
Labels: bug, Priority:MIDDLE

#2161 Alignment::update_alignment() のplayer_ptrにthisを付けた
  src/player-info/alignment.cpp
Labels: refactor

#2167 ObjectType::xtra3 を抹殺してchest_level とcaptured_monster_speed に分離した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/load/load.cpp
  src/load/old/item-flag-types-savefile50.h
  src/load/old/item-loader-savefile50.cpp
  src/load/old/load-v1-5-0.cpp
  src/load/savedata-old-flag-types.h
  src/mind/mind-weaponsmith.h
  src/object-enchant/others/apply-magic-others.cpp
  src/object/object-stack.cpp
  src/save/item-writer.cpp
  src/specific-object/chest.cpp
  src/specific-object/monster-ball.cpp
  src/spell-kind/spells-enchant.cpp
  src/system/angband-exceptions.h
  src/system/angband-version.h
  src/system/h-type.h
  src/system/object-type-definition.h
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#2181 ObjectTypeの読み込みフラグからXTRA1を削除し、軽微な誤植を修正した
  src/load/old/item-flag-types-savefile50.h
  src/load/old/item-loader-savefile50.cpp
  src/load/savedata-old-flag-types.h
  src/system/object-type-definition.cpp
Labels: refactor, Priority:MIDDLE

#2184 ディスコードでの議論に基づき、XTRA1が再利用できない潜在不具合を解消した
  src/load/old/item-loader-savefile50.cpp
  src/load/savedata-old-flag-types.h
Labels: refactor, Priority:MIDDLE

#2052 [Refactor] v_info.txtを参照する部屋生成処理がDRY原則に思いっきり反していたので三種まとめる。
  src/room/room-generator.cpp
  src/room/rooms-vault.cpp
  src/room/rooms-vault.h
Labels: refactor, Priority:HIGH

#2191 [Refactor] debug_spell_commands_listをvector化。
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
Labels: enhancement

#2194 [Fix] vanish_dungeon()が通常のダンジョンで効かなくなっていた不具合を修正。
  src/spell-realm/spells-chaos.cpp
Labels: bug

#2182 [Fix] wiz_kill_enemy()の数値入力をget_value()で実装しなおし。
  src/wizard/wizard-spells.cpp
Labels: bug, refactor, Priority:HIGH

#2196 fix: 不要な自殺コマンドへのキーマップアサインを削除
  lib/pref/pref-key.prf
Labels: enhancement

#2197 Object::xtra4を分解した
  src/action/activation-execution.cpp
  src/birth/inventory-initializer.cpp
  src/cmd-item/cmd-refill.cpp
  src/effect/spells-effect-util.cpp
  src/effect/spells-effect-util.h
  src/flavor/flavor-describer.cpp
  src/hpmp/hp-mp-regenerator.cpp
  src/load/old/item-flag-types-savefile50.h
  src/load/old/item-loader-savefile50.cpp
  src/load/old/load-v1-5-0.cpp
  src/load/savedata-old-flag-types.h
  src/monster-attack/monster-eating.cpp
  src/mutation/mutation-processor.cpp
  src/object-enchant/others/apply-magic-lite.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/object/lite-processor.cpp
  src/object/object-flags.cpp
  src/object/object-stack.cpp
  src/save/item-writer.cpp
  src/smith/smith-info.cpp
  src/specific-object/monster-ball.cpp
  src/specific-object/torch.cpp
  src/spell-realm/spells-arcane.cpp
  src/store/store-util.cpp
  src/system/angband-version.h
  src/system/object-type-definition.cpp
  src/system/object-type-definition.h
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#2203 ObjectType::xtra5 をcaptured_monster_max_hp に変更した 他微修正
  src/effect/effect-monster-charm.cpp
  src/effect/spells-effect-util.cpp
  src/effect/spells-effect-util.h
  src/hpmp/hp-mp-regenerator.cpp
  src/load/old/item-loader-savefile50.cpp
  src/load/old/load-v1-5-0.cpp
  src/save/item-writer.cpp
  src/specific-object/monster-ball.cpp
  src/spell-realm/spells-arcane.cpp
  src/system/h-type.h
  src/system/object-type-definition.h
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#2206 ownersのデータ構造リファクタリング
  src/store/cmd-store.cpp
  src/store/store-owners.cpp
  src/store/store-owners.h
  src/store/store-util.cpp
  src/store/store-util.h
  src/store/store.cpp
Labels: enhancement

#2199 [Refactor] wiz_kill_me()の項目入力にget_value()を適用。
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
Labels: refactor, Priority:MIDDLE

#2207 SPEED の型エイリアスを廃止した
  src/core/player-processor.cpp
  src/core/speed-table.cpp
  src/core/speed-table.h
  src/lore/lore-util.h
  src/monster/monster-damage.cpp
  src/monster/monster-list.cpp
  src/monster/monster-list.h
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-processor.cpp
  src/monster/monster-status.cpp
  src/player-status/player-speed.cpp
  src/player/digestion-processor.cpp
  src/spell-kind/spells-sight.cpp
  src/system/h-type.h
  src/system/monster-race-definition.h
  src/system/monster-type-definition.h
Labels: refactor

#2223 モンスターボールで捕まえたモンスターの情報をグローバル変数ではなくローカル変数で引き回した
  src/cmd-action/cmd-mind.h
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-charm.h
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-monster-switcher.h
  src/effect/effect-monster.cpp
  src/effect/effect-monster.h
  src/effect/effect-player.cpp
  src/effect/effect-player.h
  src/effect/effect-processor.cpp
  src/effect/effect-processor.h
  src/effect/spells-effect-util.cpp
  src/effect/spells-effect-util.h
  src/io/input-key-processor.cpp
  src/specific-object/monster-ball.cpp
  src/spell-kind/spells-launcher.cpp
  src/spell-kind/spells-launcher.h
Labels: refactor, Priority:MIDDLE

#2218 prace == HOGEの判定をPlayerRace::equals(HOGE) で置換した
  src/autopick/autopick-destroyer.cpp
  src/birth/birth-body-spec.cpp
  src/birth/birth-stat.cpp
  src/birth/character-builder.cpp
  src/birth/inventory-initializer.cpp
  src/cmd-item/cmd-destroy.cpp
  src/cmd-item/cmd-equipment.cpp
  src/cmd-visual/cmd-draw.cpp
  src/core/game-play.cpp
  src/core/scores.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/inventory/inventory-curse.cpp
  src/monster-attack/monster-attack-lose.cpp
  src/monster-attack/monster-attack-status.cpp
  src/mspell/mspell-judgement.cpp
  src/mutation/mutation-calculator.cpp
  src/mutation/mutation-investor-remover.cpp
  src/object-use/quaff-execution.cpp
  src/player-base/player-race.cpp
  src/player-status/player-speed.cpp
  src/player/patron.cpp
  src/player/player-damage.cpp
  src/player/player-move.cpp
  src/player/player-skill.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/racial/racial-android.cpp
  src/specific-object/bloody-moon.cpp
  src/status/bad-status-setter.cpp
  src/status/experience.cpp
  src/status/shape-changer.cpp
  src/target/target-describer.cpp
  src/view/display-player-middle.cpp
  src/window/main-window-left-frame.cpp
  src/wizard/wizard-special-process.cpp
Labels: Priority:MIDDLE

#2226 [Feature] ビルドテストの Workflow に BOM チェックを追加
  .github/scripts/check-bom.sh
  .github/workflows/buildtest-on-linux.yml
Labels: enhancement

#2227 [Feature] wiz_kill_target() で指定できる属性一覧を表示する
  src/wizard/wizard-spells.cpp
Labels: enhancement

#2225 STR_OFFSETの型エイリアスを廃止し、ushortに統一した
  src/effect/spells-effect-util.h
  src/system/h-type.h
  src/system/monster-type-definition.h
  src/util/quarks.cpp
  src/util/quarks.h
Labels: refactor, Priority:MIDDLE

#2229 gf_desc のテーブルの順番を直し、gf_desc とgf_color を静的配列からmapに変えた
  src/io/gf-descriptions.cpp
  src/io/gf-descriptions.h
  src/io/interpret-pref-file.cpp
  src/main/game-data-initializer.cpp
  src/term/gameterm.cpp
  src/term/gameterm.h
  src/wizard/wizard-spells.cpp
Labels: refactor, Priority:MIDDLE

#2214 命名がスネークケースでないものをスネークケースに改名した
  src/cmd-action/cmd-pet.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-visual/cmd-draw.cpp
  src/io/input-key-acceptor.cpp
  src/io/record-play-movie.cpp
  src/main-cap.cpp
  src/main-gcu.cpp
  src/main-win.cpp
  src/main-x11.cpp
  src/main/x11-type-string.cpp
  src/player/player-damage.cpp
  src/spell-kind/spells-sight.cpp
  src/term/screen-processor.cpp
  src/term/z-term.cpp
  src/term/z-term.h
  src/view/display-lore.cpp
  src/view/object-describer.cpp
  src/window/display-sub-window-spells.cpp
  src/window/display-sub-windows.cpp
Labels: refactor

#2166 モンスターのフラグをまとめる（耐性）
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/movement-execution.cpp
  src/blue-magic/blue-magic-caster.cpp
  src/cmd-action/cmd-mane.cpp
  src/combat/attack-accuracy.cpp
  src/combat/aura-counterattack.cpp
  src/combat/shoot.cpp
  src/combat/slaying.cpp
  src/dungeon/dungeon.h
  src/effect/effect-monster-evil.cpp
  src/effect/effect-monster-lite-dark.cpp
  src/effect/effect-monster-resist-hurt.cpp
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-monster.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/load/lore-loader.cpp
  src/load/old/load-v1-5-0.cpp
  src/load/savedata-old-flag-types.h
  src/lore/lore-calculator.cpp
  src/lore/lore-store.cpp
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/lore/magic-types-setter.cpp
  src/melee/melee-postprocess.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/melee/monster-attack-monster.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-ninja.cpp
  src/mind/mind-samurai.cpp
  src/mind/mind-sniper.cpp
  src/monster-floor/monster-object.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race.cpp
  src/monster-race/race-flags-resistance.h
  src/monster-race/race-resistance-mask.cpp
  src/monster-race/race-resistance-mask.h
  src/monster/monster-info.cpp
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-processor.cpp
  src/monster/monster-status.cpp
  src/monster/monster-update.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-floor.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-lite.cpp
  src/object-enchant/vorpal-weapon.cpp
  src/player-attack/attack-chaos-effect.cpp
  src/save/monster-writer.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-kind/spells-world.cpp
  src/spell/spells-diceroll.cpp
  src/system/angband-version.h
  src/system/monster-race-definition.h
  src/view/display-lore-status.cpp
Labels: refactor

#2237 ownersの修正をリバートした
  src/store/cmd-store.cpp
  src/store/store-owners.cpp
  src/store/store-owners.h
  src/store/store-util.cpp
  src/store/store-util.h
  src/store/store.cpp
Labels: bug, Priority:HIGH

#2240 [Release] 3.0.0Alpha53
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#2242 関数引数のTARGET_TYPEが命名規則に違反しているので全てtarget_typeに変更した (機械的置換)
  src/mspell/mspell-ball.cpp
  src/mspell/mspell-ball.h
  src/mspell/mspell-bolt.cpp
  src/mspell/mspell-bolt.h
  src/mspell/mspell-breath.cpp
  src/mspell/mspell-breath.h
  src/mspell/mspell-curse.cpp
  src/mspell/mspell-curse.h
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-dispel.h
  src/mspell/mspell-floor.cpp
  src/mspell/mspell-floor.h
  src/mspell/mspell-particularity.cpp
  src/mspell/mspell-particularity.h
  src/mspell/mspell-special.cpp
  src/mspell/mspell-special.h
  src/mspell/mspell-status.cpp
  src/mspell/mspell-status.h
  src/mspell/mspell-summon.cpp
  src/mspell/mspell-summon.h
  src/mspell/mspell-util.cpp
  src/mspell/mspell-util.h
  src/mspell/specified-summon.cpp
  src/mspell/specified-summon.h
Labels: refactor, Priority:MIDDLE

#2247 耐性フラグのパーステーブルを現状のフラグ定義に合わせた
  src/info-reader/race-info-tokens-table.cpp
Labels: refactor

#2248 店舗のデータ整理後に発生したエラーについて、ロード時剰余計算で、店舗情報領域からのアウトを修正。
  src/load/store-loader.cpp
  src/store/cmd-store.cpp
  src/store/store-owners.cpp
  src/store/store-owners.h
  src/store/store-util.cpp
  src/store/store-util.h
  src/store/store.cpp
Labels: enhancement

#1411 [Refactor] エゴIDのenum class(EgoType)化
  src/action/activation-execution.cpp
  src/artifact/artifact-info.cpp
  src/artifact/random-art-generator.cpp
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick-entry.cpp
  src/birth/inventory-initializer.cpp
  src/dungeon/quest-completion-checker.cpp
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-util.cpp
  src/flavor/named-item-describer.cpp
  src/floor/floor-events.cpp
  src/info-reader/ego-reader.cpp
  src/info-reader/general-parser.cpp
  src/info-reader/general-parser.h
  src/load/old/item-loader-savefile50.cpp
  src/load/old/load-v1-5-0.cpp
  src/mind/mind-chaos-warrior.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object-enchant/object-ego.cpp
  src/object-enchant/object-ego.h
  src/object-enchant/old-ego-extra-values.h
  src/object-enchant/others/apply-magic-amulet.cpp
  src/object-enchant/others/apply-magic-lite.cpp
  src/object-enchant/others/apply-magic-ring.cpp
  src/object-enchant/protector/apply-magic-armor.cpp
  src/object-enchant/protector/apply-magic-crown.cpp
  src/object-enchant/protector/apply-magic-helm.cpp
  src/object-enchant/protector/apply-magic-shield.cpp
  src/object-enchant/weapon/apply-magic-weapon.cpp
  src/object/lite-processor.cpp
  src/object/object-flags.cpp
  src/object/object-value-calc.cpp
  src/object/object-value.cpp
  src/perception/identification.cpp
  src/racial/racial-android.cpp
  src/save/item-writer.cpp
  src/specific-object/torch.cpp
  src/spell-realm/spells-craft.cpp
  src/spell/spells-object.cpp
  src/system/object-type-definition.cpp
  src/system/object-type-definition.h
  src/wizard/artifact-analyzer.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: enhancement, Priority:HIGH

#2222 input-key-requestor.cpp/h をクラス化した
  src/core/player-processor.cpp
  src/io/input-key-requester.cpp
  src/io/input-key-requester.h
  src/store/cmd-store.cpp
  src/system/h-type.h
Labels: refactor

#2244 breath関数を4つの関数に分割
  src/mspell/mspell-ball.cpp
  src/mspell/mspell-breath.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-checker.h
  src/mspell/mspell-curse.cpp
  src/mspell/mspell-particularity.cpp
  src/mspell/mspell-status.cpp
Labels: refactor

#2259 ブレスのルールを変更した
  src/effect/effect-characteristics.h
  src/effect/effect-processor.cpp
  src/mspell/mspell-checker.cpp
Labels: refactor

#2261 思い出フラグがモンスター情報の変更に対応できてないバグを修正
  src/load/lore-loader.cpp
Labels: bug, Priority:HIGH

#2263 project()関数内のy, xを一部ローカル化した①+グローバルなy, xをtemp_*に変えた
  src/effect/effect-processor.cpp
Labels: refactor

#2265 [Fix] wiz_restore_monster_max_num()の範囲指定を修正しつつn/Nコマンドと同等の仕様にリファクタリング。
  src/wizard/wizard-game-modifier.cpp
Labels: bug, refactor

#2251 [Refactor] エゴアイテムの情報を格納する e_info を std::map にする
  src/action/activation-execution.cpp
  src/artifact/artifact-info.cpp
  src/autopick/autopick-entry.cpp
  src/flavor/flavor-util.cpp
  src/flavor/named-item-describer.cpp
  src/floor/floor-events.cpp
  src/info-reader/ego-reader.cpp
  src/load/old/load-v1-5-0.cpp
  src/main/info-initializer.cpp
  src/object-enchant/object-ego.cpp
  src/object-enchant/object-ego.h
  src/object-enchant/weapon/apply-magic-weapon.cpp
  src/object/object-flags.cpp
  src/object/object-value-calc.cpp
  src/object/object-value.cpp
  src/racial/racial-android.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#2269 クラスまたは荒野に依存する判定の設計を修正した
  src/cmd-io/cmd-menu-content-table.cpp
  src/cmd-io/cmd-menu-content-table.h
  src/io/input-key-requester.cpp
  src/io/input-key-requester.h
Labels: refactor, Priority:HIGH

#2249 AbstractWeaponEnchanter のコンストラクタで武器類の強化/弱化を判定させることにした
  src/object-enchant/apply-magic.cpp
  src/object-enchant/weapon/abstract-weapon-enchanter.cpp
  src/object-enchant/weapon/abstract-weapon-enchanter.h
  src/object-enchant/weapon/apply-magic-weapon.cpp
Labels: refactor, Priority:MIDDLE

#2174 重力属性のobviousの挙動を修正
  src/effect/effect-monster-resist-hurt.cpp
Labels: bug

#2266 apply-magic-others.cpp/h をクラス化した
  src/object-enchant/apply-magic.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/object-enchant/others/apply-magic-others.h
Labels: refactor, Priority:HIGH

#2280 [Feature] ビルドテストに ccache を使用する
  .github/workflows/buildtest-on-linux.yml
Labels: enhancement

#2283 [Fix] 店に売り出される矢の決定時に誤った矢が選択される
  lib/edit/k_info.txt
Labels: bug

#2279 mimic_kind_type をenum class として再定義した
  src/action/racial-execution.cpp
  src/cmd-action/cmd-racial.cpp
  src/load/load-zangband.cpp
  src/load/player-info-loader.cpp
  src/monster-attack/monster-eating.cpp
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-judgement.cpp
  src/player-base/player-race.cpp
  src/player-info/alignment.cpp
  src/player-info/mimic-info-table.cpp
  src/player-info/mimic-info-table.h
  src/player-info/race-info.h
  src/player-info/self-info.cpp
  src/player/player-status-flags.cpp
  src/player/player-status-resist.cpp
  src/player/player-status.cpp
  src/racial/race-racial-command-setter.cpp
  src/racial/racial-switcher.cpp
  src/realm/realm-death.cpp
  src/realm/realm-demon.cpp
  src/specific-object/death-scythe.cpp
  src/status/buff-setter.cpp
  src/status/buff-setter.h
  src/status/element-resistance.cpp
  src/system/player-type-definition.h
  src/view/display-player-misc-info.cpp
  src/view/display-player-stat-info.cpp
  src/view/display-player.cpp
  src/view/display-self-info.cpp
  src/window/main-window-left-frame.cpp
Labels: refactor, Priority:MIDDLE

#2284 SYMBOL_CODE をchar型に変えた
  src/cmd-io/cmd-process-screen.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/combat/shoot.cpp
  src/effect/effect-processor.cpp
  src/floor/object-scanner.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/grid/grid.cpp
  src/grid/grid.h
  src/inventory/inventory-util.cpp
  src/io-dump/dump-util.cpp
  src/io-dump/dump-util.h
  src/io/cursor.cpp
  src/io/interpret-pref-file.cpp
  src/io/report.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/mspell/summon-checker.cpp
  src/object/object-kind.cpp
  src/object/object-kind.h
  src/player-info/race-info.cpp
  src/player-info/race-info.h
  src/system/h-type.h
  src/system/monster-race-definition.h
  src/term/gameterm.cpp
  src/term/gameterm.h
  src/view/display-inventory.cpp
  src/view/display-map.cpp
  src/view/display-map.h
  src/view/display-player.cpp
  src/view/display-store.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-equipments.cpp
  src/window/main-window-util.cpp
  src/window/main-window-util.h
Labels: refactor, Priority:MIDDLE

#2288 gcc-wrap の改良
  src/Makefile.am
  src/autopick/autopick-destroyer.cpp
  src/effect/effect-monster.cpp
  src/gcc-wrap
  src/io/command-repeater.cpp
  src/knowledge/knowledge-quests.cpp
  src/knowledge/knowledge-self.cpp
  src/knowledge/knowledge-uniques.cpp
  src/load/birth-loader.cpp
  src/market/play-gamble.cpp
  src/mind/mind-elementalist.cpp
  src/mspell/mspell-learn-checker.cpp
  src/player/permanent-resistances.cpp
  src/player/race-resistances.cpp
  src/player/temporary-resistances.cpp
  src/view/display-characteristic.cpp
  src/view/display-fruit.cpp
  src/view/display-player-stat-info.cpp
  src/view/display-player.cpp
  src/view/display-util.cpp
  src/view/status-first-page.cpp
Labels: enhancement

#2307 [Feature] PR ステータスチェックのワークフロー再構成
  .github/scripts/check-format.sh
  .github/workflows/build-with-autotools.yml
  .github/workflows/buildtest-on-linux.yml
  .github/workflows/pull-request-status-check.yml
Labels: enhancement

#2296 monster-attack-types.cpp/h をmonster-attack-table.cpp/h に改名した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/lore/combat-types-setter.cpp
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/melee/melee-postprocess.cpp
  src/melee/melee-util.h
  src/monster-attack/monster-attack-describer.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/monster-attack/monster-attack-table.cpp
  src/monster-attack/monster-attack-table.h
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race-hook.cpp
  src/mspell/summon-checker.cpp
  src/object/warning.cpp
  src/system/monster-race-definition.h
  src/view/display-lore-attacks.cpp
  src/view/display-lore.cpp
Labels: refactor, Priority:MIDDLE

#2309 ペットを押し退けようとすると攻撃動作に入ってしまう事象を修正した
  src/action/movement-execution.cpp
Labels: bug, Priority:HIGH

#2304 #2273 で出た別の修正点を施した
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-move.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest-completion-checker.cpp
  src/dungeon/quest-monster-placer.cpp
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/effect/effect-monster-charm.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-events.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-util.cpp
  src/floor/object-allocator.cpp
  src/floor/wild.cpp
  src/info-reader/fixed-map-parser.cpp
  src/info-reader/general-parser.cpp
  src/io-dump/character-dump.cpp
  src/io/write-diary.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/dungeon-loader.cpp
  src/load/load.cpp
  src/load/quest-loader.cpp
  src/main/game-data-initializer.cpp
  src/market/building-quest.cpp
  src/monster-floor/one-monster-placer.cpp
  src/object-hook/hook-quest.cpp
  src/player/player-move.cpp
  src/save/save.cpp
  src/spell-kind/spells-world.cpp
  src/target/target-describer.cpp
  src/util/sort.cpp
  src/view/display-player.cpp
  src/wizard/wizard-game-modifier.cpp
  src/world/world-movement-processor.cpp
Labels: refactor

#2310 [Feature] ccache のためにキャッシュを生成するワークフロー
  .github/workflows/create-cache-for-ccache.yml
Labels: enhancement

#2315 [Refactor] 独自定義例外に継承コンストラクタを使用する
  src/system/angband-exceptions.h
Labels: refactor

#2302 幻覚に関するエンティティをPlayerHallucinationクラスにまとめた
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/action-limited.cpp
  src/action/movement-execution.cpp
  src/action/open-close-execution.cpp
  src/blue-magic/blue-magic-checker.cpp
  src/cmd-action/cmd-attack.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-io/cmd-dump.cpp
  src/combat/shoot.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/core/player-processor.cpp
  src/effect/effect-processor.cpp
  src/floor/pattern-walk.cpp
  src/load/player-info-loader.cpp
  src/melee/melee-util.cpp
  src/mind/mind-ninja.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-floor/monster-death.cpp
  src/monster/monster-damage.cpp
  src/monster/monster-describer.cpp
  src/monster/monster-info.cpp
  src/monster/monster-status.cpp
  src/monster/monster-update.cpp
  src/object-use/throw-execution.cpp
  src/player-info/self-info.cpp
  src/player/eldritch-horror.cpp
  src/player/player-damage.cpp
  src/player/player-move.cpp
  src/save/player-writer.cpp
  src/spell-kind/spells-fetcher.cpp
  src/status/bad-status-setter.cpp
  src/status/buff-setter.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/target/grid-selector.cpp
  src/target/target-describer.cpp
  src/target/target-preparation.cpp
  src/timed-effect/player-hallucination.cpp
  src/timed-effect/player-hallucination.h
  src/timed-effect/timed-effects.cpp
  src/timed-effect/timed-effects.h
  src/view/display-map.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-left-frame.cpp
  src/window/main-window-stat-poster.cpp
  src/window/main-window-util.cpp
Labels: refactor, Priority:HIGH

#2313 クエスト「海底都市」と関連コードを完全に削除した
  lib/edit/Makefile.am
  lib/edit/q000lyeh.txt
  lib/edit/q_info.txt
  src/dungeon/quest-completion-checker.cpp
  src/dungeon/quest-completion-checker.h
  src/knowledge/knowledge-quests.cpp
  src/load/player-info-loader.cpp
  src/load/quest-loader.cpp
  src/load/savedata-old-flag-types.h
  src/market/building-quest.cpp
  src/system/angband-version.h
Labels: refactor

#2316 マンキュバスを弱体化した
  lib/edit/r_info.txt
Labels: enhancement

#2317 プレイヤーの麻痺に関するパラメータをクラス化した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/blue-magic/blue-magic-checker.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/core/player-processor.cpp
  src/load/player-info-loader.cpp
  src/mind/mind-ninja.cpp
  src/monster-attack/monster-attack-status.cpp
  src/monster-attack/monster-eating.cpp
  src/player/digestion-processor.cpp
  src/player/player-damage.cpp
  src/racial/racial-switcher.cpp
  src/save/player-writer.cpp
  src/status/bad-status-setter.cpp
  src/status/buff-setter.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/timed-effect/player-paralysis.cpp
  src/timed-effect/player-paralysis.h
  src/timed-effect/timed-effects.cpp
  src/timed-effect/timed-effects.h
  src/window/main-window-stat-poster.cpp
Labels: refactor, Priority:HIGH

#2324 スレイの対象が逆転してしまっているバグを修正した
  src/combat/slaying.cpp
Labels: bug, Priority:Critical

#2321 [Refactor] PlayerType::died_from を std::string 型にする
  src/cmd-action/cmd-others.cpp
  src/cmd-io/cmd-save.cpp
  src/core/game-closer.cpp
  src/core/scores.cpp
  src/io/exit-panic.cpp
  src/io/report.cpp
  src/io/signal-handlers.cpp
  src/load/load-util.cpp
  src/load/load-util.h
  src/load/player-info-loader.cpp
  src/player/player-damage.cpp
  src/player/process-death.cpp
  src/save/save-util.cpp
  src/save/save-util.h
  src/system/player-type-definition.h
  src/view/display-player.cpp
  src/wizard/wizard-special-process.cpp
Labels: bug, refactor

#2327 速度補正が正しく機能していない不具合を解消した
  src/player-status/player-speed.cpp
Labels: bug, Priority:HIGH

#2329 Windowsでコンパイルエラーが出る事象を修正した
  src/main-win.cpp
Labels: bug, Priority:Critical

#2332 自分のキャラ表示が @ ではなく別の文字に変わってしまう事象を解決した
  src/object-enchant/others/apply-magic-others.cpp
Labels: bug, Priority:Critical

#2334 [Release] 3.0.0Alpha54(Hotfix)
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release
