Repository hengband/hengband, pull requests merged in 2022-08, with the labels that each got.

#2576 Eric氏の修正でBitFlagsCalculatorが使われていなかったので差し替えた
  src/flavor/named-item-describer.cpp
Labels: refactor

#2579 PlayerType::slow フィールド変数をPlayerDeceleration クラスでカプセル化した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-action/cmd-shoot.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/effect/effect-player-oldies.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/effect/effect-player-spirit.cpp
  src/grid/trap.cpp
  src/load/player-info-loader.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-status.cpp
  src/mutation/mutation-processor.cpp
  src/object-use/quaff/quaff-effects.cpp
  src/player-status/player-speed.cpp
  src/save/player-writer.cpp
  src/status/bad-status-setter.cpp
  src/status/bad-status-setter.h
  src/status/buff-setter.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/timed-effect/player-acceleration.cpp
  src/timed-effect/player-acceleration.h
  src/timed-effect/player-deceleration.cpp
  src/timed-effect/player-deceleration.h
  src/timed-effect/timed-effects.cpp
  src/timed-effect/timed-effects.h
  src/view/display-player-middle.cpp
  src/window/main-window-stat-poster.cpp
Labels: refactor

#2582 Visual Studio 2022 v17.3 からコンパイルエラーが出るようになったのを修正した
  src/store/store-util.h
Labels: bug, Priority:HIGH

#2578 store_create() からコールバックをなくした
  src/store/store-util.cpp
  src/store/store-util.h
  src/store/store.cpp
Labels: refactor

#2590 Release/3.0.0 alpha65
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  doxygen/Hengband.doxyfile
  src/Makefile.am
  src/cmd-action/cmd-shoot.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/effect/effect-player-oldies.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/effect/effect-player-spirit.cpp
  src/flavor/named-item-describer.cpp
  src/grid/trap.cpp
  src/load/player-info-loader.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-status.cpp
  src/mutation/mutation-processor.cpp
  src/object-use/quaff/quaff-effects.cpp
  src/player-status/player-speed.cpp
  src/save/player-writer.cpp
  src/status/bad-status-setter.cpp
  src/status/bad-status-setter.h
  src/status/buff-setter.cpp
  src/store/store-util.cpp
  src/store/store-util.h
  src/store/store.cpp
  src/system/angband-version.h
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/timed-effect/player-acceleration.cpp
  src/timed-effect/player-acceleration.h
  src/timed-effect/player-deceleration.cpp
  src/timed-effect/player-deceleration.h
  src/timed-effect/timed-effects.cpp
  src/timed-effect/timed-effects.h
  src/view/display-player-middle.cpp
  src/window/main-window-stat-poster.cpp
Labels: release

#2589 [Release] 3.0.0Alpha65
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#2583 PlayerType::poisoned フィールド変数をPlayerPoison クラスでカプセル化した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-building/cmd-inn.cpp
  src/cmd-item/cmd-eat.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/hpmp/hp-mp-processor.cpp
  src/load/player-info-loader.cpp
  src/object-activation/activation-switcher.cpp
  src/object-use/quaff/quaff-effects.cpp
  src/player-info/self-info.cpp
  src/realm/realm-arcane.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-life.cpp
  src/realm/realm-nature.cpp
  src/save/player-writer.cpp
  src/spell/spells-staff-only.cpp
  src/spell/spells-status.cpp
  src/status/bad-status-setter.cpp
  src/status/bad-status-setter.h
  src/status/buff-setter.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/timed-effect/player-poison.cpp
  src/timed-effect/player-poison.h
  src/timed-effect/timed-effects.cpp
  src/timed-effect/timed-effects.h
  src/window/main-window-stat-poster.cpp
Labels: refactor
