Repository hengband/hengband, pull requests merged in 2022-03, with the labels that each got.

#2336 プレイヤーの恐怖に関するパラメータをクラス化した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-action/cmd-attack.cpp
  src/cmd-item/cmd-eat.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/core/player-processor.cpp
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-psi.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/inventory/inventory-curse.cpp
  src/load/player-info-loader.cpp
  src/mind/mind-mindcrafter.cpp
  src/mind/mind-samurai.cpp
  src/monster-attack/monster-attack-status.cpp
  src/monster/monster-timed-effect-types.h
  src/mspell/mspell-status.cpp
  src/mutation/mutation-processor.cpp
  src/object-activation/activation-others.cpp
  src/object-activation/activation-resistance.cpp
  src/object-activation/activation-switcher.cpp
  src/object-use/quaff-execution.cpp
  src/player-info/self-info.cpp
  src/racial/racial-switcher.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-demon.cpp
  src/realm/realm-song.cpp
  src/save/player-writer.cpp
  src/specific-object/blade-turner.cpp
  src/spell/spells-staff-only.cpp
  src/spell/spells-status.cpp
  src/spell/spells-summon.cpp
  src/status/bad-status-setter.cpp
  src/status/bad-status-setter.h
  src/status/buff-setter.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/timed-effect/player-fear.cpp
  src/timed-effect/player-fear.h
  src/timed-effect/timed-effects.cpp
  src/timed-effect/timed-effects.h
  src/window/main-window-stat-poster.cpp
Labels: refactor, Priority:HIGH

#2340 projectの temp_x, y を一意にし、 const化
  src/effect/effect-processor.cpp
Labels: refactor

#2343 project() の dist 変数のスコープを切り分けた
  src/effect/effect-processor.cpp
Labels: refactor

#2342 [Refactor] 賞金首情報の処理コードのリファクタリング
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/knowledge/knowledge-monsters.cpp
  src/load/load-zangband.cpp
  src/load/player-info-loader.cpp
  src/market/bounty-type-definition.h
  src/market/bounty.cpp
  src/market/bounty.h
  src/monster/monster-damage.cpp
  src/object-hook/hook-quest.cpp
  src/save/player-writer.cpp
  src/system/angband-version.h
  src/window/display-sub-windows.cpp
  src/world/world.h
Labels: refactor

#2294 read-execution.cpp/h を分割した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-item/cmd-item.cpp
  src/cmd-item/cmd-read.cpp
  src/object-use/read-execution.cpp
  src/object-use/read/gbh-shirt-read-executor.cpp
  src/object-use/read/gbh-shirt-read-executor.h
  src/object-use/read/parchment-read-executor.cpp
  src/object-use/read/parchment-read-executor.h
  src/object-use/read/read-execution.cpp
  src/object-use/read/read-execution.h
  src/object-use/read/read-executor-base.h
  src/object-use/read/read-executor-factory.cpp
  src/object-use/read/read-executor-factory.h
  src/object-use/read/ring-power-read-executor.cpp
  src/object-use/read/ring-power-read-executor.h
  src/object-use/read/scroll-read-executor.cpp
  src/object-use/read/scroll-read-executor.h
  src/system/object-type-definition.h
Labels: refactor, Priority:MIDDLE

#2351 [Fix] モンスター間の生命力吸収攻撃の挙動がおかしい
  src/melee/monster-attack-monster.cpp
Labels: bug

#2346 project() 内の一部変数のスコープを処理内容に合わせた + ブレスのエンバグ修正
  src/effect/effect-processor.cpp
  src/spell-kind/spells-launcher.cpp
Labels: bug, refactor

#2330 プレイヤーのステータス補正に関するメソッド名と変数名を分かりやすく変更した
  src/player-ability/player-charisma.cpp
  src/player-ability/player-charisma.h
  src/player-ability/player-constitution.cpp
  src/player-ability/player-constitution.h
  src/player-ability/player-dexterity.cpp
  src/player-ability/player-dexterity.h
  src/player-ability/player-intelligence.cpp
  src/player-ability/player-intelligence.h
  src/player-ability/player-strength.cpp
  src/player-ability/player-strength.h
  src/player-ability/player-wisdom.cpp
  src/player-ability/player-wisdom.h
  src/player-status/player-basic-statistics.cpp
  src/player-status/player-basic-statistics.h
  src/player-status/player-infravision.cpp
  src/player-status/player-infravision.h
  src/player-status/player-speed.cpp
  src/player-status/player-speed.h
  src/player-status/player-status-base.cpp
  src/player-status/player-status-base.h
  src/player-status/player-stealth.cpp
  src/player-status/player-stealth.h
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
Labels: refactor, Priority:MIDDLE

#2359 プレイヤーのブレスが発動しないバグを修正(master)
  doxygen/Hengband.doxyfile
  src/spell-kind/spells-launcher.cpp
  src/system/angband-version.h
Labels: bug, release, Priority:Critical

#2370 [Fix] 暗黒免疫があるにも関わらず暗黒属性の攻撃で盲目になる
  src/effect/effect-player-resist-hurt.cpp
Labels: bug

#2372 地獄免疫の回復メッセージがひらがなと漢字で２度表示されるバグを修正
  src/effect/effect-player-resist-hurt.cpp
Labels: bug

#2373 MSVCにおけるコンパイルエラー/警告を解消した
  src/main-win/main-win-music.cpp
  src/monster-race/monster-race.h
Labels: bug, Priority:HIGH

#2374 [Fix] モンスターが暗黒免疫を学習しない
  src/monster/monster-update.cpp
  src/mspell/high-resistance-checker.cpp
Labels: enhancement

#2354 enum process_resultをenum class ProcessResultに変えた
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-charm.h
  src/effect/effect-monster-curse.cpp
  src/effect/effect-monster-curse.h
  src/effect/effect-monster-evil.cpp
  src/effect/effect-monster-evil.h
  src/effect/effect-monster-lite-dark.cpp
  src/effect/effect-monster-lite-dark.h
  src/effect/effect-monster-oldies.cpp
  src/effect/effect-monster-oldies.h
  src/effect/effect-monster-psi.cpp
  src/effect/effect-monster-psi.h
  src/effect/effect-monster-resist-hurt.cpp
  src/effect/effect-monster-resist-hurt.h
  src/effect/effect-monster-spirit.cpp
  src/effect/effect-monster-spirit.h
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-monster-switcher.h
  src/effect/effect-monster.cpp
  src/effect/effect-player.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-elementalist.h
  src/system/h-type.h
  src/target/target-describer.cpp
Labels: refactor, Priority:HIGH

#2377 [Refactor] calc_monrace_power() を MonsterRace のメンバ関数にする
  src/floor/floor-generator.cpp
  src/load/world-loader.cpp
  src/market/arena.cpp
  src/monster-race/monster-race.cpp
  src/monster-race/monster-race.h
  src/save/player-writer.cpp
  src/system/building-type-definition.cpp
  src/system/building-type-definition.h
Labels: refactor

#2379 [Fix] gcc-wrap を .cpp 以外の拡張子にも対応する
  src/gcc-wrap
Labels: bug, enhancement

#2378 [Refactor] 賞金首関連のコードの整理
  src/birth/game-play-initializer.cpp
  src/knowledge/knowledge-monsters.cpp
  src/load/world-loader.cpp
  src/market/bounty.cpp
  src/market/bounty.h
  src/monster-race/monster-race.cpp
  src/monster-race/monster-race.h
  src/monster/monster-damage.cpp
  src/object-hook/hook-quest.cpp
  src/save/player-writer.cpp
  src/system/player-type-definition.h
  src/window/display-sub-windows.cpp
Labels: refactor

#2381 [Refactor] do_cmd_knowledge_monsters() のコード整理
  src/cmd-visual/cmd-visuals.cpp
  src/knowledge/knowledge-monsters.cpp
Labels: refactor

#2375 小文字しか入力範囲のないコマンドで大文字を入力した際の確認機能を削除した
  src/cmd-action/cmd-hissatsu.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-power-getter.cpp
  src/mind/mind-power-getter.h
  src/mind/mind-sniper.cpp
  src/mind/mind-weaponsmith.cpp
Labels: refactor, Priority:MIDDLE

#2383 SpellsMirrorMaster クラスを作成して鏡魔法の効果処理を大部分移した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/effect/effect-feature.cpp
  src/effect/effect-processor.cpp
  src/floor/floor-leaver.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/mind/mind-mirror-master.cpp
  src/mind/mind-mirror-master.h
  src/racial/racial-switcher.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-class/spells-mirror-master.h
Labels: refactor, Priority:HIGH

#2389 [Refactor] save_type を enum class SaveType に置換。
  src/cmd-io/cmd-save.cpp
  src/core/game-closer.cpp
  src/core/game-play.cpp
  src/io/exit-panic.cpp
  src/io/input-key-requester.cpp
  src/io/signal-handlers.cpp
  src/main-win.cpp
  src/player/player-damage.cpp
  src/save/info-writer.cpp
  src/save/info-writer.h
  src/save/save.cpp
  src/save/save.h
Labels: refactor

#2391 ランダムクエストの50Fが存在しないバグを修正
  doxygen/Hengband.doxyfile
  src/birth/game-play-initializer.cpp
  src/system/angband-version.h
Labels: bug, Priority:Critical

#2390 ランダムクエストの50Fが存在しないバグを修正
  doxygen/Hengband.doxyfile
  src/birth/game-play-initializer.cpp
  src/system/angband-version.h
Labels: bug, Priority:Critical

#2397 変身していないカメレオンが生成されるバグを修正
  src/monster/monster-list.cpp
Labels: bug, Priority:MIDDLE

#2392 max_q_idxを廃止した
  lib/edit/misc.txt
  lib/edit/q_random.txt
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/floor/fixed-map-generator.cpp
  src/info-reader/fixed-map-parser.cpp
  src/info-reader/fixed-map-parser.h
  src/load/load-zangband.cpp
  src/load/load-zangband.h
  src/load/load.cpp
  src/load/quest-loader.cpp
  src/load/quest-loader.h
  src/main-win/main-win-music.cpp
  src/main/game-data-initializer.cpp
  src/save/save.cpp
  src/system/angband-version.h
  src/wizard/wizard-game-modifier.cpp
Labels: refactor

#2400 [Fix] ascii_to_textのバッファオーバーランを修正
  src/autopick/autopick-inserter-killer.cpp
  src/cmd-io/cmd-macro.cpp
  src/io/input-key-acceptor.cpp
  src/io/interpret-pref-file.cpp
  src/util/string-processor.cpp
  src/util/string-processor.h
Labels: bug, Priority:HIGH

#2409 シーカーレイとスーパーレイをproject()からクラスへ切り離した
  src/effect/effect-processor.cpp
  src/mind/mind-mirror-master.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-class/spells-mirror-master.h
Labels: refactor

#2394 ObjectQuaffEntity クラスから QuaffEffects クラスを分離した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-item/cmd-item.cpp
  src/cmd-item/cmd-quaff.cpp
  src/object-use/quaff-execution.cpp
  src/object-use/quaff/quaff-effects.cpp
  src/object-use/quaff/quaff-effects.h
  src/object-use/quaff/quaff-execution.cpp
  src/object-use/quaff/quaff-execution.h
  src/perception/object-perception.cpp
  src/perception/object-perception.h
  src/system/object-type-definition.cpp
  src/system/object-type-definition.h
Labels: refactor, Priority:MIDDLE

#2399 [Refactor] be_type を enum class BlowEffectType 化。
  src/melee/melee-switcher.cpp
  src/melee/melee-switcher.h
  src/melee/melee-util.cpp
  src/melee/melee-util.h
  src/melee/monster-attack-monster.cpp
Labels: refactor

#2410 モンスターのフラグをまとめる（ドロップ）
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/dungeon/dungeon.h
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/load/lore-loader.cpp
  src/load/savedata-old-flag-types.h
  src/lore/lore-calculator.cpp
  src/lore/lore-store.cpp
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/market/bounty.cpp
  src/monster-floor/monster-death-util.cpp
  src/monster-floor/monster-death.cpp
  src/monster-race/race-drop-flags.h
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-update.cpp
  src/monster/monster-util.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/save/monster-writer.cpp
  src/system/angband-version.h
  src/system/monster-race-definition.h
  src/view/display-lore-drops.cpp
Labels: refactor

#2408 ファクトリクラスにおいてshared_ptr を返している箇所をunique_ptr に差し替えた
  src/load/item/item-loader-factory.cpp
  src/load/item/item-loader-factory.h
  src/load/monster/monster-loader-factory.cpp
  src/load/monster/monster-loader-factory.h
  src/object-use/read/read-executor-factory.cpp
  src/object-use/read/read-executor-factory.h
Labels: refactor, Priority:MIDDLE

#2419 [Fix] #2416 魔力食いを失敗した時のメッセージがおかしい
  src/mind/mind-mage.cpp
Labels: bug

#2421 [Fix] 指定護衛のデータ数の制限をなくす
  src/info-reader/race-reader.cpp
  src/lore/monster-lore.cpp
  src/monster-floor/monster-generator.cpp
  src/system/monster-race-definition.h
  src/view/display-lore.cpp
Labels: refactor

#2422 ダンジョンで指定された条件とは違うモンスターが生成されることのあるバグを修正
  src/monster/monster-util.cpp
Labels: bug, Priority:HIGH

#2418 [Refactor] メッセージ表示関連関数の引数の型を std::string_view にする
  src/effect/effect-player.cpp
  src/io/write-diary.cpp
  src/main/game-data-initializer.cpp
  src/object-use/item-use-checker.cpp
  src/room/rooms-pit-nest.cpp
  src/status/bad-status-setter.cpp
  src/view/display-messages.cpp
  src/view/display-messages.h
  src/wizard/wizard-game-modifier.cpp
Labels: refactor

#2404 WeaponEnchanter を武器種別ごとに分離した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/object-enchant/apply-magic.cpp
  src/object-enchant/weapon/apply-magic-arrow.cpp
  src/object-enchant/weapon/apply-magic-arrow.h
  src/object-enchant/weapon/apply-magic-bow.cpp
  src/object-enchant/weapon/apply-magic-bow.h
  src/object-enchant/weapon/apply-magic-digging.cpp
  src/object-enchant/weapon/apply-magic-digging.h
  src/object-enchant/weapon/apply-magic-sword.cpp
  src/object-enchant/weapon/apply-magic-sword.h
  src/object-enchant/weapon/apply-magic-weapon.cpp
Labels: refactor, Priority:HIGH

#2423 [Fix] 特定アーティファクトドロップのデータ数の制限をなくす
  lib/edit/r_info.txt
  src/info-reader/race-reader.cpp
  src/monster-floor/monster-death.cpp
  src/system/monster-race-definition.h
Labels: refactor

#2426 思い出補完のカウントとダンジョンのモンスターフラグフィルターのコピペを低減
  src/lore/lore-store.cpp
  src/monster/monster-util.cpp
Labels: refactor, Priority:HIGH

#2428 projection_path をクラス化した
  src/combat/shoot.cpp
  src/effect/effect-characteristics.h
  src/effect/effect-processor.cpp
  src/io/cursor.cpp
  src/mind/mind-ninja.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-judgement.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell/range-calc.cpp
  src/spell/range-calc.h
  src/target/projection-path-calculator.cpp
  src/target/projection-path-calculator.h
Labels: refactor

#2431 [Fix] #2430 光源の残ターン数が負のオーバーフローを起こす
  src/load/old/item-loader-savefile50.cpp
  src/save/item-writer.cpp
  src/system/object-type-definition.h
Labels: bug

#2433 モンスターの死体を食べた時の効果のフラグを削除した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  lib/edit/r_info.txt
  src/Makefile.am
  src/dungeon/dungeon.h
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/market/bounty.cpp
  src/monster-floor/monster-death.cpp
  src/monster-race/race-flags9.h
  src/monster/monster-util.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/system/monster-race-definition.h
Labels: refactor

#2437 モンスターのフラグをまとめる（荒野）
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/movement-execution.cpp
  src/dungeon/dungeon.h
  src/dungeon/quest.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/monster-floor/monster-move.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/race-wilderness-flags.h
  src/monster/monster-damage.cpp
  src/monster/monster-info.cpp
  src/monster/monster-util.cpp
  src/mspell/summon-checker.cpp
  src/system/monster-race-definition.h
  src/wizard/wizard-spoiler.cpp
Labels: refactor

#2434 [Refactor] ボルトの軌道の描画を関数化する
  src/effect/effect-processor.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/mind/mind-mirror-master.cpp
  src/spell-class/spells-mirror-master.cpp
  src/term/gameterm.cpp
  src/term/gameterm.h
Labels: refactor

#2445 モンスターのアイテムを拾う挙動のバグを修正
  src/monster-floor/monster-object.cpp
Labels: bug

#2447 イテレータ範囲の要素をシャッフルする関数 rand_shuffle を実装
  src/flavor/object-flavor.cpp
  src/market/poker.cpp
  src/term/z-rand.h
Labels: enhancement, refactor

#2446 [Refactor] グローバル変数 cur_store_num を削除する
  src/object/item-tester-hooker.cpp
  src/object/item-tester-hooker.h
  src/store/cmd-store.cpp
  src/store/home.cpp
  src/store/home.h
  src/store/museum.cpp
  src/store/pricing.cpp
  src/store/pricing.h
  src/store/purchase-order.cpp
  src/store/purchase-order.h
  src/store/say-comments.cpp
  src/store/say-comments.h
  src/store/sell-order.cpp
  src/store/sell-order.h
  src/store/service-checker.cpp
  src/store/service-checker.h
  src/store/store-key-processor.cpp
  src/store/store-key-processor.h
  src/store/store-util.cpp
  src/store/store-util.h
  src/store/store.cpp
  src/store/store.h
  src/view/display-store.cpp
  src/view/display-store.h
Labels: bug, refactor

#2436 [Fix] X11版で起動直後の初期化中にキーを押すとクラッシュする
  src/main-x11.cpp
Labels: bug

#2448 mind-numbers.h をenum class 化
  src/cmd-action/cmd-mind.cpp
  src/mind/mind-berserker.cpp
  src/mind/mind-berserker.h
  src/mind/mind-force-trainer.cpp
  src/mind/mind-force-trainer.h
  src/mind/mind-mindcrafter.cpp
  src/mind/mind-mindcrafter.h
  src/mind/mind-mirror-master.cpp
  src/mind/mind-mirror-master.h
  src/mind/mind-ninja.cpp
  src/mind/mind-ninja.h
  src/mind/mind-numbers.h
Labels: refactor, Priority:HIGH

#2455 [Fix] 充填魔力吸収打撃でpvalが負値になる
  src/monster-attack/monster-eating.cpp
Labels: bug, Priority:HIGH

#2453 fix: スーパーレイの不自然な挙動を自然な感じにする
  src/spell-class/spells-mirror-master.cpp
  src/target/projection-path-calculator.h
Labels: enhancement, refactor

#2451 apply-magic.cpp/h をItemMagicApplier クラスとして再定義し、各アイテム種別へapply_magic() を適用していた箇所をファクトリ化した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/inventory-initializer.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-object.cpp
  src/market/bounty.cpp
  src/mind/mind-archer.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object-enchant/apply-magic.cpp
  src/object-enchant/apply-magic.h
  src/object-enchant/enchanter-factory.cpp
  src/object-enchant/enchanter-factory.h
  src/object-enchant/item-magic-applier.cpp
  src/object-enchant/item-magic-applier.h
  src/object-enchant/others/apply-magic-amulet.h
  src/object-enchant/others/apply-magic-lite.h
  src/object-enchant/others/apply-magic-others.h
  src/object-enchant/others/apply-magic-ring.h
  src/object-enchant/protector/abstract-protector-enchanter.h
  src/object-enchant/protector/apply-magic-boots.h
  src/object-enchant/protector/apply-magic-cloak.h
  src/object-enchant/protector/apply-magic-crown.h
  src/object-enchant/protector/apply-magic-dragon-armor.h
  src/object-enchant/protector/apply-magic-gloves.h
  src/object-enchant/protector/apply-magic-hard-armor.h
  src/object-enchant/protector/apply-magic-helm.h
  src/object-enchant/protector/apply-magic-shield.h
  src/object-enchant/protector/apply-magic-soft-armor.h
  src/object-enchant/weapon/apply-magic-arrow.h
  src/object-enchant/weapon/apply-magic-bow.h
  src/object-enchant/weapon/apply-magic-digging.h
  src/spell/spells-object.cpp
  src/store/store-util.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#2460 [Release] 3.0.0Alpha57
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#2467 English: change some messages, mostly related to the elementalists
  src/birth/history.cpp
  src/cmd-action/cmd-racial.cpp
  src/mind/mind-elementalist.cpp
Labels: bug, documentation
