Repository hengband/hengband, pull requests merged in 2022-12, with the labels that each got.

#2866 [Refactor] flavor_type 構造体の show_weapon/show_armour メンバを削除
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-util.cpp
  src/flavor/flavor-util.h
  src/flavor/named-item-describer.cpp
  src/flavor/tval-description-switcher.cpp
Labels: refactor

#2868 [Fix] ヘッダのインクルード漏れ
  src/store/rumor.cpp
  src/system/baseitem-info.cpp
  src/window/display-sub-windows.cpp
Labels: bug

#2874 wild.cpp において、使われていない型エイリアスを削除し、ファイルの中途半端な行で宣言されている構造体やファイルスコープグローバル変数の定義を上に寄せた
  src/floor/wild.cpp
Labels: refactor, Priority:MIDDLE

#2878 Avoid use of sprintf() in probed_monster_info(). That's part of …
  src/player-attack/attack-chaos-effect.cpp
  src/spell-kind/spells-sight.cpp
  src/spell-kind/spells-sight.h
Labels: refactor, Priority:MIDDLE

#2881 [Fix] mon-info.txt に出力される情報がおかしい
  src/wizard/monster-info-spoiler.cpp
Labels: bug

#2890 displey_koff() が呼ばれる前と関数本体の両方でベースアイテムIDの有無チェックをしていたので後者に統一した
  src/core/stuff-handler.cpp
  src/system/player-type-definition.h
  src/view/object-describer.cpp
  src/view/object-describer.h
  src/window/display-sub-windows.cpp
Labels: refactor, Priority:MIDDLE

#2895 [Refactor] describe_named_item
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-util.cpp
  src/flavor/flavor-util.h
  src/flavor/named-item-describer.cpp
  src/flavor/named-item-describer.h
  src/flavor/tval-description-switcher.cpp
  src/flavor/tval-description-switcher.h
Labels: refactor

#2896 [Refactor] describe_flavor (1/n)
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-util.h
  src/object-hook/hook-quest.cpp
  src/object-hook/hook-quest.h
  src/player/player-status.cpp
  src/player/player-status.h
Labels: refactor

#2899 弓を装備せずにキャラクタ情報を表示するとクラッシュする不具合を修正した
  src/view/display-player-middle.cpp
Labels: bug, refactor, Priority:Critical

#2903 弓を装備していない状態でアイテムを投げるとクラッシュする不具合を修正した
  src/combat/shoot.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/view/display-player-middle.cpp
Labels: bug, refactor, Priority:Critical

#2902 [Refactor] describe_flavor (2/n)
  src/flavor/flavor-describer.cpp
Labels: refactor

#2909 [Refactor] describe_flavor (3/n)
  src/flavor/flavor-describer.cpp
Labels: refactor

#2905 ベースアイテムへのポインタ/参照 をbii_ptr/baseitem に差し替えた
  src/artifact/random-art-generator.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/birth/game-play-initializer.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/visuals-reseter.cpp
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-util.cpp
  src/flavor/flavor-util.h
  src/flavor/object-flavor.cpp
  src/floor/floor-events.cpp
  src/info-reader/baseitem-reader.cpp
  src/info-reader/parse-error-types.h
  src/inventory/recharge-processor.cpp
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-items.cpp
  src/load/item/item-loader-base.cpp
  src/main/game-data-initializer.cpp
  src/market/building-craft-fix.cpp
  src/object-enchant/item-magic-applier.cpp
  src/object-enchant/others/apply-magic-amulet.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/object-enchant/others/apply-magic-ring.cpp
  src/object-use/zaprod-execution.cpp
  src/object/object-broken.cpp
  src/object/object-flags.cpp
  src/object/object-kind-hook.cpp
  src/object/object-value-calc.cpp
  src/object/object-value.cpp
  src/save/item-writer.cpp
  src/view/display-map.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/world/world-object.cpp
Labels: refactor, Priority:MIDDLE

#2924 [Refactor] describe_flavor (5/5)
  src/flavor/flavor-util.cpp
  src/flavor/flavor-util.h
  src/flavor/named-item-describer.cpp
  src/inventory/player-inventory.cpp
Labels: refactor

#2922 モンスターのフラグをまとめる（明かり・闇）
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/effect/effect-monster-resist-hurt.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/lore/magic-types-setter.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-force-trainer.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-lite.cpp
  src/monster-floor/monster-remover.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/race-brightness-flags.h
  src/monster-race/race-brightness-mask.cpp
  src/monster-race/race-brightness-mask.h
  src/monster/monster-list.cpp
  src/monster/monster-status-setter.cpp
  src/monster/monster-update.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-floor.cpp
  src/mspell/mspell-lite.cpp
  src/realm/realm-hissatsu.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-teleport.cpp
  src/system/dungeon-info.h
  src/system/monster-race-info.h
  src/view/display-lore-status.cpp
Labels: refactor

#2927 [Fix] angband_terms の配列外参照
  src/main.cpp
Labels: bug, Priority:HIGH

#2921 BasitemInfo::locale/chance の取り扱いを改善した
  src/info-reader/baseitem-reader.cpp
  src/knowledge/knowledge-items.cpp
  src/main/game-data-initializer.cpp
  src/system/baseitem-info.h
  src/wizard/items-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#2935 [Refactor] 画面に文字列を出力する関数のシグネチャ変更
  src/term/screen-processor.cpp
  src/term/screen-processor.h
  src/term/z-term.cpp
  src/term/z-term.h
Labels: refactor

#2930 [Refactor] get_ability_abbreviation 関数のインターフェース
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-util.cpp
  src/flavor/flavor-util.h
Labels: refactor

#2959 [Refactor] いくつかの関数の文字列引数の型を std::string_view に変更
  src/load/load-util.cpp
  src/load/load-util.h
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/term/screen-processor.cpp
  src/term/screen-processor.h
  src/view/display-lore.cpp
  src/view/display-lore.h
  src/wizard/monster-info-spoiler.cpp
Labels: refactor

#2958 [Refactor] display_player_one_line 関数のシグネチャ変更
  src/view/display-player.cpp
  src/view/display-util.cpp
  src/view/display-util.h
  src/view/status-first-page.cpp
Labels: refactor

#2937 [Refactor] get_inscription 関数のシグネチャを変更
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-util.cpp
  src/flavor/flavor-util.h
Labels: refactor

#2936 [Refactor] asking-player.cpp の関数群のシグネチャを変更
  src/core/asking-player.cpp
  src/core/asking-player.h
Labels: refactor

#2957 [Refactor] exe_spell 関数の戻り値の型を変更
  src/cmd-action/cmd-hissatsu.cpp
  src/cmd-action/cmd-spell.cpp
  src/knowledge/knowledge-experiences.cpp
  src/player/player-status.cpp
  src/realm/realm-arcane.cpp
  src/realm/realm-arcane.h
  src/realm/realm-chaos.cpp
  src/realm/realm-chaos.h
  src/realm/realm-craft.cpp
  src/realm/realm-craft.h
  src/realm/realm-crusade.cpp
  src/realm/realm-crusade.h
  src/realm/realm-death.cpp
  src/realm/realm-death.h
  src/realm/realm-demon.cpp
  src/realm/realm-demon.h
  src/realm/realm-hex.cpp
  src/realm/realm-hex.h
  src/realm/realm-hissatsu.cpp
  src/realm/realm-hissatsu.h
  src/realm/realm-life.cpp
  src/realm/realm-life.h
  src/realm/realm-nature.cpp
  src/realm/realm-nature.h
  src/realm/realm-song.cpp
  src/realm/realm-song.h
  src/realm/realm-sorcery.cpp
  src/realm/realm-sorcery.h
  src/realm/realm-trump.cpp
  src/realm/realm-trump.h
  src/spell-realm/spells-hex.cpp
  src/spell/spell-info.cpp
  src/spell/spells-execution.cpp
  src/spell/spells-execution.h
  src/window/display-sub-window-spells.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor

#2961 [Refactor] get_quantity 関数のシグネチャ変更
  src/cmd-item/cmd-destroy.cpp
  src/cmd-item/cmd-item.cpp
  src/core/asking-player.cpp
  src/core/asking-player.h
  src/spell-realm/spells-sorcery.cpp
  src/store/purchase-order.cpp
  src/store/sell-order.cpp
Labels: refactor

#2966 get_random_name() の戻り値をvoidからstd::string に変え、char * の引数を削除した
  src/artifact/random-art-characteristics.cpp
  src/artifact/random-art-characteristics.h
  src/artifact/random-art-generator.cpp
Labels: refactor, Priority:MIDDLE

#2968 [Fix] Workflow ファイルの actions/checkout のバージョン更新
  .github/workflows/build-with-autotools.yml
  .github/workflows/publish-spoiler-page.yml
  .github/workflows/pull-request-status-check.yml
Labels: bug

#2969 [Fix] CIで使用するコンパイラのバージョンをアップデート
  .github/workflows/build-with-autotools.yml
  .github/workflows/create-cache-for-ccache.yml
  .github/workflows/pull-request-status-check.yml
Labels: enhancement

#2978 [Feature] C++ 言語の標準バージョンを C++20 にする
  Hengband/Hengband/Hengband.vcxproj
  configure.ac
  m4/ax_cxx_compile_stdcxx.m4
  src/maid-x11.cpp
Labels: enhancement

#2975 Refactor cnv_stat() to avoid sprintf(). Does part of the work of …
  src/birth/birth-wizard.cpp
  src/player/player-status.cpp
  src/player/player-status.h
  src/view/display-birth.cpp
  src/view/display-player-stat-info.cpp
  src/view/display-player.cpp
  src/window/main-window-stat-poster.cpp
Labels: refactor, Priority:MIDDLE

#2979 [Refactor] shape_buffer のシグネチャ変更に伴うリファクタリング
  src/autopick/autopick-drawer.cpp
  src/birth/birth-select-realm.cpp
  src/birth/birth-wizard.cpp
  src/birth/history-generator.cpp
  src/cmd-action/cmd-mind.cpp
  src/cmd-action/cmd-racial.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/io/read-pref-file.cpp
  src/knowledge/knowledge-self.cpp
  src/market/building-craft-armor.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-sniper.cpp
  src/mind/mind-weaponsmith.cpp
  src/perception/identification.cpp
  src/player/process-death.cpp
  src/util/buffer-shaper.cpp
  src/util/buffer-shaper.h
  src/view/display-player.cpp
  src/view/display-util.cpp
  src/view/display-util.h
Labels: refactor

#2953 Refactor record-play-movie.cpp to avoid sprintf(). Does part of the …
  src/io/record-play-movie.cpp
  src/system/h-config.h
Labels: refactor, Priority:HIGH

#2985 [Fix] std::ranges::transform -> std::transform
  src/perception/identification.cpp
Labels: bug

#2986 [Fix] SIGKILL にシグナルハンドラを設定している
  src/io/signal-handlers.cpp
Labels: bug

#2980 [Fix/Refactor] 殺されたモンスター名を墓石に表示するコード
  src/player/process-death.cpp
Labels: bug, refactor

#2987 record-play-movie.cpp のコンパイルエラーを修正した
  src/io/record-play-movie.cpp
Labels: bug, Priority:HIGH

#2988 [Refactor] アイテムがランダムアーティファクトかどうかの判定にメソッドを使用する
  src/core/object-compressor.cpp
  src/flavor/named-item-describer.cpp
  src/floor/floor-streams.cpp
  src/io-dump/random-art-info-dumper.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object-enchant/weapon/melee-weapon-enchanter.cpp
  src/object/object-value-calc.cpp
  src/racial/racial-android.cpp
  src/save/item-writer.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-perception.cpp
  src/store/purchase-order.cpp
  src/store/service-checker.cpp
  src/util/object-sort.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#2989 [Fix] 巻物でアーティファクトを生成した時に徳が変化しない事がある
  src/artifact/random-art-generator.cpp
Labels: bug

#2992 shape_buffer で使用している is_kinsoku 関数を c_roff の折り返し表示にも適用する
  src/locale/japanese.cpp
  src/locale/japanese.h
  src/term/screen-processor.cpp
  src/util/buffer-shaper.cpp
Labels: enhancement

#2994 [Fix] モンスターを倒した時のメッセージがおかしい
  src/monster-floor/monster-death.cpp
  src/monster/monster-damage.cpp
Labels: bug

#2996 [Fix] モンスターの爆発でプレイヤーがダメージを受けない
  src/effect/effect-player-switcher.cpp
Labels: bug

#2997 [Refactor] ItemEntity::art_name の型/名称を変更
  src/artifact/random-art-generator.cpp
  src/flavor/named-item-describer.cpp
  src/load/old/item-loader-savefile50.cpp
  src/load/old/load-v1-5-0.cpp
  src/object-activation/activation-others.cpp
  src/save/item-writer.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: refactor

#2999 [Fix] 光源のスタックの挙動がおかしい
  src/object-enchant/others/apply-magic-lite.cpp
  src/store/store-util.cpp
Labels: bug

#3000 [Refactor] ItemEntity::inscription の型を変更
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-util.cpp
  src/cmd-item/cmd-item.cpp
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-util.cpp
  src/flavor/named-item-describer.cpp
  src/inventory/inventory-curse.cpp
  src/inventory/inventory-util.cpp
  src/inventory/recharge-processor.cpp
  src/io/input-key-requester.cpp
  src/load/old/item-loader-savefile50.cpp
  src/load/old/load-v1-5-0.cpp
  src/object/object-stack.cpp
  src/player/player-status-flags.cpp
  src/save/item-writer.cpp
  src/specific-object/monster-ball.cpp
  src/spell-kind/spells-enchant.cpp
  src/store/purchase-order.cpp
  src/store/sell-order.cpp
  src/store/store-util.cpp
  src/store/store.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: refactor

#3004 [Release] 3.0.0Alpha73
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3007 [Fix] Apple Clang で日本語版がコンパイルできない
  src/player/process-death.cpp
Labels: bug

#3009 [Refactor] MonsterEntity::nickname をquarkインデックスから std::string に変える
  src/action/mutation-execution.cpp
  src/cmd-action/cmd-pet.cpp
  src/effect/effect-monster.cpp
  src/effect/spells-effect-util.h
  src/floor/floor-changer.cpp
  src/floor/floor-leaver.cpp
  src/io-dump/character-dump.cpp
  src/load/old/load-v1-5-0.cpp
  src/load/old/monster-loader-savefile50.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-compaction.cpp
  src/monster/monster-describer.cpp
  src/monster/monster-processor.cpp
  src/save/monster-writer.cpp
  src/specific-object/monster-ball.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-genocide.cpp
  src/spell-kind/spells-pet.cpp
  src/spell-kind/spells-world.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/util/sort.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor

#3010 [Refactor] gf_colors に直接 std::string を持たせる
  src/io/interpret-pref-file.cpp
  src/main/game-data-initializer.cpp
  src/term/gameterm.cpp
  src/term/gameterm.h
Labels: refactor

#3011 マクロ関数update_local_illumination_aux() を普通の関数に展開した
  src/grid/grid.cpp
Labels: refactor, Priority:MIDDLE

#3013 [Refactor] モンスターボール発動のソースコード
  src/action/activation-execution.cpp
  src/specific-object/monster-ball.cpp
  src/specific-object/monster-ball.h
Labels: refactor

#3015 [Fix] モンスターの死体や骨が正しく表示されない
  src/flavor/tval-description-switcher.cpp
Labels: bug

#3012 get_rnd_line() の引数からchar *を削除し、返り値をstd::optional<std::string> に変えた
  src/artifact/random-art-characteristics.cpp
  src/flavor/object-flavor.cpp
  src/inventory/inventory-curse.cpp
  src/io/files-util.cpp
  src/io/files-util.h
  src/io/input-key-processor.cpp
  src/monster-floor/monster-move.cpp
  src/monster/monster-damage.cpp
  src/monster/monster-describer.cpp
  src/object-enchant/vorpal-weapon.cpp
  src/player/player-damage.cpp
  src/store/rumor.cpp
Labels: refactor, Priority:MIDDLE

#3016 [Refactor/Feature] format/strnfmt の機能整理/コード整形
  src/term/z-form.cpp
  src/view/display-lore.cpp
Labels: enhancement, refactor

#3018 monster_desc() の整形
  src/monster/monster-describer.cpp
Labels: refactor, Priority:MIDDLE

#3025 [Refactor] message_pain 関数を MessagePainDescriber で置き換える
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/combat/shoot.cpp
  src/effect/effect-monster.cpp
  src/monster/monster-describer.cpp
  src/monster/monster-describer.h
  src/monster/monster-pain-describer.cpp
  src/monster/monster-pain-describer.h
  src/object-use/throw-execution.cpp
Labels: refactor

#3024 flavor_init() と関連メソッドの移動
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/core/game-play.cpp
  src/flavor/object-flavor.cpp
  src/flavor/object-flavor.h
  src/item-info/flavor-initializer.cpp
  src/item-info/flavor-initializer.h
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
Labels: refactor, Priority:MIDDLE

#3031 [Fix] スポイラーページの自動生成に失敗する
  .github/workflows/publish-spoiler-page.yml
Labels: bug

#3030 [Fix] スナイパーの技の説明がおかしい (英語版)
  src/mind/mind-sniper.cpp
Labels: bug

#3034 [Fix] __attribute__((format)) による警告に対応
  src/action/activation-execution.cpp
  src/action/movement-execution.cpp
  src/action/mutation-execution.cpp
  src/artifact/random-art-generator.cpp
  src/birth/birth-wizard.cpp
  src/cmd-action/cmd-attack.cpp
  src/cmd-action/cmd-mind.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/player-processor.cpp
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-oldies.cpp
  src/effect/effect-player.cpp
  src/flavor/named-item-describer.cpp
  src/io/read-pref-file.h
  src/knowledge/knowledge-monsters.cpp
  src/load/info-loader.cpp
  src/load/load.cpp
  src/main/info-initializer.cpp
  src/market/bounty.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-mage.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster/monster-list.cpp
  src/mspell/mspell-special.cpp
  src/mspell/mspell-status.cpp
  src/object-activation/activation-switcher.cpp
  src/object-use/read/parchment-read-executor.cpp
  src/racial/mutation-racial-selector.cpp
  src/room/room-generator.cpp
  src/spell-kind/spells-world.cpp
  src/spell-realm/spells-sorcery.cpp
  src/spell/spells-summon.cpp
  src/status/shape-changer.cpp
  src/system/h-config.h
  src/term/z-form.h
  src/util/flag-group.h
  src/view/display-lore.cpp
  src/view/display-messages.cpp
  src/view/display-messages.h
  src/view/display-player-middle.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-messages.h
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spells.cpp
Labels: bug
