Repository hengband/hengband, pull requests merged in 2022-10, with the labels that each got.

#2677 [Feature] キャラクタダンプなどで長いモンスター名を折り返し表示する
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-quests.cpp
  src/knowledge/knowledge-uniques.cpp
  src/util/string-processor.cpp
  src/util/string-processor.h
  src/wizard/monster-info-spoiler.cpp
Labels: enhancement

#2659 decide_mosnter_speed() をオブジェクトメソッド「monster_type::get_riding_speed()」にした
  src/mind/monk-attack.cpp
  src/monster-race/monster-race.cpp
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-processor.cpp
  src/mspell/mspell-judgement.cpp
  src/player-status/player-speed.cpp
  src/spell-kind/spells-sight.cpp
  src/system/gamevalue.h
  src/system/monster-type-definition.cpp
  src/system/monster-type-definition.h
  src/view/display-lore.cpp
  src/view/display-player-middle.cpp
  src/window/main-window-stat-poster.cpp
  src/wizard/monster-info-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#2695 object_value() とobject_value_base() をObjectTypeのオブジェクトメソッドとして再定義した
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-item/cmd-destroy.cpp
  src/inventory/inventory-object.cpp
  src/load/store-loader.cpp
  src/object/object-value.cpp
  src/object/object-value.h
  src/spell-realm/spells-sorcery.cpp
  src/store/home.cpp
  src/store/pricing.cpp
  src/store/sell-order.cpp
  src/store/service-checker.cpp
  src/store/store-util.cpp
  src/store/store.cpp
  src/system/object-type-definition.cpp
  src/system/object-type-definition.h
  src/util/object-sort.cpp
  src/wizard/items-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#2690 生い立ちの日英を統合した (1)
  src/birth/history-generator.cpp
  src/birth/history.cpp
  src/birth/history.h
Labels: refactor, Priority:MIDDLE

#2696 k_info.txt から使われていないフィールドを除外した
  lib/edit/k_info.txt
  src/info-reader/kind-reader.cpp
  src/system/baseitem-info-definition.h
Labels: refactor, Priority:MIDDLE

#2285 ウィザードモード一部の数値入力にget_value()適用
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:HIGH

#2700 Release/3.0.0 alpha69
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#2708 現askfor() を廃止し、askfor_aux() に統合した
  src/core/asking-player.cpp
  src/core/asking-player.h
Labels: refactor, Priority:MIDDLE

#2710 decide_social_class() のシグネチャを、std::stringを返すように書き換えた
  src/birth/history-generator.cpp
Labels: refactor, Priority:MIDDLE

#2720 ウィザードモードの全回復で減速と恐怖にも対応した
  src/wizard/wizard-special-process.cpp
Labels: bug, refactor

#2723 クラスによって生い立ちが一部欠ける場合がある事象を修正した
  src/birth/history.cpp
Labels: bug, Priority:MIDDLE

#2726 BadStatusSetter のメソッド名を調整した
  src/blue-magic/blue-magic-caster.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-item/cmd-eat.cpp
  src/inventory/inventory-curse.cpp
  src/mind/mind-mindcrafter.cpp
  src/monster-attack/monster-attack-status.cpp
  src/mutation/mutation-processor.cpp
  src/object-activation/activation-others.cpp
  src/object-activation/activation-resistance.cpp
  src/object-activation/activation-switcher.cpp
  src/object-use/quaff/quaff-effects.cpp
  src/racial/racial-switcher.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-demon.cpp
  src/realm/realm-hissatsu.cpp
  src/realm/realm-nature.cpp
  src/realm/realm-song.cpp
  src/specific-object/blade-turner.cpp
  src/spell/spells-staff-only.cpp
  src/spell/spells-status.cpp
  src/status/bad-status-setter.cpp
  src/status/bad-status-setter.h
  src/status/shape-changer.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#2594 Readme translations
  readme-eng.md
  readme.md
  src/ang_eng.rc
  src/view/display-util.cpp
Labels: documentation

#2730 町の名前を分かりやすくし、使われていない町を削除した
  lib/edit/Makefile.am
  lib/edit/TownDefinitionList.txt
  lib/edit/TownPreferences.txt
  lib/edit/WildernessDefinition.txt
  lib/edit/towns/01_Outpost_Full.txt
  lib/edit/towns/01_Outpost_Lite.txt
  lib/edit/towns/01_Outpost_OnlyAngband.txt
  lib/edit/towns/02_Telmora.txt
  lib/edit/towns/03_Morivant.txt
  lib/edit/towns/04_Angwil.txt
  lib/edit/towns/05_Zul.txt
  lib/edit/towns/06_Rlyeh_Obsoleted.txt
Labels: refactor, Priority:MIDDLE

#2736 [Fix] configure の --with-setgid オプションが正しく機能しない
  configure.ac
Labels: bug

#2735 ObjectType::fixed_artifact_idx とFixedArtifactId の比較をis_specific_artifact() でメソッド化した
  src/action/movement-execution.cpp
  src/action/racial-execution.cpp
  src/artifact/fixed-art-generator.cpp
  src/cmd-action/cmd-attack.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-item/cmd-equipment.cpp
  src/combat/shoot.cpp
  src/combat/slaying.cpp
  src/dungeon/quest.cpp
  src/inventory/inventory-curse.cpp
  src/inventory/player-inventory.cpp
  src/load/old/item-loader-savefile50.cpp
  src/market/building-craft-fix.cpp
  src/market/building-craft-weapon.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object-activation/activation-others.cpp
  src/object-enchant/vorpal-weapon.cpp
  src/object-use/read/read-executor-factory.cpp
  src/object-use/throw-execution.cpp
  src/object/object-info.cpp
  src/perception/identification.cpp
  src/player-attack/attack-chaos-effect.cpp
  src/player-attack/blood-sucking-processor.cpp
  src/player-attack/player-attack.cpp
  src/player-info/alignment.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/realm/realm-hissatsu.cpp
  src/specific-object/bloody-moon.cpp
  src/specific-object/death-crimson.cpp
  src/specific-object/muramasa.cpp
  src/system/object-type-definition.cpp
  src/system/object-type-definition.h
  src/view/status-first-page.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor, Priority:MIDDLE

#2743 jump_floor() 関数を floor_leaver.cpp/h からwizard-special-process.cpp/h に移した
  src/floor/floor-leaver.cpp
  src/floor/floor-leaver.h
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#2715 store_table近辺リファクタリング
  src/market/building-initializer.cpp
  src/store/articles-on-sale.cpp
  src/store/articles-on-sale.h
Labels: refactor

#2750 [Release] 3.0.0Alpha70
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release
