Repository hengband/hengband, pull requests merged in 2022-06, with the labels that each got.

#2525 [Fix]暗黒耐性判定フラグに暗黒免疫の論理和を付加し、暗闇の巻物で吸血鬼が盲目になるエンバグを修正。
  src/player/player-status-flags.cpp
Labels: bug

#2534 Release/3.0.0 alpha61
  doxygen/Hengband.doxyfile
  lib/edit/t0000002.txt
  src/load/info-loader.cpp
  src/player/player-status-flags.cpp
  src/system/angband-version.h
Labels: release

#2533 [Release] 3.0.0Alpha61
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#2545 English: fix typo in smithing menus ("gauntlets of Genji")
  src/smith/smith-tables.cpp
Labels: bug

#2539 [Fix] chest_traps 配列外アクセス
  src/action/open-util.cpp
  src/player/player-move.cpp
Labels: bug

#2544 [Fix] 一部の魔法で smart_learn が正常に機能していない
  src/mspell/mspell-data.cpp
Labels: bug

#2551 Release/3.0.0 alpha62
  doxygen/Hengband.doxyfile
  src/action/open-util.cpp
  src/gcc-wrap
  src/locale/english.cpp
  src/mspell/mspell-data.cpp
  src/player/player-move.cpp
  src/smith/smith-tables.cpp
  src/system/angband-version.h
Labels: release

#2554 GCU: remove assumed window width of 80 columns in wipe hook
  src/main-gcu.cpp
Labels: bug

#2553 Preprocess out definitions for plural_aux() and is_a_vowel() when JP …
  src/locale/english.cpp
Labels: bug

#2530 PlayerType::fast フィールド変数をPlayerAcceleration クラスでカプセル化した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/blue-magic/blue-magic-caster.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/cmd-item/cmd-zaprod.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/effect/effect-player-oldies.cpp
  src/load/player-info-loader.cpp
  src/mind/mind-mindcrafter.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/mspell/mspell-dispel.cpp
  src/mutation/mutation-processor.cpp
  src/object-activation/activation-switcher.cpp
  src/object-use/quaff/quaff-effects.cpp
  src/player/player-status.cpp
  src/realm/realm-craft.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-death.cpp
  src/realm/realm-life.cpp
  src/realm/realm-song.cpp
  src/realm/realm-sorcery.cpp
  src/save/player-writer.cpp
  src/spell/spells-status.cpp
  src/status/buff-setter.cpp
  src/status/buff-setter.h
  src/system/player-type-definition.h
  src/timed-effect/player-acceleration.cpp
  src/timed-effect/player-acceleration.h
  src/timed-effect/timed-effects.cpp
  src/timed-effect/timed-effects.h
Labels: refactor, Priority:MIDDLE
