Repository hengband/hengband, pull requests merged in 2023-05, with the labels that each got.

#3226 Include <sstream> since prepare_movie_hooks() uses std::stringstream
  src/io/record-play-movie.cpp
Labels: bug, Priority:MIDDLE

#3220 ItemEntity クラスにget_ego() メソッドを追加した
  src/action/activation-execution.cpp
  src/artifact/artifact-info.cpp
  src/autopick/autopick-entry.cpp
  src/flavor/flavor-util.cpp
  src/flavor/named-item-describer.cpp
  src/floor/floor-events.cpp
  src/info-reader/ego-reader.cpp
  src/load/old/load-v1-5-0.cpp
  src/object-enchant/object-ego.cpp
  src/object-enchant/object-ego.h
  src/object-enchant/weapon/apply-magic-sword.cpp
  src/object/object-flags.cpp
  src/object/object-value-calc.cpp
  src/object/object-value.cpp
  src/racial/racial-android.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/wizard/wizard-item-modifier.cpp
Labels: refactor, Priority:MIDDLE

#3227 path_build() に関連する関数の入出力をpath に変えた
  src/io/files-util.cpp
  src/io/files-util.h
  src/main-win.cpp
  src/main-win/main-win-file-utils.cpp
  src/main-win/main-win-file-utils.h
  src/main-win/main-win-utils.cpp
  src/main-win/main-win-utils.h
  src/main.cpp
  src/main/angband-initializer.cpp
  src/main/angband-initializer.h
  src/system/h-config.h
Labels: refactor, Priority:MIDDLE

#3232 [Release] 3.0.0Alpha79
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3238 main-win.cpp で、prefファイルの読み書きが正常に行われない事象を修正した
  src/main-win.cpp
Labels: bug, Priority:HIGH

#3240 自動拾い設定ファイルへの書き込み時に(null)が出力される事象を修正した
  src/autopick/autopick-reader-writer.cpp
Labels: bug, Priority:HIGH

#3242 [Release] 3.0.0Alpha80
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3235 mysqrt() を削除し、std::sqrt に差し替えた
  src/monster/monster-list.cpp
  src/term/z-util.cpp
  src/term/z-util.h
Labels: refactor, Priority:MIDDLE

#3234 ItemEntity にget_artifact() メソッドを追加し、ArtifactsInfo から取得していた処理を差し替えた
  src/action/activation-execution.cpp
  src/artifact/artifact-info.cpp
  src/artifact/fixed-art-generator.cpp
  src/flavor/flavor-util.cpp
  src/flavor/named-item-describer.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-object.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/grid/object-placer.cpp
  src/load/old/load-v1-5-0.cpp
  src/object-enchant/item-magic-applier.cpp
  src/object/object-flags.cpp
  src/object/object-value-calc.cpp
  src/object/object-value.cpp
  src/perception/identification.cpp
  src/racial/racial-android.cpp
  src/spell-kind/spells-floor.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/wizard/artifact-analyzer.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor, Priority:MIDDLE

#3249 misc.txt を廃止した
  lib/edit/WildernessDefinition.txt
  lib/edit/misc.txt
  src/floor/fixed-map-generator.cpp
  src/floor/wild.cpp
  src/floor/wild.h
  src/main/angband-initializer.cpp
  src/main/info-initializer.cpp
  src/main/info-initializer.h
  src/world/world.h
Labels: refactor, Priority:MIDDLE

#3251 [Refactor] 古いデバッグ用セーブファイルの削除
  src/main/angband-initializer.cpp
Labels: refactor

#3254 picktypeで保護されるはずのアイテムが破壊される事象を修正した
  src/autopick/autopick-matcher.cpp
Labels: bug, Priority:HIGH

#3255 str_split() の戻り値をコピーで受け取っていたので参照に受け変えた
  src/main/info-initializer.cpp
Labels: refactor, Priority:MIDDLE

#3252 [Fix] デバッグセーブ用ディレクトリが存在しない場合にクラッシュする
  src/main/angband-initializer.cpp
Labels: bug

#3259 [Release] 3.0.0Alpha81
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3260 Release/3.0.0 alpha81
  doxygen/Hengband.doxyfile
  lib/edit/Makefile.am
  lib/edit/WildernessDefinition.txt
  lib/edit/misc.txt
  src/action/activation-execution.cpp
  src/artifact/artifact-info.cpp
  src/artifact/fixed-art-generator.cpp
  src/autopick/autopick-matcher.cpp
  src/flavor/flavor-util.cpp
  src/flavor/named-item-describer.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-object.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/floor/wild.cpp
  src/floor/wild.h
  src/grid/object-placer.cpp
  src/load/old/load-v1-5-0.cpp
  src/main/angband-initializer.cpp
  src/main/info-initializer.cpp
  src/main/info-initializer.h
  src/monster/monster-list.cpp
  src/object-enchant/item-magic-applier.cpp
  src/object/object-flags.cpp
  src/object/object-value-calc.cpp
  src/object/object-value.cpp
  src/perception/identification.cpp
  src/racial/racial-android.cpp
  src/spell-kind/spells-floor.cpp
  src/system/angband-version.h
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/term/z-util.cpp
  src/term/z-util.h
  src/wizard/artifact-analyzer.cpp
  src/wizard/wizard-item-modifier.cpp
  src/world/world.h
Labels: release

#3244 8ビットカラー環境のWindowsはもう絶滅したと判断し、モニタの色数チェックを除去した
  src/main-win.cpp
Labels: refactor, Priority:MIDDLE

#3266 自動拾いで兜を拾えない問題を修正した
  src/autopick/autopick-matcher.cpp
Labels: bug, Priority:MIDDLE

#3268 特定パターンの文字列を持ったアイテムを店で売るとクラッシュする不具合を解消した
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-describer.h
  src/knowledge/knowledge-inventory.cpp
  src/view/display-store.cpp
Labels: bug, Priority:Critical

#3271 [Release] 3.0.0Alpha82
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3272 Release/3.0.0 alpha82
  doxygen/Hengband.doxyfile
  hengband.spec
  src/autopick/autopick-matcher.cpp
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-describer.h
  src/knowledge/knowledge-inventory.cpp
  src/main-win.cpp
  src/system/angband-version.h
  src/view/display-store.cpp
Labels: release

#3274 [Fix] スポイラーのオブジェクト一覧(obj-desc.txt)の内容がおかしい
  src/wizard/items-spoiler.cpp
Labels: bug, refactor

#3276 [Refactor] #3275 jverb関数のシグネチャ改善
  src/cmd-action/cmd-spell.cpp
  src/locale/japanese.cpp
  src/locale/japanese.h
  src/lore/lore-util.h
  src/view/display-lore-attacks.cpp
  src/view/display-lore-status.cpp
  src/view/display-lore.cpp
Labels: refactor

#3245 path_build() のシグネチャを変える準備 その3
  src/cmd-io/cmd-process-screen.cpp
  src/floor/floor-save.cpp
  src/io/files-util.cpp
  src/io/files-util.h
  src/load/floor-loader.cpp
  src/load/load.cpp
  src/main-win.cpp
  src/main-win/graphics-win.cpp
  src/main-win/graphics-win.h
  src/main-win/main-win-cfg-reader.cpp
  src/main-win/main-win-cfg-reader.h
  src/main-win/main-win-music.cpp
  src/main-win/main-win-music.h
  src/main-win/main-win-sound.cpp
  src/main-win/main-win-sound.h
  src/main-win/main-win-utils.cpp
  src/main-win/main-win-utils.h
  src/main/angband-initializer.cpp
  src/player/process-name.cpp
  src/save/floor-writer.cpp
  src/save/save.cpp
  src/util/angband-files.cpp
Labels: refactor, Priority:MIDDLE

#3246 path_build() のシグネチャを変える準備 その4
  src/main-win.cpp
  src/main-win/graphics-win.cpp
  src/main-win/graphics-win.h
  src/main-win/main-win-bg.cpp
  src/main-win/main-win-bg.h
  src/main-win/main-win-utils.cpp
  src/main-win/main-win-utils.h
Labels: refactor, Priority:MIDDLE

#3278 path_build() の返り値をvoid からpath に差し替えた
  src/autopick/autopick-reader-writer.cpp
  src/autopick/autopick-registry.cpp
  src/cmd-io/cmd-diary.cpp
  src/cmd-io/cmd-dump.cpp
  src/cmd-io/cmd-macro.cpp
  src/cmd-io/cmd-process-screen.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/game-closer.cpp
  src/core/game-play.cpp
  src/core/scores.cpp
  src/core/show-file.cpp
  src/info-reader/fixed-map-parser.cpp
  src/io-dump/random-art-info-dumper.cpp
  src/io/files-util.cpp
  src/io/inet.cpp
  src/io/read-pref-file.cpp
  src/io/record-play-movie.cpp
  src/io/write-diary.cpp
  src/main-gcu.cpp
  src/main-win.cpp
  src/main-win/graphics-win.cpp
  src/main-win/main-win-cfg-reader.cpp
  src/main-win/main-win-file-utils.cpp
  src/main-win/main-win-music.cpp
  src/main-win/main-win-sound.cpp
  src/main-x11.cpp
  src/main.cpp
  src/main/angband-initializer.cpp
  src/main/info-initializer.cpp
  src/market/building-initializer.cpp
  src/object-use/read/parchment-read-executor.cpp
  src/player/process-name.cpp
  src/util/angband-files.cpp
  src/util/angband-files.h
  src/view/display-scores.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/monster-info-spoiler.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#3280 背景画像設定をiniファイルへ書き込む際の判定が反転していた事象を修正した
  src/main-win.cpp
Labels: bug, Priority:MIDDLE

#3285 autopick-key-flag-process.h に定義されていた関数マクロを削除し、普通の関数に置き換えた
  src/autopick/autopick-editor-util.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-key-flag-process.h
  src/autopick/autopick-util.cpp
  src/autopick/autopick-util.h
Labels: refactor, Priority:MIDDLE

#3279 [Feature] 現在の知識の確認画面および記録の設定画面をウィンドウ中央に表示する
  src/cmd-io/cmd-diary.cpp
  src/cmd-io/cmd-knowledge.cpp
  src/io/record-play-movie.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
Labels: enhancement

#3289 画面再描画フラグの更新準備 コピペコードの低減
  src/floor/floor-events.cpp
  src/mind/mind-sniper.cpp
  src/mind/mind-weaponsmith.cpp
  src/status/action-setter.cpp
  src/status/sight-setter.cpp
Labels: refactor, Priority:MIDDLE

#3295 fd_hoge() の引数をstring_view からpath に変えた
  src/cmd-io/cmd-diary.cpp
  src/core/game-closer.cpp
  src/core/game-play.cpp
  src/core/scores.cpp
  src/floor/floor-save.cpp
  src/io/files-util.cpp
  src/io/record-play-movie.cpp
  src/io/record-play-movie.h
  src/load/floor-loader.cpp
  src/load/load.cpp
  src/main-win.cpp
  src/main-x11.cpp
  src/main/angband-initializer.cpp
  src/save/floor-writer.cpp
  src/save/save.cpp
  src/util/angband-files.cpp
  src/util/angband-files.h
Labels: refactor, Priority:MIDDLE

#3294 [Fix] ペットのブレスがプレイヤーを巻き込む
  src/mspell/mspell-judgement.cpp
Labels: bug

#3300 town_type の調整
  src/cmd-building/cmd-building.cpp
  src/cmd-io/cmd-dump.cpp
  src/core/game-play.cpp
  src/core/turn-compensator.cpp
  src/core/window-redrawer.cpp
  src/floor/floor-town.h
  src/floor/floor-util.cpp
  src/floor/floor-util.h
  src/floor/wild.cpp
  src/info-reader/general-parser.cpp
  src/io-dump/character-dump.cpp
  src/io-dump/random-art-info-dumper.cpp
  src/knowledge/knowledge-inventory.cpp
  src/knowledge/knowledge-self.cpp
  src/load/store-loader.cpp
  src/market/building-initializer.cpp
  src/player/process-death.cpp
  src/save/save.cpp
  src/spell-kind/spells-world.cpp
  src/store/black-market.cpp
  src/store/cmd-store.cpp
  src/store/home.cpp
  src/store/rumor.cpp
  src/store/store.cpp
  src/system/building-type-definition.cpp
  src/system/building-type-definition.h
  src/target/target-describer.cpp
  src/view/display-player.cpp
Labels: refactor, Priority:MIDDLE

#3301 [Release] 3.0.0Alpha83
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3305 init_alloc() をinit_monsters_alloc() とinit_items_alloc() に分割した
  src/main/angband-initializer.cpp
  src/main/game-data-initializer.cpp
  src/main/game-data-initializer.h
Labels: refactor, Priority:MIDDLE

#3306 BASE_STATUS 型エイリアスを削除した
  src/action/racial-execution.cpp
  src/birth/birth-stat.cpp
  src/birth/quick-start.h
  src/spell/spells-status.cpp
  src/status/base-status.cpp
  src/system/h-type.h
  src/system/player-type-definition.h
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#3303 羊皮紙を追加した
  lib/edit/BaseitemDefinitions.txt
  lib/file/books/book-000_en.txt
  lib/file/books/book-000_jp.txt
  lib/file/books/book-001_en.txt
  lib/file/books/book-001_jp.txt
  lib/file/books/book-002_en.txt
  lib/file/books/book-002_jp.txt
  lib/file/books/book-003_en.txt
  lib/file/books/book-003_jp.txt
  lib/file/books/book-004_en.txt
  lib/file/books/book-004_jp.txt
  lib/file/books/book-005_en.txt
  lib/file/books/book-005_jp.txt
  lib/file/books/book-006_en.txt
  lib/file/books/book-006_jp.txt
  lib/file/books/book-007_en.txt
  lib/file/books/book-007_jp.txt
  src/object-use/read/parchment-read-executor.cpp
  src/wizard/tval-descriptions-table.cpp
Labels: enhancement, Priority:MIDDLE

#3309 OBJECT_SUBTYPE_VALUE 型エイリアスを削除した
  src/cmd-action/cmd-spell.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/cmd-item/cmd-usestaff.h
  src/cmd-item/cmd-zaprod.cpp
  src/cmd-item/cmd-zaprod.h
  src/cmd-item/cmd-zapwand.cpp
  src/cmd-item/cmd-zapwand.h
  src/mind/mind-archer.cpp
  src/mind/mind-chaos-warrior.cpp
  src/monster-floor/monster-death-util.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/system/h-type.h
  src/system/system-variables.cpp
  src/system/system-variables.h
Labels: refactor, Priority:MIDDLE

#3311 [Refactor] rand_choice()の実装とそれによるリファクタリング
  src/flavor/object-flavor.cpp
  src/floor/floor-changer.cpp
  src/grid/door.cpp
  src/grid/feature.cpp
  src/grid/grid.cpp
  src/grid/trap.cpp
  src/market/building-craft-fix.cpp
  src/melee/melee-spell.cpp
  src/melee/monster-attack-monster.cpp
  src/mind/monk-attack.cpp
  src/monster-attack/monster-attack-describer.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-floor/special-death-switcher.cpp
  src/monster-race/monster-race-hook.cpp
  src/mspell/mspell-selector.cpp
  src/object-enchant/object-boost.cpp
  src/object-enchant/object-ego.cpp
  src/object/object-kind-hook.cpp
  src/object/warning.cpp
  src/player/eldritch-horror.cpp
  src/player/player-damage.cpp
  src/room/cave-filler.cpp
  src/room/rooms-builder.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-grid.cpp
  src/spell-kind/spells-random.cpp
  src/store/say-comments.cpp
  src/store/store.cpp
  src/term/gameterm.cpp
  src/term/z-rand.h
  src/view/display-map.cpp
  src/view/display-map.h
Labels: refactor

#3316 [Fix] 記録の表示でゲームの乱数シードを消費してしまう
  src/cmd-io/cmd-diary.cpp
Labels: bug

#3317 Update the version and macros in the spec file.
  hengband.spec
Labels: release

#3320 macOS 環境で正しくlib/file/books/ を含むリポジトリをコンパイルできるようにした
  configure.ac
  lib/edit/BaseitemDefinitions.txt
  lib/file/Makefile.am
  lib/file/books/Makefile.am
Labels: bug, Priority:MIDDLE

#3322 [Refactor] switch (randint1(x)) のパターンを rand_choice で書き換え
  src/artifact/random-art-misc.cpp
  src/avatar/avatar.cpp
  src/cmd-item/cmd-zapwand.cpp
  src/effect/effect-player-resist-hurt.cpp
  src/mind/mind-chaos-warrior.cpp
  src/monster-attack/monster-attack-describer.cpp
  src/object-enchant/object-boost.cpp
  src/realm/realm-arcane.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-equipment.cpp
  src/term/gameterm.cpp
  src/view/display-map.cpp
Labels: refactor

#3323 [Refactor] ブラッディムーン発動時のフラグ選択に rand_choice を使用する
  src/specific-object/bloody-moon.cpp
Labels: refactor

#3332 take_hit_mon() 及び関連する関数群の引数をconcptr からstring_view に変えた
  src/effect/effect-player-resist-hurt.cpp
  src/effect/effect-player-resist-hurt.h
  src/player/player-damage.cpp
  src/player/player-damage.h
Labels: refactor, Priority:MIDDLE

#3331 PlayerRace/PlayerClass にだけ依存する処理をそれぞれのオブジェクトメソッドに繰り込んだ
  src/cmd-io/cmd-diary.cpp
  src/mspell/summon-checker.cpp
  src/player-base/player-class.cpp
  src/player-base/player-class.h
  src/player-base/player-race.cpp
  src/player-base/player-race.h
  src/player-info/race-info.cpp
  src/player-info/race-info.h
Labels: refactor, Priority:MIDDLE

#3324 [Refactor] *鑑定*時のサブウィンドウ更新処理
  src/spell-kind/spells-perception.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#3328 アビリティスコア減少処理をdecrease_ability_*() にまとめた
  src/effect/effect-player-resist-hurt.cpp
  src/monster-attack/monster-attack-status.cpp
  src/monster-attack/monster-attack-status.h
  src/monster-attack/monster-attack-switcher.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
Labels: refactor, Priority:MIDDLE

#3337 呼ぶ必要のない.data() を削除した
  src/birth/auto-roller.cpp
  src/birth/birth-select-realm.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-io/cmd-autopick.cpp
  src/core/visuals-reseter.cpp
  src/hpmp/hp-mp-processor.cpp
  src/inventory/inventory-curse.cpp
  src/io/input-key-requester.cpp
  src/io/read-pref-file.cpp
  src/main/angband-initializer.cpp
  src/market/building-craft-weapon.cpp
  src/mspell/mspell-special.cpp
  src/player/patron.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-genocide.cpp
  src/spell-kind/spells-sight.cpp
  src/view/display-characteristic.cpp
  src/view/display-lore.cpp
  src/view/display-store.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-stat-poster.cpp
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-player-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#3327 MonsterRaceInfo にだけ依存する関数をメソッドに移した
  src/avatar/avatar-changer.cpp
  src/cmd-action/cmd-attack.cpp
  src/combat/shoot.cpp
  src/dungeon/quest.cpp
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-evil.cpp
  src/effect/effect-monster-psi.cpp
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-monster-util.cpp
  src/effect/effect-monster-util.h
  src/effect/effect-monster.cpp
  src/info-reader/race-reader.cpp
  src/lore/combat-types-setter.cpp
  src/lore/lore-calculator.cpp
  src/lore/lore-store.cpp
  src/market/arena.cpp
  src/market/bounty.cpp
  src/melee/melee-postprocess.cpp
  src/melee/melee-postprocess.h
  src/melee/monster-attack-monster.cpp
  src/mind/mind-samurai.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-death.h
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-damage.cpp
  src/monster/monster-damage.h
  src/monster/monster-list.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/mspell/mspell-special.cpp
  src/mspell/summon-checker.cpp
  src/object-use/throw-execution.cpp
  src/object/warning.cpp
  src/player-attack/blood-sucking-processor.cpp
  src/player-attack/player-attack.cpp
  src/realm/realm-hissatsu.cpp
  src/spell-kind/spells-detection.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/view/display-lore-attacks.cpp
  src/view/display-lore.cpp
  src/view/display-monster-status.cpp
Labels: refactor, Priority:MIDDLE

#3350 [Release] 3.0.0Alpha84
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3355 string 型にnullptrを代入していた潜在的不具合を解消した
  src/effect/effect-monster-charm.cpp
Labels: bug, Priority:LOW

#3347 UNIX系のユーザIDをPlayerType からUnixUserIds に分離した
  src/Makefile.am
  src/birth/game-play-initializer.cpp
  src/core/game-closer.cpp
  src/core/scores.cpp
  src/floor/floor-save.cpp
  src/io/files-util.cpp
  src/io/uid-checker.cpp
  src/io/uid-checker.h
  src/load/floor-loader.cpp
  src/load/load.cpp
  src/maid-x11.cpp
  src/main-unix/unix-user-ids.cpp
  src/main-unix/unix-user-ids.h
  src/main-unix/x11-gamma-builder.cpp
  src/main-unix/x11-gamma-builder.h
  src/main-unix/x11-type-string.cpp
  src/main-unix/x11-type-string.h
  src/main-x11.cpp
  src/main.cpp
  src/main/angband-initializer.cpp
  src/player/process-name.cpp
  src/save/floor-writer.cpp
  src/save/save.cpp
  src/system/player-type-definition.h
Labels: refactor, Priority:MIDDLE

#3340 sniper_data_type を構造体からクラスへ変更し、メソッドを追加した
  src/cmd-action/cmd-shoot.cpp
  src/combat/shoot.cpp
  src/core/player-processor.cpp
  src/io/input-key-processor.cpp
  src/load/player-class-specific-data-loader.cpp
  src/load/player-class-specific-data-loader.h
  src/load/player-info-loader.cpp
  src/mind/mind-sniper.cpp
  src/monster/monster-update.cpp
  src/player-base/player-class.cpp
  src/player-info/class-specific-data.h
  src/player-info/sniper-data-type.h
  src/player/player-status.cpp
  src/save/player-class-specific-data-writer.cpp
  src/save/player-class-specific-data-writer.h
  src/window/main-window-stat-poster.cpp
Labels: refactor, Priority:MIDDLE

#3345 ウィザードコマンドによる帰還処理を日記に書くのではなくメッセージウィンドウに表示するよう差し替えた
  src/action/mutation-execution.cpp
  src/birth/character-builder.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-action/cmd-others.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-building/cmd-inn.cpp
  src/cmd-io/cmd-diary.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-io/cmd-save.cpp
  src/core/game-closer.cpp
  src/core/game-play.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest.cpp
  src/effect/effect-monster.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/pattern-walk.cpp
  src/grid/trap.cpp
  src/io/input-key-processor.cpp
  src/io/signal-handlers.cpp
  src/io/write-diary.cpp
  src/io/write-diary.h
  src/main-win.cpp
  src/monster-floor/monster-death.cpp
  src/monster/monster-compaction.cpp
  src/monster/monster-damage.cpp
  src/monster/monster-processor.cpp
  src/perception/object-perception.cpp
  src/player/patron.cpp
  src/player/player-damage.cpp
  src/player/player-status.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-enchant.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-genocide.cpp
  src/spell-kind/spells-perception.cpp
  src/spell-kind/spells-pet.cpp
  src/spell-kind/spells-world.cpp
  src/store/purchase-order.cpp
  src/store/sell-order.cpp
  src/wizard/wizard-messages.cpp
  src/wizard/wizard-messages.h
  src/wizard/wizard-special-process.cpp
  src/world/world-movement-processor.cpp
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE
