Repository hengband/hengband, pull requests merged in 2023-02, with the labels that each got.

#3089 [Feature] 2バイト文字を考慮しつつ部分文字列を切り出す関数
  src/knowledge/knowledge-inventory.cpp
  src/util/string-processor.cpp
  src/util/string-processor.h
Labels: enhancement

#3097 [Fix] 航海士『ナミ』の経験値が0になっていたので修正。
  lib/edit/MonsterRaceDefinitions.txt
Labels: bug

#3100 Release/3.0.0 alpha76
  doxygen/Hengband.doxyfile
  lib/edit/MonsterRaceDefinitions.txt
  src/knowledge/knowledge-inventory.cpp
  src/system/angband-version.h
  src/util/string-processor.cpp
  src/util/string-processor.h
  src/window/main-window-left-frame.cpp
Labels: release

#3099 [Release] 3.0.0Alpha76
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3108 [Feature] トラップ感知のロッドをアリーナの報酬に追加する
  src/market/arena-info-table.cpp
Labels: enhancement

#3104 [Feature] PDSMに時間逆転の耐性を追加する
  lib/edit/BaseitemDefinitions.txt
Labels: enhancement

#3112 [Fix] 巻物で生成したアーティファクトにランダムで名付けるとおかしな名称になる
  src/artifact/random-art-generator.cpp
Labels: bug

#3114 [Fix] サブウィンドウにモンスターの思い出を表示すると重くなる
  src/monster/monster-processor-util.cpp
Labels: bug

#3119 [Fix] 秩序の指輪の命中補正の表記方法
  src/flavor/flavor-describer.cpp
Labels: enhancement

#3117 [Fix] shape_buffer関数の文字列分割位置がおかしい
  src/util/buffer-shaper.cpp
Labels: bug

#3115 [Feature] カオスと破邪の4冊目の魔法書の出現階層を90Fに変更する
  lib/edit/BaseitemDefinitions.txt
Labels: enhancement

#3116 [Fix] 床置きした固定アーティファクトが階移動で消滅する
  src/floor/floor-object.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object-enchant/item-magic-applier.cpp
Labels: bug

#3125 Release/3.0.0 alpha77
  doxygen/Hengband.doxyfile
  lib/edit/BaseitemDefinitions.txt
  src/artifact/random-art-generator.cpp
  src/flavor/flavor-describer.cpp
  src/floor/floor-object.cpp
  src/market/arena-info-table.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/monster/monster-processor-util.cpp
  src/object-enchant/item-magic-applier.cpp
  src/system/angband-version.h
  src/util/buffer-shaper.cpp
  src/view/display-lore-status.cpp
Labels: release

#3124 [Release] 3.0.0Alpha77
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3127 [Fix] ランダムアーティファクトが床に落ちるとクラッシュする
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/autopick/autopick-registry.cpp
  src/core/object-compressor.cpp
  src/effect/effect-item.cpp
  src/flavor/named-item-describer.cpp
  src/floor/floor-events.cpp
  src/floor/floor-object.cpp
  src/grid/stair.cpp
  src/inventory/inventory-damage.cpp
  src/knowledge/knowledge-inventory.cpp
  src/market/building-craft-fix.cpp
  src/mind/mind-priest.cpp
  src/monster-attack/monster-eating.cpp
  src/monster-floor/monster-object.cpp
  src/object-enchant/object-curse.cpp
  src/object-hook/hook-expendable.cpp
  src/perception/simple-perception.cpp
  src/racial/racial-android.cpp
  src/realm/realm-hex.cpp
  src/smith/object-smith.cpp
  src/smith/smith-info.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-enchant.cpp
  src/spell-kind/spells-equipment.cpp
  src/spell-kind/spells-perception.cpp
  src/spell-realm/spells-craft.cpp
  src/spell/spells-object.cpp
  src/store/service-checker.cpp
  src/store/store-util.cpp
  src/store/store.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/wizard/wizard-item-modifier.cpp
Labels: bug, refactor

#3129 [Release] 3.0.0Alpha78
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3122 [Fix] メインウィンドウ左のプレイヤーの状態表示
  src/window/main-window-row-column.h
  src/window/main-window-stat-poster.cpp
Labels: enhancement
