Repository hengband/hengband, pull requests merged in 2023-12, with the labels that each got.

#3770 VS2022 で出ているコンパイル警告を解消した
  src/action/activation-execution.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: refactor, Priority:MIDDLE

#3771 ItemEntity のメソッド群を軽量化した その1
  src/action/activation-execution.cpp
  src/object-enchant/activation-info-table.cpp
  src/object-enchant/activation-info-table.h
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#3776 rooms-normal.cpp を整形した
  src/room/rooms-normal.cpp
Labels: refactor, Priority:MIDDLE

#3780 world_type 構造体をAngbandWorld クラスへ作り替えた
  src/birth/birth-select-class.cpp
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-others.cpp
  src/cmd-building/cmd-building.cpp
  src/cmd-building/cmd-inn.cpp
  src/cmd-io/cmd-autopick.cpp
  src/cmd-io/cmd-dump.cpp
  src/cmd-visual/cmd-draw.cpp
  src/core/game-closer.cpp
  src/core/game-play.cpp
  src/dungeon/quest.cpp
  src/effect/effect-feature.cpp
  src/floor/floor-generator.cpp
  src/floor/wild.cpp
  src/hpmp/hp-mp-processor.cpp
  src/io/write-diary.cpp
  src/knowledge/knowledge-self.cpp
  src/load/floor-loader.cpp
  src/load/player-info-loader.cpp
  src/market/arena.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-lite.cpp
  src/player/player-damage.cpp
  src/save/player-writer.cpp
  src/save/save.cpp
  src/spell-kind/spells-lite.cpp
  src/system/player-type-definition.h
  src/view/display-map.cpp
  src/view/display-player-middle.cpp
  src/window/display-sub-windows.cpp
  src/world/world-movement-processor.cpp
  src/world/world-turn-processor.cpp
  src/world/world.cpp
  src/world/world.h
Labels: refactor, Priority:MIDDLE

#3788 [Release] 3.0.1.3-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3790 Update hengband.spec version to 3.0.1.3
  hengband.spec
Labels: release

#3798 [Chore] clangでのccache用のキャッシュ生成にlibc++を使用する
  .github/workflows/create-cache-for-ccache.yml
Labels: bug

#3796 [Fix]アリーナの出口が開く条件がおかしいのを修正
  src/cmd-building/cmd-building.cpp
Labels: bug

#3801 Release/3.0.1.4 beta
  .github/workflows/create-cache-for-ccache.yml
  configure.ac
  doxygen/Hengband.doxyfile
  hengband.spec
  src/cmd-building/cmd-building.cpp
  src/system/angband-version.h
Labels: release

#3800 [Release] 3.0.1.4-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3802 Update spec
  hengband.spec
Labels: release
