Repository hengband/hengband, pull requests merged in 2023-01, with the labels that each got.

#3043 [Refactor] c_roff 関数を読みやすくする
  src/term/screen-processor.cpp
Labels: refactor

#3048 [Release] 3.0.0Alpha74
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3046 [Fix] トランプ魔術の塔の選択肢が消えてしまう
  src/cmd-building/cmd-building.cpp
Labels: bug

#3044 [Fix] inkey() の処理で直接カーソル座標にアクセスしている
  src/io/input-key-acceptor.cpp
Labels: bug

#3051 [Fix] スポイラーの出力にドロップアイテムの質が表示されない
  src/lore/lore-calculator.cpp
  src/lore/lore-calculator.h
  src/lore/monster-lore.cpp
Labels: bug

#3053 [Refactor] flgs, flags表記をflagsに統一。
  src/artifact/random-art-characteristics.cpp
  src/artifact/random-art-generator.cpp
  src/cmd-item/cmd-refill.cpp
  src/combat/slaying.cpp
  src/combat/slaying.h
  src/flavor/flavor-util.cpp
  src/hpmp/hp-mp-processor.cpp
  src/inventory/inventory-curse.cpp
  src/market/building-craft-fix.cpp
  src/market/building-craft-weapon.cpp
  src/mind/mind-priest.cpp
  src/mind/mind-samurai.h
  src/monster-floor/monster-object.cpp
  src/object-enchant/object-curse.cpp
  src/object-hook/hook-weapon.cpp
  src/object/object-broken.cpp
  src/object/object-flags.cpp
  src/object/object-info.cpp
  src/object/object-value-calc.cpp
  src/object/object-value.cpp
  src/object/warning.cpp
  src/perception/identification.cpp
  src/player-info/base-status-info.cpp
  src/player/player-damage.cpp
  src/player/player-status-flags.cpp
  src/player/player-status-resist.cpp
  src/player/player-status.cpp
  src/realm/realm-hissatsu.cpp
  src/smith/object-smith.cpp
  src/smith/smith-info.cpp
  src/specific-object/torch.cpp
  src/specific-object/torch.h
  src/spell-kind/spells-teleport.cpp
  src/store/service-checker.cpp
  src/view/status-first-page.cpp
  src/wizard/artifact-analyzer.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#3039 [Feature] キャラクタ情報を画面中央に表示する
  src/cmd-visual/cmd-draw.cpp
  src/io-dump/character-dump.cpp
  src/io/files-util.cpp
  src/term/screen-processor.cpp
  src/term/z-term.cpp
  src/term/z-term.h
  src/view/display-player.cpp
Labels: enhancement

#3054 [Feature] タイトル画面をウィンドウの中央に表示する
  src/main-win.cpp
  src/main.cpp
Labels: enhancement

#3055 [Feature] キャラメイク画面をウィンドウの中央に表示する
  src/birth/character-builder.cpp
Labels: enhancement

#3056 [Feature] スコアランキング画面をウィンドウの中央に表示する
  src/view/display-scores.cpp
Labels: enhancement

#3059 [Refactor] サブウィンドウの描画処理を関数にまとめる
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/core/window-redrawer.cpp
  src/window/display-sub-window-spells.cpp
  src/window/display-sub-window-spells.h
  src/window/display-sub-windows.cpp
  src/window/display-sub-windows.h
Labels: refactor

#3061 [Fix] メイン画面のサイズ変更時に自動で再描画されない
  src/core/game-play.cpp
Labels: bug

#3062 [Feature] ゲームオーバー時の画面をウィンドウの中央に表示する
  src/core/game-closer.cpp
  src/floor/object-scanner.cpp
  src/view/display-inventory.cpp
  src/window/main-window-equipments.cpp
Labels: enhancement

#3063 [Fix] 画面左下部の情報が正しく表示されない
  src/core/window-redrawer.cpp
  src/locale/language-switcher.h
  src/window/main-window-left-frame.cpp
  src/window/main-window-row-column.h
  src/window/main-window-stat-poster.cpp
  src/world/world-turn-processor.cpp
Labels: bug

#3064 [Fix] hilite_player オプションが機能しない事がある
  src/term/z-term.cpp
Labels: bug

#3065 [Fix] 店舗内でデバッグセーブを実行している
  src/io/input-key-requester.cpp
Labels: bug

#3067 [Fix] 極端な修正値を持つ光源の暗視エゴアイテムが生成される
  lib/edit/BaseitemDefinitions.txt
  src/object-enchant/others/apply-magic-lite.cpp
Labels: bug

#3070 [Fix] 忍者にふさわしくない武器の攻撃回数ペナルティが機能していない
  src/player/player-status.cpp
Labels: bug

#3071 [Fix] クロークの灼熱エゴアイテムでクラッシュする
  src/object/object-flags.cpp
Labels: bug

#3038 describe_flavor() のシグネチャを変更する準備 その1
  Hengband/Hengband/Hengband.vcxproj.filters
  src/autopick/autopick-finder.cpp
  src/cmd-item/cmd-equipment.cpp
  src/combat/shoot.cpp
  src/combat/shoot.h
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-describer.h
  src/market/bounty.cpp
  src/market/building-craft-fix.cpp
  src/mind/mind-priest.cpp
  src/monster/monster-describer.cpp
  src/window/main-window-equipments.cpp
  src/window/main-window-util.cpp
Labels: refactor, Priority:MIDDLE

#3077 [Refactor] ウィンドウのデフォルトサイズを定数にする
  src/birth/character-builder.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-visual/cmd-draw.cpp
  src/core/asking-player.cpp
  src/core/game-closer.cpp
  src/load/load-util.cpp
  src/main-cap.cpp
  src/main-gcu.cpp
  src/main-win.cpp
  src/main-x11.cpp
  src/main.cpp
  src/main/angband-initializer.cpp
  src/player-info/self-info.cpp
  src/store/cmd-store.cpp
  src/term/gameterm.h
  src/view/display-messages.cpp
  src/view/display-player.cpp
  src/view/display-scores.cpp
  src/view/display-self-info.cpp
  src/window/main-window-left-frame.cpp
Labels: refactor

#3079 [Feature] 店舗・建物内の画面をウィンドウ中央に表示する
  src/cmd-building/cmd-building.cpp
  src/core/show-file.cpp
  src/floor/object-scanner.cpp
  src/io-dump/character-dump.cpp
  src/store/cmd-store.cpp
  src/term/z-term.cpp
  src/term/z-term.h
  src/view/display-inventory.cpp
  src/window/main-window-equipments.cpp
Labels: enhancement

#3080 [Modify] 航海士『ナミ』を原作中盤ほどまでを意識して強化。
  lib/edit/MonsterRaceDefinitions.txt
Labels: enhancement

#3081 [Feature] オプション画面をウィンドウ中央に表示する
  src/cmd-io/cmd-autopick.cpp
  src/cmd-io/cmd-gameoption.cpp
Labels: enhancement

#3076 describe_flavor() のシグネチャを変更する準備 その2
  src/knowledge/knowledge-inventory.cpp
  src/knowledge/knowledge-self.cpp
  src/market/building-craft-fix.cpp
  src/monster-floor/monster-object.cpp
  src/util/string-processor.cpp
  src/util/string-processor.h
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#3084 [Release] 3.0.0Alpha75
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3088 [Fix] モンスターの一時状態異常表示が画面に残る
  src/window/main-window-left-frame.cpp
Labels: bug
