Repository hengband/hengband, pull requests merged in 2023-10, with the labels that each got.

#3637 コンパイル警告の解消 α90 その2
  src/cmd-io/cmd-process-screen.cpp
  src/cmd-item/cmd-equipment.cpp
  src/cmd-item/cmd-item.cpp
  src/cmd-visual/cmd-draw.cpp
  src/cmd-visual/cmd-map.cpp
  src/core/show-file.cpp
  src/core/window-redrawer.cpp
  src/floor/object-scanner.cpp
  src/io-dump/dump-util.cpp
  src/io/record-play-movie.cpp
  src/io/report.cpp
  src/io/signal-handlers.cpp
  src/io/write-diary.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/perception/identification.cpp
  src/store/cmd-store.cpp
  src/term/screen-processor.cpp
  src/util/candidate-selector.cpp
  src/view/display-inventory.cpp
  src/view/display-player-misc-info.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-equipments.cpp
  src/window/main-window-left-frame.cpp
  src/window/main-window-stat-poster.cpp
  src/wizard/cmd-wizard.cpp
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#3634 フロアとクエストの依存性を片方向に寄せた
  src/action/mutation-execution.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-io/cmd-dump.cpp
  src/core/game-play.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/effect/effect-monster-charm.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-events.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-util.cpp
  src/floor/object-allocator.cpp
  src/grid/feature-generator.cpp
  src/grid/stair.cpp
  src/grid/trap.cpp
  src/info-reader/general-parser.cpp
  src/io/input-key-processor.cpp
  src/io/input-key-requester.cpp
  src/io/write-diary.cpp
  src/load/old/load-v1-7-0.cpp
  src/main/scene-table-floor.cpp
  src/melee/melee-spell-util.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-attack.cpp
  src/player/player-damage.cpp
  src/player/player-move.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-genocide.cpp
  src/spell-kind/spells-grid.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-kind/spells-world.cpp
  src/spell-realm/spells-chaos.cpp
  src/system/floor-type-definition.cpp
  src/system/floor-type-definition.h
  src/view/display-player.cpp
  src/window/main-window-left-frame.cpp
  src/wizard/wizard-game-modifier.cpp
  src/world/world-movement-processor.cpp
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#3608 [Fix] 不正な名前のファイルにキャラクタダンプを出力するとクラッシュ
  src/io/files-util.cpp
Labels: bug

#3652 ケット・シー及びイェンダーの魔法使い(YENDER_WIZARD_2)を地上で倒すと(なし)をドロップしてしまうバグを修正
  src/monster-floor/special-death-switcher.cpp
Labels: bug

#3643 コンパイル警告の解消 (変数キャプチャ)
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/packages.config
  src/cmd-io/cmd-floor.cpp
  src/grid/grid.cpp
  src/io/cursor.cpp
  src/mspell/mspell-checker.cpp
  src/room/cave-filler.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-realm/spells-hex.cpp
  src/spell/range-calc.cpp
  src/target/projection-path-calculator.cpp
  src/target/target-checker.cpp
  src/target/target-setter.cpp
  src/util/string-processor.cpp
  src/window/display-sub-windows.cpp
  src/wizard/items-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#3648 [Fix] アイテム破壊時に自動破壊登録すると自動拾いファイルがリセットされる
  src/autopick/autopick-reader-writer.cpp
  src/autopick/autopick-reader-writer.h
  src/autopick/autopick-registry.cpp
Labels: bug, refactor

#3653 English: use Homonculi as the plural for Homonculous
  src/locale/english.cpp
Labels: bug

#3651 TerrainList クラスを作った
  src/action/movement-execution.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/visuals-reseter.cpp
  src/floor/floor-streams.cpp
  src/floor/object-allocator.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/grid/grid.cpp
  src/grid/trap.cpp
  src/info-reader/feature-reader.cpp
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-features.cpp
  src/monster/monster-info.cpp
  src/player/player-move.cpp
  src/room/rooms-builder.cpp
  src/room/rooms-city.cpp
  src/room/rooms-trap.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-realm/spells-chaos.cpp
  src/store/purchase-order.cpp
  src/store/store.cpp
  src/store/store.h
  src/system/terrain-type-definition.cpp
  src/system/terrain-type-definition.h
  src/view/display-map.cpp
  src/view/display-store.cpp
  src/window/display-sub-windows.cpp
  src/wizard/wizard-special-process.cpp
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#3632 MonraceList クラスを定義し、monraces_info へのアクセスをカプセル化し、もって分離/合体ユニークの処理を一般化した
  src/dungeon/quest.cpp
  src/market/bounty.cpp
  src/monster-floor/monster-remover.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-damage.cpp
  src/monster/monster-damage.h
  src/monster/monster-list.cpp
  src/mspell/mspell-selector.cpp
  src/mspell/mspell-special.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#3658 Release/3.0.0.89 alpha
  doxygen/Hengband.doxyfile
  hengband.spec
  src/system/angband-version.h
Labels: release

#3663 [Release] 3.0.0.90-Alpha (develop)
  configure.ac
  doxygen/Hengband.doxyfile
  hengband.spec
  src/system/angband-version.h
Labels: release

#3665 choose_random_trap() の引数をPlayerType からFloorType に差し替えた
  src/effect/effect-feature.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/object-allocator.cpp
  src/grid/trap.cpp
  src/grid/trap.h
  src/load/old/load-v1-5-0.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-vault.cpp
  src/room/treasure-deployment.cpp
  src/room/vault-builder.cpp
  src/room/vault-builder.h
Labels: refactor, Priority:MIDDLE

#3671 [Fix] カメレオンやたぬきが化けない
  src/core/player-processor.cpp
  src/main/scene-table-monster.cpp
  src/monster-floor/monster-move.cpp
  src/monster/monster-describer.cpp
  src/monster/monster-update.cpp
  src/player/eldritch-horror.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/target/target-describer.cpp
  src/view/display-map.cpp
  src/view/display-monster-status.cpp
  src/window/display-sub-windows.cpp
Labels: bug

#3673 [Release] 3.0.0.91-Alpha
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3679 状態異常無効化フラグをEnum Class化
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-evil.cpp
  src/effect/effect-monster-oldies.cpp
  src/effect/effect-monster-psi.cpp
  src/effect/effect-monster-resist-hurt.cpp
  src/effect/effect-monster-spirit.cpp
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-monster.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/load/lore-loader.cpp
  src/load/old/load-v1-5-0.cpp
  src/load/savedata-old-flag-types.h
  src/melee/melee-postprocess.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-samurai.cpp
  src/mind/monk-attack.cpp
  src/monster-race/race-flags-resistance.h
  src/monster-race/race-flags3.h
  src/monster/monster-damage.cpp
  src/mspell/mspell-status.cpp
  src/player-attack/attack-chaos-effect.cpp
  src/spell/spells-diceroll.cpp
  src/view/display-lore-status.cpp
Labels: refactor

#3670 SMART/STUPID フラグの更新処理が無意味なものになっていたので修正した
  src/monster/monster-update.cpp
Labels: bug, Priority:MIDDLE

#3683 最新のモンスター種族追加が反映されていないセーブデータを読み込むとそれらの種族が出現しなくなる不具合を解消した
  src/birth/game-play-initializer.cpp
  src/floor/fixed-map-generator.cpp
  src/load/lore-loader.cpp
  src/system/system-variables.h
  src/wizard/wizard-game-modifier.cpp
Labels: bug, refactor, Priority:MIDDLE

#3688 コンパイル警告の解消 β (予定)
  src/dungeon/quest.h
  src/info-reader/fixed-map-parser.h
  src/knowledge/knowledge-quests.h
  src/main-win.cpp
  src/main-win/graphics-win.cpp
  src/util/flag-group.h
Labels: refactor, Priority:MIDDLE

#3697 [Release] 3.0.1.0-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3699 [Hotfix] バージョン表示切替ミス修正。
  src/system/angband-version.h
Labels: bug, release, Priority:Critical

#3700 Hotfix/3.0.1.0 beta version desc
  src/system/angband-version.h
Labels: bug, release, Priority:Critical

#3703 グローバル変数 error_lineをなくした
  src/info-reader/general-parser.cpp
  src/info-reader/general-parser.h
  src/info-reader/info-reader-util.h
  src/main/info-initializer.cpp
Labels: refactor
