Repository hengband/hengband, pull requests merged in 2023-11, with the labels that each got.

#3701 テキストデータから定数を読み込めるようにした
  src/info-reader/info-reader-util.h
  src/util/flag-group.h
Labels: enhancement, refactor

#3707 [Fix] update_lite_flags()の処理におけるダングリング参照
  src/monster/monster-update.cpp
  src/util/flag-group.h
Labels: bug

#3691 グリッドから地形へのアクセスをカプセル化する準備 その2
  src/action/movement-execution.cpp
  src/action/run-execution.cpp
  src/action/tunnel-execution.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-others.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-action/cmd-travel.cpp
  src/cmd-action/cmd-tunnel.cpp
  src/cmd-building/cmd-building.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/effect/effect-feature.cpp
  src/floor/cave-generator.cpp
  src/floor/wild.cpp
  src/grid/door.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/monster-floor/monster-sweep-grid.cpp
  src/pet/pet-util.cpp
  src/pet/pet-util.h
  src/player/player-move.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-fetcher.cpp
  src/store/cmd-store.cpp
  src/view/display-map.cpp
  src/window/display-sub-windows.cpp
Labels: refactor, Priority:MIDDLE

#3714 グリッドから地形へのアクセスをカプセル化する準備 その4
  src/action/open-close-execution.cpp
  src/dungeon/quest-monster-placer.cpp
  src/effect/effect-feature.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-streams.cpp
  src/grid/grid.cpp
Labels: refactor, Priority:MIDDLE

#3716 グリッドから地形へのアクセスをカプセル化する準備 その5
  src/grid/grid.cpp
  src/info-reader/feature-reader.cpp
  src/player/player-move.cpp
  src/target/target-describer.cpp
Labels: refactor, Priority:MIDDLE

#3717 [Fix] モルサンクに永久光源特性がついている
  lib/edit/ArtifactDefinitions.txt
Labels: bug

#3719 グリッドから地形へのアクセスをカプセル化する準備 その6
  src/floor/pattern-walk.cpp
  src/hpmp/hp-mp-processor.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-ninja.cpp
  src/monster-attack/monster-attack-processor.cpp
  src/monster-attack/monster-attack-processor.h
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-move.h
  src/monster/monster-processor.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-lite.cpp
  src/mutation/mutation-techniques.cpp
  src/player-base/player-race.cpp
  src/room/rooms-builder.cpp
  src/spell-kind/spells-lite.cpp
Labels: refactor, Priority:MIDDLE

#3723 グリッドから地形へのアクセスをカプセル化する準備 その7
  src/action/movement-execution.cpp
  src/action/run-execution.cpp
  src/floor/cave.cpp
  src/floor/floor-streams.cpp
  src/floor/pattern-walk.cpp
  src/monster/monster-util.cpp
  src/player/player-status.cpp
  src/spell-kind/spells-floor.cpp
Labels: refactor, Priority:MIDDLE

#3726 グリッドから地形へのアクセスをカプセル化する準備 その8
  src/info-reader/feature-reader.cpp
  src/system/terrain-type-definition.cpp
  src/system/terrain-type-definition.h
Labels: refactor, Priority:MIDDLE

#3692 Grid クラスにget_terrain() メソッドを追加した
  src/action/movement-execution.cpp
  src/action/open-close-execution.cpp
  src/action/run-execution.cpp
  src/action/tunnel-execution.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-others.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-action/cmd-travel.cpp
  src/cmd-action/cmd-tunnel.cpp
  src/cmd-building/cmd-building.cpp
  src/dungeon/quest-monster-placer.cpp
  src/effect/effect-feature.cpp
  src/floor/cave-generator.cpp
  src/floor/cave.cpp
  src/floor/floor-events.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-streams.cpp
  src/floor/pattern-walk.cpp
  src/floor/wild.cpp
  src/grid/door.cpp
  src/grid/grid.cpp
  src/grid/trap.cpp
  src/hpmp/hp-mp-processor.cpp
  src/main/info-initializer.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-move.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-lite.cpp
  src/mutation/mutation-techniques.cpp
  src/player-base/player-race.cpp
  src/player/player-move.cpp
  src/player/player-status.cpp
  src/room/rooms-builder.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-realm/spells-chaos.cpp
  src/store/cmd-store.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/system/terrain-type-definition.cpp
  src/system/terrain-type-definition.h
  src/target/target-describer.cpp
  src/target/target-preparation.cpp
  src/util/sort.cpp
  src/view/display-map.cpp
  src/window/display-sub-windows.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#3704 Update spec
  hengband.spec
Labels: enhancement

#3721 秘術領域の特異点クエストを追加した
  lib/edit/QuestDefinitionList.txt
  lib/edit/quests/013_NodeOfArcane.txt
  lib/edit/quests/Makefile.am
  lib/edit/towns/05_Zul.txt
  src/dungeon/quest.h
Labels: enhancement

#3739 [Release] 3.0.1.1-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3741 Update spec
  hengband.spec
Labels: release

#3742 optional::value() を*optional へ差し替えた その2
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/combat/shoot.cpp
  src/core/show-file.cpp
  src/flavor/named-item-describer.cpp
  src/flavor/object-flavor.cpp
  src/floor/pattern-walk.cpp
  src/io/record-play-movie.cpp
  src/main-win.cpp
  src/market/play-gamble.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-power-getter.cpp
  src/mind/mind-sniper.cpp
  src/mind/mind-weaponsmith.cpp
  src/monster-floor/monster-generator.cpp
  src/monster/monster-describer.cpp
  src/mutation/mutation-processor.cpp
  src/object-enchant/vorpal-weapon.cpp
  src/object-use/quaff/quaff-effects.cpp
  src/object-use/quaff/quaff-effects.h
  src/object-use/read/parchment-read-executor.cpp
  src/object-use/read/scroll-read-executor.cpp
  src/object-use/use-execution.cpp
  src/object-use/zaprod-execution.cpp
  src/object-use/zapwand-execution.cpp
  src/object/object-broken.cpp
  src/object/object-kind-hook.cpp
  src/player-base/player-race.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/player/process-name.cpp
  src/room/rooms-pit-nest.cpp
  src/spell-kind/spells-genocide.cpp
  src/spell-kind/spells-world.cpp
  src/spell-realm/spells-hex.cpp
  src/store/store.cpp
  src/target/target-getter.cpp
  src/test/test-sha256.cpp
  src/util/sort.cpp
  src/view/object-describer.cpp
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spells.cpp
Labels: refactor, Priority:MIDDLE

#3749 トラップ付の箱を開けた時、箱が破損する処理と中のアイテムを取り出す処理が競合してクラッシュする不具合を解消した
  src/specific-object/chest.cpp
Labels: refactor, Priority:MIDDLE

#3753 BaseitemKey のコンストラクタをコンパイル時定数に置き換えた
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
Labels: refactor, Priority:MIDDLE

#3758 [Fix] 施設入場不可メッセージがズレるエラーを修正。
  src/cmd-building/cmd-building.cpp
Labels: bug

#3761 [Release] 3.0.1.2-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3765 Update the version to 3.0.1.2 in hengband.spec
  hengband.spec
Labels: release

#3752 POSITION y, POSITION x の引数を持つ関数をPos2D に差し替えた その1
  src/action/movement-execution.cpp
  src/action/open-close-execution.cpp
  src/action/open-util.cpp
  src/action/open-util.h
  src/autopick/autopick.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-pet.cpp
  src/combat/shoot.cpp
  src/core/window-redrawer.cpp
  src/floor/geometry.cpp
  src/floor/geometry.h
  src/floor/pattern-walk.cpp
  src/floor/pattern-walk.h
  src/grid/grid.cpp
  src/grid/grid.h
  src/object-use/throw-execution.cpp
  src/room/space-finder.cpp
  src/specific-object/chest.cpp
  src/specific-object/chest.h
  src/spell-realm/spells-crusade.cpp
  src/target/target-describer.cpp
  src/target/target-setter.cpp
  src/window/display-sub-windows.cpp
  src/window/display-sub-windows.h
Labels: refactor, Priority:MIDDLE

#3754 装備品の発動に関する処理をItemEntity へ寄せた その1
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/activation-execution.cpp
  src/artifact/artifact-info.cpp
  src/artifact/artifact-info.h
  src/info-reader/artifact-reader.cpp
  src/info-reader/baseitem-reader.cpp
  src/info-reader/ego-reader.cpp
  src/info-reader/info-reader-util.cpp
  src/info-reader/info-reader-util.h
  src/market/building-craft-fix.cpp
  src/object-activation/activation-bolt-ball.cpp
  src/object-activation/activation-bolt-ball.h
  src/object-activation/activation-others.cpp
  src/object-activation/activation-others.h
  src/object-activation/activation-resistance.cpp
  src/object-activation/activation-resistance.h
  src/object-activation/activation-switcher.cpp
  src/object-activation/activation-switcher.h
  src/object-enchant/activation-info-table.cpp
  src/object-enchant/activation-info-table.h
  src/object/object-info.cpp
  src/object/object-value-calc.cpp
  src/specific-object/ring-of-power.cpp
  src/specific-object/ring-of-power.h
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: refactor, Priority:MIDDLE

#3769 Include THIRD-PARTY-NOTICES.txt in archive from 'make dist'
  Makefile.am
Labels: bug
