Repository hengband/hengband, pull requests merged in 2023-04, with the labels that each got.

#3139 [Feature] 全属性系モンスターに虚無属性、深淵属性の攻撃手段を追加。
  lib/edit/MonsterRaceDefinitions.txt
Labels: enhancement

#3161 未鑑定のフェアノールのランプが重なる事象を修正した
  src/object/object-stack.cpp
Labels: bug, refactor, Priority:MIDDLE

#3169 インクルードガードを#pragma once に統一した
  src/main-win/main-win-utils.h
  src/system/angband.h
  src/system/h-basic.h
  src/term/z-form.h
  src/term/z-term.h
  src/term/z-util.h
  src/term/z-virt.cpp
  src/term/z-virt.h
Labels: refactor, Priority:MIDDLE

#3171 [Fix] #3137 キャラメイク時職業の能力修正値情報が更新されない
  src/birth/birth-select-class.cpp
Labels: bug

#3170 misc.txt から町の最大数を削除した
  lib/edit/misc.txt
  src/birth/character-builder.cpp
  src/cmd-io/cmd-dump.cpp
  src/core/turn-compensator.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-town.cpp
  src/floor/floor-town.h
  src/floor/floor-util.cpp
  src/floor/wild.cpp
  src/io-dump/character-dump.cpp
  src/io-dump/random-art-info-dumper.cpp
  src/knowledge/knowledge-inventory.cpp
  src/knowledge/knowledge-self.cpp
  src/load/quest-loader.cpp
  src/load/store-loader.cpp
  src/main-win/main-win-music.cpp
  src/market/building-initializer.cpp
  src/player/process-death.cpp
  src/save/save.cpp
  src/spell-kind/spells-world.cpp
  src/store/black-market.cpp
  src/store/cmd-store.cpp
  src/store/home.cpp
  src/store/rumor.cpp
  src/store/store.cpp
  src/target/target-describer.cpp
Labels: refactor, Priority:MIDDLE

#3167 日記のサブタイトルをconcptr[] からstd::vector<std::string> に変えた
  src/cmd-io/cmd-diary.cpp
  src/cmd-io/diary-subtitle-table.cpp
  src/cmd-io/diary-subtitle-table.h
Labels: refactor, Priority:MIDDLE

#3178 固定アーティファクトを追加し、ArtifactDefinitions.txt の欠番を埋めた
  lib/edit/ArtifactDefinitions.txt
  lib/edit/BaseitemDefinitions.txt
  src/flavor/named-item-describer.cpp
  src/floor/fixed-map-generator.cpp
  src/load/item/item-loader-base.cpp
  src/object-enchant/activation-info-table.cpp
  src/save/save.cpp
  src/system/artifact-type-definition.cpp
  src/wizard/wizard-special-process.cpp
Labels: enhancement, refactor, Priority:MIDDLE

#3202 カオスパトロン報酬が時々異常になる不具合を修正した
  src/player/patron.cpp
Labels: bug, Priority:HIGH

#3201 エルドリッチホラーの形容詞テーブルをconcptr[] からvector<string> に変えた
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/monster/horror-descriptions.cpp
  src/monster/horror-descriptions.h
  src/player/eldritch-horror.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#3198 named_num::name をconcptr からstd::string に変えた
  src/io/gf-descriptions.h
  src/io/interpret-pref-file.cpp
  src/wizard/wizard-spells.cpp
Labels: refactor, Priority:MIDDLE

#3175 path_parse() のシグネチャからchar* 引数を削除し、戻り値の型をpathにした
  src/floor/floor-save.cpp
  src/io/files-util.cpp
  src/io/record-play-movie.cpp
  src/main.cpp
  src/main/angband-initializer.cpp
  src/save/floor-writer.cpp
  src/save/save.cpp
  src/util/angband-files.cpp
  src/util/angband-files.h
Labels: refactor, Priority:MIDDLE

#3196 ダミークエストが表示される不具合を解消した
  lib/edit/quests/027_TheOldCatsle.txt
  src/knowledge/knowledge-quests.cpp
Labels: bug, refactor, Priority:MIDDLE

#3180 artifacts_info.at() をArtifactsInfo::get_instance().get_artifact() へカプセル化した
  src/action/activation-execution.cpp
  src/artifact/artifact-info.cpp
  src/artifact/fixed-art-generator.cpp
  src/birth/game-play-initializer.cpp
  src/combat/shoot.cpp
  src/dungeon/quest.cpp
  src/flavor/flavor-util.cpp
  src/flavor/named-item-describer.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-object.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/grid/object-placer.cpp
  src/info-reader/artifact-reader.cpp
  src/info-reader/general-parser.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/item/item-loader-base.cpp
  src/load/old/load-v1-5-0.cpp
  src/load/quest-loader.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object-enchant/item-magic-applier.cpp
  src/object-hook/hook-quest.cpp
  src/object/object-flags.cpp
  src/object/object-value-calc.cpp
  src/object/object-value.cpp
  src/perception/identification.cpp
  src/racial/racial-android.cpp
  src/save/save.cpp
  src/specific-object/bloody-moon.cpp
  src/spell-kind/spells-floor.cpp
  src/spell/spells-object.cpp
  src/store/rumor.cpp
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/util/sort.cpp
  src/wizard/artifact-analyzer.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#3192 関数マクロIS_FLG() を削除した
  src/autopick/autopick-describer.cpp
  src/autopick/autopick-describer.h
  src/autopick/autopick-drawer.cpp
  src/autopick/autopick-editor-command.cpp
  src/autopick/autopick-editor-util.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-entry.h
  src/autopick/autopick-finder.cpp
  src/autopick/autopick-key-flag-process.h
  src/autopick/autopick-matcher.cpp
  src/autopick/autopick-matcher.h
  src/autopick/autopick-pref-processor.cpp
  src/autopick/autopick-registry.cpp
  src/autopick/autopick-util.cpp
  src/autopick/autopick-util.h
  src/cmd-io/cmd-autopick.cpp
  src/knowledge/knowledge-autopick.cpp
Labels: refactor, Priority:MIDDLE

#3211 z-form.cpp/h のコメント等を調整した
  src/term/z-form.cpp
  src/term/z-form.h
Labels: refactor, Priority:MIDDLE

#3212 path_build() のシグネチャをchar*からstringへ差し替える準備 その1
  src/autopick/autopick-reader-writer.cpp
  src/autopick/autopick-reader-writer.h
  src/autopick/autopick-registry.cpp
  src/cmd-io/cmd-autopick.cpp
  src/cmd-io/cmd-diary.cpp
  src/cmd-io/cmd-dump.cpp
  src/cmd-io/cmd-macro.cpp
  src/cmd-io/cmd-process-screen.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/game-closer.cpp
  src/core/scores.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/fixed-map-generator.h
  src/info-reader/fixed-map-parser.cpp
  src/info-reader/fixed-map-parser.h
  src/io-dump/dump-remover.cpp
  src/io-dump/dump-remover.h
  src/io-dump/random-art-info-dumper.cpp
  src/io/files-util.cpp
  src/io/files-util.h
  src/io/inet.cpp
  src/io/read-pref-file.cpp
  src/io/read-pref-file.h
  src/io/record-play-movie.cpp
  src/io/record-play-movie.h
  src/io/write-diary.cpp
  src/main-gcu.cpp
  src/main-win/graphics-win.cpp
  src/main-win/main-win-cfg-reader.cpp
  src/main-win/main-win-music.cpp
  src/main-win/main-win-sound.cpp
  src/main-x11.cpp
  src/main.cpp
  src/main/angband-initializer.cpp
  src/main/info-initializer.cpp
  src/object-use/read/parchment-read-executor.cpp
  src/player/process-death.cpp
  src/player/process-name.cpp
  src/util/angband-files.cpp
  src/util/angband-files.h
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#3216 quest_type 構造体をQuestType クラスに変換し、オブジェクトメソッドを2つ追加した
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-move.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest-completion-checker.cpp
  src/dungeon/quest-completion-checker.h
  src/dungeon/quest-monster-placer.cpp
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/floor/fixed-map-generator.cpp
  src/floor/floor-events.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-util.cpp
  src/floor/wild.cpp
  src/info-reader/general-parser.cpp
  src/io-dump/character-dump.cpp
  src/io/write-diary.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/load-zangband.cpp
  src/load/load-zangband.h
  src/load/quest-loader.cpp
  src/market/building-quest.cpp
  src/melee/melee-spell-util.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-attack.cpp
  src/object-hook/hook-quest.cpp
  src/player/player-damage.cpp
  src/save/save.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-grid.cpp
  src/spell-realm/spells-chaos.cpp
  src/target/target-describer.cpp
  src/view/display-player.cpp
  src/world/world-movement-processor.cpp
Labels: refactor, Priority:MIDDLE

#3219 [Fix] 職業選択時にカーソルやテンキーで選択できない
  src/birth/birth-select-class.cpp
Labels: bug
