Repository hengband/hengband, pull requests merged in 2023-07, with the labels that each got.

#3489 [Feature] プレイヤー名を中央寄せして表示する
  src/birth/birth-select-personality.cpp
  src/birth/birth-wizard.cpp
  src/player/process-name.cpp
  src/view/display-player-misc-info.cpp
  src/view/display-player-misc-info.h
  src/view/display-player.cpp
Labels: enhancement

#3486 [Feature] SHA-256ハッシュ値計算クラス
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/test/test-sha256.cpp
  src/util/sha256.cpp
  src/util/sha256.h
Labels: enhancement

#3493 #3469 に混入した不具合修正
  src/player/process-name.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: bug

#3495 [Feature] HTTP通信でファイルに直接ダウンロードする
  src/net/curl-easy-session.cpp
  src/net/http-client.cpp
  src/net/http-client.h
Labels: enhancement

#3490 get_com() のシグネチャを変える準備
  src/action/mutation-execution.cpp
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-hissatsu.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-action/cmd-racial.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-action/cmd-tunnel.cpp
  src/cmd-io/cmd-floor.cpp
  src/cmd-io/cmd-lore.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/core/asking-player.cpp
  src/core/asking-player.h
  src/io/input-key-requester.cpp
  src/io/input-key-requester.h
  src/market/building-monster.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-berserker.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-power-getter.cpp
  src/mind/mind-power-getter.h
  src/mind/mind-sniper.cpp
  src/mind/mind-warrior.cpp
  src/mind/mind-weaponsmith.cpp
  src/mind/monk-attack.cpp
  src/mutation/mutation-processor.cpp
  src/mutation/mutation-techniques.cpp
  src/player/player-status.cpp
  src/racial/racial-switcher.cpp
  src/racial/racial-vampire.cpp
  src/realm/realm-hissatsu.cpp
  src/specific-object/monster-ball.cpp
  src/spell-kind/spells-genocide.cpp
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-hex.h
  src/spell/spells-describer.cpp
  src/spell/spells-describer.h
  src/spell/spells-status.cpp
  src/store/store.cpp
  src/target/target-getter.cpp
  src/target/target-getter.h
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-player-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#3497 [Feature] HTTP通信の進捗のコールバック機能
  src/net/curl-easy-session.cpp
  src/net/curl-easy-session.h
  src/net/http-client.cpp
  src/net/http-client.h
Labels: enhancement

#3501 [Fix] 装備変更時に店のアイテム表示内容が更新されない
  src/store/cmd-store.cpp
Labels: bug

#3502 [Fix] （デバッグ）セーブ時にクラッシュ
  src/save/save.cpp
  src/util/angband-files.cpp
Labels: bug

#3498 input_command() のシグネチャを変更した
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-hissatsu.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-action/cmd-racial.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-io/cmd-floor.cpp
  src/cmd-io/cmd-lore.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/core/asking-player.cpp
  src/core/asking-player.h
  src/io/input-key-requester.cpp
  src/market/building-monster.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-power-getter.cpp
  src/mind/mind-sniper.cpp
  src/mind/mind-weaponsmith.cpp
  src/mutation/mutation-processor.cpp
  src/racial/racial-util.h
  src/spell-kind/spells-genocide.cpp
  src/spell-realm/spells-hex.cpp
  src/store/store.cpp
  src/target/target-getter.cpp
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-player-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#3505 [Fix] #3479 での修正漏れ
  src/realm/realm-hex.cpp
Labels: bug

#3512 [Chore] MSVCのビルドテストでCached LFS checkoutを使用する
  .github/workflows/build-test-with-msvc.yml
Labels: enhancement

#3515 数値入力プロンプトにおいて、テンキー入力を数字の入力へ強制するよう修正した
  src/core/asking-player.cpp
  src/core/asking-player.h
Labels: bug, Priority:MIDDLE

#3508 [Feature] JSONライブラリの導入
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  THIRD-PARTY-NOTICES.txt
  src/Makefile.am
  src/external-lib/include-json.h
  src/external-lib/json.hpp
  src/locale/japanese.cpp
  src/locale/japanese.h
Labels: enhancement

#3516 [Feature] エラー情報送信機能
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  configure.ac
  src/Makefile.am
  src/main-win.cpp
  src/main-win/main-win-exception.cpp
  src/main-win/main-win-exception.h
  src/net/curl-easy-session.cpp
  src/net/curl-easy-session.h
  src/net/curl-slist.cpp
  src/net/curl-slist.h
  src/net/http-client.cpp
  src/net/http-client.h
  src/net/report-error.cpp
  src/net/report-error.h
  src/system/angband-exceptions.h
Labels: enhancement

#3519 乱数ジェネレータのコピーで静的解析警告が出ていたので対処した
  src/floor/wild.cpp
Labels: refactor, Priority:MIDDLE

#3523 [Chore] ccacheが使用するキャッシュを分け、ビルドテストを並列に実行できるようにする
  .github/workflows/build-with-autotools.yml
  .github/workflows/create-cache-for-ccache.yml
  .github/workflows/pull-request-status-check.yml
Labels: enhancement

#3525 [Fix] ダンプの名前の位置が右にずれる
  src/io-dump/character-dump.cpp
Labels: bug

#3520 askfor() の引数からchar* を除去し、戻り値をoptional<string> に変えた
  src/cmd-io/cmd-dump.cpp
  src/cmd-io/cmd-macro.cpp
  src/cmd-visual/cmd-draw.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/asking-player.cpp
  src/core/asking-player.h
  src/core/show-file.cpp
  src/player/process-death.cpp
Labels: refactor, Priority:MIDDLE

#3526 [Fix] nlohmann-jsonライブラリの静的解析警告
  src/external-lib/json.hpp
Labels: bug

#3527 静的解析パッケージの更新
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/packages.config
  src/item-info/flavor-initializer.cpp
  src/term/z-util.cpp
Labels: refactor, Priority:MIDDLE

#3528 [Chore] GitHub Actionsによる自動リリースのワークフロー
  .github/workflows/create-release.yml
Labels: enhancement

#3531 [Release] 3.0.0.87-Alpha
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3533 stat_flags_desc とpval_flags1_desc を生配列からvector に変えた
  src/io-dump/random-art-info-dumper.cpp
  src/wizard/artifact-analyzer.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/fixed-artifacts-spoiler.h
  src/wizard/spoiler-table.cpp
  src/wizard/spoiler-table.h
  src/wizard/spoiler-util.cpp
  src/wizard/spoiler-util.h
Labels: refactor, Priority:MIDDLE

#3544 [Fix] 博物館で240個までしかアイテムが表示されない
  src/store/store-key-processor.cpp
Labels: bug

#3540 get_stock() をinput_stock() に変え、シグネチャを差し替えた
  src/store/museum.cpp
  src/store/purchase-order.cpp
  src/store/store.cpp
  src/store/store.h
Labels: refactor, Priority:MIDDLE

#3549 勝利メッセージ確定のyes/no が反転していた不具合を修正した
  src/cmd-action/cmd-others.cpp
Labels: refactor, Priority:MIDDLE

#3548 店で存在しないアイテム番号を選択した後にEsc で抜けるとクラッシュする不具合を修正した
  src/store/store.cpp
Labels: refactor, Priority:MIDDLE

#3550 obj_desc_list を構成していた生配列を全てvector とstring に変えた
  src/io-dump/random-art-info-dumper.cpp
  src/object/object-info.cpp
  src/object/object-info.h
  src/perception/identification.cpp
  src/wizard/artifact-analyzer.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/fixed-artifacts-spoiler.h
  src/wizard/spoiler-table.cpp
  src/wizard/spoiler-table.h
  src/wizard/spoiler-util.h
Labels: refactor, Priority:MIDDLE

#3553 アーティファクトスポイラー周りのシグネチャ整理
  src/io-dump/random-art-info-dumper.cpp
  src/object/object-info.cpp
  src/object/object-info.h
  src/wizard/artifact-analyzer.cpp
  src/wizard/artifact-analyzer.h
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/fixed-artifacts-spoiler.h
  src/wizard/spoiler-util.cpp
  src/wizard/spoiler-util.h
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#3556 [Fix] 消去時に画面右端までの消去されないことがある
  src/autopick/autopick-finder.cpp
  src/birth/history-editor.cpp
  src/cmd-action/cmd-mind.cpp
  src/cmd-action/cmd-racial.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/cmd-visual/cmd-draw.cpp
  src/core/show-file.cpp
  src/io/signal-handlers.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/main/angband-initializer.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-sniper.cpp
  src/mind/mind-weaponsmith.cpp
  src/spell-kind/spells-sight.cpp
  src/spell-realm/spells-hex.cpp
  src/term/screen-processor.cpp
  src/term/z-term.cpp
  src/term/z-term.h
  src/view/display-inventory.cpp
  src/view/display-lore.cpp
  src/view/display-messages.cpp
  src/view/display-player-misc-info.cpp
  src/view/object-describer.cpp
  src/window/display-sub-windows.cpp
  src/wizard/wizard-special-process.cpp
Labels: bug

#2875 [Feature] 候補を表示して選択するクラス
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/util/candidate-selector.cpp
  src/util/candidate-selector.h
  src/wizard/wizard-special-process.cpp
Labels: enhancement, refactor

#3557 [Fix] クエスト「もの言えぬ証人」のクローカーのマスが暗い
  lib/edit/quests/034_DumpWitness.txt
Labels: enhancement

#3558 [Fix] GitHub Actionsによる自動生成スポイラーページの公開に失敗する
  .github/workflows/publish-spoiler-page.yml
Labels: bug

#3561 画面サイズを取得する関数からint* の引数をなくし、戻り値をXY のpair にした
  src/autopick/autopick-drawer.cpp
  src/cmd-io/cmd-floor.cpp
  src/cmd-io/cmd-process-screen.cpp
  src/cmd-item/cmd-equipment.cpp
  src/cmd-item/cmd-item.cpp
  src/cmd-visual/cmd-draw.cpp
  src/cmd-visual/cmd-map.cpp
  src/core/show-file.cpp
  src/core/window-redrawer.cpp
  src/floor/object-scanner.cpp
  src/io-dump/dump-util.cpp
  src/io/cursor.cpp
  src/io/record-play-movie.cpp
  src/io/report.cpp
  src/io/screen-util.cpp
  src/io/screen-util.h
  src/io/signal-handlers.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/perception/identification.cpp
  src/store/cmd-store.cpp
  src/target/grid-selector.cpp
  src/target/target-checker.cpp
  src/target/target-setter.cpp
  src/term/screen-processor.cpp
  src/term/z-term.cpp
  src/term/z-term.h
  src/util/candidate-selector.cpp
  src/view/display-inventory.cpp
  src/view/display-player-misc-info.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-equipments.cpp
  src/window/main-window-left-frame.cpp
  src/window/main-window-stat-poster.cpp
  src/window/main-window-util.cpp
  src/wizard/cmd-wizard.cpp
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#3560 spoiler_file グローバル変数の使用箇所削減
  src/io-dump/random-art-info-dumper.cpp
  src/io-dump/random-art-info-dumper.h
  src/io/input-key-processor.cpp
  src/util/angband-files.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/fixed-artifacts-spoiler.h
  src/wizard/items-spoiler.cpp
  src/wizard/items-spoiler.h
  src/wizard/spoiler-util.cpp
  src/wizard/spoiler-util.h
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#3568 [Release] 3.0.0.88-Alpha
  doxygen/Hengband.doxyfile
  hengband.spec
  src/system/angband-version.h
Labels: release

#3570 Update spec
  hengband.spec
Labels: enhancement

#3564 concptr の削減
  src/autopick/autopick-drawer.cpp
  src/autopick/autopick-finder.cpp
  src/autopick/autopick-inserter-killer.cpp
  src/avatar/avatar.cpp
  src/birth/character-builder.cpp
  src/cmd-action/cmd-shoot.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-item/cmd-destroy.cpp
  src/cmd-item/cmd-equipment.cpp
  src/cmd-item/cmd-item.cpp
  src/cmd-item/cmd-quaff.cpp
  src/cmd-item/cmd-read.cpp
  src/cmd-item/cmd-refill.cpp
  src/flavor/tval-description-switcher.cpp
  src/game-option/keymap-directory-getter.cpp
  src/inventory/player-inventory.cpp
  src/knowledge/knowledge-quests.cpp
  src/market/building-craft-fix.cpp
  src/market/building-craft-weapon.cpp
  src/market/building-enchanter.cpp
  src/market/building-recharger.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-mage.cpp
  src/mind/mind-magic-eater.cpp
  src/mind/mind-mindcrafter.cpp
  src/mind/mind-priest.cpp
  src/mind/mind-weaponsmith.cpp
  src/realm/realm-hex.cpp
  src/spell-kind/magic-item-recharger.cpp
  src/spell-kind/spells-enchant.cpp
  src/spell-realm/spells-craft.cpp
  src/spell-realm/spells-nature.cpp
  src/spell/spells-object.cpp
  src/spell/spells-summon.cpp
  src/util/angband-files.cpp
  src/view/display-player-middle.cpp
  src/window/main-window-left-frame.cpp
  src/wizard/monster-info-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#3562 spoiler_file グローバル変数の使用箇所削減 その2
  src/wizard/monster-info-spoiler.cpp
  src/wizard/monster-info-spoiler.h
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#3580 サルーインのExpを0→66666に修正
  lib/edit/MonsterRaceDefinitions.txt
Labels: bug
