Repository hengband/hengband, pull requests merged in 2023-06, with the labels that each got.

#3361 memcmp() を廃止した
  src/locale/japanese.cpp
Labels: refactor, Priority:MIDDLE

#3172 ペットの名前に依存して全コマンドに確認を求められる仕様を削除した
  src/io/input-key-requester.cpp
  src/io/input-key-requester.h
Labels: enhancement, refactor

#3363 [Feature] オートローラーの単位をcm、kgに
  src/birth/auto-roller.cpp
Labels: enhancement, Priority:MIDDLE

#3365 FlagGroupクラスのコンストラクタをconstexpr化する
  src/util/enum-range.h
  src/util/flag-group.h
Labels: enhancement

#3367 memcpy() を1箇所削除した
  src/autopick/autopick-describer.cpp
  src/autopick/autopick-reader-writer.cpp
  src/birth/history-editor.cpp
  src/birth/history-generator.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-item/cmd-item.cpp
  src/core/scores.cpp
  src/effect/effect-monster-psi.cpp
  src/effect/effect-monster-spirit.cpp
  src/effect/effect-monster.cpp
  src/effect/effect-player.cpp
  src/inventory/player-inventory.cpp
  src/io/read-pref-file.cpp
  src/melee/melee-postprocess.cpp
  src/melee/melee-spell.cpp
  src/melee/monster-attack-monster.cpp
  src/monster-attack/monster-attack-player.cpp
  src/mspell/mspell-attack.cpp
  src/player-attack/attack-chaos-effect.cpp
  src/player-attack/player-attack.cpp
  src/player/player-damage.cpp
  src/player/process-death.cpp
  src/spell-kind/spells-perception.cpp
  src/store/purchase-order.cpp
  src/util/string-processor.cpp
  src/util/string-processor.h
  src/view/display-self-info.cpp
  src/window/main-window-left-frame.cpp
  src/wizard/artifact-analyzer.cpp
Labels: refactor, Priority:MIDDLE

#3368 memcpy を置換・削除した
  Hengband/Hengband/Hengband.vcxproj
  src/Makefile.am
  src/birth/game-play-initializer.cpp
  src/core/game-play.cpp
  src/core/score-util.cpp
  src/core/score-util.h
  src/core/scores.cpp
  src/core/show-file.cpp
  src/io/inet.h
  src/io/record-play-movie.cpp
  src/io/report.cpp
  src/main.cpp
Labels: refactor, Priority:MIDDLE

#3369 [Refactor] g_window_masks の型を g_window_flags に合わせる
  src/game-option/option-flags.cpp
  src/game-option/option-flags.h
  src/load/option-loader.cpp
  src/main/game-data-initializer.cpp
  src/save/info-writer.cpp
Labels: refactor

#3370 memset() を削除した
  src/floor/floor-generator.cpp
  src/floor/floor-util.cpp
  src/grid/grid.cpp
  src/main-win.cpp
  src/main-win/main-win-utils.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
Labels: refactor, Priority:MIDDLE

#3371 ダングリング参照に陥る不具合を修正した
  src/grid/grid.cpp
Labels: refactor, Priority:MIDDLE

#3372 [Fix] 足元の魔道具の魔力を吸収するとクラッシュする
  src/window/display-sub-windows.cpp
Labels: bug

#3373 dungeons_info からdungeon_type を取得するメソッドへの置換に漏れがあったので対応した
  src/melee/melee-spell-flags-checker.cpp
  src/melee/monster-attack-monster.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-floor/monster-death.cpp
  src/mspell/mspell-lite.cpp
  src/room/space-finder.cpp
  src/specific-object/torch.cpp
  src/spell-kind/spells-lite.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#3375 シンボルエディタのシンボルが非表示になることがある不具合を修正した
  src/io-dump/dump-util.cpp
Labels: bug, Priority:MIDDLE

#3376 汎用的な時止めメッセージを実装した
  src/monster/monster-status-setter.cpp
Labels: enhancement, Priority:MIDDLE

#3377 静的解析警告の解消 その1
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  Hengband/Hengband/packages.config
  src/autopick/autopick-util.h
  src/birth/auto-roller.cpp
  src/cmd-item/cmd-destroy.cpp
  src/spell-realm/spells-craft.cpp
  src/target/target-describer.cpp
  src/term/z-term.cpp
Labels: refactor, Priority:MIDDLE

#3382 静的解析警告の解消 その2
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-charm.h
  src/effect/effect-monster-curse.cpp
  src/effect/effect-monster-curse.h
  src/effect/effect-monster-evil.cpp
  src/effect/effect-monster-evil.h
  src/effect/effect-monster-lite-dark.cpp
  src/effect/effect-monster-lite-dark.h
  src/effect/effect-monster-oldies.cpp
  src/effect/effect-monster-oldies.h
  src/effect/effect-monster-psi.cpp
  src/effect/effect-monster-psi.h
  src/effect/effect-monster-resist-hurt.cpp
  src/effect/effect-monster-resist-hurt.h
  src/effect/effect-monster-spirit.cpp
  src/effect/effect-monster-spirit.h
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-monster-switcher.h
  src/effect/effect-monster-util.cpp
  src/effect/effect-monster-util.h
  src/effect/effect-monster.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-elementalist.h
Labels: refactor, Priority:MIDDLE

#3380 show_file() の引数をchar* からstring_view に変えた
  src/autopick/autopick-editor-command.cpp
  src/birth/birth-util.cpp
  src/cmd-building/cmd-building.cpp
  src/cmd-io/cmd-diary.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-io/cmd-help.cpp
  src/core/show-file.cpp
  src/core/show-file.h
  src/knowledge/knowledge-autopick.cpp
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-inventory.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-mutations.cpp
  src/knowledge/knowledge-quests.cpp
  src/knowledge/knowledge-self.cpp
  src/knowledge/knowledge-uniques.cpp
  src/market/arena.cpp
  src/market/play-gamble.cpp
  src/object-use/read/parchment-read-executor.cpp
Labels: refactor, Priority:MIDDLE

#3384 [Fix] 名前の長いアイテムを博物館に寄贈しようとするとクラッシュする
  src/term/z-term.cpp
Labels: bug

#3387 [Feature] 例外メッセージに追加情報を付与する
  src/autopick/autopick-reader-writer.cpp
  src/core/show-file.cpp
  src/info-reader/fixed-map-parser.cpp
  src/player-base/player-race.cpp
  src/player-info/alignment.cpp
  src/spell-kind/magic-item-recharger.cpp
  src/spell-realm/spells-hex.cpp
  src/status/bad-status-setter.cpp
  src/store/rumor.cpp
  src/system/angband-exceptions.h
  src/system/angband-version.cpp
  src/system/baseitem-info.cpp
  src/timed-effect/player-acceleration.cpp
  src/timed-effect/player-blindness.cpp
  src/timed-effect/player-cut.cpp
  src/timed-effect/player-deceleration.cpp
  src/timed-effect/player-poison.cpp
  src/timed-effect/player-stun.cpp
  src/util/angband-files.cpp
  src/util/probability-table.h
  src/wizard/wizard-messages.cpp
Labels: enhancement, refactor

#3388 静的解析警告の解消 その3
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-others.cpp
  src/effect/spells-effect-util.cpp
  src/effect/spells-effect-util.h
  src/inventory/inventory-util.cpp
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-uniques.cpp
  src/load/player-info-loader.cpp
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/lore/monster-lore.cpp
  src/market/building-initializer.cpp
  src/melee/melee-postprocess.cpp
  src/monster-floor/monster-generator.cpp
  src/object/item-tester-hooker.h
  src/player/player-damage.cpp
  src/room/rooms-city.cpp
  src/save/player-writer.cpp
  src/system/building-type-definition.cpp
  src/system/building-type-definition.h
  src/system/player-type-definition.h
  src/target/grid-selector.cpp
Labels: refactor, Priority:MIDDLE

#3402 [Fix] モンスターを視認していないのに損傷具合が分かってしまう
  src/view/display-monster-status.cpp
Labels: bug

#3398 静的解析警告の解消 その4
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/combat/attack-accuracy.cpp
  src/combat/attack-criticality.cpp
  src/melee/melee-spell-util.cpp
  src/melee/melee-spell-util.h
  src/melee/melee-spell.cpp
  src/mind/mind-ninja.cpp
  src/mind/mind-samurai.cpp
  src/mind/monk-attack.cpp
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-processor.cpp
  src/mspell/element-resistance-checker.cpp
  src/mspell/high-resistance-checker.cpp
  src/mspell/improper-mspell-remover.cpp
  src/mspell/mspell-attack-util.cpp
  src/mspell/mspell-attack-util.h
  src/mspell/mspell-attack.cpp
  src/mspell/smart-mspell-util.cpp
  src/mspell/smart-mspell-util.h
  src/object-enchant/vorpal-weapon.cpp
  src/player-attack/attack-chaos-effect.cpp
  src/player-attack/blood-sucking-processor.cpp
  src/player-attack/player-attack-util.h
  src/player-attack/player-attack.cpp
  src/player-attack/player-attack.h
  src/player-info/self-info-util.cpp
  src/player-info/self-info-util.h
  src/player-info/self-info.cpp
  src/room/rooms-vault.h
  src/specific-object/death-scythe.cpp
Labels: refactor, Priority:MIDDLE

#3404 [Feature] ウインドウ・フラグ「ペット一覧」
  src/core/player-processor.cpp
  src/core/window-redrawer.cpp
  src/monster/monster-describer.cpp
  src/monster/monster-description-types.h
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/system/redrawing-flags-updater.cpp
  src/system/redrawing-flags-updater.h
  src/target/target-preparation.cpp
  src/target/target-preparation.h
  src/term/gameterm.cpp
  src/window/display-sub-windows.cpp
  src/window/display-sub-windows.h
  src/window/main-window-left-frame.cpp
Labels: enhancement

#3413 地形の明度変更コマンド打鍵時にシンボル一覧が表示されない不具合を修正した
  src/knowledge/knowledge-features.cpp
Labels: bug, Priority:MIDDLE

#3408 [Fix] 呪術と歌の詠唱時の配列範囲外アクセス
  src/player/player-skill.cpp
  src/realm/realm-names-table.h
Labels: bug

#3405 静的解析警告の解消 その5
  src/autopick/autopick-editor-util.cpp
  src/birth/birth-select-personality.cpp
  src/cmd-action/cmd-hissatsu.cpp
  src/dungeon/quest-completion-checker.cpp
  src/io/record-play-movie.cpp
  src/main-win.cpp
  src/market/building-craft-armor.cpp
  src/market/building-craft-armor.h
  src/mind/mind-elementalist.cpp
  src/mind/mind-power-getter.cpp
  src/mind/mind-power-getter.h
  src/mind/mind-samurai.cpp
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/room/space-finder.cpp
  src/status/bad-status-setter.cpp
  src/target/target-preparation.cpp
  src/timed-effect/player-cut.cpp
  src/timed-effect/player-cut.h
  src/wizard/spoiler-util.h
Labels: refactor, Priority:MIDDLE

#3411 アイテム/モンスターをランダム生成するウィザードコマンドを実装した
  src/core/game-play.cpp
  src/core/player-processor.cpp
  src/dungeon/quest-monster-placer.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-generator.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-generator.h
  src/monster-floor/monster-summon.cpp
  src/object-enchant/item-apply-magic.h
  src/object-use/read/scroll-read-executor.cpp
  src/player/patron.cpp
  src/room/rooms-pit-nest.cpp
  src/room/rooms-special.cpp
  src/room/rooms-vault.cpp
  src/room/treasure-deployment.cpp
  src/room/vault-builder.cpp
  src/specific-object/monster-ball.cpp
  src/spell-kind/spells-polymorph.cpp
  src/spell/spells-object.cpp
  src/spell/spells-object.h
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
Labels: enhancement, refactor, Priority:MIDDLE

#3415 [Release] 3.0.0.85
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3421 もう使われていないinet.cpp を削除した
  src/io/inet.cpp
Labels: refactor, Priority:MIDDLE

#3422 msg_format(string_view,...) のオーバーロードを削除した
  src/mspell/mspell-util.cpp
  src/view/display-messages.cpp
  src/view/display-messages.h
Labels: refactor, Priority:MIDDLE

#3423 [Refactor] report.cpp
  src/io/report.cpp
Labels: refactor

#3424 quarks.cpp/h を削除した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/activation-execution.cpp
  src/artifact/random-art-generator.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-util.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-item/cmd-item.cpp
  src/flavor/flavor-describer.cpp
  src/flavor/flavor-util.cpp
  src/flavor/named-item-describer.cpp
  src/flavor/object-flavor.cpp
  src/inventory/inventory-curse.cpp
  src/inventory/inventory-util.cpp
  src/inventory/recharge-processor.cpp
  src/io/input-key-requester.cpp
  src/io/interpret-pref-file.cpp
  src/load/old/item-loader-savefile50.cpp
  src/load/old/load-v1-5-0.cpp
  src/load/old/monster-loader-savefile50.cpp
  src/main/game-data-initializer.cpp
  src/monster/monster-describer.cpp
  src/object-activation/activation-others.cpp
  src/player/player-status-flags.cpp
  src/player/player-status-resist.cpp
  src/player/player-status.cpp
  src/save/item-writer.cpp
  src/save/monster-writer.cpp
  src/store/store.cpp
  src/term/gameterm.cpp
  src/util/quarks.cpp
  src/util/quarks.h
  src/wizard/artifact-analyzer.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/fixed-artifacts-spoiler.h
  src/wizard/spoiler-table.cpp
  src/wizard/spoiler-table.h
  src/wizard/spoiler-util.h
Labels: refactor, Priority:MIDDLE

#3426 [Refactor] record-play-movie.cpp
  src/io/record-play-movie.cpp
Labels: refactor

#3427 [Fix] ムービーファイルの上書き確認メッセージにゴミが入っている
  src/io/record-play-movie.cpp
Labels: bug

#3428 [Refactor] 自動拾いのエディタのヤンクバッファ処理
  src/autopick/autopick-editor-command.cpp
  src/autopick/autopick-editor-util.cpp
  src/autopick/autopick-util.h
  src/cmd-io/cmd-autopick.cpp
Labels: refactor

#3425 Update the Version in hengband.spec
  hengband.spec
Labels: enhancement

#3430 [Fix] 体格オートローラで指定した値で止まらない
  src/birth/auto-roller.cpp
  src/birth/birth-wizard.cpp
  src/locale/japanese.h
  src/view/display-player.cpp
Labels: bug

#3434 [Fix] メイン画面左に表示されるモンスターの状態表示の一部が残る
  src/window/main-window-left-frame.cpp
Labels: bug

#3443 [Fix] get_open_filename関数でのダングリングポインタ参照
  src/main-win/main-win-utils.cpp
  src/main-win/main-win-utils.h
Labels: bug

#3444 [Fix] 自動拾いエディタの配列範囲外アクセス
  src/autopick/autopick-editor-command.cpp
Labels: bug

#3440 [Feature] Xft/X11版でカーソルおよび選択領域の下の文字をわかるようにする
  src/main-x11.cpp
Labels: enhancement

#3435 get_value() の引数からchar* を消し、戻り値をoptional<string> に変えた
  src/artifact/fixed-art-types.h
  src/autopick/autopick-matcher.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-io/cmd-process-screen.cpp
  src/cmd-io/cmd-process-screen.h
  src/cmd-visual/cmd-draw.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/asking-player.cpp
  src/core/asking-player.h
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-uniques.cpp
  src/main-win/main-win-utils.cpp
  src/market/building-monster.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/race-indice-types.h
  src/monster/monster-describer.cpp
  src/monster/monster-status.cpp
  src/player/process-death.cpp
  src/player/process-name.cpp
  src/store/rumor.cpp
  src/system/h-type.h
  src/util/string-processor.cpp
  src/util/string-processor.h
  src/view/display-messages.cpp
  src/view/display-messages.h
  src/window/display-sub-windows.cpp
  src/wizard/monster-info-spoiler.cpp
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
Labels: refactor, Priority:MIDDLE

#3452 [Refactor] message_strの戻り値を変更
  src/cmd-visual/cmd-draw.cpp
  src/io-dump/character-dump.cpp
  src/save/save.cpp
  src/view/display-messages.cpp
  src/view/display-messages.h
  src/window/display-sub-windows.cpp
Labels: refactor

#3454 [Feature] HTTP通信機能クラス
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  configure.ac
  src/Makefile.am
  src/io/report.cpp
  src/net/curl-easy-session.cpp
  src/net/curl-easy-session.h
  src/net/curl-slist.cpp
  src/net/curl-slist.h
  src/net/http-client.cpp
  src/net/http-client.h
Labels: enhancement

#3457 静的警告の解消 その7
  src/autopick/autopick-describer.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-io/cmd-lore.cpp
  src/cmd-visual/cmd-draw.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/asking-player.cpp
  src/core/asking-player.h
  src/core/show-file.cpp
  src/floor/pattern-walk.cpp
  src/io/record-play-movie.cpp
  src/market/arena.cpp
  src/market/building-monster.cpp
  src/market/play-gamble.cpp
  src/mind/mind-weaponsmith.cpp
  src/spell-kind/spells-world.cpp
  src/util/string-processor.cpp
  src/util/string-processor.h
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
Labels: refactor, Priority:MIDDLE

#3456 [Fix] メッセージ表示位置のずれ
  src/cmd-visual/cmd-map.cpp
  src/core/game-closer.cpp
Labels: bug

#3464 修行僧で酔っ払いの薬を飲むと時々記憶を失い、その他のクラスでは記憶を失わない不具合を解消した
  src/object-use/quaff/quaff-effects.cpp
Labels: bug, Priority:MIDDLE

#3465 [Fix] デバッグコマンドのステータス変更が反映されない
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/util/finalizer.h
  src/wizard/wizard-special-process.cpp
Labels: bug, refactor

#3468 MSVCにおけるC++バージョンをC++20に統一した
  Hengband/Hengband/Hengband.vcxproj
Labels: bug, Priority:Critical

#3472 [Release] 3.0.0.86(Alpha)
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3471 [Chore] MSVCでのビルドテストを行うワークフロー
  .github/workflows/build-test-with-msvc.yml
  .github/workflows/pull-request-status-check.yml
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/curl/lib/libcurl_a_debug.lib
  Makefile.am
Labels: enhancement

#3475 [Feature] 文字列入力で先頭と末尾に移動
  src/core/asking-player.cpp
Labels: enhancement

#3478 [Fix] Player spells infoスポイラーの出力でクラッシュ
  src/wizard/wizard-spoiler.cpp
Labels: bug

#3479 [Fix] 英語版に日本語のメッセージが含まれる
  src/action/racial-execution.cpp
  src/artifact/random-art-characteristics.cpp
  src/market/bounty.cpp
  src/realm/realm-hex.cpp
  src/room/rooms-pit-nest.cpp
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-spoiler.cpp
Labels: bug

#3476 [Feature] デバッグコマンドで一発で全ステータスをMAXにする機能
  src/wizard/wizard-special-process.cpp
Labels: enhancement

#3469 静的解析警告対応 その8
  src/artifact/random-art-generator.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-action/cmd-others.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-io/cmd-diary.cpp
  src/cmd-io/cmd-dump.cpp
  src/cmd-io/cmd-lore.cpp
  src/cmd-io/cmd-process-screen.cpp
  src/cmd-item/cmd-item.cpp
  src/cmd-visual/cmd-draw.cpp
  src/core/asking-player.cpp
  src/core/asking-player.h
  src/core/show-file.cpp
  src/io/files-util.cpp
  src/io/files-util.h
  src/io/record-play-movie.cpp
  src/market/building-monster.cpp
  src/market/play-gamble.cpp
  src/market/play-gamble.h
  src/player/player-damage.cpp
  src/player/process-death.cpp
  src/player/process-name.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-spells.cpp
Labels: refactor, Priority:MIDDLE
