Repository hengband/hengband, pull requests merged in 2023-08, with the labels that each got.

#3582 [Fix] 突然変異の炎のブレス威力表記がレベルx1になっていたものを実際通り、レベルx2に修正。
  src/racial/mutation-racial-selector.cpp
Labels: bug

#3576 隕石属性のボール・ボルトを追加
  lib/edit/MonsterRaceDefinitions.txt
  src/blue-magic/blue-magic-ball-bolt.cpp
  src/blue-magic/blue-magic-ball-bolt.h
  src/blue-magic/blue-magic-caster.cpp
  src/blue-magic/learnt-info.cpp
  src/cmd-action/cmd-mane.cpp
  src/effect/effect-monster-resist-hurt.cpp
  src/effect/effect-monster-resist-hurt.h
  src/effect/effect-monster-switcher.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/lore/magic-types-setter.cpp
  src/monster-race/race-ability-flags.h
  src/monster-race/race-ability-mask.cpp
  src/monster-race/race-flags-resistance.h
  src/mspell/assign-monster-spell.cpp
  src/mspell/monster-power-table.cpp
  src/mspell/mspell-attack/mspell-ball.cpp
  src/mspell/mspell-attack/mspell-bolt.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/mspell/mspell-selector.cpp
  src/view/display-lore-status.cpp
Labels: enhancement

#3584 English: add colon and space after prompt for last words
  src/player/player-damage.cpp
Labels: bug

#3590 [Release] 3.0.0.89-Alpha
  doxygen/Hengband.doxyfile
  hengband.spec
  src/system/angband-version.h
Labels: release

#3591 Release/3.0.0.89 alpha
  doxygen/Hengband.doxyfile
  hengband.spec
  lib/edit/MonsterRaceDefinitions.txt
  src/autopick/autopick-drawer.cpp
  src/autopick/autopick-finder.cpp
  src/autopick/autopick-inserter-killer.cpp
  src/avatar/avatar.cpp
  src/birth/character-builder.cpp
  src/cmd-action/cmd-shoot.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-item/cmd-destroy.cpp
  src/cmd-item/cmd-equipment.cpp
  src/cmd-item/cmd-item.cpp
  src/cmd-item/cmd-quaff.cpp
  src/cmd-item/cmd-read.cpp
  src/cmd-item/cmd-refill.cpp
  src/flavor/tval-description-switcher.cpp
  src/game-option/keymap-directory-getter.cpp
  src/inventory/player-inventory.cpp
  src/knowledge/knowledge-quests.cpp
  src/market/building-craft-fix.cpp
  src/market/building-craft-weapon.cpp
  src/market/building-enchanter.cpp
  src/market/building-recharger.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-mage.cpp
  src/mind/mind-magic-eater.cpp
  src/mind/mind-mindcrafter.cpp
  src/mind/mind-priest.cpp
  src/mind/mind-weaponsmith.cpp
  src/realm/realm-hex.cpp
  src/spell-kind/magic-item-recharger.cpp
  src/spell-kind/spells-enchant.cpp
  src/spell-realm/spells-craft.cpp
  src/spell-realm/spells-nature.cpp
  src/spell/spells-object.cpp
  src/spell/spells-summon.cpp
  src/system/angband-version.h
  src/util/angband-files.cpp
  src/view/display-player-middle.cpp
  src/window/main-window-left-frame.cpp
  src/wizard/monster-info-spoiler.cpp
  src/wizard/monster-info-spoiler.h
  src/wizard/wizard-spoiler.cpp
Labels: release

#3588 赤チォコヴォLv99を実装
  lib/edit/MonsterRaceDefinitions.txt
Labels: enhancement

#3596 ケット・シー及びイェンダーの魔法使い(YENDER_WIZARD_2)を地上で倒すとハングアップするバグを修正
  src/monster-floor/special-death-switcher.cpp
Labels: bug, Priority:Critical

#3586 spell-selector用のマスクを追加し、spell_between()を廃止した
  src/monster-race/race-ability-mask.cpp
  src/monster-race/race-ability-mask.h
  src/mspell/mspell-selector.cpp
Labels: refactor, Priority:MIDDLE

#3587 ものまねの範囲指定を全部マスクに移した
  src/cmd-action/cmd-mane.cpp
Labels: refactor, Priority:MIDDLE
