Repository hengband/hengband, pull requests merged in 2024-02, with the labels that each got.

#3852 [Fix] 悪魔領域の血の呪いの追加効果発生場所が正しくない
  src/effect/effect-monster.cpp
Labels: bug

#3847 [Refactor] 保存済フロア読込関連の可読性向上
  src/floor/floor-changer.cpp
Labels: refactor

#3854 [Release] 3.0.1.7-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3857 Update hengband.spec
  hengband.spec
Labels: release

#3866 [Fix] 属性への免疫を唱えた時のメッセージ
  src/spell-realm/spells-craft.cpp
Labels: bug
