Repository hengband/hengband, pull requests merged in 2024-07, with the labels that each got.

#4373 [Fix] スポイラーの魔法領域出力の内容がおかしい
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/wizard/wizard-spoiler.cpp
Labels: bug, enhancement

#4336 [Refactor] ClassMagicDefinitionsの魔法読込をidから名称に変更する
  lib/edit/ClassMagicDefinitions.jsonc
  schema/ClassMagicDefinitions.schema.json
  src/info-reader/magic-reader.cpp
  src/system/spell-info-list.cpp
  src/system/spell-info-list.h
Labels: refactor

#4375 [Refactor] 領域が有効か調べる判定
  src/avatar/avatar.cpp
  src/birth/character-builder.cpp
  src/cmd-action/cmd-spell.cpp
  src/io/read-pref-file.cpp
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-self.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/view/display-player.cpp
  src/view/object-describer.cpp
  src/window/display-sub-windows.cpp
Labels: refactor

#4376 [Reafctor] 特定の領域かどうかを調べる判定
  src/cmd-action/cmd-spell.cpp
  src/knowledge/knowledge-experiences.cpp
  src/player-ability/player-constitution.cpp
  src/player-ability/player-dexterity.cpp
  src/player-ability/player-strength.cpp
  src/player-base/player-class.cpp
  src/player-info/class-ability-info.cpp
  src/player-status/player-speed.cpp
  src/player-status/player-stealth.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/player/player-skill.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/racial/class-racial-switcher.cpp
  src/racial/racial-switcher.cpp
  src/spell/spell-info.cpp
  src/view/object-describer.cpp
  src/window/main-window-stat-poster.cpp
Labels: refactor

#4377 [Refactor] キャラメイク時の領域選択処理
  src/birth/birth-select-realm.cpp
Labels: refactor

#4381 [Refactor] 呪文の名称と説明文の取得処理
  src/cmd-action/cmd-hissatsu.cpp
  src/cmd-action/cmd-spell.cpp
  src/knowledge/knowledge-experiences.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/player/player-status.cpp
  src/realm/realm-arcane.cpp
  src/realm/realm-chaos.cpp
  src/realm/realm-craft.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-death.cpp
  src/realm/realm-demon.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-hissatsu.cpp
  src/realm/realm-life.cpp
  src/realm/realm-nature.cpp
  src/realm/realm-song.cpp
  src/realm/realm-sorcery.cpp
  src/realm/realm-trump.cpp
  src/spell-realm/spells-hex.cpp
  src/spell/spell-info.cpp
  src/spell/spells-util.h
  src/window/display-sub-windows.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor

#4382 [Refactor] SpellInfoListクラスのカプセル化を促進
  src/info-reader/spell-reader.cpp
  src/info-reader/spell-reader.h
  src/main/info-initializer.cpp
  src/player/player-realm.cpp
  src/system/spell-info-list.cpp
  src/system/spell-info-list.h
Labels: refactor

#4383 [Refactor] 領域の説明の取得処理
  src/birth/birth-explanations-table.cpp
  src/birth/birth-explanations-table.h
  src/birth/birth-select-realm.cpp
  src/knowledge/knowledge-self.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/realm/realm-names-table.h
Labels: refactor

#4384 [Refactor] 魔法書のItemKindTypeから領域を取得する処理
  src/birth/inventory-initializer.cpp
  src/cmd-action/cmd-spell.cpp
  src/object-hook/hook-magic.cpp
  src/object/object-info.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/realm/realm-names-table.h
  src/view/object-describer.cpp
Labels: refactor

#4387 [Refactor] 魔法領域のセット処理
  src/birth/birth-select-realm.cpp
  src/birth/quick-start.cpp
  src/cmd-action/cmd-spell.cpp
  src/load/load-zangband.cpp
  src/load/player-info-loader.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/wizard/wizard-special-process.cpp
Labels: refactor

#4389 [Refactor] 魔法領域の取得処理
  src/avatar/avatar.cpp
  src/birth/inventory-initializer.cpp
  src/birth/quick-start.cpp
  src/cmd-action/cmd-spell.cpp
  src/load/load-zangband.cpp
  src/market/building-service.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/save/player-writer.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor

#4390 [Refactor] 魔法領域の種類が呪文か技術かを判定する処理
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/avatar/avatar.cpp
  src/birth/birth-select-realm.cpp
  src/cmd-action/cmd-spell.cpp
  src/core/game-play.cpp
  src/floor/wild.cpp
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-self.cpp
  src/market/building-service.cpp
  src/object-hook/hook-magic.cpp
  src/object/object-info.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/player/player-skill.cpp
  src/player/player-status.cpp
  src/realm/realm-names-table.cpp
  src/realm/realm-names-table.h
  src/spell/spell-info.cpp
  src/spell/spells-execution.cpp
  src/view/object-describer.cpp
  src/window/display-sub-windows.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor

#4391 [Refactor] 領域の列挙値をenum classにする
  src/avatar/avatar.cpp
  src/birth/birth-select-realm.cpp
  src/birth/inventory-initializer.cpp
  src/birth/quick-start.cpp
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-hissatsu.cpp
  src/cmd-action/cmd-spell.cpp
  src/info-reader/magic-reader.cpp
  src/info-reader/spell-reader.cpp
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-experiences.cpp
  src/load/load-zangband.cpp
  src/load/player-info-loader.cpp
  src/market/building-service.cpp
  src/mind/mind-blue-mage.cpp
  src/object-hook/hook-magic.cpp
  src/object/object-info.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/player/player-skill.cpp
  src/player/player-skill.h
  src/player/player-status-flags.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-hissatsu.cpp
  src/realm/realm-types.h
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-song.cpp
  src/spell/spell-info.cpp
  src/spell/spell-info.h
  src/spell/spells-execution.cpp
  src/spell/spells-execution.h
  src/system/player-type-definition.h
  src/system/spell-info-list.cpp
  src/system/spell-info-list.h
  src/view/display-player.cpp
  src/view/object-describer.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor

#4392 [Fix] 第2領域変更後の魔法選択がおかしい
  src/cmd-action/cmd-spell.cpp
Labels: bug

#4394 [Fix] 魔法領域なしの職業のセーブデータで起動するとクラッシュ
  src/birth/quick-start.cpp
  src/load/player-info-loader.cpp
Labels: bug

#4399 [Feature] エラーレポートにコールスタック情報を含める
  Build-Windows-Release-Package.ps1
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/main-unix/stack-trace-unix.cpp
  src/main-win/main-win-exception.cpp
  src/main-win/stack-trace-win.cpp
  src/system/angband-exceptions.h
  src/util/stack-trace.h
Labels: enhancement

#4404 [Fix] 神の怒りを画面端に打つとクラッシュする
  src/spell-realm/spells-crusade.cpp
Labels: bug

#4400 [Refactor] カメレオンの種族選択処理のモンスターの位置情報への依存をなくした
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-list.cpp
  src/monster/monster-list.h
  src/monster/monster-processor.cpp
Labels: refactor

#4402 [Fix] カメレオンが爆発するモンスターに変身してしまう
  src/monster/monster-list.cpp
Labels: bug

#4408 [Fix] 乗馬中のカメレオンが変身した際のメッセージで変身後の名前で表示されてしまうバグを修正
  src/monster/monster-processor.cpp
Labels: bug

#4332 [Feature] デバッグコマンドの種族・職業・領域変更をリストから選択
  src/wizard/wizard-special-process.cpp
Labels: enhancement

#4407 [Fix] ヘルスバー下部に表示されるモンスターの状態が更新されない
  src/monster/monster-status.cpp
Labels: bug

#4410 モンスター「地獄の出店」を追加
  lib/edit/MonraceDefinitions.jsonc
Labels: enhancement

#4412 [Release] 3.0.1.17-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#4411 [Refactor] カメレオンの変身処理を種族番号の代入処理に統合した
  src/monster-floor/one-monster-placer.cpp
Labels: refactor

#4415 Update hengband.spec version to 3.0.1.17
  hengband.spec
Labels: release

#4420 [Fix] 空の名前が設定できてしまう
  src/player/process-name.cpp
Labels: bug

#4416 [Refactor] summon_specificのシグニチャ
  src/action/mutation-execution.cpp
  src/blue-magic/blue-magic-summon.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/grid/trap.cpp
  src/inventory/inventory-curse.cpp
  src/mind/mind-force-trainer.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-generator.h
  src/monster-floor/monster-summon.cpp
  src/monster-floor/monster-summon.h
  src/monster-floor/special-death-switcher.cpp
  src/monster/monster-processor.cpp
  src/mspell/mspell-summon.cpp
  src/mspell/specified-summon.cpp
  src/mutation/mutation-processor.cpp
  src/object-activation/activation-switcher.cpp
  src/object-use/read/scroll-read-executor.cpp
  src/player/patron.cpp
  src/realm/realm-arcane.cpp
  src/realm/realm-craft.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-demon.cpp
  src/realm/realm-nature.cpp
  src/specific-object/chest.cpp
  src/spell-kind/blood-curse.cpp
  src/spell-kind/spells-random.cpp
  src/spell-realm/spells-trump.cpp
  src/spell/spells-summon.cpp
  src/spell/spells-summon.h
  src/wizard/wizard-spells.cpp
Labels: refactor

#4424 [Fix] エラーレポートの文字化け
  src/main-win/main-win-exception.cpp
Labels: enhancement

#4422 [Refactor] PlayerType::spell_order
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-hissatsu.cpp
  src/cmd-action/cmd-spell.cpp
  src/load/inventory-loader.cpp
  src/player/player-status.cpp
  src/save/save.cpp
  src/system/player-type-definition.h
Labels: refactor

#4425 [Fix] WindowsのシステムロケールがUTF-8の時クラッシュする
  src/util/angband-files.cpp
Labels: enhancement

#4426 [Fix] システムロケールがUTF-8の時BGM・効果音が鳴らないことがある
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/main-win.cpp
  src/main-win/main-win-cfg-reader.cpp
  src/main-win/main-win-cfg-reader.h
  src/main-win/main-win-file-utils.cpp
  src/main-win/main-win-file-utils.h
  src/main-win/main-win-music.cpp
  src/main-win/main-win-sound.cpp
  src/main-win/wav-reader.cpp
  src/main-win/wav-reader.h
Labels: enhancement

#4430 [Refactor] 呪文の学習・試行・忘却状態の処理
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-hissatsu.cpp
  src/cmd-action/cmd-spell.cpp
  src/load/load-zangband.cpp
  src/player/player-spell-status.cpp
  src/player/player-spell-status.h
  src/player/player-status.cpp
  src/spell/spell-info.cpp
  src/window/display-sub-windows.cpp
  src/wizard/wizard-special-process.cpp
Labels: bug, refactor

#4431 [Refactor] CfgReader
  src/main-win/main-win-cfg-reader.cpp
  src/main-win/main-win-cfg-reader.h
  src/main-win/main-win-music.cpp
  src/main-win/main-win-music.h
  src/main-win/main-win-sound.cpp
  src/main-win/main-win-sound.h
Labels: refactor

#4433 [Fix] 8bitサンプリングの効果音にノイズが乗る
  src/main-win/main-win-sound.cpp
Labels: bug

#4434 [Fix] システムロケールがUTF-8の時設定フォルダを開くのに失敗する
  src/main-win.cpp
  src/main-win/main-win-utils.cpp
  src/main-win/main-win-utils.h
Labels: enhancement

#4417 [Feature] 悪魔領域最終攻撃魔法の差し替え
  lib/edit/ClassMagicDefinitions.jsonc
  lib/edit/SpellDefinitions.jsonc
  src/realm/realm-demon.cpp
Labels: enhancement

#4436 [Fix] 凡庸の巻物をモンスターの人形・像・骨・死体に使用するとクラッシュ
  src/spell-kind/spells-enchant.cpp
Labels: bug

#4438 set_target()（及びreset_target()）、set_friendly() をMonsterEntity に組み込んだ
  src/combat/shoot.cpp
  src/effect/effect-monster.cpp
  src/floor/floor-generator.cpp
  src/load/old/load-v1-5-0.cpp
  src/melee/melee-postprocess.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-move.h
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-info.cpp
  src/monster/monster-processor.cpp
  src/monster/monster-status-setter.cpp
  src/monster/monster-status-setter.h
  src/mspell/mspell-attack.cpp
  src/spell-kind/spells-teleport.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
Labels: refactor

#3941 ウサウサストライカーの性能を調整
  lib/edit/MonraceDefinitions.jsonc
  src/birth/game-play-initializer.cpp
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-oldies.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/load/lore-loader.cpp
  src/market/bounty.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/race-population-flags.h
  src/monster/monster-list.cpp
  src/mspell/specified-summon.cpp
  src/system/system-variables.h
Labels: enhancement

#4442 [Fix] 骨から矢、クロスボウの矢を生成する時に骨が重ね書きされて消滅する不具合を修正。
  src/mind/mind-archer.cpp
Labels: bug

#4444 [Release] 3.0.1.18-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#4455 [Refactor] MonsterConstantFlagType に騎乗フラグを追加した
  src/cmd-action/cmd-pet.cpp
  src/core/game-play.cpp
  src/floor/floor-leaver.cpp
  src/load/extra-loader.cpp
  src/mind/mind-cavalry.cpp
  src/monster-floor/monster-remover.cpp
  src/monster/monster-flag-types.h
  src/pet/pet-fall-off.cpp
  src/pet/pet-util.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
Labels: refactor

#4456 [Fix] MonraceDefinitions.shcema.jsoncの修正
  schema/MonraceDefinitions.schema.json
Labels: bug
