Repository hengband/hengband, pull requests merged in 2024-06, with the labels that each got.

#4190 [Feature] 新しいバージョンのセーブデータを読み込まないようにする
  src/load/load.cpp
Labels: enhancement

#4186 [Refactor] モンスターに関する情報の表示処理
  src/lore/lore-calculator.cpp
  src/lore/lore-calculator.h
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/lore/magic-types-setter.cpp
  src/lore/monster-lore.cpp
  src/view/display-lore-attacks.cpp
  src/view/display-lore-magics.cpp
  src/view/display-lore-status.cpp
  src/view/display-lore.cpp
Labels: refactor

#4185 FloorChangeModesStore クラスを作ってPlayerType::change_floor_mode を廃止した
  src/cmd-action/cmd-move.cpp
  src/cmd-building/cmd-building.cpp
  src/core/game-play.cpp
  src/dungeon/quest.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-mode-changer.cpp
  src/floor/floor-mode-changer.h
  src/floor/floor-save.cpp
  src/floor/floor-save.h
  src/floor/pattern-walk.cpp
  src/grid/trap.cpp
  src/load/dungeon-loader.cpp
  src/market/arena.cpp
  src/monster-floor/monster-safety-hiding.cpp
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/spell-kind/spells-world.cpp
  src/system/player-type-definition.h
  src/wizard/wizard-special-process.cpp
  src/world/world-movement-processor.cpp
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#4184 [Refactor] メッセージ履歴の繰り返しの保持方法の変更
  src/load/info-loader.cpp
  src/save/save.cpp
  src/system/angband-version.h
  src/view/display-messages.cpp
  src/view/display-messages.h
Labels: enhancement, refactor

#4191 MonraceRace::is_valid() を廃止してMonsterEntity/MonsterRaceInfo/MonraceList に分散させた
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-attack.cpp
  src/core/player-processor.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/effect/effect-monster.cpp
  src/flavor/tval-description-switcher.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-leaver.cpp
  src/floor/wild.cpp
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-quests.cpp
  src/knowledge/knowledge-uniques.cpp
  src/load/quest-loader.cpp
  src/lore/monster-lore.cpp
  src/main/angband-initializer.cpp
  src/main/game-data-initializer.cpp
  src/market/arena.cpp
  src/market/building-monster.cpp
  src/melee/monster-attack-monster.cpp
  src/monster-attack/monster-attack-processor.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-remover.cpp
  src/monster-floor/monster-summon.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race.cpp
  src/monster-race/monster-race.h
  src/monster/monster-compaction.cpp
  src/monster/monster-list.cpp
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor.cpp
  src/monster/monster-status.cpp
  src/mspell/summon-checker.cpp
  src/object/object-value.cpp
  src/room/pit-nest-util.cpp
  src/room/rooms-special.cpp
  src/spell-kind/blood-curse.cpp
  src/spell-kind/spells-pet.cpp
  src/spell-kind/spells-polymorph.cpp
  src/spell-kind/spells-sight.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-kind/spells-world.cpp
  src/system/dungeon-info.cpp
  src/system/dungeon-info.h
  src/system/monster-entity.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/view/display-lore-status.cpp
  src/view/display-lore.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-left-frame.cpp
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#4199 [Release] 3.0.1.13-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#4205 [Refactor] セーブファイルの文字コードをenum class化
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/load/floor-loader.cpp
  src/load/info-loader.cpp
  src/load/load-util.cpp
  src/load/load-util.h
  src/locale/character-encoding.h
  src/locale/japanese.cpp
  src/locale/japanese.h
  src/save/save.cpp
Labels: bug, refactor

#4210 モンスター撃破時に経験値が入らない不具合を修正した to develop
  configure.ac
  doxygen/Hengband.doxyfile
  src/monster/monster-damage.cpp
  src/monster/monster-damage.h
  src/system/angband-version.h
Labels: bug, Priority:Critical

#4211 モンスター撃破時に経験値が入らない不具合を修正した to master
  configure.ac
  doxygen/Hengband.doxyfile
  src/monster/monster-damage.cpp
  src/monster/monster-damage.h
  src/system/angband-version.h
Labels: bug, Priority:Critical

#4207 [Refactor] strnfmtとvstrnfmtをそれぞれformatとvformatで置き換える
  src/autopick/autopick-editor-command.cpp
  src/birth/auto-roller.cpp
  src/birth/birth-select-class.cpp
  src/birth/birth-select-personality.cpp
  src/birth/birth-select-race.cpp
  src/birth/birth-select-realm.cpp
  src/birth/birth-wizard.cpp
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-racial.cpp
  src/floor/floor-save.cpp
  src/floor/object-scanner.cpp
  src/inventory/floor-item-getter.cpp
  src/inventory/item-getter.cpp
  src/inventory/item-selection-util.h
  src/inventory/player-inventory.cpp
  src/io-dump/dump-remover.cpp
  src/io/files-util.cpp
  src/io/input-key-requester.cpp
  src/io/pref-file-expressor.cpp
  src/io/read-pref-file.cpp
  src/load/floor-loader.cpp
  src/main-cap.cpp
  src/main-x11.cpp
  src/melee/monster-attack-monster.cpp
  src/mind/mind-monk.cpp
  src/mind/mind-samurai.cpp
  src/mind/mind-sniper.cpp
  src/racial/racial-util.h
  src/save/floor-writer.cpp
  src/spell-kind/spells-world.cpp
  src/spell-realm/spells-sorcery.cpp
  src/target/target-describer.cpp
  src/target/target-setter.cpp
  src/term/z-form.cpp
  src/term/z-form.h
  src/util/angband-files.cpp
  src/view/display-inventory.cpp
  src/view/display-messages.cpp
  src/window/main-window-equipments.cpp
  src/wizard/wizard-messages.cpp
Labels: refactor

#4208 TerrainList::[] をget_terrain() に差し替えた
  src/action/open-close-execution.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/floor/cave.cpp
  src/floor/floor-streams.cpp
  src/floor/object-allocator.cpp
  src/grid/feature.cpp
  src/grid/grid.cpp
  src/grid/trap.cpp
  src/info-reader/feature-reader.cpp
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-features.cpp
  src/monster/monster-info.cpp
  src/player/player-move.cpp
  src/room/rooms-trap.cpp
  src/spell-kind/spells-floor.cpp
  src/store/purchase-order.cpp
  src/system/artifact-type-definition.cpp
  src/system/grid-type-definition.cpp
  src/system/monster-race-info.cpp
  src/system/terrain-type-definition.cpp
  src/system/terrain-type-definition.h
  src/target/target-describer.cpp
  src/view/display-map.cpp
  src/view/display-store.cpp
  src/window/display-sub-windows.cpp
Labels: refactor, Priority:MIDDLE

#4206 MonraceList::[] をMonraceList::get_monrace() に変えた
  src/dungeon/quest.cpp
  src/io-dump/character-dump.cpp
  src/market/bounty.cpp
  src/mspell/mspell-special.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#4217 バイアスはないが発動はあるランダムアーティファクトを生成しようとすると例外を吐く設計を吐かないように修正した to develop
  src/artifact/random-art-activation.cpp
Labels: bug, Priority:Critical

#4219 プレイヤー作成ウィザードで未初期化文字を表示してしまう不具合を修正した
  src/birth/birth-wizard.cpp
Labels: bug, Priority:MIDDLE

#4213 [Refactor] *Listクラスの内部コンテナの参照を得るメンバ関数を削除
  src/floor/floor-generator.cpp
  src/grid/trap.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/feature-reader.cpp
  src/info-reader/feature-reader.h
  src/info-reader/general-parser.cpp
  src/info-reader/magic-reader.cpp
  src/info-reader/skill-reader.cpp
  src/main/angband-headers.h
  src/main/angband-initializer.cpp
  src/main/info-initializer.cpp
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/terrain-type-definition.cpp
  src/system/terrain-type-definition.h
Labels: refactor

#4226 [Refactor] init_info/init_jsonの戻り値をvoidにする
  src/info-reader/dungeon-reader.cpp
  src/info-reader/dungeon-reader.h
  src/main/angband-initializer.cpp
  src/main/info-initializer.cpp
  src/main/info-initializer.h
Labels: refactor

#4221 monraces_info からMonsterRaceInfo を取得している箇所をMonraceList に差し替えた その1
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-item/cmd-eat.cpp
  src/effect/effect-item.cpp
  src/flavor/named-item-describer.cpp
  src/flavor/tval-description-switcher.cpp
  src/hpmp/hp-mp-regenerator.cpp
  src/load/old/load-v1-5-0.cpp
  src/market/bounty.cpp
  src/monster/monster-info.cpp
  src/monster/monster-info.h
  src/mspell/mspell-checker.cpp
  src/object-hook/hook-expendable.cpp
  src/object-hook/hook-quest.cpp
  src/object/object-value.cpp
  src/perception/identification.cpp
  src/specific-object/monster-ball.cpp
  src/spell/spells-object.cpp
  src/spell/spells-summon.cpp
  src/store/service-checker.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/util/object-sort.cpp
Labels: refactor, Priority:MIDDLE

#4227 monraces_info をMonraceList に繰り込む作業 その2
  src/knowledge/knowledge-monsters.cpp
  src/load/load-zangband.cpp
  src/load/player-info-loader.cpp
  src/market/bounty.cpp
  src/object-hook/hook-quest.cpp
  src/save/player-writer.cpp
  src/system/baseitem-info.cpp
  src/util/object-sort.cpp
  src/world/world.cpp
  src/world/world.h
Labels: refactor, Priority:MIDDLE

#4229 MonraceList::size() が呼ばれている周辺のmonraces_info をMonraceList に変えた
  src/cmd-visual/cmd-visuals.cpp
Labels: refactor, Priority:MIDDLE

#4230 monraces_info をMonraceList に繰り込む作業 その4
  src/player/eldritch-horror.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#4231 monraces_info をMonraceList に繰り込む作業 その5
  src/birth/game-play-initializer.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest-monster-placer.cpp
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/floor/fixed-map-generator.cpp
  src/floor/object-allocator.cpp
  src/io/write-diary.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/dungeon-loader.cpp
  src/load/quest-loader.cpp
  src/world/world-movement-processor.cpp
Labels: refactor, Priority:MIDDLE

#4232 [Fix] コメントのTypo修正。
  src/system/monster-entity.cpp
Labels: documentation

#4233 monraces_info をMonraceList に繰り込む作業 その6
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/movement-execution.cpp
  src/cmd-action/cmd-attack.cpp
  src/cmd-io/cmd-lore.cpp
  src/combat/shoot.cpp
  src/core/stuff-handler.cpp
  src/core/stuff-handler.h
  src/effect/effect-monster.cpp
  src/effect/effect-processor.cpp
  src/knowledge/knowledge-monsters.cpp
  src/lore/lore-store.cpp
  src/lore/lore-store.h
  src/market/arena.cpp
  src/market/building-monster.cpp
  src/monster-floor/monster-death.cpp
  src/monster/monster-damage.cpp
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-processor.cpp
  src/monster/monster-update.cpp
  src/monster/monster-update.h
  src/object-use/throw-execution.cpp
  src/player-attack/attack-chaos-effect.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-sight.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/target/target-describer.cpp
  src/tracking/lore-tracker.cpp
  src/tracking/lore-tracker.h
  src/view/display-lore.cpp
  src/window/display-sub-windows.cpp
Labels: refactor, Priority:MIDDLE

#4234 PlayerType::tracking_bi_id をBaseitemTracker に移した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-action/cmd-spell.cpp
  src/core/stuff-handler.cpp
  src/core/stuff-handler.h
  src/knowledge/knowledge-items.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/system/player-type-definition.h
  src/tracking/baseitem-tracker.cpp
  src/tracking/baseitem-tracker.h
  src/view/object-describer.cpp
Labels: refactor, Priority:MIDDLE

#4235 old_race_flags 構造体をOldRaceFlags クラスに変えた
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-processor.cpp
Labels: refactor, Priority:MIDDLE

#4238 Prevent unhandled exception when corpse-eating player tries to eat
  src/object-hook/hook-expendable.cpp
Labels: bug

#4236 モンスターのHPバー管理をHealthBarTracker に移した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-action/cmd-pet.cpp
  src/core/player-processor.cpp
  src/core/stuff-handler.cpp
  src/effect/effect-monster-oldies.cpp
  src/effect/effect-monster-spirit.cpp
  src/effect/effect-monster.cpp
  src/effect/effect-player-spirit.cpp
  src/hpmp/hp-mp-regenerator.cpp
  src/melee/melee-postprocess.cpp
  src/melee/monster-attack-monster.cpp
  src/monster-attack/monster-eating.cpp
  src/monster-floor/monster-remover.cpp
  src/monster/monster-compaction.cpp
  src/monster/monster-damage.cpp
  src/monster/monster-status-setter.cpp
  src/monster/monster-update.cpp
  src/mspell/mspell-status.cpp
  src/spell-kind/spells-polymorph.cpp
  src/system/player-type-definition.h
  src/tracking/health-bar-tracker.cpp
  src/tracking/health-bar-tracker.h
  src/window/main-window-left-frame.cpp
Labels: refactor, Priority:MIDDLE

#4245 [Refactor] モンスター種族のシンボル文字による判定
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-item/cmd-eat.cpp
  src/knowledge/knowledge-monsters.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mind/monk-attack.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-race/monster-race-hook.cpp
  src/mspell/mspell-special.cpp
  src/mspell/summon-checker.cpp
  src/object-hook/hook-expendable.cpp
  src/player-attack/player-attack.cpp
  src/store/service-checker.cpp
  src/system/item-entity.cpp
  src/system/monster-entity.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor

#4250 JSON関連ファイルの改行をLFに修正
  lib/edit/ArtifactDefinitions.jsonc
  lib/edit/BaseitemDefinitions.jsonc
  lib/edit/MonraceDefinitions.jsonc
  schema/ArtifactDefinitions.schema.json
  schema/BaseitemDefinitions.schema.json
  schema/MonraceDefinitions.schema.json
Labels: bug

#4252 [Fix] ダンジョンによる出現モンスター制限が機能していない
  src/monster/monster-util.cpp
Labels: bug

#4239 Miscコード最適化 β15
  src/external-lib/json.hpp
  src/flavor/flavor-describer.cpp
  src/game-option/option-flags.h
  src/io/input-key-requester.cpp
  src/load/angband-version-comparer.h
  src/load/info-loader.cpp
  src/load/item/item-loader-factory.cpp
  src/load/load.cpp
  src/load/monster/monster-loader-factory.cpp
  src/load/store-loader.cpp
  src/object-use/read/read-executor-factory.cpp
  src/room/rooms-vault.h
  src/status/action-setter.h
  src/system/angband-system.h
  src/system/angband-version.h
  src/system/h-system.h
  src/system/h-type.h
  src/target/target-setter.h
  src/target/target-types.h
  src/util/flag-group.h
Labels: refactor, Priority:MIDDLE

#4247 PlayerType::knows_daily_bounty をAngbandWorld へ移し、hook-quest.cpp/h を廃止した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/birth/game-play-initializer.cpp
  src/cmd-building/cmd-building.cpp
  src/cmd-io/cmd-knowledge.cpp
  src/flavor/flavor-describer.cpp
  src/flavor/object-flavor.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-monsters.h
  src/load/world-loader.cpp
  src/market/bounty.cpp
  src/market/bounty.h
  src/object-hook/hook-quest.cpp
  src/object-hook/hook-quest.h
  src/save/player-writer.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/system/player-type-definition.h
  src/world/world.h
Labels: refactor, Priority:MIDDLE

#4256 [Refactor] player_magic::spell_xtraを解体する
  src/cmd-action/cmd-spell.cpp
  src/info-reader/magic-reader.cpp
  src/player-info/class-info.h
  src/player/player-status.cpp
  src/spell/spell-info.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor

#4254 [Chore] 改行コードがLFであることをチェックする
  .github/scripts/check-bom.sh
  .github/scripts/check-newline.sh
  .github/workflows/pull-request-status-check.yml
  src/monster-race/race-flags-resistance.h
  src/util/sha256.cpp
Labels: bug, enhancement

#4263 [Fix] マーシャルアーツの仕様が日本語版と英語版で異なる
  src/combat/martial-arts-table.cpp
Labels: bug

#4266 [Release] 3.0.1.15-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#4251 ArenaEntryListクラスを作ってmonraces_info への依存性をなくした
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/game-play-initializer.cpp
  src/cmd-building/cmd-building.cpp
  src/cmd-building/cmd-building.h
  src/core/game-play.cpp
  src/floor/floor-generator.cpp
  src/io-dump/character-dump.cpp
  src/io/write-diary.cpp
  src/io/write-diary.h
  src/load/player-info-loader.cpp
  src/market/arena-entry.cpp
  src/market/arena-entry.h
  src/market/arena-info-table.cpp
  src/market/arena-info-table.h
  src/market/arena.cpp
  src/monster-floor/monster-death.cpp
  src/player/player-damage.cpp
  src/player/player-status.cpp
  src/save/player-writer.cpp
  src/system/angband-version.h
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/window/main-window-left-frame.cpp
  src/world/world.cpp
  src/world/world.h
Labels: refactor, Priority:MIDDLE

#4265 [Refactor] get_mspeed() をMonsterEntity のメソッドに繰り込んだ
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-list.cpp
  src/monster/monster-list.h
  src/monster/monster-status.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
Labels: refactor

#4269 AngbandWorld をシングルトンに変える準備 その1
  src/cmd-building/cmd-inn.cpp
  src/view/display-player-middle.cpp
  src/world/world.cpp
  src/world/world.h
Labels: refactor, Priority:MIDDLE

#4268 [Refactor] Diceクラスを実装し、アイテムのダイスデータをDiceクラスで置き換える
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/artifact/fixed-art-generator.cpp
  src/artifact/random-art-characteristics.cpp
  src/artifact/random-art-generator.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/combat/aura-counterattack.cpp
  src/combat/shoot.cpp
  src/combat/slaying.cpp
  src/flavor/flavor-describer.cpp
  src/info-reader/artifact-reader.cpp
  src/info-reader/baseitem-reader.cpp
  src/info-reader/json-reader-util.cpp
  src/info-reader/json-reader-util.h
  src/load/old/item-loader-savefile50.cpp
  src/load/old/load-v1-5-0.cpp
  src/market/building-craft-fix.cpp
  src/market/building-craft-weapon.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/object-enchant/object-ego.cpp
  src/object-enchant/weapon/apply-magic-arrow.cpp
  src/object-enchant/weapon/melee-weapon-enchanter.cpp
  src/object-use/throw-execution.cpp
  src/object/object-value.cpp
  src/player-attack/player-attack.cpp
  src/realm/realm-hissatsu.cpp
  src/save/item-writer.cpp
  src/smith/object-smith.cpp
  src/specific-object/death-scythe.cpp
  src/specific-object/torch.cpp
  src/specific-object/torch.h
  src/spell/spells-object.cpp
  src/store/store-util.cpp
  src/system/artifact-type-definition.h
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/util/dice.cpp
  src/util/dice.h
  src/view/status-first-page.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#4270 AngbandWorld をシングルトンに変える準備 その2
  src/cmd-io/cmd-dump.cpp
  src/core/show-file.cpp
  src/io-dump/character-dump.cpp
  src/io/report.cpp
  src/load/angband-version-comparer.cpp
  src/load/floor-loader.cpp
  src/load/info-loader.cpp
  src/load/load.cpp
  src/main/angband-initializer.cpp
  src/net/report-error.cpp
  src/system/angband-system.cpp
  src/system/angband-system.h
  src/system/angband-version.cpp
  src/system/angband-version.h
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/monster-info-spoiler.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#4272 [Refactor] 死体と骨のを表すItemKindTypeの列挙値の名称を変更
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/birth/inventory-initializer.cpp
  src/effect/effect-item.cpp
  src/flavor/named-item-describer.cpp
  src/flavor/tval-description-switcher.cpp
  src/knowledge/item-group-table.cpp
  src/market/bounty.cpp
  src/monster-attack/monster-eating.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-object.cpp
  src/mspell/mspell-checker.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/object/object-broken.cpp
  src/object/object-stack.cpp
  src/object/tval-types.h
  src/spell/spells-object.cpp
  src/system/baseitem-info.cpp
  src/system/item-entity.cpp
  src/util/object-sort.cpp
  src/wizard/spoiler-table.cpp
  src/wizard/tval-descriptions-table.cpp
Labels: refactor

#4271 [Refactor] モンスター情報の各種ダイスデータをDiceクラスにする
  src/artifact/random-art-characteristics.cpp
  src/avatar/avatar-changer.cpp
  src/combat/aura-counterattack.cpp
  src/core/game-play.cpp
  src/effect/effect-monster-charm.cpp
  src/flavor/flavor-describer.cpp
  src/info-reader/race-reader.cpp
  src/load/old/load-v1-5-0.cpp
  src/lore/lore-calculator.cpp
  src/lore/monster-lore.cpp
  src/melee/melee-util.h
  src/melee/monster-attack-monster.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-attack/monster-attack-player.h
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster/monster-damage.cpp
  src/monster/monster-list.cpp
  src/monster/monster-status.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/object-enchant/object-ego.cpp
  src/object/warning.cpp
  src/realm/realm-hissatsu.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/util/dice.cpp
  src/util/dice.h
  src/view/display-lore-attacks.cpp
  src/view/display-lore-status.cpp
  src/view/display-lore.cpp
  src/wizard/monster-info-spoiler.cpp
Labels: refactor

#4273 [Refactor] プレイヤーの各種ダイスデータをDiceクラスにする
  src/combat/aura-counterattack.cpp
  src/combat/martial-arts-table.cpp
  src/combat/martial-arts-table.h
  src/market/building-craft-weapon.cpp
  src/mind/monk-attack.cpp
  src/player-attack/player-attack.cpp
  src/player/player-status.cpp
  src/specific-object/death-scythe.cpp
  src/system/player-type-definition.h
  src/view/status-first-page.cpp
Labels: refactor

#4274 AngbandWorld をシングルトンに変える準備 その3
  src/player-info/class-info.cpp
  src/player-info/class-info.h
  src/player/process-death.cpp
  src/window/main-window-left-frame.cpp
  src/window/main-window-util.cpp
  src/window/main-window-util.h
Labels: refactor, Priority:MIDDLE

#4280 Prevent compiler error when not using precompiled headers
  src/market/arena-entry.h
Labels: bug

#4275 [Refactor] 魔法のダイスデータをDiceクラスにする
  src/cmd-action/cmd-spell.cpp
  src/cmd-action/cmd-spell.h
  src/cmd-item/cmd-eat.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/lore/monster-lore.cpp
  src/object-activation/activation-switcher.cpp
  src/object-use/quaff/quaff-effects.cpp
  src/realm/realm-arcane.cpp
  src/realm/realm-chaos.cpp
  src/realm/realm-craft.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-death.cpp
  src/realm/realm-demon.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-life.cpp
  src/realm/realm-nature.cpp
  src/realm/realm-song.cpp
  src/realm/realm-sorcery.cpp
  src/realm/realm-trump.cpp
  src/spell-kind/spells-launcher.cpp
  src/spell-kind/spells-launcher.h
  src/spell-realm/spells-craft.cpp
  src/spell-realm/spells-craft.h
  src/spell/spells-status.cpp
  src/spell/spells-status.h
  src/util/dice.cpp
  src/util/dice.h
  src/view/display-lore-attacks.cpp
  src/view/display-lore.cpp
Labels: refactor

#4276 AngbandWorld をシングルトンに変える準備 その4
  src/birth/auto-roller.cpp
  src/birth/birth-select-class.cpp
  src/birth/character-builder.cpp
  src/birth/quick-start.cpp
  src/flavor/flag-inscriptions-table.cpp
  src/knowledge/knowledge-self.cpp
  src/load/load.cpp
  src/locale/language-switcher.h
  src/player-info/class-info.cpp
  src/player-info/class-info.h
  src/player-info/mimic-info-table.cpp
  src/player-status/player-basic-statistics.cpp
  src/player-status/player-stealth.cpp
  src/player/patron.cpp
  src/player/player-status.cpp
  src/player/race-info-table.cpp
  src/view/display-scores.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#4284 set_gametime() をAngbandWorld のオブジェクトメソッドに繰り込んだ
  src/wizard/wizard-game-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-special-process.h
  src/world/world.cpp
  src/world/world.h
Labels: refactor, Priority:MIDDLE

#4285 [Refactor] プレイヤーのHDにDiceクラスを使用する
  src/birth/birth-stat.cpp
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-self.cpp
  src/load/load-zangband.cpp
  src/load/player-info-loader.cpp
  src/player/player-status.cpp
  src/save/player-writer.cpp
  src/spell/spells-status.cpp
  src/status/shape-changer.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/view/display-self-info.cpp
Labels: refactor

#4288 アイテムのスポイラー出力時にクラッシュする不具合を修正した
  src/flavor/tval-description-switcher.cpp
  src/wizard/items-spoiler.cpp
Labels: bug

#4293 [Refactor] parse_fix_map_expression
  src/info-reader/fixed-map-parser.cpp
Labels: refactor

#4289 rooms-vault.cpp の整形
  src/room/rooms-vault.cpp
Labels: refactor, Priority:MIDDLE

#4294 [Refactor] process_pref_file_expr
  src/autopick/autopick-drawer.cpp
  src/io/pref-file-expressor.cpp
  src/io/pref-file-expressor.h
  src/io/read-pref-file.cpp
Labels: refactor

#4303 [Fix] 地形シンボルエディタでカーソルキーが反応しない
  src/knowledge/knowledge-features.cpp
Labels: bug

#4297 cmd-building.cpp/h に定義されていたグローバル変数を適切な場所へ移した
  src/cmd-building/cmd-building.cpp
  src/cmd-building/cmd-building.h
  src/dungeon/dungeon-processor.cpp
  src/floor/floor-leaver.cpp
  src/floor/wild.cpp
  src/floor/wild.h
  src/info-reader/general-parser.cpp
  src/load/load-zangband.cpp
  src/load/world-loader.cpp
  src/market/arena.cpp
  src/market/bounty.cpp
  src/market/building-initializer.cpp
  src/market/building-quest.cpp
  src/market/building-service.cpp
  src/monster-floor/monster-death.cpp
  src/save/player-writer.cpp
  src/system/building-type-definition.cpp
  src/system/building-type-definition.h
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#4240 choose_new_monster() 関数を分割した
  src/effect/effect-monster-charm.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-list.cpp
  src/monster/monster-list.h
  src/monster/monster-processor.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
Labels: refactor

#4296 PlayerType::wild_mode をAngbandWorld に移した
  src/action/movement-execution.cpp
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-action/cmd-racial.cpp
  src/cmd-action/cmd-shoot.cpp
  src/cmd-building/cmd-building.cpp
  src/cmd-io/cmd-dump.cpp
  src/cmd-io/cmd-floor.cpp
  src/cmd-io/cmd-menu-content-table.cpp
  src/cmd-io/cmd-menu-content-table.h
  src/cmd-item/cmd-item.cpp
  src/cmd-item/cmd-quaff.cpp
  src/cmd-item/cmd-read.cpp
  src/cmd-item/cmd-throw.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/cmd-item/cmd-zaprod.cpp
  src/cmd-item/cmd-zapwand.cpp
  src/cmd-visual/cmd-map.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-events.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-save.cpp
  src/floor/floor-save.h
  src/floor/floor-util.cpp
  src/floor/wild.cpp
  src/inventory/inventory-curse.cpp
  src/io/input-key-processor.cpp
  src/io/input-key-requester.cpp
  src/io/input-key-requester.h
  src/load/world-loader.cpp
  src/main/scene-table-floor.cpp
  src/mind/mind-force-trainer.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-processor.cpp
  src/monster/monster-status-setter.cpp
  src/mutation/mutation-processor.cpp
  src/pet/pet-fall-off.cpp
  src/player/digestion-processor.cpp
  src/player/player-damage.cpp
  src/save/save.cpp
  src/spell-kind/spells-teleport.cpp
  src/store/cmd-store.cpp
  src/system/player-type-definition.h
  src/target/target-describer.cpp
  src/view/display-map.cpp
  src/wizard/wizard-special-process.cpp
  src/world/world-movement-processor.cpp
  src/world/world-turn-processor.cpp
  src/world/world.cpp
  src/world/world.h
Labels: refactor, Priority:MIDDLE

#4313 [Chore] プリコンパイルヘッダを使用しないようにする
  .github/workflows/create-cache-for-ccache.yml
  .github/workflows/pull-request-status-check.yml
Labels: enhancement

#4314 [Refactor] enum-converter.hの各関数群にコンセプトを使用する
  src/inventory/inventory-object.cpp
  src/util/enum-converter.h
Labels: enhancement, refactor

#4317 z-rand.h にある全てのマクロ変数をテンプレートに変えた
  src/action/open-close-execution.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-action/cmd-mind.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/core/object-compressor.cpp
  src/floor/cave-generator.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-object.cpp
  src/floor/tunnel-generator.cpp
  src/grid/feature-generator.cpp
  src/grid/grid.cpp
  src/hpmp/hp-mp-processor.cpp
  src/inventory/inventory-damage.cpp
  src/market/arena.cpp
  src/melee/melee-postprocess.cpp
  src/mind/mind-blue-mage.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-priest.cpp
  src/monster-attack/monster-eating.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-direction.cpp
  src/monster/monster-compaction.cpp
  src/monster/monster-damage.cpp
  src/mspell/mspell-attack-util.cpp
  src/mspell/mspell-attack.cpp
  src/mspell/mspell-selector.cpp
  src/mspell/smart-mspell-util.cpp
  src/object-enchant/item-magic-applier.cpp
  src/object-enchant/protector/apply-magic-soft-armor.cpp
  src/player-attack/attack-chaos-effect.cpp
  src/player/eldritch-horror.cpp
  src/player/player-move.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-vault.cpp
  src/room/vault-builder.cpp
  src/spell-kind/blood-curse.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-equipment.cpp
  src/spell-kind/spells-launcher.cpp
  src/spell-kind/spells-lite.cpp
  src/spell/spells-object.cpp
  src/spell/spells-status.cpp
  src/status/base-status.cpp
  src/status/experience.cpp
  src/system/player-type-definition.cpp
  src/target/target-getter.cpp
  src/term/z-rand.h
  src/view/display-map.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor, Priority:MIDDLE

#4319 [Fix] デバッグコマンドのライフレート変更のキー割り当て
  src/wizard/wizard-player-modifier.cpp
Labels: bug

#4320 [Fix] 思い出の文章で天使種族の表示が反映されていないバグを修正
  src/lore/monster-lore.cpp
Labels: bug

#4323 [Feature/Refactor] EnumRangeクラスの改良
  src/birth/game-play-initializer.cpp
  src/dungeon/quest.h
  src/load/dungeon-loader.cpp
  src/object/tval-types.h
  src/player/player-skill.h
  src/room/room-types.h
  src/store/store-util.h
  src/system/floor-type-definition.cpp
  src/system/redrawing-flags-updater.cpp
  src/util/enum-range.h
  src/util/flag-group.h
  src/wizard/artifact-analyzer.cpp
  src/wizard/spoiler-util.cpp
  src/world/world-movement-processor.cpp
Labels: enhancement, refactor

#4334 [Refactor] 爆発のルーンの作動処理をモジュールとして分割した
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-move.h
  src/monster-floor/one-monster-placer.cpp
Labels: refactor

#4348 [Refactor] bool型を直接足し算でカウントするのをやめる
  src/mspell/mspell-special.cpp
  src/mspell/mspell-summon.cpp
  src/mspell/specified-summon.cpp
  src/spell-kind/blood-curse.cpp
  src/spell-kind/spells-random.cpp
  src/spell/spells-summon.cpp
Labels: refactor

#4353 呪文情報を定義ファイルから取得する
  Makefile.am
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  lib/edit/SpellDefinitions.jsonc
  schema/SpellDefinitions.schema.json
  src/Makefile.am
  src/info-reader/magic-reader.cpp
  src/info-reader/spell-reader.cpp
  src/info-reader/spell-reader.h
  src/main/angband-headers.cpp
  src/main/angband-headers.h
  src/main/angband-initializer.cpp
  src/main/info-initializer.cpp
  src/main/info-initializer.h
  src/realm/realm-arcane.cpp
  src/realm/realm-chaos.cpp
  src/realm/realm-craft.cpp
  src/realm/realm-crusade.cpp
  src/realm/realm-death.cpp
  src/realm/realm-demon.cpp
  src/realm/realm-life.cpp
  src/realm/realm-nature.cpp
  src/realm/realm-sorcery.cpp
  src/realm/realm-trump.cpp
  src/system/spell-info-list.cpp
  src/system/spell-info-list.h
Labels: refactor

#4345 [Refactor] chameleon_change_m_idx を削除する
  src/monster-floor/place-monster-types.h
  src/monster/monster-list.cpp
  src/monster/monster-util.cpp
  src/monster/monster-util.h
Labels: refactor

#4347 [Refactor] place_monster_idx, place_monster_m_idx を削除する
  src/monster-floor/monster-generator.cpp
Labels: refactor

#4335 [Fix] 元素使いの呪文一覧をサブウィンドウに表示するとクラッシュ
  src/mind/mind-elementalist.cpp
  src/mind/mind-elementalist.h
  src/mind/mind-types.h
  src/window/display-sub-windows.cpp
Labels: bug

#4339 [Refactor] mind_powers、mind_tips をstd::vectorにする
  src/mind/mind-explanations-table.cpp
  src/mind/mind-explanations-table.h
  src/mind/mind-power-getter.cpp
  src/window/display-sub-windows.cpp
Labels: refactor

#4354 [Refactor] グローバル変数 hack_m_idx_ii を削除する
  src/core/game-play.cpp
  src/core/player-processor.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-generator.cpp
  src/grid/trap.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-generator.h
  src/monster-floor/monster-summon.cpp
  src/monster-floor/monster-summon.h
  src/monster-floor/one-monster-placer.cpp
  src/monster-floor/one-monster-placer.h
  src/monster/monster-processor.cpp
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/mspell/mspell-special.cpp
  src/specific-object/monster-ball.cpp
  src/spell-kind/spells-polymorph.cpp
  src/spell/spells-summon.cpp
Labels: refactor

#4328 [Add] ユニーク・モンスター「聖園ミカ」を追加
  lib/edit/MonraceDefinitions.jsonc
  lib/file/mondeath.txt
  lib/file/mondeath_j.txt
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
Labels: enhancement

#4360 グローバル変数 hack_m_idx を削除する
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-flag-types.h
  src/monster/monster-processor.cpp
  src/monster/monster-status-setter.cpp
  src/monster/monster-status-setter.h
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/mspell/mspell-floor.cpp
Labels: refactor

#4361 PlayerRealmクラスを作り、魔法情報へのアクセスをカプセル化する
  src/cmd-action/cmd-hissatsu.cpp
  src/cmd-action/cmd-spell.cpp
  src/knowledge/knowledge-experiences.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/player/player-skill.cpp
  src/player/player-status.cpp
  src/realm/realm-hissatsu.cpp
  src/realm/realm-types.h
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-song.cpp
  src/spell/spell-info.cpp
  src/spell/spell-info.h
  src/util/enum-range.h
  src/window/display-sub-windows.cpp
Labels: enhancement, refactor

#4363 get_realm*_book をPlayerRealmクラスのメンバ関数にする
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-action/cmd-spell.cpp
  src/object-hook/hook-magic.cpp
  src/object/object-info.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/util/object-sort.cpp
Labels: refactor

#4362 落馬ダメージ処理クラスを作成し、グローバル変数 rakubadam_p, rakubadam_m を削除する
  src/effect/effect-monster.cpp
  src/effect/effect-monster.h
  src/effect/effect-player.cpp
  src/effect/effect-player.h
  src/effect/effect-processor.cpp
  src/effect/spells-effect-util.cpp
  src/effect/spells-effect-util.h
  src/spell-class/spells-mirror-master.cpp
Labels: refactor

#4365 [Feature] PlayerRealm::Realm クラス
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-action/cmd-spell.cpp
  src/knowledge/knowledge-experiences.cpp
  src/object-hook/hook-magic.cpp
  src/object/object-info.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/player/player-status.cpp
  src/util/object-sort.cpp
Labels: refactor

#4364 [Refactor] 魔法領域の選択候補の取得方法
  src/birth/birth-select-realm.cpp
  src/object-hook/hook-magic.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/realm/realm-names-table.h
  src/realm/realm-types.h
  src/spell/spell-info.cpp
  src/spell/technic-info-table.h
  src/wizard/wizard-special-process.cpp
Labels: refactor

#4368 [Refactor] 善良な魔法領域かどうかの判定
  src/birth/birth-select-realm.cpp
  src/cmd-item/cmd-destroy.cpp
  src/object-hook/hook-magic.cpp
  src/player-info/class-ability-info.cpp
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/racial/class-racial-switcher.cpp
  src/racial/racial-switcher.cpp
  src/realm/realm-names-table.h
Labels: refactor

#4371 [Release] 3.0.1.16-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#4369 [Refactor] 領域の名称の取得方法
  src/birth/birth-select-realm.cpp
  src/birth/character-builder.cpp
  src/cmd-action/cmd-spell.cpp
  src/info-reader/fixed-map-parser.cpp
  src/io-dump/character-dump.cpp
  src/io/pref-file-expressor.cpp
  src/io/read-pref-file.cpp
  src/io/report.cpp
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-self.cpp
  src/locale/localized-string.h
  src/player/player-realm.cpp
  src/player/player-realm.h
  src/realm/realm-names-table.cpp
  src/realm/realm-names-table.h
  src/view/display-player.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor
