Repository hengband/hengband, pull requests merged in 2024-08, with the labels that each got.

#4440 [Refactor] Windows版の効果音再生処理
  src/main-win/main-win-sound.cpp
  src/main-win/wav-reader.cpp
  src/main-win/wav-reader.h
Labels: refactor

#4458 [Refactor] place_monster_one/place_monster_specificのシグニチャ
  src/core/game-play.cpp
  src/core/player-processor.cpp
  src/dungeon/quest-monster-placer.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-generator.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-generator.h
  src/monster-floor/monster-summon.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-floor/one-monster-placer.h
  src/room/rooms-nest.cpp
  src/room/rooms-pit.cpp
  src/room/rooms-special.cpp
  src/specific-object/monster-ball.cpp
  src/spell-kind/spells-polymorph.cpp
Labels: refactor

#4457 [Implement] レベル不明のモンスターが動いたら行動を中止するオプションの追加
  src/game-option/disturbance-options.cpp
  src/game-option/disturbance-options.h
  src/game-option/option-types-table.cpp
  src/monster-floor/monster-move.cpp
Labels: enhancement

#4459 [Refactor] モンスターの騎乗判定をモンスター自身の騎乗フラグでするようにした
  src/core/player-processor.cpp
  src/effect/effect-monster-oldies.cpp
  src/effect/effect-monster-spirit.cpp
  src/effect/effect-monster-util.cpp
  src/effect/effect-monster-util.h
  src/effect/effect-monster.cpp
  src/effect/effect-player-spirit.cpp
  src/effect/effect-player.cpp
  src/effect/effect-player.h
  src/floor/floor-leaver.cpp
  src/hpmp/hp-mp-regenerator.cpp
  src/melee/melee-postprocess.cpp
  src/melee/monster-attack-monster.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/monster-attack/monster-eating.cpp
  src/monster-attack/monster-eating.h
  src/monster-floor/monster-remover.cpp
  src/monster/monster-compaction.cpp
  src/monster/monster-damage.cpp
  src/monster/monster-processor.cpp
  src/monster/monster-status-setter.cpp
  src/monster/monster-update.cpp
  src/mspell/mspell-special.cpp
  src/mspell/mspell-status.cpp
  src/pet/pet-util.cpp
  src/spell-kind/spells-polymorph.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/target/target-preparation.cpp
Labels: refactor

#4321 モンスター闘技場のベット対象モンスターを表すクラスを作り、関連処理を別ファイルに分離した
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/game-play-initializer.cpp
  src/cmd-building/cmd-building.cpp
  src/dungeon/dungeon-processor.cpp
  src/load/load-zangband.cpp
  src/load/load-zangband.h
  src/load/player-info-loader.cpp
  src/load/world-loader.cpp
  src/market/arena.cpp
  src/market/arena.h
  src/market/building-actions-table.h
  src/market/melee-arena.cpp
  src/market/melee-arena.h
  src/save/player-writer.cpp
  src/system/building-type-definition.cpp
  src/system/building-type-definition.h
  src/wizard/wizard-game-modifier.cpp
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#4202 wr_monster() とその下の関数をクラス化し、 MonsterEntity に関連付けた
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/save/floor-writer.cpp
  src/save/lore-writer.cpp
  src/save/lore-writer.h
  src/save/monster-entity-writer.cpp
  src/save/monster-entity-writer.h
  src/save/monster-writer.cpp
  src/save/save.cpp
  src/system/monster-entity.h
Labels: refactor

#4464 Update hengband.spec version to 3.0.1.18
  hengband.spec
Labels: release

#4470 [Refactor] シングルトンクラスにFloorType のデータを移し、初期化はFloorType のコンストラクタで行うようにした
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/game-play-initializer.cpp
  src/floor/floor-list.cpp
  src/floor/floor-list.h
  src/main/game-data-initializer.cpp
  src/system/floor-type-definition.cpp
  src/system/floor-type-definition.h
Labels: refactor

#4467 [Fix] src_ptr がsrc_idx のチェックをしておらず、-1 などが入ると範囲外アクセスエラーを起こしてしまうバグを修正
  src/effect/effect-monster-spirit.cpp
  src/effect/effect-monster-util.cpp
  src/effect/effect-monster-util.h
  src/effect/effect-player-spirit.cpp
  src/effect/effect-player.cpp
  src/effect/effect-player.h
Labels: bug, Priority:HIGH

#4478 [Feature] レアおたずねものムシの英名の誤りを訂正
  lib/edit/MonraceDefinitions.jsonc
Labels: enhancement

#4475 [Feature] ミカの性能調整＆テキスト修正及び追加
  lib/edit/MonraceDefinitions.jsonc
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
Labels: enhancement

#4473 [Feature] 悪魔領域呪文の習得順・レベル・コスト・難易度の調整
  lib/edit/ClassMagicDefinitions.jsonc
  lib/edit/SpellDefinitions.jsonc
  src/realm/realm-demon.cpp
Labels: enhancement

#4479 [Release] 3.0.1.19-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#4482 Update hengband.spec version to 3.0.1.19
  hengband.spec
Labels: release

#4481 攻撃方法"CRUSH" の誤訳を修正
  src/lore/combat-types-setter.cpp
Labels: translation

#4477 モンスター闘技場のエントリーとそのオッズをMeleeArena/MeleeGladiator に繰り込んだ
  src/birth/game-play-initializer.cpp
  src/dungeon/dungeon-processor.cpp
  src/floor/floor-generator.cpp
  src/load/player-info-loader.cpp
  src/load/world-loader.cpp
  src/market/melee-arena.cpp
  src/market/melee-arena.h
  src/save/player-writer.cpp
  src/system/building-type-definition.cpp
  src/system/building-type-definition.h
  src/wizard/wizard-game-modifier.cpp
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#4497 [Fix] #4496 ガラスの床にしなければいけない箇所が壁になっていた不具合を修正した
  src/room/rooms-special.cpp
Labels: bug, Priority:HIGH

#4490 モンスター闘技場に関するグローバル変数をMeleeArena クラスへ繰り込んだ
  src/market/melee-arena.cpp
  src/system/building-type-definition.cpp
  src/system/building-type-definition.h
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#4501 [Add]モンスター「這いずる粘体」、「タイタン・ゾンビ」を追加
  lib/edit/MonraceDefinitions.jsonc
Labels: enhancement

#4504 モンスターの指定護衛をクラス化した
  src/info-reader/race-reader.cpp
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/lore/monster-lore.cpp
  src/monster-floor/monster-generator.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/view/display-lore.cpp
Labels: refactor, Priority:MIDDLE

#4514 モンスターの固定ドロップをクラス化した
  src/info-reader/race-reader.cpp
  src/monster-floor/monster-death.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#4509 race-sex-const.cpp を廃止し、MonsterRaceInfoのオブジェクトメソッドでモンスター性別をカプセル化した
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/avatar/avatar-changer.cpp
  src/cmd-action/cmd-attack.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/io/files-util.cpp
  src/lore/monster-lore.cpp
  src/main/game-data-initializer.cpp
  src/mind/monk-attack.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-race/race-indice-types.h
  src/monster-race/race-sex-const.cpp
  src/monster-race/race-sex-const.h
  src/monster-race/race-sex.h
  src/monster/monster-describer.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/target/target-describer.cpp
Labels: refactor, Priority:MIDDLE

#4463 ProbabilityTableクラスの確率分布生成に std::discrete_distribution を使用する
  src/Makefile.am
  src/term/z-rand.cpp
  src/term/z-rand.h
  src/test/test-probability-table.cpp
  src/util/probability-table.h
Labels: refactor

#4515 モンスター性別を表すenumが重複していたので片方を消した
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/lore/monster-lore.cpp
  src/view/display-lore-attacks.cpp
  src/view/display-lore-drops.cpp
  src/view/display-lore-magics.cpp
  src/view/display-lore-status.cpp
  src/view/display-lore.cpp
Labels: refactor, Priority:MIDDLE

#4471 [Refactor] 騎乗判定のPlayerType 依存を全部置き換えた
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-pet.cpp
  src/core/stuff-handler.cpp
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-psi.cpp
  src/effect/effect-monster-psi.h
  src/effect/effect-monster-resist-hurt.cpp
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-monster.cpp
  src/effect/effect-player.cpp
  src/effect/effect-processor.cpp
  src/floor/floor-leaver.cpp
  src/floor/wild.cpp
  src/grid/grid.cpp
  src/io-dump/character-dump.cpp
  src/melee/melee-postprocess.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/melee/melee-spell.cpp
  src/melee/melee-switcher.cpp
  src/melee/monster-attack-monster.cpp
  src/monster-attack/monster-attack-processor.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-direction.cpp
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster/monster-compaction.cpp
  src/monster/monster-describer.cpp
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-processor.cpp
  src/monster/monster-status.cpp
  src/mspell/mspell-dispel.cpp
  src/mspell/mspell-floor.cpp
  src/mspell/mspell-special.cpp
  src/object-activation/activation-others.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-genocide.cpp
  src/spell-kind/spells-teleport.cpp
  src/target/target-preparation.cpp
  src/wizard/wizard-special-process.cpp
  src/world/world-turn-processor.cpp
Labels: refactor

#4499 [Feature] CRUSH の訳を「押し潰す」に変更し、置き換え忘れ部分を全て同様の文章に変えた
  src/lore/combat-types-setter.cpp
  src/melee/melee-switcher.cpp
  src/monster-attack/monster-attack-describer.cpp
Labels: enhancement

#4518 [Release] 3.0.1.20-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#4516 モンスター種族のレベルソートをメソッド化した
  src/knowledge/knowledge-monsters.cpp
  src/main/game-data-initializer.cpp
  src/market/bounty.cpp
  src/room/rooms-nest.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/target/target-preparation.cpp
  src/target/target-sorter.cpp
  src/util/object-sort.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE
