Repository hengband/hengband, pull requests merged in 2024-12, with the labels that each got.

#4672 monraces_info へのアクセスをMonraceList に差し替えた その25
  src/monster-floor/monster-generator.cpp
  src/mspell/summon-checker.cpp
Labels: refactor, Priority:MIDDLE

#4674 monraces_info へのアクセスをMonraceList に差し替えた その26
  src/monster-floor/monster-summon.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/mspell/mspell-damage-calculator.h
  src/mspell/specified-summon.cpp
  src/save/save.cpp
  src/spell-kind/spells-polymorph.cpp
  src/store/rumor.cpp
Labels: refactor, Priority:MIDDLE

#4671 [Add] ライト/シャドウボルテックスの追加
  lib/edit/MonraceDefinitions.jsonc
Labels: enhancement

#4673 [Add] モンスター:クリーピング宝石シリーズを追加
  lib/edit/MonraceDefinitions.jsonc
Labels: enhancement

#4670 Update hengband.spec versionto 3.0.1.21
  hengband.spec
Labels: enhancement

#4669 [Feature] クエスト宝物庫のゴーレムなどを変更
  lib/edit/BaseitemDefinitions.jsonc
  lib/edit/quests/004_TheVault.txt
Labels: enhancement

#4675 monraces_info へのアクセスをMonraceList に差し替えた その27
  src/market/bounty.cpp
  src/monster-floor/one-monster-placer.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/system/monster-entity.cpp
  src/window/main-window-util.cpp
  src/wizard/wizard-game-modifier.cpp
Labels: refactor, Priority:MIDDLE

#4679 vectorの要素数が変わる前後で同じ参照を見続けた結果、ダングリング化してフロア生成に失敗する不具合を解消した
  src/monster-floor/monster-generator.cpp
Labels: bug, Priority:HIGH

#4665 store_type::stock.get() を消滅させた
  src/artifact/random-art-generator.cpp
  src/cmd-item/cmd-item.cpp
  src/knowledge/knowledge-items.cpp
  src/perception/identification.cpp
  src/perception/identification.h
  src/spell-kind/spells-perception.cpp
  src/store/black-market.cpp
  src/store/black-market.h
  src/store/home.cpp
  src/store/pricing.cpp
  src/store/pricing.h
  src/store/purchase-order.cpp
  src/store/sell-order.cpp
  src/store/store.cpp
  src/view/display-store.cpp
Labels: refactor, Priority:MIDDLE

#4680 monraces_info へのアクセスをMonraceList に差し替えた その28
  src/info-reader/race-reader.cpp
  src/main/info-initializer.cpp
  src/monster-floor/monster-generator.cpp
  src/room/rooms-nest.cpp
  src/room/rooms-pit.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#4682 get_obj_index() をFloorType::select_baseitem_id() に繰り込み、確率テーブル処理をBaseitemAllocationTable へ移した
  src/floor/floor-object.cpp
  src/monster-floor/special-death-switcher.cpp
  src/room/rooms-special.cpp
  src/store/store.cpp
  src/system/alloc-entries.cpp
  src/system/alloc-entries.h
  src/system/floor-type-definition.cpp
  src/system/floor-type-definition.h
  src/system/system-variables.cpp
  src/system/system-variables.h
  src/world/world-object.cpp
  src/world/world-object.h
Labels: refactor, Priority:MIDDLE

#4667 store_type::stock へのアクセスをunique_ptr から参照に差し替えた
  src/io-dump/random-art-info-dumper.cpp
  src/knowledge/knowledge-inventory.cpp
  src/load/store-loader.cpp
  src/player/process-death.cpp
  src/store/home.cpp
  src/store/museum.cpp
  src/store/purchase-order.cpp
  src/store/store-util.cpp
  src/store/store.cpp
  src/view/display-store.cpp
Labels: refactor, Priority:MIDDLE

#4684 AllocationTable をベースアイテム用とモンスター種族用に分けた
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/floor/floor-object.cpp
  src/main/game-data-initializer.cpp
  src/monster/monster-list.cpp
  src/monster/monster-util.cpp
  src/system/baseitem/baseitem-allocation.cpp
  src/system/baseitem/baseitem-allocation.h
  src/system/floor-type-definition.cpp
  src/system/monrace/monrace-allocation.cpp
  src/system/monrace/monrace-allocation.h
  src/wizard/wizard-item-modifier.cpp
Labels: refactor, Priority:MIDDLE

#4691 [Fix] 持ち物が一杯で装備を外したときの挙動
  src/inventory/inventory-object.cpp
Labels: bug

#4693 [Refactor] ItemEntityのコピーコンストラクタとコピー代入演算子を隠蔽
  src/action/weapon-shield.cpp
  src/autopick/autopick-destroyer.cpp
  src/cmd-item/cmd-destroy.cpp
  src/cmd-item/cmd-eat.cpp
  src/core/object-compressor.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-object.cpp
  src/grid/object-placer.cpp
  src/inventory/inventory-object.cpp
  src/load/store-loader.cpp
  src/object-use/quaff/quaff-execution.cpp
  src/perception/object-perception.cpp
  src/smith/object-smith.cpp
  src/spell/spells-status.cpp
  src/store/cmd-store.cpp
  src/store/home.cpp
  src/store/purchase-order.cpp
  src/store/store-util.cpp
  src/system/item-entity.h
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#4692 townとstore を構造体からクラスへ変えた
  src/load/store-loader.cpp
  src/market/building-initializer.cpp
  src/save/info-writer.cpp
  src/save/info-writer.h
  src/store/store-util.cpp
  src/store/store-util.h
  src/system/floor/town-info.cpp
  src/system/floor/town-info.h
  src/system/floor/town-list.cpp
  src/system/floor/town-list.h
Labels: refactor, Priority:MIDDLE

#4694 find_space() の引数からポインタを削除し、戻り値をoptional に変えた
  src/floor/cave-generator.cpp
  src/room/rooms-city.cpp
  src/room/rooms-fractal.cpp
  src/room/rooms-maze-vault.cpp
  src/room/rooms-maze-vault.h
  src/room/rooms-nest.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-pit.cpp
  src/room/rooms-special.cpp
  src/room/rooms-trap.cpp
  src/room/rooms-vault.cpp
  src/room/space-finder.cpp
  src/room/space-finder.h
Labels: refactor, Priority:MIDDLE

#4690 [Feature] クエスト:宝物庫の難易度微調整
  lib/edit/quests/004_TheVault.txt
Labels: enhancement

#4698 [Refactor] MonsterEntityのコピーコンストラクタとコピー代入演算子を隠蔽
  src/floor/floor-changer.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/monster/monster-compaction.cpp
  src/monster/monster-damage.cpp
  src/spell-kind/spells-polymorph.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
Labels: enhancement

#4695 randint0 の不適切なキャストをrandnum0<T> に置き換えた
  src/artifact/random-art-generator.cpp
  src/artifact/random-art-misc.cpp
  src/birth/birth-wizard.cpp
  src/birth/inventory-initializer.cpp
  src/floor/wild.cpp
  src/grid/grid.cpp
  src/mind/mind-archer.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/monster-attack/monster-eating.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-status.cpp
  src/mutation/mutation-processor.cpp
  src/object-enchant/object-boost.cpp
  src/save/floor-writer.cpp
  src/save/save.cpp
  src/spell-kind/spells-teleport.cpp
  src/status/shape-changer.cpp
  src/store/store.cpp
  src/term/z-rand.h
Labels: refactor, Priority:MIDDLE

#4697 店に関するグローバル関数をStore クラスのメソッドへ繰り込んだ その1
  src/store/black-market.cpp
  src/store/black-market.h
  src/store/museum.cpp
  src/store/purchase-order.cpp
  src/store/sell-order.cpp
  src/store/store-util.cpp
  src/store/store-util.h
  src/store/store.cpp
Labels: refactor, Priority:MIDDLE

#4699 モンスター生成周りのルーチンを改善した
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/combat/shoot.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-object.cpp
  src/grid/object-placer.cpp
  src/info-reader/fixed-map-parser.cpp
  src/load/floor-loader.cpp
  src/load/old/load-v1-5-0.cpp
  src/monster-attack/monster-eating.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-list.cpp
  src/monster/monster-list.h
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/store/store.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/world/world-object.cpp
  src/world/world-object.h
Labels: refactor, Priority:MIDDLE

#4700 地形IDを動的に引く仕組みの構築 その1
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-info-tokens-table.cpp
  src/info-reader/feature-info-tokens-table.h
  src/info-reader/feature-reader.cpp
  src/info-reader/feature-reader.h
  src/io/cursor.cpp
  src/main/info-initializer.cpp
  src/system/enums/terrain/terrain-tag.h
  src/system/terrain-type-definition.cpp
  src/system/terrain-type-definition.h
  src/view/display-symbol.h
Labels: refactor, Priority:MIDDLE

#4702 地形IDを動的に引く仕組みの構築 その3
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/open-close-execution.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/visuals-reseter.cpp
  src/floor/cave.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-streams.cpp
  src/floor/object-allocator.cpp
  src/grid/door.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/grid/grid.cpp
  src/grid/trap.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/feature-reader.cpp
  src/info-reader/general-parser.cpp
  src/info-reader/general-parser.h
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-features.cpp
  src/main/info-initializer.cpp
  src/monster/monster-info.cpp
  src/player/player-move.cpp
  src/room/rooms-city.cpp
  src/room/rooms-trap.cpp
  src/spell-kind/spells-floor.cpp
  src/store/purchase-order.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/grid-type-definition.cpp
  src/system/terrain/terrain-actions-table.cpp
  src/system/terrain/terrain-actions-table.h
  src/system/terrain/terrain-definition.cpp
  src/system/terrain/terrain-definition.h
  src/system/terrain/terrain-list.cpp
  src/system/terrain/terrain-list.h
  src/target/target-describer.cpp
  src/view/display-map.cpp
  src/view/display-store.cpp
  src/window/display-sub-windows.cpp
  src/wizard/wizard-special-process.cpp
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#4706 [Chore] download-artifactのバージョンをv4に更新
  .github/workflows/publish-spoiler-page.yml
Labels: enhancement

#4707 MSVCのビルド設定を改善した
  VisualStudio/Hengband/Hengband.vcxproj
Labels: refactor, Priority:MIDDLE

#4704 地形IDを動的に引く仕組みの構築 その4
  src/floor/floor-generator.cpp
  src/floor/wild.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-info-tokens-table.cpp
  src/info-reader/feature-reader.cpp
  src/load/old/load-v1-5-0.cpp
  src/system/enums/terrain/terrain-tag.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/target/target-describer.cpp
Labels: refactor, Priority:MIDDLE

#4711 [Fix] リピートコマンドで方向入力の値の妥当性をチェックする
  src/target/target-getter.cpp
Labels: bug

#4710 地形IDを動的に引く仕組みの構築 その5
  src/effect/effect-feature.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-info-tokens-table.cpp
  src/info-reader/feature-reader.cpp
  src/load/old/load-v1-5-0.cpp
  src/mind/mind-mirror-master.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-class/spells-mirror-master.h
  src/spell-kind/spells-grid.cpp
  src/system/enums/terrain/terrain-tag.h
Labels: refactor, Priority:MIDDLE

#4712 dungeons_info をDungeonList に差し替えた
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-move.cpp
  src/dungeon/quest.h
  src/floor/fixed-map-generator.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/wild.cpp
  src/floor/wild.h
  src/info-reader/dungeon-reader.cpp
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-features.cpp
  src/load/world-loader.cpp
  src/main-win/main-win-music.cpp
  src/main/game-data-initializer.cpp
  src/main/info-initializer.cpp
  src/market/bounty.cpp
  src/player/player-status.cpp
  src/save/player-writer.cpp
  src/spell-kind/spells-world.cpp
  src/store/rumor.cpp
  src/system/building-type-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/dungeon/dungeon-list.cpp
  src/system/dungeon/dungeon-list.h
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/h-type.h
  src/system/player-type-definition.h
  src/target/target-describer.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#4716 MSVC において、デバッグビルド以外のビルドに失敗する問題を修正した
  VisualStudio/Hengband/Hengband.vcxproj
  src/flavor/object-flavor.cpp
  src/main-gcu.cpp
  src/main-win.cpp
  src/main-x11.cpp
  src/term/gameterm.h
Labels: bug, Priority:HIGH

#4714 地形IDを動的に引く仕組みの構築 その6
  src/dungeon/quest-completion-checker.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-streams.h
  src/grid/feature.cpp
  src/grid/feature.h
  src/grid/stair.cpp
  src/grid/stair.h
  src/info-reader/feature-info-tokens-table.cpp
  src/info-reader/feature-reader.cpp
  src/load/floor-loader.cpp
  src/load/old/load-v1-5-0.cpp
  src/room/rooms-normal.cpp
  src/spell-kind/spells-grid.cpp
  src/system/enums/terrain/terrain-tag.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
Labels: refactor, Priority:MIDDLE

#4713 ダンジョンの最深階層を保持するクラスDungeonRecord 及びその集合論的クラスDungeonRecords クラスを作った
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-move.cpp
  src/core/score-util.cpp
  src/dungeon/dungeon-processor.cpp
  src/io-dump/character-dump.cpp
  src/io/report.cpp
  src/io/write-diary.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/load-zangband.cpp
  src/load/world-loader.cpp
  src/main/game-data-initializer.cpp
  src/market/bounty.cpp
  src/player/player-status.cpp
  src/save/player-writer.cpp
  src/spell-kind/spells-world.cpp
  src/store/rumor.cpp
  src/system/building-type-definition.cpp
  src/system/dungeon/dungeon-record.cpp
  src/system/dungeon/dungeon-record.h
  src/world/world-movement-processor.cpp
Labels: refactor, Priority:MIDDLE

#4720 [Fix] クエスト定義ファイルの最後の空行が統一されていない
  lib/edit/quests/001_ThievesHideout.txt
  lib/edit/quests/002_TheSewer.txt
  lib/edit/quests/003_LogrusMaster.txt
  lib/edit/quests/005_TheTower_1.txt
  lib/edit/quests/006_TheTower_2.txt
  lib/edit/quests/007_TheTower_3.txt
  lib/edit/quests/009_SerpentOfChaos.txt
  lib/edit/quests/010_NodeOfSorcery.txt
  lib/edit/quests/011_NodeOfChaos.txt
  lib/edit/quests/012_NodeOfNature.txt
  lib/edit/quests/013_NodeOfArcane.txt
  lib/edit/quests/016_AssaultOnMontsalvat.txt
  lib/edit/quests/019_DoomQuest1.txt
  lib/edit/quests/020_VaporQuest.txt
  lib/edit/quests/021_DoomQuest2.txt
  lib/edit/quests/022_OrcCamp.txt
  lib/edit/quests/023_SpawningPits.txt
  lib/edit/quests/024_MicroShaft.txt
  lib/edit/quests/025_HauntedHouse.txt
  lib/edit/quests/026_KillingFields.txt
  lib/edit/quests/027_TheOldCatsle.txt
  lib/edit/quests/028_TheRoyalCrypt.txt
  lib/edit/quests/029_TheMimicTreasure.txt
  lib/edit/quests/030_TenguAndDeathSword.txt
  lib/edit/quests/031_OldManWillow.txt
  lib/edit/quests/034_DumpWitness.txt
Labels: bug

#4721 lib/edit 以下のファイル末尾を統一した
  lib/edit/BaseitemDefinitions.jsonc
  lib/edit/ClassMagicDefinitions.jsonc
  lib/edit/EgoDefinitions.txt
  lib/edit/Makefile.am
  lib/edit/MonraceDefinitions.jsonc
  lib/edit/SpellDefinitions.jsonc
  lib/edit/TownPreferences.txt
  lib/edit/VaultDefinitions.txt
  lib/edit/WildernessDefinition.txt
  lib/edit/towns/01_Outpost_Full.txt
  lib/edit/towns/01_Outpost_Lite.txt
  lib/edit/towns/01_Outpost_OnlyAngband.txt
  lib/edit/towns/02_Telmora.txt
  lib/edit/towns/04_Angwil.txt
  lib/edit/towns/06_Rlyeh_Obsoleted.txt
Labels: refactor, Priority:MIDDLE

#4717 地形IDを動的に引く仕組みの構築 その7
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/floor/object-allocator.cpp
  src/grid/door.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/grid/stair.cpp
  src/grid/stair.h
  src/room/rooms-normal.cpp
  src/room/rooms-vault.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-grid.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
Labels: refactor, Priority:MIDDLE

#4703 旧バージョンの静的解析ツールを指していたNuGetパッケージ一覧を最新版まで引き上げた
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/packages.config
Labels: bug, Priority:LOW

#4727 [Fix] 迷宮が狭い
  src/floor/cave-generator.cpp
Labels: bug

#4724 [Version] 3.0.1.22-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#4735 階段昇降でクラッシュする場合がある事象を修正した
  src/floor/cave-generator.cpp
  src/floor/tunnel-generator.cpp
  src/main-win.cpp
  src/room/rooms-vault.cpp
  src/view/display-map.cpp
Labels: refactor, Priority:MIDDLE

#4729 [Fix] 自動リリースのWorkflowで英語版のビルドに失敗する
  VisualStudio/Hengband/Hengband.vcxproj
Labels: bug

#4736 Update hengband.spec
  hengband.spec
Labels: release

#4737 [Release] 3.0.1.23-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#4738 Release/3.0.1.23 beta
  VisualStudio/Hengband/Hengband.vcxproj
  configure.ac
  doxygen/Hengband.doxyfile
  hengband.spec
  lib/edit/MonraceDefinitions.jsonc
  src/floor/cave-generator.cpp
  src/floor/tunnel-generator.cpp
  src/main-win.cpp
  src/room/rooms-vault.cpp
  src/system/angband-version.h
  src/view/display-map.cpp
Labels: release

#4743 [Fix] クリーピングモンスターの感知範囲の再設定
  lib/edit/MonraceDefinitions.jsonc
Labels: enhancement

#4747 English: in revenge part of lore, add missing space and match verb to subject
  src/lore/lore-util.cpp
Labels: bug

#4723 TerrainKind を定義し、グリッドから地形特性を得やすくした
  src/action/movement-execution.cpp
  src/action/open-close-execution.cpp
  src/action/run-execution.cpp
  src/action/tunnel-execution.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-others.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-action/cmd-tunnel.cpp
  src/effect/effect-feature.cpp
  src/floor/cave.cpp
  src/floor/cave.h
  src/floor/floor-events.cpp
  src/floor/geometry.cpp
  src/floor/wild.cpp
  src/grid/door.cpp
  src/grid/grid.cpp
  src/hpmp/hp-mp-processor.cpp
  src/mind/mind-archer.cpp
  src/monster-floor/monster-lite.cpp
  src/mutation/mutation-techniques.cpp
  src/player/player-view.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-realm/spells-chaos.cpp
  src/system/floor/floor-info.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/target/target-preparation.cpp
  src/view/display-map.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#4746 [Feature] モンスター定義ファイルからのNEVER_BLOWフラグ撤廃
  lib/edit/MonraceDefinitions.jsonc
  schema/MonraceDefinitions.schema.json
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-reader.cpp
Labels: enhancement

#4728 帰還先情報をDungeonRecords のメソッドへ繰り込んだ
  src/cmd-action/cmd-move.cpp
  src/cmd-building/cmd-inn.cpp
  src/core/game-play.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/dungeon-reader.h
  src/io-dump/character-dump.cpp
  src/load/world-loader.cpp
  src/main/info-initializer.cpp
  src/market/bounty.cpp
  src/market/bounty.h
  src/player/player-status.cpp
  src/system/building-type-definition.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/dungeon/dungeon-list.cpp
  src/system/dungeon/dungeon-list.h
  src/system/dungeon/dungeon-record.cpp
  src/system/dungeon/dungeon-record.h
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#4750 DungeonRecords::collect_entered_dungeons() を実装してダンジョン表記を統一化した
  src/knowledge/knowledge-features.cpp
  src/spell-kind/spells-world.cpp
  src/store/rumor.cpp
  src/system/dungeon/dungeon-record.cpp
  src/system/dungeon/dungeon-record.h
Labels: refactor, Priority:MIDDLE

#4749 静的解析警告を除去した (3.0.1.23-Beta)
  src/birth/birth-select-realm.cpp
  src/mind/mind-weaponsmith.cpp
Labels: refactor, Priority:MIDDLE

#4751 [Refactor] AbstractVectorWrapperによるボイラープレートの削減
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/system/baseitem/baseitem-allocation.cpp
  src/system/baseitem/baseitem-allocation.h
  src/system/baseitem/baseitem-list.cpp
  src/system/baseitem/baseitem-list.h
  src/system/monrace/monrace-allocation.cpp
  src/system/monrace/monrace-allocation.h
  src/system/terrain/terrain-list.cpp
  src/system/terrain/terrain-list.h
  src/util/abstract-vector-wrapper.h
Labels: refactor

#4744 Update hengband.spec versionto 3.0.1.23
  hengband.spec
Labels: documentation

#4754 DungeonList とDungeonRecords の要素をshared_ptr に変えた
  src/cmd-action/cmd-move.cpp
  src/floor/wild.cpp
  src/info-reader/dungeon-reader.cpp
  src/load/world-loader.cpp
  src/save/player-writer.cpp
  src/spell-kind/spells-world.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/dungeon/dungeon-list.cpp
  src/system/dungeon/dungeon-list.h
  src/system/dungeon/dungeon-record.cpp
  src/system/dungeon/dungeon-record.h
  src/target/target-describer.cpp
Labels: refactor, Priority:MIDDLE

#4757 [Fix] 新規キャラクター作成時にクラッシュ
  src/system/dungeon/dungeon-record.cpp
Labels: bug

#4759 [Fix] clang-15でビルドエラー
  src/cmd-action/cmd-mane.cpp
  src/system/baseitem/baseitem-list.cpp
  src/system/baseitem/baseitem-list.h
  src/system/terrain/terrain-list.h
Labels: bug

#4760 DungeonDefinition 周りのラップアップ
  src/core/game-play.cpp
  src/core/score-util.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest-monster-placer.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/pattern-walk.cpp
  src/floor/wild.cpp
  src/info-reader/dungeon-reader.cpp
  src/io/write-diary.cpp
  src/load/dungeon-loader.cpp
  src/main/scene-table-floor.cpp
  src/room/rooms-pit.cpp
  src/save/floor-writer.cpp
  src/spell-kind/spells-world.cpp
  src/system/building-type-definition.cpp
  src/system/building-type-definition.h
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/dungeon/dungeon-record.cpp
  src/system/dungeon/dungeon-record.h
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/window/main-window-left-frame.cpp
  src/wizard/wizard-special-process.cpp
  src/world/world-movement-processor.cpp
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE

#4762 [Fix] クエスト内部のトラップドア用の処理の追加
  src/cmd-action/cmd-move.cpp
  src/grid/trap.cpp
Labels: bug

#4761 DungeonService クラスを作り、DungeonDefinition とDungeonRecord の両方に依存する処理を移設した
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/birth-select-realm.cpp
  src/cmd-action/cmd-move.cpp
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-features.cpp
  src/load/world-loader.cpp
  src/market/bounty.cpp
  src/player/player-status.cpp
  src/spell-kind/spells-world.cpp
  src/system/building-type-definition.cpp
  src/system/dungeon/dungeon-list.cpp
  src/system/dungeon/dungeon-list.h
  src/system/dungeon/dungeon-record.cpp
  src/system/dungeon/dungeon-record.h
  src/system/enums/dungeon/dungeon-id.h
  src/system/services/dungeon-service.cpp
  src/system/services/dungeon-service.h
Labels: refactor, Priority:MIDDLE

#4763 DungeonData のコンストラクタを改善し、外から初期化する項目を減らした
  src/floor/cave-generator.cpp
  src/system/dungeon/dungeon-data-definition.cpp
  src/system/dungeon/dungeon-data-definition.h
Labels: refactor, Priority:MIDDLE

#4764 モンスター生成フィルタの2つ目を関数ポインタからenum class に差し替えた
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/inventory-initializer.cpp
  src/core/player-processor.cpp
  src/dungeon/quest.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-generator.cpp
  src/floor/wild.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/object-enchant/others/apply-magic-others.cpp
  src/player/eldritch-horror.cpp
  src/room/rooms-nest.cpp
  src/room/rooms-pit.cpp
  src/room/rooms-special.cpp
  src/system/building-type-definition.cpp
  src/system/enums/monrace/monrace-hook-types.h
  src/wizard/monrace-filter-debug-info.cpp
  src/wizard/monrace-filter-debug-info.h
Labels: refactor, Priority:MIDDLE

#4769 [Feature] AbstracMapWrapperによるボイラープレートの削減
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/load/quest-loader.cpp
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/system/dungeon/dungeon-list.cpp
  src/system/dungeon/dungeon-list.h
  src/system/dungeon/dungeon-record.cpp
  src/system/dungeon/dungeon-record.h
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
  src/util/abstract-map-wrapper.h
Labels: refactor

#4773 [Refactor] str_tolower()のシグネチャの変更
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-finder.cpp
  src/core/show-file.cpp
  src/core/show-file.h
  src/util/string-processor.cpp
  src/util/string-processor.h
  src/wizard/wizard-item-modifier.cpp
Labels: refactor

#4765 カメレオンの変身先選択ルーチンをdo_get_mon_num_prep() から分離した
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-list.cpp
  src/monster/monster-list.h
  src/monster/monster-processor.cpp
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/system/enums/monrace/monrace-hook-types.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
Labels: refactor, Priority:MIDDLE

#4776 [Refactor] do_cmd_query_symbol
  src/cmd-io/cmd-lore.cpp
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
Labels: refactor
