Repository hengband/hengband, pull requests merged in 2024-04, with the labels that each got.

#3886 [Refactor] summon_specificで使用するグローバル変数の除去
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-generator.h
  src/monster-floor/monster-summon.cpp
  src/monster-floor/monster-summon.h
  src/monster-floor/one-monster-placer.cpp
  src/monster-floor/one-monster-placer.h
  src/monster/monster-list.cpp
  src/monster/monster-list.h
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/mspell/summon-checker.cpp
  src/mspell/summon-checker.h
Labels: refactor

#3898 Update hengband.spec
  hengband.spec
Labels: release

#3784 AngbandWorld のフィールド変数をAngbandSystem へ移した その1
  src/core/game-play.cpp
  src/dungeon/dungeon-processor.cpp
  src/floor/floor-generator.cpp
  src/floor/wild.cpp
  src/info-reader/fixed-map-parser.cpp
  src/item-info/flavor-initializer.cpp
  src/load/angband-version-comparer.cpp
  src/load/angband-version-comparer.h
  src/load/floor-loader.cpp
  src/load/info-loader.cpp
  src/load/load.cpp
  src/load/old/load-v1-5-0.cpp
  src/load/world-loader.cpp
  src/main-win.cpp
  src/main/game-data-initializer.cpp
  src/monster/monster-list.cpp
  src/monster/monster-status.cpp
  src/save/info-writer.cpp
  src/save/player-writer.cpp
  src/system/angband-system.cpp
  src/system/angband-system.h
  src/system/angband-version.cpp
  src/system/angband-version.h
  src/system/gamevalue.h
  src/term/z-rand.cpp
  src/world/world-object.cpp
  src/world/world.h
Labels: refactor, Priority:MIDDLE

#3889 デバッグコマンド「敵をクローンとして生成」を追加 + コマンドキー表示をCTRLとの組み合わせに対応した
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
Labels: enhancement

#3908 Release/3.0.1.11 beta
  configure.ac
  doxygen/Hengband.doxyfile
  hengband.spec
  src/core/game-play.cpp
  src/dungeon/dungeon-processor.cpp
  src/floor/floor-generator.cpp
  src/floor/wild.cpp
  src/info-reader/fixed-map-parser.cpp
  src/item-info/flavor-initializer.cpp
  src/load/angband-version-comparer.cpp
  src/load/angband-version-comparer.h
  src/load/floor-loader.cpp
  src/load/info-loader.cpp
  src/load/load.cpp
  src/load/old/load-v1-5-0.cpp
  src/load/world-loader.cpp
  src/main-win.cpp
  src/main/game-data-initializer.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-generator.h
  src/monster-floor/monster-summon.cpp
  src/monster-floor/monster-summon.h
  src/monster-floor/one-monster-placer.cpp
  src/monster-floor/one-monster-placer.h
  src/monster/monster-list.cpp
  src/monster/monster-list.h
  src/monster/monster-status.cpp
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/mspell/summon-checker.cpp
  src/mspell/summon-checker.h
  src/save/info-writer.cpp
  src/save/player-writer.cpp
  src/system/angband-system.cpp
  src/system/angband-system.h
  src/system/angband-version.cpp
  src/system/angband-version.h
  src/system/gamevalue.h
  src/term/z-rand.cpp
  src/wizard/cmd-wizard.cpp
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
  src/world/world-object.cpp
  src/world/world.h
Labels: release

#3907 [Release] 3.0.1.11-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3910 Update hengband.spec for 3.0.1.11
  hengband.spec
Labels: release

#3904 get_direction() のシグネチャを変える準備 その1
  src/action/movement-execution.cpp
  src/action/mutation-execution.cpp
  src/cmd-action/cmd-pet.cpp
  src/floor/geometry.cpp
  src/floor/geometry.h
  src/mind/mind-berserker.cpp
  src/mind/mind-warrior.cpp
  src/mutation/mutation-techniques.cpp
  src/racial/racial-vampire.cpp
  src/realm/realm-hissatsu.cpp
  src/spell/spells-status.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
Labels: refactor, Priority:MIDDLE

#3915 get_direction() のシグネチャ変更準備 その2
  src/action/run-execution.cpp
  src/action/travel-execution.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-others.cpp
  src/cmd-action/cmd-tunnel.cpp
  src/core/player-processor.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-force-trainer.cpp
  src/mind/monk-attack.cpp
  src/realm/realm-hissatsu.cpp
  src/specific-object/monster-ball.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-class/spells-mirror-master.h
  src/spell-kind/spells-launcher.cpp
  src/spell-kind/spells-teleport.cpp
Labels: refactor, Priority:MIDDLE

#3929 各 is_explodable() メソッドにMonsterEntity::get_died_message() にDoxygenコメント付加。
  src/system/monster-entity.cpp
  src/system/monster-race-info.cpp
Labels: refactor

#3921 get_direction() のシグネチャからポインタの引数を除去し、optionalの戻り値を返すようにした
  src/action/mutation-execution.cpp
  src/cmd-action/cmd-pet.cpp
  src/mind/mind-berserker.cpp
  src/mind/mind-warrior.cpp
  src/mutation/mutation-techniques.cpp
  src/racial/racial-vampire.cpp
  src/realm/realm-hissatsu.cpp
  src/specific-object/monster-ball.cpp
  src/spell/spells-status.cpp
  src/target/target-getter.cpp
  src/target/target-getter.h
Labels: refactor, Priority:MIDDLE

#3940 VS2022 で出ているコンパイル警告を解消した (v3.0.0 β12)
  src/io-dump/special-class-dump.cpp
  src/io/interpret-pref-file.cpp
  src/save/save.cpp
Labels: refactor, Priority:MIDDLE

#3948 describe() の "" で返す部分を nullopt にした
  src/combat/shoot.cpp
  src/effect/effect-monster.cpp
  src/monster/monster-pain-describer.cpp
  src/monster/monster-pain-describer.h
  src/object-use/throw-execution.cpp
Labels: refactor

#3954 rooms-normal.cpp の整形作業
  src/room/rooms-normal.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
Labels: refactor, Priority:MIDDLE

#3943 正常なベースアイテムかどうかの判定にis_valid() を使うよう差し替えた
  src/cmd-visual/cmd-visuals.cpp
  src/io/interpret-pref-file.cpp
  src/item-info/flavor-initializer.cpp
  src/object/object-kind-hook.cpp
  src/system/baseitem-info.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#3956 rooms-special.cpp の整形作業
  src/room/rooms-special.cpp
  src/system/dungeon-info.h
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#3957 rooms-fractal.cpp の整形作業
  src/room/rooms-fractal.cpp
Labels: refactor, Priority:MIDDLE

#3955 rooms-city.cpp の整形作業
  src/room/rooms-city.cpp
  src/room/rooms-city.h
Labels: refactor, Priority:MIDDLE
