Repository hengband/hengband, pull requests merged in 2024-10, with the labels that each got.

#4537 [Refactor] `NUM_O_SET` / `NUM_O_BIT` をローカルconstに更新。
  src/wizard/wizard-special-process.cpp
Labels: refactor

#4547 [Feature] #4546 虹色の宝箱にテレポート耐性を追加
  lib/edit/MonraceDefinitions.jsonc
Labels: enhancement

#4539 モンスター「デカアゴムシ」と「スネッコ」を追加
  lib/edit/MonraceDefinitions.jsonc
Labels: enhancement

#4531 monraces_info へ直接アクセスしている箇所を削減した
  src/core/game-play.cpp
  src/floor/fixed-map-generator.cpp
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-uniques.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/system/dungeon-info.cpp
  src/view/display-lore.cpp
  src/view/display-lore.h
  src/window/display-sub-windows.cpp
Labels: refactor, Priority:MIDDLE

#4540 MonsterRaceInfo::cur_num を部分的にカプセル化した
  src/birth/game-play-initializer.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-save.cpp
  src/load/floor-loader.cpp
  src/load/old/load-v1-5-0.cpp
  src/monster-floor/monster-remover.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-list.cpp
  src/monster/monster-status.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#4550 monraces_info への直接アクセスをメソッドに書き換えた その15
  src/monster/monster-damage.cpp
  src/monster/monster-damage.h
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/wizard/monster-info-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#4535 lore_type::build_speed() を定義して表記部分を軽量化した
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/view/display-lore.cpp
  src/view/display-lore.h
Labels: refactor, Priority:MIDDLE

#4534 モンスターの加速表記を細分化した
  src/lore/lore-util.cpp
Labels: refactor, Priority:MIDDLE

#4551 monraces_info へ直接アクセスしている箇所を削減した その16
  src/dungeon/quest.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster/monster-info.cpp
  src/monster/monster-info.h
  src/monster/monster-list.cpp
  src/mspell/mspell-summon.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#4544 FloorType::mproc_list/mproc_max とMonsterEntity::mproc をmap に変えた
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/dungeon/dungeon-processor.cpp
  src/floor/floor-generator.cpp
  src/io/screen-util.cpp
  src/monster-floor/monster-remover.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-compaction.cpp
  src/monster/monster-status-setter.cpp
  src/monster/monster-status.cpp
  src/monster/monster-status.h
  src/monster/monster-timed-effects.cpp
  src/monster/monster-timed-effects.h
  src/save/monster-entity-writer.cpp
  src/save/save.cpp
  src/spell-kind/spells-polymorph.cpp
  src/system/floor-type-definition.cpp
  src/system/floor-type-definition.h
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/window/main-window-row-column.h
  src/world/world-turn-processor.cpp
Labels: refactor, Priority:MIDDLE
