Repository hengband/hengband, pull requests merged in 2024-01, with the labels that each got.

#3803 性別フラグをEnum class化した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  lib/edit/MonsterRaceDefinitions.txt
  src/Makefile.am
  src/cmd-action/cmd-attack.cpp
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/io/files-util.cpp
  src/lore/monster-lore.cpp
  src/mind/monk-attack.cpp
  src/monster-race/race-sex-const.cpp
  src/monster-race/race-sex-const.h
  src/monster/monster-describer.cpp
  src/monster/monster-util.cpp
  src/system/dungeon-info.h
  src/system/monster-race-info.h
  src/target/target-describer.cpp
Labels: refactor

#3806 敵の打撃効果にカオス効果を追加した
  src/info-reader/race-info-tokens-table.cpp
  src/lore/combat-types-setter.cpp
  src/melee/melee-switcher.cpp
  src/monster-attack/monster-attack-effect.h
  src/monster-attack/monster-attack-switcher.cpp
Labels: enhancement

#3807 project()のgm_radのスコープを狭めた
  src/effect/effect-processor.cpp
Labels: refactor

#3809 敵魔法「スターライトアロー」を実装+天使達に配る
  lib/edit/MonsterRaceDefinitions.txt
  src/blue-magic/blue-magic-ball-bolt.cpp
  src/blue-magic/blue-magic-ball-bolt.h
  src/blue-magic/blue-magic-caster.cpp
  src/blue-magic/learnt-info.cpp
  src/cmd-action/cmd-mane.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/lore/magic-types-setter.cpp
  src/monster-race/race-ability-flags.h
  src/monster-race/race-ability-mask.cpp
  src/mspell/assign-monster-spell.cpp
  src/mspell/monster-power-table.cpp
  src/mspell/mspell-attack/mspell-bolt.cpp
  src/mspell/mspell-damage-calculator.cpp
Labels: enhancement

#3812 MonsterRaceDefinitions.txtのWパラメータ説明文を現行仕様に修正
  lib/edit/MonsterRaceDefinitions.txt
Labels: documentation

#3810 UNIQUE2を分離した
  lib/edit/MonsterRaceDefinitions.txt
  src/combat/attack-criticality.cpp
  src/combat/shoot.cpp
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-oldies.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/load/lore-loader.cpp
  src/market/arena.cpp
  src/market/bounty.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/race-flags-resistance.h
  src/monster-race/race-population-flags.h
  src/monster/monster-list.cpp
  src/spell-kind/spells-genocide.cpp
  src/view/display-lore-status.cpp
Labels: enhancement, refactor

#3818 Update spec to 3.0.1.5
  hengband.spec
Labels: release

#3824 ナズグル及びUNIQUE2によるクローン・モンスターの魔法棒の耐性判定が真偽反転しているバグを修正
  src/effect/effect-monster-oldies.cpp
Labels: bug

#3821 赤チォコヴォLv99及びメテオ・スウォームの性能調整
  lib/edit/MonsterRaceDefinitions.txt
  src/mspell/mspell-damage-calculator.cpp
Labels: enhancement

#3833 カオス効果の打撃の地震に関する不自然なメッセージを修正
  src/melee/melee-switcher.cpp
  src/monster-attack/monster-attack-switcher.cpp
Labels: bug

#3813 ユニークモンスター「カフモ」を追加
  lib/edit/MonsterRaceDefinitions.txt
Labels: enhancement

#3830 [Fix] 初級修験者の経験値が中級修験者より高い
  lib/edit/MonsterRaceDefinitions.txt
Labels: bug

#3832 [Fix] HEAVY_SPELLとHARD_SPELLの統一
  lib/edit/ArtifactDefinitions.txt
  lib/edit/EgoDefinitions.txt
  src/info-reader/baseitem-tokens-table.cpp
  src/object-enchant/tr-types.h
  src/perception/identification.cpp
  src/player-info/body-improvement-info.cpp
  src/player/player-status-flags.cpp
  src/player/player-status-flags.h
  src/player/player-status.cpp
  src/smith/smith-tables.cpp
  src/spell/spell-info.cpp
  src/system/player-type-definition.h
Labels: refactor

#3829 [Fix] 荒野でレベルテレポートしたときダンジョン内に入らない
  src/spell-kind/spells-world.cpp
Labels: bug

#3828 [Fix] セーブファイルが相対パスで保存できない #3744
  src/main-win.cpp
Labels: bug

#3838 Release/3.0.1.6 beta
  configure.ac
  doxygen/Hengband.doxyfile
  hengband.spec
  lib/edit/ArtifactDefinitions.txt
  lib/edit/EgoDefinitions.txt
  lib/edit/MonsterRaceDefinitions.txt
  src/effect/effect-monster-oldies.cpp
  src/info-reader/baseitem-tokens-table.cpp
  src/main-win.cpp
  src/melee/melee-switcher.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/mspell/mspell-damage-calculator.cpp
  src/object-enchant/tr-types.h
  src/perception/identification.cpp
  src/player-info/body-improvement-info.cpp
  src/player/player-status-flags.cpp
  src/player/player-status-flags.h
  src/player/player-status.cpp
  src/smith/smith-tables.cpp
  src/spell-kind/spells-world.cpp
  src/spell-realm/spells-crusade.cpp
  src/spell/spell-info.cpp
  src/system/angband-version.h
  src/system/player-type-definition.h
Labels: release

#3840 Update spec
  hengband.spec
Labels: release

#3845 [Refactor] フロア移動周りの可読性向上
  src/floor/floor-changer.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-save-util.cpp
  src/floor/floor-save-util.h
  src/floor/floor-save.cpp
  src/floor/floor-save.h
  src/load/dungeon-loader.cpp
  src/save/floor-writer.cpp
  src/spell-kind/spells-grid.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
Labels: refactor

#3848 ダメージキャップを先行実装
  Hengband/Hengband/Hengband.vcxproj
  src/Makefile.am
  src/info-reader/dungeon-reader.cpp
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-info-tokens-table.h
  src/info-reader/race-reader.cpp
  src/load/lore-loader.cpp
  src/lore/lore-calculator.cpp
  src/lore/lore-store.cpp
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/lore/monster-lore.cpp
  src/monster-race/race-special-flags.h
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-status.cpp
  src/monster/monster-update.cpp
  src/monster/monster-util.cpp
  src/save/monster-writer.cpp
  src/system/angband-version.h
  src/system/dungeon-info.h
  src/system/monster-race-info.h
Labels: enhancement

#3841 [Fix] C画面近接ダメージの計算を修正
  src/combat/attack-criticality.cpp
  src/combat/attack-criticality.h
  src/combat/shoot.cpp
  src/combat/shoot.h
  src/market/building-craft-weapon.cpp
  src/mind/monk-attack.cpp
  src/mind/monk-attack.h
  src/view/status-first-page.cpp
Labels: bug
