Repository hengband/hengband, pull requests merged in 2024-03, with the labels that each got.

#3814 モンスター「ラフィーII」実装
  lib/edit/MonsterRaceDefinitions.txt
  lib/file/mondeath.txt
  lib/file/mondeath_j.txt
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
  src/monster-race/race-indice-types.h
  src/monster/monster-pain-describer.cpp
  src/mspell/mspell-summon.cpp
  src/mspell/specified-summon.cpp
  src/mspell/specified-summon.h
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: enhancement, suspended

#3869 [Release] 3.0.1.8-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3874 Update hengband.spec
  hengband.spec
Labels: release

#3872 ラフィーIIが専用のセリフをしゃべらないバグ＆ラフィーIIの護衛がラフィーIIになっているバグを修正
  lib/edit/MonsterRaceDefinitions.txt
  lib/file/mondeath.txt
  lib/file/mondeath_j.txt
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
Labels: bug, Priority:HIGH

#3875 地形の思い出フラグを読み込む際モンスターの種族情報を書き換えてしまっているバグを修正
  src/load/lore-loader.cpp
Labels: bug, Priority:HIGH

#3879 Include hengband-en.spec in the archive generated by 'make dist'
  Makefile.am
Labels: bug

#3881 [Release] 3.0.1.9-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3882 Release/3.0.1.9 beta
  Makefile.am
  configure.ac
  doxygen/Hengband.doxyfile
  hengband-en.spec
  hengband.spec
  lib/edit/MonsterRaceDefinitions.txt
  lib/file/mondeath.txt
  lib/file/mondeath_j.txt
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
  src/load/lore-loader.cpp
  src/system/angband-version.h
Labels: release

#3884 死体復活によるペット判定がおかしいバグを修正
  src/effect/effect-item.cpp
Labels: bug

#3890 タイル情報の書き出しがおかしいバグを修正
  src/cmd-visual/cmd-visuals.cpp
  src/io/interpret-pref-file.cpp
Labels: bug

#3893 Release/3.0.1.10 beta
  Makefile.am
  configure.ac
  doxygen/Hengband.doxyfile
  hengband-en.spec
  hengband.spec
  src/cmd-visual/cmd-visuals.cpp
  src/effect/effect-item.cpp
  src/io/interpret-pref-file.cpp
  src/system/angband-version.h
Labels: release

#3892 [Release] 3.0.1.10-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release
