Repository hengband/hengband, pull requests merged in 2024-11, with the labels that each got.

#4552 monraces_info へ直接アクセスしている箇所を削減した その17
  lib/edit/MonraceDefinitions.jsonc
  src/info-reader/race-reader.cpp
  src/knowledge/knowledge-uniques.cpp
  src/main/game-data-initializer.cpp
  src/monster/monster-list.cpp
  src/monster/monster-util.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/system/alloc-entries.cpp
  src/system/alloc-entries.h
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#4553 モンスターの思い出読み込み処理において、monraces_info への直接アクセスをMonraceList へ置き換えた
  src/birth/game-play-initializer.cpp
  src/load/lore-loader.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/system/system-variables.h
Labels: refactor, Priority:MIDDLE

#4564 モンスターの加速表記に亜光速、光速を追加した
  src/lore/lore-util.cpp
Labels: enhancement

#4557 enums/ ディレクトリを作って1つヘッダを移した
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/auto-roller.cpp
  src/birth/birth-util.cpp
  src/birth/birth-wizard.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-io/cmd-gameoption.h
  src/game-option/option-types-table.cpp
  src/io/interpret-pref-file.cpp
  src/mind/mind-elementalist.cpp
  src/system/enums/game-option-page.h
  src/util/string-processor.cpp
Labels: refactor, Priority:MIDDLE

#4561 enum game_option_page をenum class GameOpenPage に変えた
  src/birth/auto-roller.cpp
  src/birth/birth-util.cpp
  src/birth/birth-util.h
  src/birth/birth-wizard.cpp
  src/birth/character-builder.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-io/cmd-gameoption.h
  src/game-option/option-types-table.cpp
  src/game-option/option-types-table.h
  src/io/interpret-pref-file.cpp
  src/io/report.cpp
  src/main/game-data-initializer.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-elementalist.h
  src/racial/racial-draconian.cpp
  src/save/info-writer.cpp
  src/system/enums/game-option-page.h
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#4562 enum flow_type をenum class GridFlow に変えた
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/grid/grid.cpp
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/system/enums/grid-flow.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/target/target-describer.cpp
Labels: refactor, Priority:MIDDLE

#4565 「モンスター希少度範囲外」のエラーはリファクタリングの過程で不要になったはずが残ってしまっていたのを修正
  src/info-reader/race-reader.cpp
Labels: bug, Priority:LOW

#4566 PlayerProtection クラスを作った
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/core/magic-effects-timeout-reducer.cpp
  src/load/player-info-loader.cpp
  src/monster-attack/monster-attack-player.cpp
  src/mspell/mspell-dispel.cpp
  src/object-activation/activation-switcher.cpp
  src/object-use/read/scroll-read-executor.cpp
  src/player-info/body-improvement-info.cpp
  src/player-info/self-info.cpp
  src/realm/realm-craft.cpp
  src/realm/realm-crusade.cpp
  src/save/player-writer.cpp
  src/spell/spells-staff-only.cpp
  src/status/body-improvement.cpp
  src/status/body-improvement.h
  src/status/buff-setter.cpp
  src/system/player-type-definition.h
  src/timed-effect/player-protection.cpp
  src/timed-effect/player-protection.h
  src/timed-effect/timed-effects.cpp
  src/timed-effect/timed-effects.h
  src/window/main-window-stat-poster.cpp
Labels: refactor, Priority:MIDDLE

#4571 count_dt() の引数から関数ポインタを除去した
  src/action/open-close-execution.cpp
  src/cmd-action/cmd-open-close.cpp
  src/floor/cave-generator.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/object-allocator.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/grid/grid.cpp
  src/grid/grid.h
  src/monster-floor/monster-move.cpp
  src/spell-kind/spells-grid.cpp
  src/spell-realm/spells-chaos.cpp
  src/system/dungeon-info.cpp
  src/system/dungeon-info.h
Labels: refactor, Priority:MIDDLE

#4579 make_gold() をFloorType のオブジェクトメソッドへ繰り込んだ
  src/floor/fixed-map-generator.cpp
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/grid/object-placer.cpp
  src/monster-floor/monster-death.cpp
  src/object/object-info.h
  src/specific-object/chest.cpp
  src/system/floor-type-definition.cpp
  src/system/floor-type-definition.h
Labels: refactor, Priority:MIDDLE

#4580 store_type::stock をunique_ptr<ItemEntity[]> からvector<unique_ptr<ItemEntity>> に変えた
  src/floor/floor-town.cpp
  src/floor/floor-town.h
  src/io-dump/character-dump.cpp
  src/io-dump/random-art-info-dumper.cpp
  src/knowledge/knowledge-inventory.cpp
  src/knowledge/knowledge-self.cpp
  src/load/store-loader.cpp
  src/main/game-data-initializer.h
  src/market/building-initializer.cpp
  src/player/process-death.cpp
  src/save/info-writer.cpp
  src/store/black-market.cpp
  src/store/home.cpp
  src/store/museum.cpp
  src/store/pricing.cpp
  src/store/pricing.h
  src/store/purchase-order.cpp
  src/store/store-util.cpp
  src/store/store-util.h
  src/store/store.cpp
  src/view/display-store.cpp
Labels: refactor, Priority:MIDDLE

#4583 describe_flavor() を呼び出している箇所のコード整形 その1
  src/action/weapon-shield.cpp
  src/autopick/autopick.cpp
Labels: refactor, Priority:MIDDLE

#4587 [Refactor] object_sort_comp 関数のシグネチャ調整
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-item/cmd-destroy.cpp
  src/inventory/inventory-object.cpp
  src/load/store-loader.cpp
  src/spell-realm/spells-sorcery.cpp
  src/store/home.cpp
  src/store/pricing.cpp
  src/store/sell-order.cpp
  src/store/service-checker.cpp
  src/store/store-util.cpp
  src/store/store.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/util/object-sort.cpp
  src/util/object-sort.h
  src/window/display-sub-windows.cpp
  src/wizard/items-spoiler.cpp
Labels: refactor

#4588 [Refactor] 店舗のアイテム一覧の挿入/削除/並び替え処理
  src/load/store-loader.cpp
  src/store/home.cpp
  src/store/store-util.cpp
Labels: refactor

#4584 describe_flavor() を呼び出している箇所のコード整形 その2
  src/cmd-item/cmd-equipment.cpp
  src/effect/effect-item.cpp
Labels: refactor, Priority:MIDDLE

#4589 describe_flavor() を呼び出している箇所のコード整形 その3
  src/floor/floor-object.cpp
  src/floor/floor-streams.cpp
  src/floor/object-scanner.cpp
Labels: refactor, Priority:MIDDLE

#4590 describe_flavor() を呼び出している箇所のコード整形 その4
  src/hpmp/hp-mp-processor.cpp
Labels: refactor, Priority:MIDDLE

#4594 describe_flavor() を呼び出している箇所のコード整形 その5
  src/inventory/inventory-curse.cpp
  src/inventory/inventory-damage.cpp
  src/inventory/inventory-object.cpp
  src/inventory/inventory-util.cpp
  src/inventory/pack-overflow.cpp
  src/inventory/player-inventory.cpp
  src/inventory/recharge-processor.cpp
Labels: refactor, Priority:MIDDLE

#4575 マクロ関数plural() を除去し、思い出表記のユニーク撃破状況についてlore_type へ文字列組み立てを移管した
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/view/display-lore.cpp
Labels: refactor, Priority:MIDDLE

#4581 check_magic_eater_spell_repeat() をmagic_eater_data_type のメソッドへ繰り込んだ
  src/cmd-building/cmd-inn.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/hpmp/hp-mp-regenerator.cpp
  src/io-dump/special-class-dump.cpp
  src/load/player-class-specific-data-loader.cpp
  src/load/player-class-specific-data-loader.h
  src/mind/mind-magic-eater.cpp
  src/player-base/player-class.cpp
  src/player-info/class-specific-data.h
  src/player-info/magic-eater-data-type.cpp
  src/player-info/magic-eater-data-type.h
  src/save/player-class-specific-data-writer.cpp
  src/save/player-class-specific-data-writer.h
  src/spell/spells-status.cpp
Labels: refactor, Priority:MIDDLE

#4591 make_artifact_special() をFloorType のオブジェクトメソッドへ繰り込んだ
  src/artifact/fixed-art-generator.cpp
  src/artifact/fixed-art-generator.h
  src/floor/floor-object.cpp
  src/system/floor-type-definition.cpp
  src/system/floor-type-definition.h
Labels: refactor, Priority:MIDDLE

#4593 count_dt() をFloorType へ繰り込むための準備
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-action/cmd-open-close.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/system/dungeon-info.cpp
  src/system/dungeon-info.h
  src/system/enums/grid-count-kind.h
  src/system/terrain-type-definition.cpp
  src/system/terrain-type-definition.h
Labels: refactor, Priority:MIDDLE

#4609 coin_type とOBJ_GOLD_LIST を廃止し、財宝ドロップ関連処理をBaseitemList でモデル化した
  src/floor/fixed-map-generator.cpp
  src/monster-floor/monster-death-util.cpp
  src/monster-floor/monster-death-util.h
  src/monster-floor/monster-death.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/floor-type-definition.cpp
  src/system/floor-type-definition.h
  src/system/system-variables.cpp
  src/system/system-variables.h
Labels: refactor, Priority:MIDDLE

#4608 [Feature] 特定財宝のみドロップするフラグの追加
  lib/edit/MonraceDefinitions.jsonc
  schema/MonraceDefinitions.schema.json
  src/monster-race/race-drop-flags.h
Labels: enhancement

#4611 [Fix] 財宝ドロップ指定フラグのr_info_drop_flagsへの追加
  src/info-reader/race-info-tokens-table.cpp
Labels: bug

#4598 describe_flavor() を呼び出している箇所のコード整形 その6
  src/knowledge/knowledge-inventory.cpp
  src/market/building-craft-fix.cpp
  src/market/building-craft-weapon.cpp
  src/monster-floor/monster-object.cpp
Labels: refactor, Priority:MIDDLE

#4605 FloorType::check_terrain() を実装してcount_dt() を軽量化した
  src/grid/grid.cpp
  src/system/dungeon-info.cpp
  src/system/floor-type-definition.cpp
  src/system/floor-type-definition.h
Labels: refactor, Priority:MIDDLE

#4626 rooms-trap.cpp を整形した
  src/room/rooms-trap.cpp
Labels: refactor, Priority:MIDDLE

#4631 monraces_info へのアクセスをMonraceList に差し替えた その18
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-uniques.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#4627 rooms-vault.cpp を整形した
  src/room/rooms-vault.cpp
Labels: refactor, Priority:MIDDLE

#4613 describe_flavor() を呼び出している箇所のコード整形 その8
  src/spell-kind/spells-enchant.cpp
  src/spell-kind/spells-equipment.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-perception.cpp
  src/spell-realm/spells-sorcery.cpp
  src/spell/spells-object.cpp
  src/spell/spells-status.cpp
Labels: refactor, Priority:MIDDLE

#4632 monraces_info へのアクセスをMonraceList に差し替えた その19
  src/lore/lore-calculator.cpp
  src/lore/lore-calculator.h
  src/lore/lore-util.cpp
  src/lore/lore-util.h
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/view/display-lore-attacks.cpp
  src/view/display-lore-status.cpp
  src/view/display-lore.cpp
Labels: refactor, Priority:MIDDLE

#4599 projectable() の引数調整
  src/blue-magic/blue-magic-caster.cpp
  src/cmd-action/cmd-mane.cpp
  src/effect/effect-player.cpp
  src/effect/effect-processor.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-object.cpp
  src/floor/floor-util.cpp
  src/floor/geometry.cpp
  src/grid/trap.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mind/mind-force-trainer.cpp
  src/mind/mind-mirror-master.cpp
  src/monster-floor/monster-direction.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-runaway.cpp
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
  src/monster/monster-processor.cpp
  src/monster/monster-status-setter.cpp
  src/monster/monster-update.cpp
  src/mspell/mspell-attack-util.cpp
  src/mspell/mspell-attack-util.h
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-lite.cpp
  src/mspell/mspell-lite.h
  src/object-activation/activation-others.cpp
  src/object/warning.cpp
  src/realm/realm-hissatsu.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-sight.cpp
  src/spell-kind/spells-world.cpp
  src/spell-realm/spells-chaos.cpp
  src/spell/range-calc.cpp
  src/spell/spells-summon.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/target/projection-path-calculator.cpp
  src/target/projection-path-calculator.h
  src/target/target-preparation.cpp
  src/target/target-setter.cpp
Labels: refactor, Priority:MIDDLE

#4614 describe_flavor() を呼び出している箇所のコード整形 その9
  src/store/cmd-store.cpp
  src/store/store-util.cpp
  src/store/store-util.h
  src/store/store.cpp
  src/store/store.h
Labels: refactor, Priority:MIDDLE

#4607 グローバル関数is_open()、is_closed_door()、is_trap() を廃止した
  src/action/movement-execution.cpp
  src/action/open-close-execution.cpp
  src/action/travel-execution.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-travel.cpp
  src/effect/effect-feature.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/grid/grid.cpp
  src/grid/grid.h
  src/grid/trap.cpp
  src/mind/mind-berserker.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/object/warning.cpp
  src/player/player-move.cpp
  src/realm/realm-hissatsu.cpp
  src/room/rooms-special.cpp
  src/room/rooms-vault.cpp
  src/system/floor-type-definition.cpp
  src/system/floor-type-definition.h
Labels: refactor, Priority:MIDDLE

#4638 projectable() の変換漏れを微調整した
  src/floor/floor-leaver.cpp
  src/floor/geometry.cpp
  src/monster-floor/monster-direction.cpp
  src/monster/monster-update.cpp
  src/mspell/mspell-lite.cpp
Labels: refactor, Priority:MIDDLE

#4601 try_make_instant_artifact() でArtifactType に依存する箇所をオブジェクトメソッドへ繰り込んだ
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/system/floor-type-definition.cpp
Labels: refactor, Priority:MIDDLE

#4615 describe_flavor() を呼び出している箇所のコード整形 その10
  src/target/target-describer.cpp
  src/view/display-inventory.cpp
  src/view/object-describer.cpp
Labels: refactor, Priority:MIDDLE

#4621 ArtifactType とArtifactList のカプセル化を向上させた
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/system/floor-type-definition.cpp
Labels: refactor, Priority:MIDDLE

#4633 monraces_info へのアクセスをMonraceList に差し替えた その20
  src/main-win.cpp
  src/main-win/main-win-cfg-reader.cpp
  src/main-win/main-win-cfg-reader.h
  src/main-win/main-win-music.cpp
  src/main-win/main-win-music.h
  src/main-win/main-win-sound.cpp
  src/main-win/main-win-utils.h
Labels: refactor, Priority:MIDDLE

#4616 describe_flavor() を呼び出している箇所のコード整形 その11
  src/window/display-sub-windows.cpp
  src/window/main-window-equipments.cpp
  src/window/main-window-util.cpp
  src/wizard/artifact-analyzer.cpp
Labels: refactor, Priority:MIDDLE

#4628 find_space() の引数を差し替える準備 その1
  src/floor/cave-generator.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-streams.h
  src/floor/tunnel-generator.cpp
  src/floor/tunnel-generator.h
  src/grid/feature-generator.cpp
  src/grid/feature-generator.h
  src/room/room-generator.cpp
  src/room/room-generator.h
  src/room/rooms-city.cpp
  src/room/rooms-city.h
  src/room/rooms-fractal.cpp
  src/room/rooms-fractal.h
  src/room/rooms-nest.cpp
  src/room/rooms-nest.h
  src/room/rooms-normal.cpp
  src/room/rooms-normal.h
  src/room/rooms-pit.cpp
  src/room/rooms-pit.h
  src/room/rooms-special.cpp
  src/room/rooms-special.h
  src/room/rooms-trap.cpp
  src/room/rooms-trap.h
  src/room/rooms-vault.cpp
  src/room/rooms-vault.h
  src/room/space-finder.cpp
  src/room/space-finder.h
  src/system/dungeon-data-definition.h
Labels: refactor, Priority:MIDDLE

#4634 monraces_info へのアクセスをMonraceList に差し替えた その21
  src/monster/monster-list.cpp
  src/monster/monster-status.cpp
Labels: refactor, Priority:MIDDLE

#4600 Visual Editor 周辺の小修正
  src/cmd-visual/cmd-visuals.cpp
  src/knowledge/knowledge-features.cpp
Labels: bug, refactor, Priority:LOW

#4617 is_similar_for_store() をItemEntity のオブジェクトメソッドへ繰り込んだ
  src/store/store-util.cpp
  src/store/store-util.h
  src/store/store.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: refactor, Priority:MIDDLE

#4635 EffectPlayer/EffectMonster のカプセル化を推し進めた
  src/effect/effect-monster-curse.cpp
  src/effect/effect-monster-oldies.cpp
  src/effect/effect-monster-spirit.cpp
  src/effect/effect-monster-switcher.cpp
  src/effect/effect-monster-util.cpp
  src/effect/effect-monster-util.h
  src/effect/effect-monster.cpp
  src/effect/effect-player-spirit.cpp
  src/effect/effect-player.cpp
  src/effect/effect-player.h
  src/mind/mind-elementalist.cpp
Labels: refactor, Priority:MIDDLE

#4618 BaseitemKey::are_both_statue() を作って像の判定処理を繰り込んだ
  src/autopick/autopick-matcher.cpp
  src/floor/floor-object.cpp
  src/inventory/inventory-object.cpp
  src/inventory/inventory-slot-types.h
  src/load/store-loader.cpp
  src/object/object-stack.cpp
  src/object/object-stack.h
  src/store/home.cpp
  src/store/store.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: refactor, Priority:MIDDLE

#4636 monraces_info へのアクセスをMonraceList に差し替えた その23
  src/monster/monster-util.cpp
  src/system/dungeon-info.h
Labels: refactor, Priority:MIDDLE

#4619 ItemEntity からMonraceId が陽に見えないようにした
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#4629 DungeonData のクラス化とカプセル化を推し進めた
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/floor/cave-generator.cpp
  src/floor/cave-generator.h
  src/floor/floor-generator.cpp
  src/floor/floor-streams.cpp
  src/floor/tunnel-generator.cpp
  src/room/space-finder.cpp
  src/system/dungeon-data-definition.cpp
  src/system/dungeon-data-definition.h
Labels: refactor, Priority:MIDDLE

#4620 object_absorb() をItemEntity のオブジェクトメソッドへ繰り込んだ
  src/floor/floor-object.cpp
  src/inventory/inventory-object.cpp
  src/load/store-loader.cpp
  src/object/object-stack.cpp
  src/object/object-stack.h
  src/store/home.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: refactor, Priority:MIDDLE

#4630 find_space() の引数を差し替える準備 その2
  src/floor/cave-generator.cpp
  src/floor/tunnel-generator.cpp
  src/floor/tunnel-generator.h
Labels: refactor, Priority:MIDDLE

#4646 隠しドアが見つからない不具合を修正した
  src/grid/grid.cpp
Labels: bug, Priority:MIDDLE

#4647 Release/3.0.1.21 beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#4650 is_hidden_door() をGrid のオブジェクトメソッドへ繰り込み、PlayerType への依存を外した
  src/action/tunnel-execution.cpp
  src/effect/effect-feature.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/player/player-move.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
Labels: refactor, Priority:MIDDLE

#4625 ベースアイテムに直接アクセスしている箇所をItemEntity でカプセル化した
  src/cmd-item/cmd-eat.cpp
  src/core/object-compressor.cpp
  src/flavor/flavor-describer.cpp
  src/floor/floor-events.cpp
  src/inventory/recharge-processor.cpp
  src/item-info/flavor-initializer.cpp
  src/market/building-recharger.cpp
  src/mind/mind-mage.cpp
  src/monster-attack/monster-eating.cpp
  src/object-activation/activation-util.cpp
  src/object-enchant/item-magic-applier.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/object-use/quaff/quaff-execution.cpp
  src/object-use/read/read-execution.cpp
  src/object-use/use-execution.cpp
  src/object-use/zaprod-execution.cpp
  src/object-use/zapwand-execution.cpp
  src/object/object-stack.cpp
  src/object/object-value.cpp
  src/perception/object-perception.cpp
  src/racial/racial-android.cpp
  src/spell-kind/magic-item-recharger.cpp
  src/store/store-util.cpp
  src/system/baseitem/baseitem-definition.cpp
  src/system/baseitem/baseitem-definition.h
  src/system/baseitem/baseitem-list.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/wizard/items-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor, Priority:MIDDLE

#4652 [Feature] 財宝に生成階層とレアリティを設定する
  lib/edit/BaseitemDefinitions.jsonc
  src/object-enchant/item-apply-magic.h
  src/system/alloc-entries.cpp
  src/system/alloc-entries.h
  src/world/world-object.cpp
Labels: enhancement

#4651 モンスター種族IDではなくモンスターの特定財宝ドロップフラグに基づいて生成する財宝を選択するようにした
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/main/angband-initializer.cpp
  src/monster-floor/monster-death.cpp
  src/system/baseitem/baseitem-list.cpp
  src/system/baseitem/baseitem-list.h
  src/system/services/baseitem-monrace-service.cpp
  src/system/services/baseitem-monrace-service.h
Labels: refactor, Priority:MIDDLE

#4656 [Refactor] 特殊財宝ドロップフラグの重複チェック処理
  src/main/angband-initializer.cpp
  src/system/services/baseitem-monrace-service.cpp
  src/system/services/baseitem-monrace-service.h
Labels: refactor

#4659 [Freature] 財宝の生成階層、レアリティ、価格の調整
  lib/edit/BaseitemDefinitions.jsonc
Labels: enhancement

#4662 [Fix] モンスターの思い出に撃破数が表示されない
  src/view/display-lore.cpp
Labels: bug, Priority:MIDDLE

#4664 地上でLv1の財宝ドロップモンスターを倒すと異常アイテムを生成してしまう不具合を修正した
  src/system/floor-type-definition.cpp
Labels: bug, Priority:HIGH

#4655 店のアイテムに関するunique_ptr.get() を参照に変えた その3
  src/artifact/random-art-generator.cpp
  src/birth/inventory-initializer.cpp
  src/cmd-item/cmd-eat.cpp
  src/floor/floor-object.cpp
  src/io-dump/random-art-info-dumper.cpp
  src/market/bounty.cpp
  src/mind/mind-archer.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/object-use/quaff/quaff-execution.cpp
  src/object-use/read/read-execution.cpp
  src/object-use/use-execution.cpp
  src/object-use/zaprod-execution.cpp
  src/object-use/zapwand-execution.cpp
  src/perception/object-perception.cpp
  src/perception/object-perception.h
  src/player/process-death.cpp
  src/smith/object-smith.cpp
  src/spell-kind/spells-perception.cpp
  src/spell/spells-object.cpp
  src/store/purchase-order.cpp
  src/wizard/artifact-analyzer.cpp
  src/wizard/artifact-analyzer.h
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#4666 [Feature] 財宝:黒曜石の追加、および財宝全体の生成階層、レアリティの調整
  lib/edit/BaseitemDefinitions.jsonc
  schema/MonraceDefinitions.schema.json
  src/info-reader/race-info-tokens-table.cpp
  src/monster-race/race-drop-flags.h
  src/system/services/baseitem-monrace-service.cpp
Labels: enhancement

#4668 [Add] 宝石類ゴーレムの追加
  lib/edit/MonraceDefinitions.jsonc
Labels: enhancement
