Repository hengband/hengband, pull requests merged in 2024-05, with the labels that each got.

#3979 randint0/1 が例外を吐く事象を修正した
  src/object-enchant/object-ego.cpp
  src/term/z-rand.cpp
  src/term/z-rand.h
Labels: bug, Priority:HIGH

#3980 [Refactor] plural_aux() のシグニチャの改善
  src/dungeon/quest.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-quests.cpp
  src/locale/english.cpp
  src/locale/english.h
  src/spell-kind/spells-sight.cpp
  src/view/display-lore.cpp
Labels: refactor

#3983 [Fix] キャラメイク画面で負の経験値修正が正しく表示されない
  src/birth/birth-wizard.cpp
Labels: bug

#3985 [Fix] 確認メッセージのカーソルが変な場所に表示される
  src/core/asking-player.cpp
Labels: bug

#3984 [Fix] フロア・リセットで提示される階層の初期値がおかしい
  src/spell-kind/spells-world.cpp
Labels: bug, enhancement

#3982 [Refactor] クエストの説明テキストの処理
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/floor/fixed-map-generator.cpp
  src/knowledge/knowledge-quests.cpp
  src/market/building-quest.cpp
  src/target/target-describer.cpp
  src/view/display-player.cpp
Labels: refactor

#3973 ColoredChar クラスを作成した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/view/colored-char.h
  src/view/display-map.cpp
  src/window/main-window-util.cpp
  src/window/main-window-util.h
Labels: refactor, Priority:MIDDLE

#3962 MonsterPainDescriber の MONSTER_IDX に依存したコンストラクタをなくした
  src/combat/shoot.cpp
  src/effect/effect-monster.cpp
  src/monster/monster-pain-describer.cpp
  src/monster/monster-pain-describer.h
  src/object-use/throw-execution.cpp
Labels: refactor

#3987 TerrainList にrbegin()/rend() を実装した
  src/info-reader/feature-reader.cpp
  src/system/terrain-type-definition.cpp
  src/system/terrain-type-definition.h
Labels: refactor, Priority:MIDDLE

#3918 [Feature] Vector2Dクラス
  src/floor/cave.cpp
  src/floor/cave.h
  src/floor/floor-streams.cpp
  src/floor/geometry.h
  src/grid/grid.cpp
  src/realm/realm-hissatsu.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-lite.cpp
  src/target/target-getter.cpp
  src/target/target-getter.h
  src/util/point-2d.h
  src/view/display-map.cpp
  src/window/main-window-util.cpp
Labels: enhancement, refactor

#3964 `strcpy()` 使用部位の修正 その1
  src/avatar/avatar.cpp
  src/birth/game-play-initializer.cpp
  src/window/display-sub-windows.cpp
Labels: refactor

#3998 [Release] 3.0.1.12-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#3981 [Add] おたずねものムシシリーズを実装
  lib/edit/MonsterRaceDefinitions.txt
Labels: enhancement

#3988 コンパイル警告の解消 (β13)
  src/artifact/random-art-misc.cpp
  src/autopick/autopick-command-menu.cpp
  src/autopick/autopick-describer.cpp
  src/autopick/autopick-editor-util.cpp
  src/autopick/autopick-editor-util.h
  src/autopick/autopick-entry.cpp
  src/mind/mind-elementalist.cpp
  src/room/cave-filler.cpp
Labels: refactor, Priority:MIDDLE

#3995 [Fix] GCC 13 で出力される警告の対策
  src/info-reader/info-reader-util.h
  src/player/process-death.cpp
Labels: bug

#4006 rooms-pit-nest.cpp/h の整形作業 その1
  src/room/rooms-pit-nest.cpp
  src/room/rooms-pit-nest.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
Labels: refactor, Priority:MIDDLE

#4017 Update hengband.spec version to 3.0.1.12
  hengband.spec
Labels: release

#4020 [Fix] 正当なUTF-8で guess_convert_to_system_encoding() が失敗する
  src/locale/japanese.cpp
  src/locale/japanese.h
Labels: bug

#4016 [Refactor] self_info_type
  src/player-info/base-status-info.cpp
  src/player-info/body-improvement-info.cpp
  src/player-info/class-ability-info.cpp
  src/player-info/mutation-info.cpp
  src/player-info/race-ability-info.cpp
  src/player-info/resistance-info.cpp
  src/player-info/self-info-util.h
  src/player-info/self-info.cpp
  src/player-info/weapon-effect-info.cpp
  src/view/display-self-info.cpp
Labels: refactor

#4022 rooms-pit-nest.cpp の整形 その2
  src/room/rooms-pit-nest.cpp
  src/room/rooms-pit-nest.h
  src/util/point-2d.h
Labels: refactor, Priority:MIDDLE

#4026 Rectangle2D クラスを作り、左上/右下座標のペアをまとめた
  src/floor/wild.cpp
  src/room/rooms-city.cpp
  src/room/rooms-city.h
  src/room/rooms-fractal.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-pit-nest.cpp
  src/room/rooms-special.cpp
  src/util/point-2d.h
Labels: refactor, Priority:MIDDLE

#4027 [Feature] Rectangle2Dクラスにメソッドを追加
  src/room/rooms-city.cpp
  src/room/rooms-pit-nest.cpp
  src/util/point-2d.h
Labels: refactor

#4028 rooms-pit-nest.cpp/h をpit とnest に分離した
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/room/pit-nest-util.cpp
  src/room/pit-nest-util.h
  src/room/room-generator.cpp
  src/room/rooms-nest.cpp
  src/room/rooms-nest.h
  src/room/rooms-pit.cpp
  src/room/rooms-pit.h
Labels: refactor, Priority:MIDDLE

#4031 pit用の処理とnest用の処理を分離した
  src/room/pit-nest-util.cpp
  src/room/pit-nest-util.h
  src/room/rooms-nest.cpp
  src/room/rooms-pit.cpp
Labels: refactor, Priority:MIDDLE

#4032 [Feature] デバッグコマンドでアイテム生成するときに候補の表示にCandidateSelectorを使用する
  src/util/candidate-selector.h
  src/wizard/tval-descriptions-table.cpp
  src/wizard/tval-descriptions-table.h
  src/wizard/wizard-special-process.cpp
Labels: enhancement

#4035 [Feature] ウィンドウの幅に合わせてメッセージを折り返す
  src/view/display-messages.cpp
Labels: enhancement

#4034 rooms-pit.cpp の整形作業 その4
  src/room/pit-nest-util.cpp
  src/room/pit-nest-util.h
  src/room/rooms-nest.cpp
  src/room/rooms-pit.cpp
Labels: refactor, Priority:MIDDLE

#4038 baseitems_info をBaseitemList に差し替える準備
  src/birth/inventory-initializer.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/visuals-reseter.cpp
  src/flavor/object-flavor.cpp
  src/flavor/object-flavor.h
  src/info-reader/baseitem-reader.cpp
  src/io/interpret-pref-file.cpp
  src/item-info/flavor-initializer.cpp
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-items.cpp
  src/perception/object-perception.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/system/terrain-type-definition.h
  src/view/display-map.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#4018 [Refactor] MonsterRaceDefinitions.txtをJSON形式に変更する
  lib/edit/Makefile.am
  lib/edit/MonraceDefinitions.jsonc
  lib/edit/MonsterRaceDefinitions.txt
  schema/MonraceDefinitions.schema.json
  src/info-reader/general-parser.h
  src/info-reader/race-reader.cpp
  src/info-reader/race-reader.h
  src/main/angband-initializer.cpp
  src/main/info-initializer.cpp
  src/main/info-initializer.h
  src/term/gameterm.cpp
  src/term/gameterm.h
Labels: enhancement, refactor

#4049 [Fix] 英語flavor textのロードで例外が発生する
  src/info-reader/race-reader.cpp
Labels: bug

#4054 d_attr[] とd_char[] をmap<int, ColoredChar> にまとめた
  src/cmd-io/cmd-knowledge.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/visuals-reseter.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-reader.cpp
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-features.cpp
  src/system/terrain-type-definition.cpp
  src/system/terrain-type-definition.h
  src/view/colored-char.h
Labels: refactor, Priority:MIDDLE

#4060 TERM_COLORとchar の組み合わせで表現していたグローバル変数をシングルトンクラスに差し替えた
  src/cc_configs
  src/cc_defs
  src/io-dump/dump-util.cpp
  src/io-dump/dump-util.h
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/system/terrain-type-definition.cpp
  src/system/terrain-type-definition.h
  src/view/colored-char.h
Labels: refactor, Priority:MIDDLE

#4063 show-file.cpp をクラス化した
  src/autopick/autopick-editor-command.cpp
  src/birth/birth-util.cpp
  src/cmd-building/cmd-building.cpp
  src/cmd-io/cmd-diary.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-io/cmd-help.cpp
  src/core/show-file.cpp
  src/core/show-file.h
  src/knowledge/knowledge-autopick.cpp
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-inventory.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-mutations.cpp
  src/knowledge/knowledge-quests.cpp
  src/knowledge/knowledge-self.cpp
  src/knowledge/knowledge-uniques.cpp
  src/market/arena.cpp
  src/market/play-gamble.cpp
  src/object-use/read/parchment-read-executor.cpp
Labels: refactor, Priority:MIDDLE

#4044 baseitems_info をBaseitemList::instance() に差し替えた
  src/artifact/fixed-art-generator.cpp
  src/birth/game-play-initializer.cpp
  src/birth/inventory-initializer.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/visuals-reseter.cpp
  src/flavor/named-item-describer.cpp
  src/flavor/tval-description-switcher.cpp
  src/floor/floor-object.cpp
  src/info-reader/baseitem-reader.cpp
  src/io-dump/special-class-dump.cpp
  src/io/interpret-pref-file.cpp
  src/item-info/flavor-initializer.cpp
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-items.cpp
  src/load/item/item-loader-base.cpp
  src/main/game-data-initializer.cpp
  src/main/info-initializer.cpp
  src/market/building-craft-fix.cpp
  src/object/object-broken.cpp
  src/object/object-kind-hook.cpp
  src/save/item-writer.cpp
  src/save/save.cpp
  src/spell/spells-object.cpp
  src/spell/spells-status.cpp
  src/system/alloc-entries.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/view/display-map.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#3993 [Refactor] MonsterEntity 外のMonsterEntity.r_idx 系への依存をなくした
  src/cmd-action/cmd-pet.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-streams.cpp
  src/grid/grid.cpp
  src/hpmp/hp-mp-processor.cpp
  src/mind/mind-elementalist.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster/monster-list.cpp
  src/monster/monster-status.cpp
  src/player/player-skill.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/spell/spell-info.cpp
  src/system/monster-entity.cpp
  src/target/target-preparation.cpp
  src/util/sort.cpp
Labels: refactor

#4065 [Feature] auto_debug_saveオプションの廃止
  src/game-option/game-play-options.h
  src/game-option/option-types-table.cpp
  src/io/input-key-requester.cpp
  src/save/info-writer.cpp
  src/save/info-writer.h
  src/save/save.cpp
  src/save/save.h
Labels: enhancement

#4062 [Feature] メッセージ履歴の改良
  src/cmd-visual/cmd-draw.cpp
  src/io-dump/character-dump.cpp
  src/view/display-messages.cpp
  src/window/display-sub-windows.cpp
Labels: enhancement

#4071 FileDisplaery のコンストラクタにplayer_name を追加し、display() メソッドの引数を減らした
  src/autopick/autopick-editor-command.cpp
  src/birth/birth-util.cpp
  src/cmd-building/cmd-building.cpp
  src/cmd-io/cmd-diary.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/cmd-io/cmd-help.cpp
  src/core/show-file.cpp
  src/core/show-file.h
  src/knowledge/knowledge-autopick.cpp
  src/knowledge/knowledge-experiences.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-inventory.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-mutations.cpp
  src/knowledge/knowledge-quests.cpp
  src/knowledge/knowledge-self.cpp
  src/knowledge/knowledge-uniques.cpp
  src/market/arena.cpp
  src/market/play-gamble.cpp
  src/object-use/read/parchment-read-executor.cpp
Labels: refactor, Priority:MIDDLE

#4074 BaseitemList へメソッドをいくつか繰り込んだ
  src/birth/game-play-initializer.cpp
  src/birth/inventory-initializer.cpp
  src/core/visuals-reseter.cpp
  src/item-info/flavor-initializer.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
Labels: refactor, Priority:MIDDLE

#4082 MonsterPainDescriber のPlayerType 依存をなくした
  src/combat/shoot.cpp
  src/effect/effect-monster.cpp
  src/monster/monster-pain-describer.cpp
  src/monster/monster-pain-describer.h
  src/object-use/throw-execution.cpp
Labels: refactor

#4079 コード微調整 β13
  src/autopick/autopick-initializer.h
  src/birth/birth-util.h
  src/cmd-io/cmd-dump.h
  src/cmd-io/cmd-gameoption.h
  src/cmd-io/cmd-process-screen.h
  src/cmd-visual/cmd-draw.h
  src/floor/wild.h
  src/grid/trap.h
  src/info-reader/feature-reader.h
  src/io/command-repeater.h
  src/io/cursor.h
  src/io/files-util.h
  src/io/input-key-acceptor.h
  src/io/screen-util.h
  src/io/signal-handlers.h
  src/load/birth-loader.h
  src/load/dummy-loader.h
  src/load/info-loader.h
  src/load/load-util.h
  src/load/load-zangband.h
  src/load/lore-loader.h
  src/load/quest-loader.h
  src/load/world-loader.h
  src/main-win/commandline-win.h
  src/main-win/graphics-win.h
  src/main-win/main-win-bg.h
  src/main-win/main-win-music.h
  src/main-win/main-win-sound.h
  src/main-win/main-win-utils.h
  src/main/sound-of-music.h
  src/market/bounty.h
  src/market/building-initializer.cpp
  src/market/building-initializer.h
  src/market/poker.h
  src/monster/monster-processor-util.h
  src/save/info-writer.h
  src/store/store-util.h
  src/system/terrain-type-definition.h
  src/term/screen-processor.h
  src/term/z-rand.h
  src/term/z-term.h
  src/view/display-messages.h
  src/window/display-sub-windows.h
  src/wizard/wizard-special-process.h
  src/wizard/wizard-spoiler.h
Labels: refactor, Priority:MIDDLE

#4085 (3.0.1.13-Beta)ドラウナーの経験値を調整した
  lib/edit/MonraceDefinitions.jsonc
Labels: enhancement

#4005 [Add] ユニーク・モンスター「メガ・フレイム・ドラゴン」を実装した
  lib/edit/MonraceDefinitions.jsonc
Labels: enhancement, suspended

#4086 lookup_baseitem_id() をBaseitemList のオブジェクトメソッドへ繰り込んだ
  src/artifact/fixed-art-generator.cpp
  src/artifact/random-art-generator.cpp
  src/birth/inventory-initializer.cpp
  src/cmd-item/cmd-eat.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/effect/effect-monster.cpp
  src/floor/fixed-map-generator.cpp
  src/info-reader/general-parser.cpp
  src/io-dump/special-class-dump.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/old/load-v1-5-0.cpp
  src/market/bounty.cpp
  src/market/building-craft-fix.cpp
  src/market/building-initializer.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-chaos-warrior.cpp
  src/mind/mind-hobbit.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object-enchant/protector/apply-magic-armor.cpp
  src/object-enchant/protector/apply-magic-soft-armor.cpp
  src/object/object-kind-hook.cpp
  src/object/object-kind-hook.h
  src/player/patron.cpp
  src/realm/realm-nature.cpp
  src/spell/spells-object.cpp
  src/spell/spells-status.cpp
  src/store/rumor.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#4088 BaseitemList にlookup_baseitem() を実装し、bi_id が不要な箇所を差し替えた
  src/cmd-item/cmd-eat.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/io-dump/character-dump.cpp
  src/io-dump/special-class-dump.cpp
  src/knowledge/knowledge-quests.cpp
  src/mind/mind-archer.cpp
  src/spell/spells-object.cpp
  src/spell/spells-status.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
Labels: refactor, Priority:MIDDLE

#4089 path_build() の戻り値を参照ではなく値で受けるようにした
  src/autopick/autopick-reader-writer.cpp
  src/cmd-io/cmd-diary.cpp
  src/cmd-io/cmd-dump.cpp
  src/cmd-io/cmd-macro.cpp
  src/cmd-io/cmd-process-screen.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/game-closer.cpp
  src/core/game-play.cpp
  src/core/scores.cpp
  src/core/show-file.cpp
  src/info-reader/fixed-map-parser.cpp
  src/io-dump/random-art-info-dumper.cpp
  src/io/files-util.cpp
  src/io/read-pref-file.cpp
  src/io/record-play-movie.cpp
  src/io/write-diary.cpp
  src/main-win.cpp
  src/main-win/graphics-win.cpp
  src/main-win/main-win-cfg-reader.cpp
  src/main-win/main-win-file-utils.cpp
  src/main/angband-initializer.cpp
  src/main/info-initializer.cpp
  src/market/building-initializer.cpp
  src/view/display-scores.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/monster-info-spoiler.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#4091 [Feature] ./configure で言語標準に付与されるGNU拡張をOFFにする
  configure.ac
Labels: enhancement

#4095 [Chore] CIのビルドテストのGCCのバージョンを13に更新
  .github/workflows/build-with-autotools.yml
  .github/workflows/create-cache-for-ccache.yml
  .github/workflows/pull-request-status-check.yml
Labels: enhancement

#4094 ItemEntity のコンストラクタにベースアイテムID とBaseitemKey を受け取るコンストラクタ2種を追加した
  src/artifact/fixed-art-generator.cpp
  src/birth/inventory-initializer.cpp
  src/birth/inventory-initializer.h
  src/cmd-item/cmd-eat.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/effect/effect-monster.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-object.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-quests.cpp
  src/market/bounty.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-chaos-warrior.cpp
  src/mind/mind-hobbit.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object/tval-types.h
  src/realm/realm-nature.cpp
  src/smith/object-smith.cpp
  src/spell-kind/spells-enchant.cpp
  src/spell/spells-object.cpp
  src/store/rumor.cpp
  src/store/store.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/view/object-describer.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/items-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#4096 コンパイル警告の解消＋周辺コード整備
  src/external-lib/json.hpp
  src/io/interpret-pref-file.cpp
  src/io/interpret-pref-file.h
  src/io/read-pref-file.cpp
  src/main-win/main-win-sound.cpp
Labels: refactor, Priority:MIDDLE

#4100 ArtifactList にメソッドをいくつか定義し、FloorType と共にカプセル化した
  src/action/action-limited.cpp
  src/artifact/fixed-art-generator.cpp
  src/artifact/fixed-art-generator.h
  src/avatar/avatar-changer.cpp
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-io/cmd-dump.cpp
  src/combat/shoot.cpp
  src/core/player-processor.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest.cpp
  src/effect/effect-feature.cpp
  src/flavor/named-item-describer.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/grid/grid.cpp
  src/hpmp/hp-mp-processor.cpp
  src/io/write-diary.cpp
  src/knowledge/knowledge-items.cpp
  src/load/item/item-loader-base.cpp
  src/load/old/load-v1-5-0.cpp
  src/load/player-info-loader.cpp
  src/main/scene-table-floor.cpp
  src/melee/melee-spell-util.cpp
  src/melee/melee-switcher.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster/monster-damage.cpp
  src/mspell/mspell-attack.cpp
  src/mutation/mutation-processor.cpp
  src/object-enchant/item-magic-applier.cpp
  src/player/player-damage.cpp
  src/save/save.cpp
  src/specific-object/bloody-moon.cpp
  src/spell-kind/spells-world.cpp
  src/store/cmd-store.cpp
  src/store/rumor.cpp
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/system/floor-type-definition.cpp
  src/system/floor-type-definition.h
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/util/sort.cpp
  src/view/display-player.cpp
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#4101 ang_sort_art_comp/swap() を廃止した
  src/knowledge/knowledge-items.cpp
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/util/sort.cpp
  src/util/sort.h
Labels: refactor, Priority:MIDDLE

#4110 projection_path とprojection_path_type のpair<int, int> をPos2D に変えた
  src/combat/shoot.cpp
  src/effect/effect-processor.cpp
  src/io/cursor.cpp
  src/mind/mind-ninja.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-judgement.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell/range-calc.cpp
  src/spell/range-calc.h
  src/target/projection-path-calculator.cpp
  src/target/projection-path-calculator.h
  src/util/point-2d.h
Labels: refactor, Priority:MIDDLE

#4108 [Fix] ArtifactDefinitionsのフレーバーが省略されているときエラーになる
  src/info-reader/artifact-reader.cpp
Labels: bug

#4117 [Fix/Refactor] アイテムを投げた時にクラッシュ
  src/target/projection-path-calculator.cpp
  src/util/point-2d.h
Labels: bug, refactor

#4105 [Feature] デバッグコマンドの固定アーティファクト生成で一覧をソート
  src/system/artifact-type-definition.cpp
  src/wizard/wizard-special-process.cpp
Labels: enhancement

#4116 壁抜けモンスターに騎乗すると無条件で壁抜けできる不具合を解消した
  src/player/player-status-flags.cpp
Labels: bug, Priority:MIDDLE

#4052 [Feature] MonraceDefinitionsの射撃定義を打撃定義から独立
  lib/edit/MonraceDefinitions.jsonc
  schema/MonraceDefinitions.schema.json
  src/info-reader/race-info-tokens-table.cpp
  src/info-reader/race-reader.cpp
  src/lore/combat-types-setter.cpp
  src/melee/melee-switcher.cpp
  src/melee/monster-attack-monster.cpp
  src/monster-attack/monster-attack-describer.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-attack/monster-attack-table.h
  src/mspell/mspell-damage-calculator.cpp
  src/object/warning.cpp
  src/system/monster-race-info.h
  src/view/display-lore-attacks.cpp
  src/view/display-lore.cpp
Labels: bug, enhancement

#4107 artifacts_info をArtifactList に繰り込んだ
  src/artifact/fixed-art-generator.cpp
  src/artifact/random-art-generator.cpp
  src/combat/shoot.cpp
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/flavor/named-item-describer.cpp
  src/floor/fixed-map-generator.cpp
  src/info-reader/artifact-reader.cpp
  src/info-reader/general-parser.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-quests.cpp
  src/load/old/item-loader-savefile50.cpp
  src/load/old/load-v1-5-0.cpp
  src/load/quest-loader.cpp
  src/main/info-initializer.cpp
  src/monster-floor/special-death-switcher.cpp
  src/save/item-writer.cpp
  src/save/save.cpp
  src/spell/spells-object.cpp
  src/store/rumor.cpp
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/wizard/fixed-artifacts-spoiler.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#4115 MonsterRaceInfo::d_attr/d_char をColoredChar に差し替えた
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-io/cmd-lore.cpp
  src/cmd-item/cmd-eat.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/visuals-reseter.cpp
  src/info-reader/race-reader.cpp
  src/io-dump/dump-util.cpp
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-monsters.cpp
  src/market/building-monster.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mind/monk-attack.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/special-death-switcher.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster/monster-pain-describer.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-special.cpp
  src/mspell/summon-checker.cpp
  src/object-hook/hook-expendable.cpp
  src/player-attack/player-attack.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-genocide.cpp
  src/store/service-checker.cpp
  src/system/item-entity.cpp
  src/system/monster-entity.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/term/z-term.cpp
  src/term/z-term.h
  src/view/colored-char.h
  src/view/display-lore.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-util.cpp
  src/wizard/monster-info-spoiler.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#4123 [Fix] 毒地形のダメージを酸耐性で軽減している
  src/hpmp/hp-mp-processor.cpp
Labels: bug

#4119 MonsterRaceInfo::x_attr/x_char をColoredChar に差し替えた
  src/cmd-visual/cmd-visuals.cpp
  src/core/visuals-reseter.cpp
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-monsters.cpp
  src/perception/identification.cpp
  src/system/item-entity.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/view/display-lore.cpp
  src/view/display-map.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-left-frame.cpp
  src/window/main-window-util.cpp
Labels: refactor, Priority:MIDDLE

#4118 [Refactor] 誰得の巻物のアイテム生成処理
  src/artifact/fixed-art-types.h
  src/spell/spells-object.cpp
Labels: refactor

#4124 [Feature] BaseitemDefinitionsのJSON化
  Makefile.am
  lib/edit/BaseitemDefinitions.jsonc
  lib/edit/BaseitemDefinitions.txt
  lib/edit/Makefile.am
  schema/BaseitemDefinitions.schema.json
  src/info-reader/artifact-reader.cpp
  src/info-reader/baseitem-reader.cpp
  src/info-reader/baseitem-reader.h
  src/main/info-initializer.cpp
Labels: enhancement

#4131 [Fix] BaseitemDefinitions.jsoncのキーがおかしい
  lib/edit/BaseitemDefinitions.jsonc
Labels: bug

#4126 [Refactor] MonsterPainDescriber を MonsterEntity の関連クラスにした
  src/combat/shoot.cpp
  src/effect/effect-monster.cpp
  src/monster/monster-pain-describer.cpp
  src/monster/monster-pain-describer.h
  src/object-use/throw-execution.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
Labels: refactor

#4125 map_info() の引数を表すクラスを作って差し替えた
  src/cmd-visual/cmd-visuals.cpp
  src/grid/grid.cpp
  src/io-dump/dump-util.cpp
  src/io/cursor.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/perception/identification.cpp
  src/term/z-term.cpp
  src/term/z-term.h
  src/view/colored-char.h
  src/view/display-inventory.cpp
  src/view/display-map.cpp
  src/view/display-map.h
  src/view/display-store.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-equipments.cpp
  src/window/main-window-util.cpp
Labels: refactor, Priority:MIDDLE

#4134 [Refactor] マップの単色化処理
  src/grid/grid.cpp
  src/io/cursor.cpp
  src/view/display-map.cpp
  src/view/display-map.h
  src/window/display-sub-windows.cpp
  src/window/main-window-util.cpp
Labels: refactor

#4135 モンスター種族のソート関数をMonraceList::order() に繰り込んだ
  src/cmd-io/cmd-lore.cpp
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-uniques.cpp
  src/market/building-monster.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/util/sort.cpp
  src/util/sort.h
  src/wizard/monster-info-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#4137 FloorType にペットのソートメソッドを実装した
  src/action/activation-execution.cpp
  src/cmd-action/cmd-pet.cpp
  src/effect/effect-monster-charm.cpp
  src/floor/floor-leaver.cpp
  src/monster/monster-processor.cpp
  src/save/monster-writer.cpp
  src/system/floor-type-definition.cpp
  src/system/floor-type-definition.h
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/util/sort.cpp
  src/util/sort.h
Labels: refactor, Priority:MIDDLE

#4143 [Fix] 魔法の笛とモンスター・ボールが発動できない
  lib/edit/BaseitemDefinitions.jsonc
  schema/ArtifactDefinitions.schema.json
  schema/BaseitemDefinitions.schema.json
  src/action/activation-execution.cpp
  src/artifact/random-art-effects.h
  src/object-activation/activation-others.cpp
  src/object-activation/activation-others.h
  src/object-activation/activation-switcher.cpp
  src/object-enchant/activation-info-table.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/item-entity.cpp
Labels: bug, refactor

#4149 [Refactor] jsonのパース処理を行う関数を独立したファイルへ分離
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/info-reader/artifact-reader.cpp
  src/info-reader/baseitem-reader.cpp
  src/info-reader/info-reader-util.cpp
  src/info-reader/info-reader-util.h
  src/info-reader/json-reader-util.cpp
  src/info-reader/json-reader-util.h
  src/info-reader/race-reader.cpp
Labels: bug, refactor

#4142 MonraceList::sort_level() を実装し、ang_sort_comp_monster_level() とang_sort_swap_hook() を廃止した
  src/knowledge/knowledge-monsters.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/util/sort.cpp
  src/util/sort.h
Labels: refactor, Priority:MIDDLE

#4150 QuestType/QuestList の整形作業 その1
  src/birth/game-play-initializer.cpp
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/load/quest-loader.cpp
Labels: refactor, Priority:MIDDLE

#4151 QuestType/QuestList の整形作業 その2
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-move.cpp
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest-completion-checker.cpp
  src/dungeon/quest-monster-placer.cpp
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/effect/effect-monster-charm.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-events.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-util.cpp
  src/floor/object-allocator.cpp
  src/floor/wild.cpp
  src/info-reader/fixed-map-parser.cpp
  src/info-reader/general-parser.cpp
  src/io-dump/character-dump.cpp
  src/io/write-diary.cpp
  src/io/write-diary.h
  src/knowledge/knowledge-quests.cpp
  src/knowledge/knowledge-quests.h
  src/load/dungeon-loader.cpp
  src/load/load.cpp
  src/load/quest-loader.cpp
  src/main-win/main-win-music.cpp
  src/market/building-quest.cpp
  src/monster-floor/one-monster-placer.cpp
  src/object-hook/hook-quest.cpp
  src/player/player-move.cpp
  src/save/save.cpp
  src/spell-kind/spells-world.cpp
  src/system/floor-type-definition.cpp
  src/target/target-describer.cpp
  src/util/sort.cpp
  src/view/display-player.cpp
  src/wizard/wizard-game-modifier.cpp
  src/world/world-movement-processor.cpp
Labels: refactor, Priority:MIDDLE

#4152 ang_sort_comp_quest_num() / ang_sort_swap_quest_num() を廃止した
  src/dungeon/quest.cpp
  src/dungeon/quest.h
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-quests.cpp
  src/system/floor-type-definition.cpp
  src/system/monster-race-info.cpp
  src/util/sort.cpp
  src/util/sort.h
Labels: refactor, Priority:MIDDLE

#4153 grid_template_type のソートをSTLのソートに変えた
  src/action/activation-execution.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/knowledge-quests.cpp
  src/knowledge/knowledge-uniques.cpp
  src/load/floor-loader.cpp
  src/market/building-monster.cpp
  src/save/floor-writer.cpp
  src/save/info-writer.cpp
  src/save/item-writer.cpp
  src/save/item-writer.h
  src/save/monster-writer.cpp
  src/save/monster-writer.h
  src/save/save.cpp
  src/util/sort.cpp
  src/util/sort.h
  src/window/display-sub-windows.cpp
Labels: refactor, Priority:MIDDLE

#4156 nest_mon_info_type のソート関数の自身のオブジェクトメソッドに繰り込んだ
  src/room/pit-nest-util.h
  src/room/rooms-nest.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
Labels: refactor, Priority:MIDDLE

#4160 デバッグセーブに関するグローバル変数と、古いデバッグセーブを削除するルーチンを除去した
  src/io/files-util.cpp
  src/io/files-util.h
  src/main-win.cpp
  src/main/angband-initializer.cpp
Labels: refactor, Priority:MIDDLE

#4157 ang_sort_comp_distance() / ang_sort_comp_importance() / ang_sort_swap_position() を廃止する準備
  src/target/grid-selector.cpp
  src/target/target-preparation.cpp
  src/util/sort.cpp
  src/util/sort.h
Labels: refactor, Priority:MIDDLE

#4161 savefile_base をstring からpath に変えた
  src/cmd-io/cmd-diary.cpp
  src/io/files-util.cpp
  src/io/files-util.h
  src/io/write-diary.cpp
  src/player/process-name.cpp
Labels: refactor, Priority:MIDDLE

#4162 [Refactor] ターゲットのソートにSTLを使用する
  src/target/grid-selector.cpp
  src/target/target-preparation.cpp
  src/target/target-sorter.cpp
  src/target/target-sorter.h
Labels: refactor

#4163 ColoredChar をDisplaySymbol に差し替えた
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-io/cmd-lore.cpp
  src/cmd-item/cmd-eat.cpp
  src/cmd-visual/cmd-visuals.cpp
  src/core/visuals-reseter.cpp
  src/grid/grid.cpp
  src/info-reader/baseitem-reader.cpp
  src/info-reader/feature-reader.cpp
  src/info-reader/race-reader.cpp
  src/io-dump/dump-util.cpp
  src/io-dump/dump-util.h
  src/io/cursor.cpp
  src/io/interpret-pref-file.cpp
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/market/building-monster.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mind/monk-attack.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/special-death-switcher.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster/monster-pain-describer.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-special.cpp
  src/mspell/summon-checker.cpp
  src/object-hook/hook-expendable.cpp
  src/perception/identification.cpp
  src/player-attack/player-attack.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-genocide.cpp
  src/store/service-checker.cpp
  src/system/baseitem-info.cpp
  src/system/baseitem-info.h
  src/system/grid-type-definition.cpp
  src/system/item-entity.cpp
  src/system/monster-entity.cpp
  src/system/monster-race-info.cpp
  src/system/monster-race-info.h
  src/system/terrain-type-definition.cpp
  src/system/terrain-type-definition.h
  src/term/z-term.cpp
  src/term/z-term.h
  src/view/colored-char.h
  src/view/display-lore.cpp
  src/view/display-map.cpp
  src/view/display-map.h
  src/window/display-sub-windows.cpp
  src/window/main-window-left-frame.cpp
  src/window/main-window-util.cpp
  src/window/main-window-util.h
  src/wizard/monster-info-spoiler.cpp
  src/wizard/wizard-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#4167 ItemEntity::get_symbol() の戻り値をDisplaySymbol に変え、色と文字を取得するメソッドはprivate に変えた
  src/birth/birth-wizard.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/combat/shoot.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/object-use/throw-execution.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/term/gameterm.cpp
  src/term/gameterm.h
  src/term/screen-processor.cpp
  src/term/z-term.cpp
  src/term/z-term.h
  src/view/display-inventory.cpp
  src/view/display-map.cpp
  src/view/display-player-stat-info.cpp
  src/view/display-player.cpp
  src/view/display-store.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-equipments.cpp
  src/wizard/wizard-item-modifier.cpp
Labels: refactor, Priority:MIDDLE

#4168 [Refactor] #4166 colored-char.h をクラス名に合わせてdisplay-symbol.h に変えた
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/birth-wizard.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/grid/grid.cpp
  src/system/baseitem-info.h
  src/system/monster-race-info.h
  src/system/terrain-type-definition.h
  src/term/gameterm.cpp
  src/term/screen-processor.cpp
  src/term/z-term.cpp
  src/view/display-lore.cpp
  src/view/display-map.cpp
  src/view/display-map.h
  src/view/display-symbol.h
  src/window/main-window-util.cpp
Labels: refactor, Priority:MIDDLE

#4172 TimedEffects クラスのフィールド変数をshared_ptr から普通のクラスに変えた その2
  src/action/action-limited.cpp
  src/action/movement-execution.cpp
  src/action/racial-execution.cpp
  src/blue-magic/blue-magic-checker.cpp
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-attack.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-action/cmd-mind.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-building/cmd-inn.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/core/magic-effects-timeout-reducer.cpp
  src/core/player-processor.cpp
  src/effect/effect-player-oldies.cpp
  src/floor/pattern-walk.cpp
  src/grid/trap.cpp
  src/hpmp/hp-mp-processor.cpp
  src/load/player-info-loader.cpp
  src/mind/mind-blue-mage.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-ninja.cpp
  src/mind/mind-power-getter.cpp
  src/mind/mind-power-getter.h
  src/mind/mind-samurai.cpp
  src/mind/monk-attack.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-attack/monster-attack-status.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/monster-attack/monster-eating.cpp
  src/mutation/mutation-processor.cpp
  src/object-activation/activation-switcher.cpp
  src/object-use/item-use-checker.cpp
  src/object-use/quaff/quaff-effects.cpp
  src/player-info/self-info.cpp
  src/player-status/player-speed.cpp
  src/player/digestion-processor.cpp
  src/player/player-damage.cpp
  src/player/player-status.cpp
  src/racial/racial-switcher.cpp
  src/realm/realm-song.cpp
  src/save/player-writer.cpp
  src/spell/spell-info.cpp
  src/spell/spells-status.cpp
  src/status/bad-status-setter.cpp
  src/status/buff-setter.cpp
  src/system/player-type-definition.cpp
  src/timed-effect/player-acceleration.h
  src/timed-effect/player-deceleration.h
  src/timed-effect/player-paralysis.h
  src/timed-effect/player-poison.h
  src/timed-effect/player-stun.h
  src/timed-effect/timed-effects.cpp
  src/timed-effect/timed-effects.h
  src/view/display-player-middle.cpp
  src/window/display-sub-windows.cpp
  src/window/main-window-stat-poster.cpp
Labels: refactor, Priority:MIDDLE

#4175 [Fix] モンスターが使用する一部の魔法にプレイヤーの耐性の学習が反映されていない
  src/mspell/high-resistance-checker.cpp
  src/mspell/mspell-attack/mspell-bolt.cpp
Labels: bug

#4176 display_group_list() の引数をconcptr[] からvector<string> に変えた
  Hengband/Hengband/Hengband.vcxproj
  Hengband/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/io-dump/dump-util.cpp
  src/io-dump/dump-util.h
  src/knowledge/item-group-table.cpp
  src/knowledge/item-group-table.h
  src/knowledge/knowledge-features.cpp
  src/knowledge/knowledge-items.cpp
  src/knowledge/knowledge-monsters.cpp
  src/knowledge/monster-group-table.cpp
  src/knowledge/monster-group-table.h
  src/knowledge/object-group-table.h
Labels: refactor, Priority:MIDDLE

#4179 [Fix] ターゲット比較関数がSTLのソート用比較関数の要件を満たしていない
  src/target/target-sorter.cpp
Labels: bug

#4182 [Fix] 呪術魔法の我慢が正常に機能していない
  src/monster-attack/monster-attack-player.cpp
  src/monster-attack/monster-attack-player.h
  src/spell-realm/spells-hex.cpp
  src/spell-realm/spells-hex.h
Labels: bug, refactor

#4178 random_art_bias_type をenum からenum class に変えた
  src/artifact/random-art-activation.cpp
  src/artifact/random-art-bias-types.h
  src/artifact/random-art-characteristics.cpp
  src/artifact/random-art-generator.cpp
  src/artifact/random-art-misc.cpp
  src/artifact/random-art-pval-investor.cpp
  src/artifact/random-art-resistance.cpp
  src/artifact/random-art-slay.cpp
  src/knowledge/monster-group-table.cpp
  src/knowledge/monster-group-table.h
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/wizard/artifact-bias-table.cpp
  src/wizard/artifact-bias-table.h
Labels: refactor, Priority:MIDDLE
