Repository hengband/hengband, pull requests merged in 2025-03, with the labels that each got.

#5056 cave_los_bold() をFloorType::has_los_terrrain_at() に繰り込んだ
  src/effect/effect-processor.cpp
  src/floor/cave.cpp
  src/floor/cave.h
  src/floor/line-of-sight.cpp
  src/monster-floor/monster-lite.cpp
  src/mspell/mspell-attack-util.cpp
  src/mspell/mspell-attack-util.h
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-lite.cpp
  src/mspell/mspell-lite.h
  src/specific-object/torch.cpp
  src/spell-kind/spells-lite.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/target/projection-path-calculator.cpp
Labels: refactor, Priority:MIDDLE

#5059 cave_temp_room_aux() 周辺のラップアップ
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  lib/edit/TerrainDefinitions.txt
  src/Makefile.am
  src/action/movement-execution.cpp
  src/combat/shoot.cpp
  src/effect/effect-processor.cpp
  src/info-reader/feature-info-tokens-table.cpp
  src/io/cursor.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-lite.cpp
  src/mspell/mspell-floor.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-lite.cpp
  src/mspell/mspell-lite.h
  src/object-activation/activation-bolt-ball.cpp
  src/object-use/throw-execution.cpp
  src/player-attack/player-attack.cpp
  src/player/player-move.cpp
  src/realm/realm-hissatsu.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-lite.h
  src/spell-kind/spells-neighbor.cpp
  src/spell-realm/spells-chaos.cpp
  src/spell-realm/spells-crusade.cpp
  src/system/enums/terrain/path-checker.h
  src/system/enums/terrain/terrain-characteristics.h
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/target/projection-path-calculator.cpp
  src/view/display-map.cpp
Labels: refactor, Priority:MIDDLE

#5058 [Refactor] delete_items()
  src/floor/floor-object.cpp
Labels: refactor

#5060 [Fix] デバッグコマンドで元素使いに職業を変更して魔法を使用するとクラッシュする
  src/birth/quick-start.cpp
  src/mind/mind-elementalist.h
  src/system/player-type-definition.h
  src/wizard/wizard-special-process.cpp
Labels: bug

#5064 ProjectionPath のコンストラクタとget_project_point() の引数からPlayerType を除去した
  src/combat/shoot.cpp
  src/effect/effect-processor.cpp
  src/io/cursor.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mind/mind-ninja.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-judgement.h
  src/mspell/mspell-lite.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-fetcher.cpp
  src/target/projection-path-calculator.cpp
  src/target/projection-path-calculator.h
Labels: refactor, Priority:MIDDLE

#5067 PlayerType::element の型をElementRealmTypeにし、element_realmに改名する
  src/birth/birth-select-realm.cpp
  src/birth/character-builder.cpp
  src/birth/quick-start.cpp
  src/io/report.cpp
  src/load/player-info-loader.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-elementalist.h
  src/racial/racial-draconian.cpp
  src/save/player-writer.cpp
  src/system/player-type-definition.h
  src/view/display-player.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor

#5072 [Fix] 烈風弾が1マス分しかモンスターを吹き飛ばさない
  src/combat/shoot.cpp
Labels: bug

#5074 ccache用キャッシュ生成ワークフロー実行エラーの対策
  .github/workflows/pull-request-status-check.yml
  configure.ac
Labels: enhancement

#5079 地震で埋まるとクラッシュする不具合を解消した
  src/spell-kind/earthquake.cpp
Labels: bug, Priority:HIGH

#5080 [Fix] モンスターの逃走処理
  src/monster-floor/monster-sweep-grid.cpp
Labels: bug

#5075 Beta27に向けたその他のリファクタリング
  src/autopick/autopick-describer.cpp
  src/effect/effect-feature.cpp
  src/external-lib/include/fmt/base.h
  src/external-lib/include/fmt/format.h
  src/external-lib/include/range/v3/utility/optional.hpp
  src/monster-floor/monster-death.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-grid.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/target/projection-path-calculator.cpp
  src/util/angband-files.cpp
Labels: refactor, Priority:MIDDLE

#5081 fis_type とitem_selection をクラス化した
  src/inventory/floor-item-getter.cpp
  src/inventory/item-getter.cpp
  src/inventory/item-selection-util.cpp
  src/inventory/item-selection-util.h
Labels: refactor, Priority:MIDDLE

#5086 [Fix] easy_floorが「いいえ」でアイテムを拾うとクラッシュ
  src/autopick/autopick.cpp
  src/inventory/player-inventory.cpp
  src/inventory/player-inventory.h
  src/monster-floor/monster-object.cpp
Labels: bug

#5087 [Refactor] record_o_name
  src/cmd-io/cmd-diary.cpp
  src/core/game-play.cpp
  src/game-option/play-record-options.cpp
  src/game-option/play-record-options.h
  src/inventory/player-inventory.cpp
  src/spell-kind/spells-perception.cpp
  src/store/purchase-order.cpp
Labels: refactor

#5090 player-inventory.cpp のリファクタリング その2
  src/inventory/player-inventory.cpp
Labels: refactor

#5091 player-inventory.cpp のリファクタリング その2
  src/inventory/player-inventory.cpp
Labels: refactor
