Repository hengband/hengband, pull requests merged in 2025-05, with the labels that each got.

#5099 [Fix] 薬を投げた時にクラッシュする
  src/cmd-item/cmd-throw.cpp
  src/object-use/throw-execution.cpp
  src/object-use/throw-execution.h
Labels: bug

#5101 Fixing scrolls of door/stair location and treasure detection
  src/object-use/read/scroll-read-executor.cpp
Labels: refactor

#5103 [Release] 3.0.1.27-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#5106 Update hengband.spec version for 3.0.1.27
  configure.ac
  hengband.spec
Labels: release

#5111 [Fix] キャラクタダンプの二重角括弧閉じ忘れ
  src/io-dump/character-dump.cpp
Labels: bug

#5110 [Refactor] display_rumor()
  src/store/rumor.cpp
  src/util/string-processor.cpp
  src/util/string-processor.h
Labels: refactor
