Repository hengband/hengband, pull requests merged in 2025-02, with the labels that each got.

#4902 in_bounds() の周辺コードを整備した その2
  src/effect/effect-feature.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-changer.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/mind/mind-elementalist.cpp
  src/mind/mind-ninja.cpp
  src/monster/monster-list.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-lite.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
Labels: refactor, Priority:MIDDLE

#4907 [Fix] 影移動の魔法が特定の位置関係で失敗する
  src/realm/realm-hex.cpp
Labels: bug

#4904 [Refactor] モンスターの移動先決定処理
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-safety-hiding.h
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
Labels: refactor

#4913 [Fix] ターゲット選択時の挙動がおかしい
  src/target/target-setter.cpp
Labels: bug

#4909 wt_type をenum class に変えた
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/floor/wild.cpp
  src/floor/wild.h
  src/monster/monster-util.cpp
  src/system/enums/terrain/wilderness-terrain.h
Labels: refactor, Priority:MIDDLE

#4916 in_bounds() の周辺コードを整備した その3
  src/floor/fixed-map-generator.cpp
  src/floor/floor-streams.cpp
  src/floor/object-scanner.cpp
  src/floor/object-scanner.h
  src/grid/door.cpp
  src/grid/grid.h
  src/monster-floor/monster-remover.cpp
  src/monster-floor/monster-remover.h
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-teleport.cpp
Labels: refactor, Priority:MIDDLE

#4910 AngbandSystem/FloorType へPlayerType に属していたフィールド変数を移した
  src/birth/game-play-initializer.cpp
  src/cmd-action/cmd-move.cpp
  src/core/game-closer.cpp
  src/core/game-play.cpp
  src/dungeon/dungeon-processor.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/wild.cpp
  src/io/exit-panic.cpp
  src/io/signal-handlers.cpp
  src/load/load.cpp
  src/load/world-loader.cpp
  src/main-win.cpp
  src/save/player-writer.cpp
  src/save/save.cpp
  src/system/angband-system.cpp
  src/system/angband-system.h
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/player-type-definition.h
  src/world/world-movement-processor.cpp
Labels: refactor, Priority:MIDDLE

#4917 display-monster-status.cpp/h を廃止した
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/knowledge/knowledge-monsters.cpp
  src/system/monster-entity.cpp
  src/system/monster-entity.h
  src/target/target-describer.cpp
  src/view/display-monster-status.cpp
  src/view/display-monster-status.h
Labels: refactor, Priority:MIDDLE

#4915 wild.cpp/h の構造体と関数の整理
  src/floor/fixed-map-generator.cpp
  src/floor/wild.cpp
  src/floor/wild.h
  src/main/info-initializer.cpp
Labels: refactor, Priority:MIDDLE

#4919 polymorph_of_chameleon() の引数で出ていた警告を除去した
  src/monster/monster-list.cpp
Labels: refactor, Priority:MIDDLE

#4912 std::span のコンストラクタ呼び出しに関する調整
  .github/workflows/build-with-autotools.yml
  .github/workflows/create-cache-for-ccache.yml
  .github/workflows/pull-request-status-check.yml
  src/info-reader/dungeon-reader.cpp
  src/mind/mind-chaos-warrior.cpp
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/player-base/player-class.cpp
  src/system/baseitem/baseitem-list.cpp
  src/system/baseitem/baseitem-list.h
  src/term/gameterm.cpp
  src/term/z-form.cpp
  src/util/abstract-map-wrapper.h
  src/util/abstract-vector-wrapper.h
  src/util/sha256.cpp
  src/view/display-map.cpp
Labels: enhancement, refactor

#4921 [Fix] 十字型の部屋の内部の小部屋の下側の壁がない
  src/room/rooms-normal.cpp
Labels: bug

#4918 in_bounds() が呼ばれている箇所の周辺コードを整備した その4
  src/floor/tunnel-generator.cpp
  src/floor/tunnel-generator.h
  src/grid/trap.cpp
  src/room/vault-builder.cpp
Labels: refactor, Priority:MIDDLE

#4923 [Refactor] 方向ベクトルとそれを使用する処理
  src/action/open-util.cpp
  src/action/travel-execution.cpp
  src/cmd-action/cmd-travel.cpp
  src/effect/effect-feature.cpp
  src/floor/floor-events.cpp
  src/floor/geometry.h
  src/floor/tunnel-generator.cpp
  src/grid/feature-generator.cpp
  src/grid/grid.cpp
  src/mind/mind-warrior.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster/monster-list.cpp
  src/mutation/mutation-processor.cpp
  src/pet/pet-fall-off.cpp
  src/player-attack/player-attack.cpp
  src/player/player-move.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-hissatsu.cpp
  src/room/cave-filler.cpp
  src/room/rooms-builder.cpp
  src/room/rooms-special.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-realm/spells-chaos.cpp
  src/system/floor/floor-info.cpp
  src/target/target-getter.cpp
Labels: refactor

#4933 [Fix] RF5_HOLDがモンスターを麻痺ではなく朦朧とさせる
  src/mspell/mspell-status.cpp
Labels: bug

#4935 [Feature] カオス耐性による混乱防御の仕様変更
  src/effect/effect-monster.cpp
  src/effect/effect-player-resist-hurt.cpp
Labels: enhancement

#4937 [Refactor] ddx / ddy / CCW_DD を廃止し、Directionクラスで置き換える
  src/action/movement-execution.cpp
  src/action/run-execution.cpp
  src/cmd-action/cmd-travel.cpp
  src/cmd-io/cmd-floor.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/combat/shoot.cpp
  src/floor/floor-streams.cpp
  src/floor/geometry.h
  src/grid/grid.cpp
  src/io-dump/dump-util.cpp
  src/mind/mind-berserker.cpp
  src/mind/mind-force-trainer.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-move.cpp
  src/object-use/throw-execution.cpp
  src/realm/realm-hissatsu.cpp
  src/specific-object/death-crimson.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-launcher.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-realm/spells-crusade.cpp
  src/system/player-type-definition.cpp
  src/target/grid-selector.cpp
  src/target/target-getter.cpp
  src/target/target-setter.cpp
  src/view/display-map.cpp
  src/window/main-window-util.cpp
Labels: refactor

#4938 [Refactor] モンスターの逃亡処理
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-safety-hiding.h
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
Labels: refactor

#4944 [Fix] 固定アーティファクトのデバッグ生成の名前表示
  src/wizard/wizard-special-process.cpp
Labels: bug

#4947 [Feature] Rectangle2Dにイテレータを実装
  src/room/rooms-city.cpp
  src/room/rooms-nest.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-vault.cpp
  src/room/treasure-deployment.cpp
  src/util/point-2d.h
Labels: enhancement, refactor

#4941 [Refactor] MonraceAllocationTable::initialize()
  src/system/monrace/monrace-allocation.cpp
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
Labels: refactor

#4940 [Refactor] 幻覚時のランダム表示されるモンスター名の処理
  src/monster/monster-describer.cpp
  src/monster/monster-status.cpp
Labels: refactor

#4946 [Fix] デバッグコマンドのモンスター生成で^Iが効かないことがある
  src/wizard/wizard-spells.cpp
Labels: bug

#4939 WildernessGrid/Grids クラスを作っていくつかの処理を繰り込んだ
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/action/movement-execution.cpp
  src/birth/character-builder.cpp
  src/cmd-action/cmd-move.cpp
  src/core/game-play.cpp
  src/core/player-processor.cpp
  src/floor/cave-generator.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/wild.cpp
  src/floor/wild.h
  src/knowledge/knowledge-self.cpp
  src/load/world-loader.cpp
  src/main/info-initializer.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-summon.cpp
  src/monster/monster-list.cpp
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/save/save.cpp
  src/spell-kind/spells-world.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/floor/wilderness-grid.cpp
  src/system/floor/wilderness-grid.h
  src/system/player-type-definition.h
  src/wizard/wizard-special-process.cpp
  src/world/world-movement-processor.cpp
  src/world/world.h
Labels: refactor, Priority:MIDDLE

#4950 WildernessGrids::bottom_right/positions を廃止してRect2D に差し替えた
  src/core/game-play.cpp
  src/external-lib/include/fmt/format.h
  src/floor/wild.cpp
  src/knowledge/knowledge-self.cpp
  src/load/world-loader.cpp
  src/save/save.cpp
  src/spell-kind/spells-world.cpp
  src/system/floor/wilderness-grid.cpp
  src/system/floor/wilderness-grid.h
Labels: refactor, Priority:MIDDLE

#4954 MonsterEntity *m_ptr を MonsterEntity &monster にする準備
  src/avatar/avatar-changer.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-building/cmd-inn.cpp
  src/combat/shoot.cpp
  src/core/object-compressor.cpp
  src/core/player-processor.cpp
  src/effect/effect-player-oldies.cpp
  src/floor/floor-changer.cpp
  src/grid/trap.cpp
  src/knowledge/knowledge-monsters.cpp
  src/load/old/monster-loader-savefile50.cpp
  src/load/old/monster-loader-savefile50.h
  src/melee/melee-postprocess.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-info.cpp
  src/monster/monster-info.h
  src/monster/monster-processor.cpp
  src/monster/monster-util.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-special.cpp
  src/mutation/mutation-processor.cpp
  src/object-use/quaff/quaff-effects.cpp
  src/object-use/throw-execution.cpp
  src/player-status/player-speed.cpp
  src/player/eldritch-horror.cpp
  src/player/eldritch-horror.h
  src/player/player-move.cpp
  src/room/pit-nest-util.cpp
  src/window/display-sub-windows.cpp
  src/world/world-turn-processor.cpp
Labels: refactor

#4952 DungeonFeeling クラスを作ってPlayerType の雰囲気関連フィールド変数を移した
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/cmd-io/cmd-dump.cpp
  src/cmd-io/feeling-table.h
  src/core/turn-compensator.cpp
  src/floor/dungeon-feeling.cpp
  src/floor/dungeon-feeling.h
  src/floor/floor-changer.cpp
  src/floor/floor-events.cpp
  src/load/floor-loader.cpp
  src/load/load-zangband.cpp
  src/load/world-loader.cpp
  src/main/scene-table-floor.cpp
  src/save/floor-writer.cpp
  src/save/player-writer.cpp
  src/system/player-type-definition.h
  src/window/main-window-left-frame.cpp
Labels: refactor, Priority:MIDDLE

#4955 [Feature] 例外メッセージにアイテムの詳細情報付与
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: enhancement

#4959 [Fix] X11版: 基本ウェイト量が0でもスリープしてしまう
  src/main-x11.cpp
Labels: bug

#4958 [Chore] プリコンパイルヘッダの調整
  src/Makefile.am
  src/autopick/autopick-entry.h
  src/main-win/main-win-cfg-reader.h
  src/stdafx.h
  src/wizard/monster-info-spoiler.cpp
Labels: enhancement

#4960 Remember wilderness starting position; use it in initialize_position()
  src/birth/game-play-initializer.cpp
  src/floor/wild.cpp
  src/system/floor/wilderness-grid.cpp
  src/system/floor/wilderness-grid.h
  src/wizard/wizard-special-process.cpp
Labels: bug, Priority:Critical

#4963 Directionクラスの機能追加とリファクタリング
  src/action/run-execution.cpp
  src/action/run-execution.h
  src/cmd-action/cmd-move.cpp
  src/core/player-processor.cpp
  src/floor/floor-streams.cpp
  src/floor/geometry.h
  src/realm/realm-hissatsu.cpp
  src/target/target-getter.cpp
  src/target/target-getter.h
Labels: enhancement, refactor

#4967 [Refactor] 青魔法の処理をまとめる
  src/blue-magic/blue-magic-ball-bolt.cpp
  src/blue-magic/blue-magic-ball-bolt.h
  src/blue-magic/blue-magic-breath.cpp
  src/blue-magic/blue-magic-breath.h
  src/blue-magic/blue-magic-caster.cpp
  src/blue-magic/blue-magic-spirit-curse.cpp
  src/blue-magic/blue-magic-spirit-curse.h
  src/blue-magic/blue-magic-status.cpp
  src/blue-magic/blue-magic-util.cpp
  src/blue-magic/blue-magic-util.h
Labels: refactor

#4969 荒野周りにおけるグローバル変数からフィールド変数への繰り込みとモデル化 その6
  src/cmd-building/cmd-building.cpp
  src/dungeon/dungeon-processor.cpp
  src/floor/floor-leaver.cpp
  src/floor/wild.cpp
  src/floor/wild.h
  src/main-win.cpp
  src/main/info-initializer.cpp
  src/market/building-quest.cpp
  src/system/floor/wilderness-grid.cpp
  src/system/floor/wilderness-grid.h
Labels: refactor, Priority:MIDDLE

#4964 [Refactor] command_dirの型をDirectionにする
  src/action/open-util.cpp
  src/action/open-util.h
  src/cmd-action/cmd-open-close.cpp
  src/dungeon/dungeon-processor.cpp
  src/io/input-key-requester.cpp
  src/io/input-key-requester.h
  src/mutation/mutation-processor.cpp
  src/racial/racial-switcher.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-hissatsu.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/target/target-getter.cpp
Labels: refactor

#4968 [Refactor] PlayerType::get_neighbor()にDirection型を取るオーバーロードを追加
  src/action/open-util.cpp
  src/action/run-execution.cpp
  src/action/travel-execution.cpp
  src/mind/mind-warrior.cpp
  src/pet/pet-fall-off.cpp
  src/player-attack/player-attack.cpp
  src/player/player-move.cpp
  src/realm/realm-hissatsu.cpp
  src/spell-kind/earthquake.cpp
  src/spell-realm/spells-chaos.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
Labels: refactor

#4970 [Refactor] get_direction()の戻り値をDirectionにする
  src/action/movement-execution.cpp
  src/action/movement-execution.h
  src/action/mutation-execution.cpp
  src/cmd-action/cmd-pet.cpp
  src/mind/mind-berserker.cpp
  src/mind/mind-warrior.cpp
  src/mutation/mutation-techniques.cpp
  src/racial/racial-vampire.cpp
  src/realm/realm-hissatsu.cpp
  src/specific-object/monster-ball.cpp
  src/spell-kind/spells-launcher.cpp
  src/spell-kind/spells-launcher.h
  src/spell-kind/spells-specific-bolt.cpp
  src/spell-kind/spells-specific-bolt.h
  src/spell/spells-status.cpp
  src/target/target-getter.cpp
  src/target/target-getter.h
Labels: refactor

#4974 フォーマット指定子がlong になっている箇所をintまたはfmt::format() に差し替えた
  src/cmd-item/cmd-item.cpp
  src/core/scores.cpp
  src/floor/floor-generator.cpp
  src/floor/wild.cpp
  src/io/report.cpp
  src/knowledge/knowledge-monsters.cpp
  src/monster/monster-list.cpp
  src/player-info/alignment.cpp
  src/player-info/alignment.h
  src/player/player-status.cpp
  src/player/player-status.h
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
Labels: refactor, Priority:MIDDLE

#4977 [Fix] トラベルコマンドで移動中のディレイをなくす
  src/action/travel-execution.cpp
Labels: bug

#4975 [Refactor] get_rep_dir() のシグネチャ変更
  src/action/movement-execution.cpp
  src/action/movement-execution.h
  src/action/open-close-execution.cpp
  src/action/open-close-execution.h
  src/action/run-execution.cpp
  src/action/travel-execution.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-action/cmd-others.cpp
  src/cmd-action/cmd-tunnel.cpp
  src/mind/mind-archer.cpp
  src/mind/monk-attack.cpp
  src/realm/realm-hissatsu.cpp
  src/target/target-getter.cpp
  src/target/target-getter.h
Labels: refactor

#4978 フォーマット指定子がlong になっている箇所をintまたはfmt::format() に差し替えた その2
  src/cmd-building/cmd-building.cpp
  src/market/building-recharger.cpp
  src/market/building-util.cpp
  src/market/building-util.h
  src/mind/mind-info.cpp
  src/monster-attack/monster-eating.cpp
  src/player/process-death.cpp
  src/store/purchase-order.cpp
  src/store/sell-order.cpp
  src/view/display-scores.cpp
  src/view/display-store.cpp
  src/view/display-store.h
Labels: refactor, Priority:MIDDLE

#4980 [Refactor] ものまねのターゲッティング処理
  src/cmd-action/cmd-mane.cpp
Labels: refactor

#4979 フォーマット指定子がlong になっている箇所をintまたはfmt::format() に差し替えた その3
  src/window/main-window-left-frame.cpp
  src/wizard/monster-info-spoiler.cpp
Labels: refactor, Priority:MIDDLE

#4961 リリースビルドの作成に影響のあるコンパイル警告を抑制した (MSVCのみ)
  VisualStudio/Hengband/Hengband.vcxproj
Labels: bug, refactor

#4981 WildernessGrid をカプセル化した
  src/cmd-action/cmd-move.cpp
  src/core/player-processor.cpp
  src/floor/floor-leaver.cpp
  src/floor/wild.cpp
  src/info-reader/dungeon-reader.cpp
  src/load/world-loader.cpp
  src/monster/monster-list.cpp
  src/save/save.cpp
  src/spell-kind/spells-world.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/floor/floor-info.cpp
  src/system/floor/wilderness-grid.cpp
  src/system/floor/wilderness-grid.h
Labels: refactor, Priority:MIDDLE

#4982 Directionクラスの機能追加と関連する修正
  src/action/movement-execution.cpp
  src/action/run-execution.cpp
  src/cmd-action/cmd-move.cpp
  src/floor/geometry.h
  src/io-dump/dump-util.cpp
  src/knowledge/knowledge-monsters.cpp
  src/target/target-getter.cpp
Labels: bug, enhancement

#4983 WildernessGrid クラスのラップアップ
  src/floor/wild.cpp
  src/system/floor/wilderness-grid.cpp
  src/system/floor/wilderness-grid.h
Labels: refactor, Priority:MIDDLE

#4985 [Refactor] get_aim_dir()にget_hack_dir()を統合
  src/mutation/mutation-processor.cpp
  src/target/target-getter.cpp
  src/target/target-getter.h
Labels: refactor

#4988 [Refactor] モンスターの移動方向の候補をDirection型にする
  src/monster-floor/monster-direction.cpp
  src/monster-floor/monster-direction.h
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-move.h
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-processor.cpp
Labels: refactor

#4987 [Refactor] get_keymap_dir()の戻り値をDirectionにする
  src/cmd-io/cmd-floor.cpp
  src/cmd-io/cmd-gameoption.cpp
  src/game-option/keymap-directory-getter.cpp
  src/game-option/keymap-directory-getter.h
  src/io-dump/dump-util.cpp
  src/mind/mind-force-trainer.cpp
  src/mind/mind-ninja.cpp
  src/target/grid-selector.cpp
  src/target/target-getter.cpp
  src/target/target-setter.cpp
Labels: refactor

#4989 travel_typeをTravelクラスにする その1
  src/action/travel-execution.cpp
  src/action/travel-execution.h
  src/cmd-action/cmd-travel.cpp
  src/core/disturbance.cpp
  src/core/player-processor.cpp
  src/floor/floor-changer.cpp
  src/spell-kind/spells-floor.cpp
  src/target/target-describer.cpp
Labels: refactor

#4995 [Fix] 青魔道士でキャラクタダンプ出力時にクラッシュ
  src/mspell/monster-power-table.cpp
Labels: bug

#4991 travel_flow() をstd::priority_queueを用いたダイクストラ法で書き直し、Travel::update_flow()へ移設
  src/action/travel-execution.cpp
  src/action/travel-execution.h
  src/cmd-action/cmd-travel.cpp
  src/player/player-move.cpp
  src/player/player-move.h
Labels: refactor

#4990 in_bounds() の周辺コードを整備した その5
  src/effect/effect-feature.cpp
  src/floor/cave-generator.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-streams.cpp
  src/floor/object-allocator.cpp
  src/grid/feature-generator.cpp
  src/grid/feature-generator.h
  src/grid/grid.cpp
  src/grid/object-placer.cpp
  src/grid/object-placer.h
  src/grid/trap.cpp
  src/grid/trap.h
  src/io-dump/character-dump.cpp
  src/player/player-move.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-special.cpp
  src/room/rooms-vault.cpp
  src/room/treasure-deployment.cpp
  src/room/vault-builder.cpp
  src/room/vault-builder.h
  src/spell-kind/spells-detection.cpp
Labels: refactor, Priority:MIDDLE

#4996 Travelクラスのメンバのさらなる隠蔽とシングルトン化
  src/action/run-execution.cpp
  src/action/run-execution.h
  src/action/travel-execution.cpp
  src/action/travel-execution.h
  src/cmd-action/cmd-travel.cpp
  src/core/disturbance.cpp
  src/core/player-processor.cpp
  src/floor/floor-changer.cpp
  src/spell-kind/spells-floor.cpp
  src/target/target-describer.cpp
Labels: refactor

#4998 [Refactor] MonsterSweepGrid::mmを削除
  src/monster-floor/monster-direction.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
Labels: refactor

#5001 [Feature] lookコマンドから直接トラベルする機能
  src/action/travel-execution.cpp
  src/action/travel-execution.h
  src/cmd-action/cmd-travel.cpp
  src/target/target-setter.cpp
Labels: enhancement

#5003 [Fix] トラベルコマンドが効かない
  src/cmd-action/cmd-travel.cpp
Labels: bug

#4999 in_bounds() メソッドをFloorType::contains() に繰り込んだ
  src/action/travel-execution.cpp
  src/effect/effect-player.cpp
  src/effect/effect-processor.cpp
  src/floor/cave.cpp
  src/floor/cave.h
  src/floor/floor-leaver.cpp
  src/floor/floor-object.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/floor/object-allocator.cpp
  src/floor/object-scanner.cpp
  src/floor/tunnel-generator.cpp
  src/grid/feature-generator.cpp
  src/grid/grid.cpp
  src/grid/object-placer.cpp
  src/grid/trap.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-remover.cpp
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-floor/special-death-switcher.cpp
  src/monster/monster-list.cpp
  src/mspell/mspell-checker.cpp
  src/object/warning.cpp
  src/room/cave-filler.cpp
  src/room/rooms-builder.cpp
  src/room/rooms-vault.cpp
  src/room/space-finder.cpp
  src/room/vault-builder.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-realm/spells-chaos.cpp
  src/spell-realm/spells-crusade.cpp
  src/spell/range-calc.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/target/grid-selector.cpp
  src/target/projection-path-calculator.cpp
  src/target/target-preparation.cpp
  src/view/display-map.cpp
Labels: refactor, Priority:MIDDLE

#5005 [Refactor] モンスターの移動方向のリスト管理
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/monster-floor/monster-direction.cpp
  src/monster-floor/monster-direction.h
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-move.h
  src/monster-floor/monster-movement-direction-list.cpp
  src/monster-floor/monster-movement-direction-list.h
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
  src/monster/monster-processor.cpp
Labels: refactor

#5002 Targetクラスを実装し、グローバル変数 target_who/target_row/target_col を廃止して代わりにTargetクラスを使用する その1
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/blue-magic/blue-magic-caster.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-io/cmd-floor.cpp
  src/mind/mind-force-trainer.cpp
  src/object-activation/activation-others.cpp
  src/realm/realm-trump.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-world.cpp
  src/target/target-setter.cpp
  src/target/target-setter.h
  src/target/target.cpp
  src/target/target.h
Labels: refactor

#5010 ターゲット座標のYとXが逆だったのを修正した
  src/spell-kind/spells-fetcher.cpp
  src/spell-realm/spells-crusade.cpp
Labels: bug, Priority:HIGH

#5012 [Release] 3.0.1.26-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#5007 Targetクラスを実装し、グローバル変数 target_who/target_row/target_col を廃止して代わりにTargetクラスを使用する その2
  src/combat/shoot.cpp
  src/core/game-play.cpp
  src/dungeon/dungeon-processor.cpp
  src/floor/geometry.h
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-remover.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster/monster-compaction.cpp
  src/object-use/throw-execution.cpp
  src/specific-object/death-crimson.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-launcher.cpp
  src/spell-kind/spells-polymorph.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-realm/spells-crusade.cpp
  src/target/target-checker.cpp
  src/target/target-checker.h
  src/target/target-getter.cpp
  src/target/target-setter.cpp
  src/view/display-map.cpp
  src/wizard/wizard-spells.cpp
Labels: refactor

#5008 in_bounds2() をFloorType のメソッドへ繰り込む準備 その2
  src/action/movement-execution.cpp
  src/combat/shoot.cpp
  src/core/player-processor.cpp
  src/effect/effect-feature.cpp
  src/effect/effect-item.cpp
  src/effect/effect-monster-util.cpp
  src/effect/effect-monster-util.h
  src/effect/effect-monster.cpp
  src/effect/effect-processor.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-events.cpp
  src/floor/floor-object.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/grid/object-placer.cpp
  src/grid/trap.cpp
  src/mind/mind-force-trainer.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-remover.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster/monster-processor.cpp
  src/monster/monster-status.cpp
  src/monster/monster-update.cpp
  src/mspell/specified-summon.cpp
  src/object-use/throw-execution.cpp
  src/pet/pet-fall-off.cpp
  src/player/player-move.cpp
  src/player/player-status.cpp
  src/realm/realm-hissatsu.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-grid.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-sight.cpp
  src/spell-kind/spells-teleport.cpp
  src/status/shape-changer.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/window/main-window-util.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#5015 マクロ定義周りのconcptr をstring に置き換えた
  src/io/interpret-pref-file.cpp
  src/util/string-processor.cpp
  src/util/string-processor.h
Labels: refactor, Priority:MIDDLE

#5016 [Fix] curses.hの内容をcurses名前空間に入れる
  src/main-gcu.cpp
Labels: refactor

#5017 string-processor.cpp に定義されていたマクロ関連グローバル変数をmacro-configurations-store.cpp/h に移した
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/autopick/autopick-inserter-killer.cpp
  src/cmd-io/cmd-macro.cpp
  src/io/input-key-acceptor.cpp
  src/io/interpret-pref-file.cpp
  src/io/macro-configurations-store.cpp
  src/io/macro-configurations-store.h
  src/main-win.cpp
  src/util/int-char-converter.h
  src/util/string-processor.cpp
  src/util/string-processor.h
Labels: refactor, Priority:MIDDLE

#5018 EnumRangeとRectangle2Dをrangeコンセプトに対応させる
  src/stdafx.h
  src/util/enum-range.h
  src/util/point-2d.h
Labels: enhancement

#5021 [Refactor] earthquake()
  src/spell-kind/earthquake.cpp
Labels: refactor

#5025 [Fix] {fmt}におけるSJISのダメ文字問題
  src/external-lib/include/fmt/base.h
Labels: enhancement

#5022 [Refactor] earthquake()のシグネチャ変更
  src/action/mutation-execution.cpp
  src/cmd-item/cmd-usestaff.cpp
  src/melee/melee-switcher.cpp
  src/mind/mind-berserker.cpp
  src/mind/mind-elementalist.cpp
  src/monster-attack/monster-attack-switcher.cpp
  src/object-activation/activation-others.cpp
  src/player-attack/player-attack.cpp
  src/realm/realm-hissatsu.cpp
  src/realm/realm-nature.cpp
  src/realm/realm-song.cpp
  src/spell-kind/blood-curse.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/earthquake.h
  src/spell-kind/spells-neighbor.cpp
  src/spell-kind/spells-random.cpp
  src/spell-realm/spells-trump.cpp
  src/spell/spells-summon.cpp
Labels: refactor

#5020 keymap_act の型をconcptr[][] からmap<KeymapMode, vector<unique_ptr<string>>> に変えてstring_make() / string_free() をなくした
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/autopick/autopick-editor-command.cpp
  src/autopick/autopick-inserter-killer.cpp
  src/cmd-io/cmd-macro.cpp
  src/game-option/keymap-directory-getter.cpp
  src/game-option/keymap-directory-getter.h
  src/io/input-key-requester.cpp
  src/io/input-key-requester.h
  src/io/interpret-pref-file.cpp
  src/io/macro-configurations-store.cpp
  src/io/macro-configurations-store.h
  src/main/game-data-initializer.cpp
  src/system/angband.h
  src/term/z-form.cpp
  src/term/z-term.cpp
  src/term/z-virt.cpp
  src/term/z-virt.h
Labels: refactor, Priority:MIDDLE

#5026 友好的/ペット の表記が、表示されていて欲しい場合と欲しくない場合で逆転していた不具合を修正した
  src/knowledge/knowledge-monsters.cpp
  src/target/target-describer.cpp
Labels: bug, Priority:MIDDLE

#5029 term関連関数の戻り値削除 その1
  src/cmd-io/cmd-process-screen.cpp
  src/core/asking-player.cpp
  src/io-dump/player-status-dump.cpp
  src/io/input-key-acceptor.cpp
  src/io/input-key-processor.cpp
  src/io/report.cpp
  src/main-x11.cpp
  src/main/sound-of-music.cpp
  src/main/sound-of-music.h
  src/player/player-damage.cpp
  src/store/store-key-processor.cpp
  src/term/gameterm.h
  src/term/screen-processor.cpp
  src/term/z-term.cpp
  src/term/z-term.h
Labels: refactor, Priority:MIDDLE

#5030 in_bounds2() をFloorType::contains() に置き換えた
  src/action/run-execution.cpp
  src/combat/shoot.cpp
  src/effect/effect-feature.cpp
  src/floor/cave.cpp
  src/floor/cave.h
  src/floor/floor-events.cpp
  src/floor/floor-streams.cpp
  src/grid/grid.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster/monster-processor.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-lite.cpp
  src/spell/range-calc.cpp
  src/window/display-sub-windows.cpp
Labels: refactor, Priority:MIDDLE

#5033 is_cave_empty_bold() をFloorTypeに繰り込む準備
  src/combat/shoot.cpp
  src/effect/effect-monster.cpp
  src/melee/melee-postprocess.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-force-trainer.cpp
  src/monster-floor/monster-generator.cpp
  src/realm/realm-hex.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/monster-entity.cpp
  src/system/monster-entity.h
Labels: refactor, Priority:MIDDLE

#5035 tgt_pt() のシグネチャ改善
  src/cmd-action/cmd-travel.cpp
  src/mind/mind-elementalist.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-hissatsu.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-kind/spells-teleport.h
  src/target/grid-selector.cpp
  src/target/grid-selector.h
  src/wizard/wizard-special-process.cpp
  src/wizard/wizard-spells.cpp
Labels: refactor, Priority:MIDDLE

#5038 is_cave_empty_bold() をFloorType のオブジェクトメソッドへ繰り込んだ
  src/combat/shoot.cpp
  src/floor/cave.cpp
  src/floor/cave.h
  src/floor/floor-leaver.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-force-trainer.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-generator.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/specified-summon.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-hissatsu.cpp
  src/specific-object/chest.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-fetcher.cpp
  src/wizard/wizard-spells.cpp
Labels: refactor, Priority:MIDDLE

#5041 [Feature] トラベルコマンドで施設を一覧から選択する機能
  src/target/grid-selector.cpp
Labels: enhancement

#5042 [Refactor] FloorType::o_list の型を変更
  src/action/open-close-execution.cpp
  src/action/open-util.cpp
  src/action/run-execution.cpp
  src/autopick/autopick.cpp
  src/cmd-action/cmd-open-close.cpp
  src/combat/shoot.cpp
  src/core/object-compressor.cpp
  src/effect/effect-item.cpp
  src/floor/fixed-map-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-events.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-object.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/floor/object-scanner.cpp
  src/grid/grid.cpp
  src/grid/object-placer.cpp
  src/inventory/floor-item-getter.cpp
  src/inventory/inventory-util.cpp
  src/inventory/item-getter.cpp
  src/inventory/player-inventory.cpp
  src/inventory/recharge-processor.cpp
  src/knowledge/knowledge-items.cpp
  src/load/floor-loader.cpp
  src/load/old/load-v1-5-0.cpp
  src/monster-attack/monster-eating.cpp
  src/monster-floor/monster-object.cpp
  src/monster/monster-compaction.cpp
  src/mspell/mspell-checker.cpp
  src/object/object-index-list.cpp
  src/object/object-info.cpp
  src/player-attack/attack-chaos-effect.cpp
  src/player/player-move.cpp
  src/player/player-status-flags.cpp
  src/player/player-status.cpp
  src/save/floor-writer.cpp
  src/specific-object/chest.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-polymorph.cpp
  src/spell/spells-status.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/target/target-describer.cpp
  src/target/target-preparation.cpp
  src/view/display-map.cpp
  src/window/display-sub-windows.cpp
Labels: refactor

#5049 [Fix] LOSでブレスがヒットしない
  src/spell/range-calc.cpp
Labels: bug

#5044 is_cave_empty_bold2() をFloorType::can_generate_monster_at() に繰り込んだ
  src/floor/cave.cpp
  src/floor/cave.h
  src/monster-floor/monster-generator.cpp
  src/monster-floor/special-death-switcher.cpp
  src/realm/realm-crusade.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
Labels: refactor, Priority:MIDDLE

#5051 [Chore] ビルドテストのGCCのバージョンを14にする
  .github/workflows/create-cache-for-ccache.yml
  .github/workflows/pull-request-status-check.yml
Labels: enhancement

#5046 [Refactor] FloorType::o_cnt,o_maxを廃止する
  src/core/object-compressor.cpp
  src/dungeon/dungeon-processor.cpp
  src/effect/effect-item.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-events.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/floor/floor-util.cpp
  src/inventory/player-inventory.cpp
  src/inventory/recharge-processor.cpp
  src/monster-floor/monster-object.cpp
  src/monster-floor/monster-remover.cpp
  src/save/floor-writer.cpp
  src/save/save.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-polymorph.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
Labels: refactor

#5052 cave_stop_disintegration() をFloorType::can_block_disintegration_at() に差し替えた
  src/effect/effect-processor.cpp
  src/floor/cave.cpp
  src/floor/cave.h
  src/mspell/mspell-judgement.cpp
  src/spell-realm/spells-crusade.cpp
  src/spell/range-calc.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/target/projection-path-calculator.cpp
Labels: refactor, Priority:MIDDLE

#5053 [Refactor] compact_objects()
  src/core/object-compressor.cpp
Labels: refactor

#5055 cave_los_bold() をFloorType のメソッドへ繰り込む準備
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/effect/effect-processor.cpp
  src/floor/floor-leaver.cpp
  src/melee/melee-spell-util.cpp
  src/mind/mind-mirror-master.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-object.cpp
  src/monster-floor/monster-runaway.cpp
  src/monster/monster-processor.cpp
  src/monster/monster-status-setter.cpp
  src/monster/monster-status.cpp
  src/monster/monster-update.cpp
  src/mspell/mspell-attack.cpp
  src/mspell/mspell-learn-checker.cpp
  src/mspell/mspell-lite.cpp
  src/mspell/mspell-lite.h
  src/object-activation/activation-others.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-sight.cpp
  src/system/enums/terrain/path-checker.h
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
Labels: refactor, Priority:MIDDLE

#5054 [Refactor] フロア全マスのループにFloorType::get_area()を使用する
  src/dungeon/quest-completion-checker.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-events.cpp
  src/floor/floor-generator.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-object.cpp
  src/floor/floor-util.cpp
  src/floor/object-allocator.cpp
  src/floor/wild.cpp
  src/grid/grid.cpp
  src/knowledge/knowledge-items.cpp
  src/mind/mind-mirror-master.cpp
  src/monster-floor/one-monster-placer.cpp
  src/save/floor-writer.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-grid.cpp
  src/spell-realm/spells-chaos.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/target/grid-selector.cpp
  src/util/point-2d.h
  src/wizard/cmd-wizard.cpp
  src/world/world-turn-processor.cpp
Labels: refactor
