Repository hengband/hengband, pull requests merged in 2025-01, with the labels that each got.

#4783 ダンジョン突入フラグが反対になっていたのを修正した
  src/system/services/dungeon-service.cpp
Labels: bug, Priority:MIDDLE

#4777 [Feature] デバッグコマンドでモンスターを選択しやすくする
  src/system/monrace/monrace-list.cpp
  src/wizard/wizard-spells.cpp
Labels: bug, enhancement

#4785 [Fix] 闘技場の地形が正しく生成されない
  src/floor/floor-generator.cpp
Labels: bug

#4786 [Release] 3.0.1.24-Bata
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#4766 cave_has_flag_bold() をFloorType::has_terrain_characteristics() へ繰り込んだ
  src/action/run-execution.cpp
  src/cmd-action/cmd-move.cpp
  src/cmd-building/cmd-building.cpp
  src/combat/shoot.cpp
  src/dungeon/quest-completion-checker.cpp
  src/dungeon/quest.cpp
  src/effect/effect-processor.cpp
  src/floor/cave.cpp
  src/floor/cave.h
  src/grid/feature-generator.cpp
  src/grid/feature.cpp
  src/mind/mind-elementalist.cpp
  src/monster-floor/monster-lite.cpp
  src/mspell/mspell-judgement.cpp
  src/object-activation/activation-bolt-ball.cpp
  src/object-use/throw-execution.cpp
  src/player-attack/player-attack.cpp
  src/realm/realm-hissatsu.cpp
  src/room/cave-filler.cpp
  src/room/treasure-deployment.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-neighbor.cpp
  src/spell-realm/spells-chaos.cpp
  src/spell-realm/spells-crusade.cpp
  src/spell/spells-status.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/target/projection-path-calculator.cpp
Labels: refactor, Priority:MIDDLE

#4791 [Feature] INIからのsavefile読込を拡張する
  src/main-win.cpp
Labels: enhancement

#4778 特殊なモンスター生成フィルタを個別のフィルタ関数に分割した
  src/floor/cave-generator.cpp
  src/floor/floor-generator.cpp
  src/floor/wild.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-summon.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/player/eldritch-horror.cpp
Labels: refactor, Priority:MIDDLE

#4793 get_monster_hook() を廃止した
  src/birth/inventory-initializer.cpp
  src/core/player-processor.cpp
  src/dungeon/quest.cpp
  src/monster-floor/one-monster-placer.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/object-enchant/others/apply-magic-others.cpp
  src/player/eldritch-horror.cpp
  src/room/rooms-special.cpp
  src/system/building-type-definition.cpp
  src/system/enums/monrace/monrace-hook-types.h
Labels: refactor, Priority:MIDDLE

#4794 function型の引数を取るget_mon_num_prep() を廃止した
  src/monster/monster-util.cpp
  src/monster/monster-util.h
  src/room/pit-nest-util.h
  src/room/rooms-nest.cpp
  src/room/rooms-pit.cpp
  src/system/enums/monrace/monrace-hook-types.h
Labels: refactor, Priority:MIDDLE

#4789 breath_shape() の引数を調整し、FloorType::has_terrain_characteristics() 周りの整形を行う準備をした
  src/effect/effect-processor.cpp
  src/mspell/mspell-judgement.cpp
  src/spell/range-calc.cpp
  src/spell/range-calc.h
Labels: refactor, Priority:MIDDLE

#4801 FloorType::has_terrain_characteristics() を呼び出している関数を整形した その2
  src/cmd-action/cmd-move.cpp
  src/cmd-building/cmd-building.cpp
  src/grid/feature-generator.cpp
  src/grid/feature.cpp
  src/market/building-service.cpp
  src/market/building-service.h
  src/mind/mind-elementalist.cpp
  src/room/cave-filler.cpp
  src/spell-kind/earthquake.cpp
Labels: refactor, Priority:MIDDLE

#4804 update_mon_lite() を整形した
  src/monster-floor/monster-lite-util.cpp
  src/monster-floor/monster-lite-util.h
  src/monster-floor/monster-lite.cpp
Labels: refactor, Priority:MIDDLE

#4807 FloorType::has_terrain_characteristics() を呼び出している関数を整形した その3
  src/action/run-execution.cpp
  src/combat/shoot.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/melee/melee-spell-util.cpp
  src/melee/melee-spell-util.h
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-judgement.h
  src/mspell/mspell-lite.cpp
  src/player-attack/player-attack.cpp
  src/spell-realm/spells-chaos.cpp
  src/target/projection-path-calculator.cpp
  src/target/projection-path-calculator.h
Labels: refactor, Priority:MIDDLE

#4808 モンスター生成フィルタ用のグローバル関数解体 その1 (B案)
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/monrace/monrace-allocation.cpp
  src/system/monrace/monrace-allocation.h
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/services/dungeon-monrace-service.cpp
  src/system/services/dungeon-monrace-service.h
Labels: refactor, Priority:MIDDLE

#4806 [Fix] 合体ユニークの倒した数の記録の扱いがあいまい
  src/monster/monster-damage.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/monrace/monrace-list.cpp
Labels: bug

#4810 ターゲッティングが正しく実行できない不具合を修正した
  src/target/projection-path-calculator.cpp
Labels: bug, Priority:HIGH

#4812 [Refactor] 死亡済みのユニークモンスターかどうかの判定
  src/dungeon/dungeon-processor.cpp
  src/dungeon/quest.cpp
  src/floor/object-allocator.cpp
  src/io-dump/character-dump.cpp
  src/knowledge/knowledge-monsters.cpp
  src/load/load-zangband.cpp
  src/lore/lore-util.cpp
  src/mspell/summon-checker.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/monrace/monrace-list.cpp
Labels: refactor

#4809 FloorType::has_terrain_characteristics() を呼び出している関数を整形した その4
  src/grid/feature-generator.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-judgement.h
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-realm/spells-crusade.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/item-entity.cpp
  src/system/item-entity.h
Labels: refactor, Priority:MIDDLE

#4816 [Fix] 荒野でダンジョンの主に関するメッセージが出てしまう
  src/dungeon/dungeon-processor.cpp
Labels: bug

#4814 English: skip article in tombstone explanation when hallucinating
  src/player/player-damage.cpp
Labels: bug, Priority:MIDDLE

#4817 モンスター生成フィルタ用のグローバル関数解体 その2
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
Labels: refactor, Priority:MIDDLE

#4818 [Feature] 分離先ユニークを単体で出現可能にする
  src/monster-floor/monster-remover.cpp
  src/monster/monster-list.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
Labels: enhancement

#4815 scatter() の引数と戻り値をPos2D に差し替えた
  src/dungeon/quest-completion-checker.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-util.cpp
  src/floor/floor-util.h
  src/mind/mind-elementalist.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-death-util.cpp
  src/monster-floor/monster-death-util.h
  src/monster-floor/monster-generator.cpp
  src/monster-floor/special-death-switcher.cpp
  src/mspell/specified-summon.cpp
  src/object-activation/activation-bolt-ball.cpp
  src/player/player-status.cpp
  src/realm/realm-crusade.cpp
  src/room/vault-builder.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-neighbor.cpp
  src/wizard/wizard-spells.cpp
Labels: refactor, Priority:MIDDLE

#4820 filter_monrace_hook2() を解体した
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
Labels: refactor, Priority:MIDDLE

#4819 FloorType::has_terrain_characteristics() を呼び出している関数を整形した その5
  src/object-use/throw-execution.cpp
  src/room/rooms-maze-vault.cpp
  src/room/rooms-vault.cpp
  src/room/treasure-deployment.cpp
  src/room/treasure-deployment.h
  src/util/point-2d.h
Labels: refactor, Priority:MIDDLE

#4826 [Fix] ランダムVault生成でクラッシュ
  src/room/rooms-vault.cpp
Labels: bug

#4829 自動拾い関係の引数からPlayerType を掃き出した
  src/autopick/autopick-editor-command.cpp
  src/autopick/autopick-reader-writer.cpp
  src/autopick/autopick-reader-writer.h
  src/autopick/autopick-registry.cpp
  src/cmd-io/cmd-autopick.cpp
  src/core/show-file.cpp
  src/util/angband-files.cpp
  src/util/angband-files.h
Labels: refactor, Priority:MIDDLE

#4830 [Refactor] fill_treasureの引数をRect2D型にする
  src/room/rooms-maze-vault.cpp
  src/room/rooms-vault.cpp
  src/room/treasure-deployment.cpp
  src/room/treasure-deployment.h
  src/util/point-2d.h
Labels: refactor

#4832 モンスター生成フィルタ用のグローバル関数解体 その4
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
Labels: refactor, Priority:MIDDLE

#4835 地形IDを動的に引く仕組みの構築 その9
  src/floor/object-allocator.cpp
  src/floor/wild.cpp
  src/grid/door.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-info-tokens-table.cpp
  src/info-reader/feature-reader.cpp
  src/room/rooms-vault.cpp
  src/system/enums/terrain/terrain-tag.h
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
Labels: refactor, Priority:MIDDLE

#4833 モンスター生成フィルタ用のグローバル関数解体 その5
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
Labels: refactor, Priority:MIDDLE

#4838 [Feature] 自動拾いエディタでのhome/endキーの挙動を一般的なものにする
  src/cmd-io/cmd-autopick.cpp
  src/cmd-visual/cmd-draw.cpp
  src/core/asking-player.cpp
  src/core/show-file.cpp
  src/io/input-key-acceptor.cpp
  src/io/input-key-acceptor.h
Labels: enhancement

#4839 モンスター生成フィルタ用のグローバル関数解体 その6
  src/autopick/autopick-destroyer.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-matcher.cpp
  src/cmd-item/cmd-eat.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/object-hook/hook-expendable.cpp
  src/system/item-entity.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
Labels: refactor, Priority:MIDDLE

#4840 地形IDを動的に引く仕組みの構築 その10
  src/effect/effect-feature.cpp
  src/floor/floor-streams.cpp
  src/floor/wild.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-info-tokens-table.cpp
  src/info-reader/feature-reader.cpp
  src/room/cave-filler.cpp
  src/room/rooms-vault.cpp
  src/system/enums/terrain/terrain-tag.h
Labels: refactor, Priority:MIDDLE

#4844 日付変更時に日替わり賞金首が確定できない不具合を修正した
  src/monster/monster-util.cpp
Labels: bug, Priority:Critical

#4841 川生成ルーチン周りをTerrainTag を使って改善した
  src/floor/floor-streams.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
Labels: refactor, Priority:MIDDLE

#4843 モンスター生成フィルタ用のグローバル関数解体 その7
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/room/pit-nest-util.h
  src/room/rooms-nest.cpp
  src/room/rooms-pit.cpp
  src/system/enums/monrace/monrace-hook-types.h
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
Labels: refactor, Priority:MIDDLE

#4849 [Refactor] distance()
  src/core/object-compressor.cpp
  src/dungeon/quest-monster-placer.cpp
  src/effect/effect-processor.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/floor/geometry.cpp
  src/floor/geometry.h
  src/floor/tunnel-generator.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-mirror-master.cpp
  src/monster-attack/monster-attack-player.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-lite.cpp
  src/mspell/mspell-selector.cpp
  src/object/warning.cpp
  src/realm/realm-hex.cpp
  src/realm/realm-hissatsu.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-vault.cpp
  src/room/treasure-deployment.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-detection.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-launcher.cpp
  src/spell-kind/spells-lite.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell-realm/spells-crusade.cpp
  src/spell/range-calc.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/target/target-setter.cpp
Labels: refactor

#4851 [Refactor] target_set_prepare()のシグネチャ変更
  src/target/target-preparation.cpp
  src/target/target-preparation.h
  src/target/target-setter.cpp
Labels: refactor

#4855 [Release] 3.0.1.25-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#4861 [Refactor] プレイ時間をElapsedTimeクラスで管理する
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/character-builder.cpp
  src/cmd-io/cmd-autopick.cpp
  src/cmd-visual/cmd-draw.cpp
  src/core/game-closer.cpp
  src/core/game-play.cpp
  src/dungeon/quest.cpp
  src/knowledge/knowledge-self.cpp
  src/load/extra-loader.cpp
  src/load/load.cpp
  src/monster-floor/monster-death.cpp
  src/save/player-writer.cpp
  src/save/save.cpp
  src/util/elapsed-time.cpp
  src/util/elapsed-time.h
  src/window/display-sub-windows.cpp
  src/world/world-movement-processor.cpp
  src/world/world.cpp
  src/world/world.h
Labels: bug, refactor

#4857 Nest 関係のモンスター生成フィルタをMonraceDefinition のオブジェクトメソッドに繰り込んだ
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-util.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
Labels: refactor, Priority:MIDDLE

#4863 地形IDを動的に引く仕組みの構築 その14
  src/floor/floor-changer.cpp
  src/floor/floor-leaver.cpp
  src/floor/pattern-walk.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/grid/grid.cpp
  src/grid/grid.h
  src/grid/trap.cpp
  src/grid/trap.h
  src/info-reader/feature-info-tokens-table.cpp
  src/info-reader/feature-reader.cpp
  src/load/old/load-v1-5-0.cpp
  src/player/player-status.cpp
  src/room/rooms-pit.cpp
  src/room/rooms-trap.cpp
  src/room/rooms-vault.cpp
  src/spell-kind/spells-grid.cpp
  src/system/enums/terrain/terrain-tag.h
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/system/terrain/terrain-list.cpp
  src/system/terrain/terrain-list.h
Labels: refactor, Priority:MIDDLE

#4859 [Refactor] ty_type を TargetSetter クラスにする
  src/target/target-setter.cpp
Labels: refactor

#4866 feat_door に関するタグ文字列をTerrainTag に変換した
  src/effect/effect-feature.cpp
  src/grid/door.cpp
  src/grid/door.h
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-info-tokens-table.cpp
  src/info-reader/feature-reader.cpp
  src/room/door-definition.cpp
  src/room/door-definition.h
  src/room/rooms-builder.cpp
  src/room/rooms-nest.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-pit.cpp
  src/room/rooms-special.cpp
  src/room/rooms-vault.cpp
  src/system/enums/terrain/terrain-tag.h
  src/system/grid-type-definition.cpp
Labels: refactor, Priority:MIDDLE

#4867 [Refactor] los()のシグネチャを変更
  src/effect/effect-monster-psi.cpp
  src/effect/effect-processor.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-util.cpp
  src/floor/line-of-sight.cpp
  src/floor/line-of-sight.h
  src/melee/melee-spell-flags-checker.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/quantum-effect.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-lite.cpp
  src/player/player-view.cpp
  src/spell-kind/spells-teleport.cpp
  src/spell/range-calc.cpp
  src/spell/range-calc.h
  src/spell/spells-summon.cpp
  src/target/target-setter.cpp
Labels: refactor

#4869 [Refactor] in_disintegration_range()のシグネチャを変更
  src/effect/effect-processor.cpp
  src/monster-floor/monster-direction.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-lite.cpp
  src/spell-realm/spells-crusade.cpp
  src/spell/range-calc.cpp
  src/spell/range-calc.h
Labels: refactor

#4870 DoorKind 周りのラップアップ
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/effect/effect-feature.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-generator.cpp
  src/grid/door.cpp
  src/grid/door.h
  src/grid/feature-generator.cpp
  src/grid/feature.h
  src/info-reader/dungeon-reader.cpp
  src/info-reader/feature-reader.cpp
  src/info-reader/general-parser.cpp
  src/load/old/load-v1-5-0.cpp
  src/room/door-definition.h
  src/room/rooms-builder.cpp
  src/room/rooms-nest.cpp
  src/room/rooms-normal.cpp
  src/room/rooms-pit.cpp
  src/room/rooms-special.cpp
  src/room/rooms-vault.cpp
  src/spell-class/spells-mirror-master.cpp
  src/spell-kind/spells-grid.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/enums/terrain/terrain-kind.h
  src/system/enums/terrain/terrain-tag.h
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/system/terrain/terrain-list.cpp
  src/system/terrain/terrain-list.h
Labels: refactor, Priority:MIDDLE

#4873 project()内での軌道保持方法のリファクタリング
  src/effect/effect-processor.cpp
  src/mspell/mspell-judgement.cpp
  src/spell/range-calc.cpp
  src/spell/range-calc.h
Labels: refactor

#4831 自動拾い関係のconcptr をstring に変えた
  src/autopick/autopick-drawer.cpp
  src/autopick/autopick-editor-command.cpp
  src/autopick/autopick-editor-util.cpp
  src/autopick/autopick-entry.cpp
  src/autopick/autopick-entry.h
  src/autopick/autopick-finder.cpp
  src/autopick/autopick-finder.h
  src/autopick/autopick-inserter-killer.cpp
  src/autopick/autopick-reader-writer.cpp
  src/autopick/autopick-reader-writer.h
  src/autopick/autopick-registry.cpp
  src/autopick/autopick-util.cpp
  src/autopick/autopick-util.h
  src/cmd-io/cmd-autopick.cpp
  src/knowledge/knowledge-autopick.cpp
Labels: refactor, Priority:LOW

#4872 monraces_info を絶滅させた
  src/main/info-initializer.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/room/pit-nest-util.cpp
  src/room/pit-nest-util.h
  src/room/rooms-nest.cpp
  src/room/rooms-pit.cpp
  src/system/monrace/monrace-list.cpp
  src/system/monrace/monrace-list.h
Labels: refactor, Priority:MIDDLE

#4878 [Fix] 自動拾いエディタの横スクロールの挙動がおかしい
  src/autopick/autopick-drawer.cpp
Labels: bug

#4879 [Refactor/Fix] 文字入力処理
  src/autopick/autopick-editor-command.cpp
  src/autopick/autopick-finder.cpp
  src/core/asking-player.cpp
  src/util/string-processor.cpp
  src/util/string-processor.h
Labels: bug, refactor

#4876 Doors クラスを作ってシングルトン化した
  src/effect/effect-feature.cpp
  src/grid/door.cpp
  src/grid/feature.cpp
  src/grid/feature.h
  src/info-reader/feature-reader.cpp
  src/room/door-definition.cpp
  src/room/door-definition.h
  src/room/room-generator.cpp
  src/room/rooms-normal.cpp
  src/system/grid-type-definition.cpp
Labels: refactor, Priority:MIDDLE

#4881 [Refactor] コピーされるべきでないクラスのコピーコンストラクタ/コピー代入演算子の削除
  src/info-reader/artifact-reader.cpp
  src/monster/monster-util.cpp
  src/object-enchant/object-ego.h
  src/system/artifact-type-definition.cpp
  src/system/artifact-type-definition.h
  src/system/baseitem/baseitem-definition.h
  src/system/monrace/monrace-definition.h
Labels: refactor

#4880 [Feature] 自動拾いエディタのカーソル上下の挙動を自然にする
  src/autopick/autopick-util.h
  src/cmd-io/cmd-autopick.cpp
Labels: enhancement

#4883 [Refactor] dist_to_line()のシグネチャ
  src/effect/effect-processor.cpp
  src/spell/range-calc.cpp
  src/spell/range-calc.h
Labels: refactor

#4877 ダンジョンごとに地形IDを差し替えていたグローバル変数をDungeonDefinition へ繰り込み、feature.cpp/h ファイルを廃止した
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/core/game-play.cpp
  src/dungeon/quest-completion-checker.cpp
  src/effect/effect-feature.cpp
  src/floor/cave-generator.cpp
  src/floor/floor-changer.cpp
  src/floor/floor-generator.cpp
  src/floor/pattern-walk.cpp
  src/floor/wild.cpp
  src/floor/wild.h
  src/grid/door.cpp
  src/grid/feature-generator.cpp
  src/grid/feature-generator.h
  src/grid/feature.cpp
  src/grid/feature.h
  src/grid/grid.cpp
  src/grid/grid.h
  src/info-reader/dungeon-reader.cpp
  src/player/player-status.cpp
  src/room/cave-filler.cpp
  src/room/rooms-city.cpp
  src/room/rooms-city.h
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-grid.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/dungeon/dungeon-list.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#4885 [Refactor] 床と壁の確率による選択
  src/info-reader/dungeon-reader.cpp
  src/system/dungeon/dungeon-definition.cpp
  src/system/dungeon/dungeon-definition.h
  src/system/dungeon/dungeon-list.cpp
Labels: refactor

#4888 Grid::get_feat_mimic() をget_terrain_id() に吸収合併した
  src/action/run-execution.cpp
  src/spell-kind/spells-floor.cpp
  src/system/floor/floor-info.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/target/target-describer.cpp
Labels: refactor, Priority:MIDDLE

#4886 [Feature] 分解のブレス/ボールの軌道の表示を自然にする
  src/effect/effect-processor.cpp
Labels: enhancement

#4889 モンスター生成フィルタを全てMonraceDefinition に繰り込み、monster-race-hook.cpp/h を廃止した
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  src/Makefile.am
  src/birth/inventory-initializer.cpp
  src/cmd-action/cmd-hissatsu.cpp
  src/core/player-processor.cpp
  src/dungeon/quest.cpp
  src/effect/effect-monster-charm.cpp
  src/effect/effect-monster-evil.cpp
  src/effect/effect-monster-switcher.cpp
  src/market/bounty.cpp
  src/melee/melee-postprocess.cpp
  src/melee/monster-attack-monster.cpp
  src/mind/mind-samurai.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-summon.cpp
  src/monster-race/monster-race-hook.cpp
  src/monster-race/monster-race-hook.h
  src/monster/monster-damage.cpp
  src/monster/monster-util.cpp
  src/mspell/summon-checker.cpp
  src/object-enchant/others/apply-magic-others.cpp
  src/player-attack/blood-sucking-processor.cpp
  src/player-attack/player-attack.cpp
  src/player/eldritch-horror.cpp
  src/player/patron.cpp
  src/player/player-status.cpp
  src/realm/realm-hissatsu.cpp
  src/room/pit-nest-util.cpp
  src/room/pit-nest-util.h
  src/room/rooms-nest.cpp
  src/room/rooms-pit.cpp
  src/room/rooms-special.cpp
  src/spell-kind/spells-detection.cpp
  src/spell/spells-diceroll.cpp
  src/spell/spells-diceroll.h
  src/system/building-type-definition.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/view/display-monster-status.cpp
  src/view/display-symbol.h
Labels: refactor, Priority:MIDDLE

#4890 in_bounds() の周辺コードを整備した その1
  src/core/player-processor.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/floor/floor-streams.cpp
  src/floor/floor-util.cpp
  src/floor/floor-util.h
  src/mind/mind-elementalist.cpp
  src/spell-kind/earthquake.cpp
  src/spell-kind/spells-floor.cpp
  src/spell-kind/spells-grid.cpp
  src/system/grid-type-definition.cpp
  src/system/grid-type-definition.h
  src/target/grid-selector.cpp
Labels: refactor, Priority:MIDDLE

#4887 drop_near() の引数をPos2D に変え、chance の引数をoptional に変えた
  src/artifact/fixed-art-generator.cpp
  src/cmd-action/cmd-open-close.cpp
  src/cmd-item/cmd-eat.cpp
  src/combat/shoot.cpp
  src/dungeon/quest-completion-checker.cpp
  src/effect/effect-monster.cpp
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/floor/geometry.cpp
  src/floor/geometry.h
  src/inventory/inventory-object.cpp
  src/inventory/pack-overflow.cpp
  src/mind/mind-chaos-warrior.cpp
  src/mind/mind-hobbit.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-object.cpp
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-safety-hiding.h
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
  src/monster-floor/special-death-switcher.cpp
  src/monster/monster-processor-util.h
  src/object-use/throw-execution.cpp
  src/realm/realm-nature.cpp
  src/specific-object/chest.cpp
  src/spell/spells-object.cpp
  src/spell/spells-status.cpp
  src/system/player-type-definition.cpp
  src/system/player-type-definition.h
  src/util/point-2d.h
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor, Priority:MIDDLE

#4893 sweep_ranged_attack_grid() の引数をPos2D に変え、戻り値をoptional<Pos2D> に変えた
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
Labels: refactor, Priority:MIDDLE

#4892 マルチバイト文字の入出力をchar\* からstring_view に変えた
  src/main-win.cpp
  src/main-win/graphics-win.cpp
  src/main-win/graphics-win.h
  src/main-win/main-win-bg.cpp
  src/main-win/main-win-exception.cpp
  src/main-win/main-win-music.cpp
  src/main-win/main-win-utils.h
  src/util/angband-files.cpp
Labels: refactor, Priority:MIDDLE

#4895 [Refactor] 距離nの座標のオフセット配列
  src/monster-floor/monster-dist-offsets.cpp
  src/monster-floor/monster-dist-offsets.h
  src/monster-floor/monster-safety-hiding.cpp
Labels: refactor

#4897 [Fix] メイン画面の種族表示がはみ出る
  src/window/main-window-left-frame.cpp
Labels: bug

#4898 [Fix] build_bubble_value() でクラッシュ
  src/room/rooms-vault.cpp
Labels: bug

#4896 [Fix] マクロ設定で空のファイル名を指定するとクラッシュ
  src/cmd-io/cmd-macro.cpp
Labels: bug

#4899 [Fix] 強力発動地震の杖の半径
  src/spell-kind/earthquake.cpp
Labels: bug

#4900 MonsterSweepGrid のメソッドからポインタ引数を掃き出した
  src/monster-floor/monster-sweep-grid.cpp
  src/monster-floor/monster-sweep-grid.h
  src/monster/monster-processor-util.cpp
  src/monster/monster-processor-util.h
Labels: refactor, Priority:MIDDLE

#4903 表示が崩れる不具合の修正
  src/main-win.cpp
Labels: bug, Priority:Critical
