Repository hengband/hengband, pull requests merged in 2025-09, with the labels that each got.

#5210 [Fix] 強撃武器を装備中にゲームが重くなる
  src/combat/attack-criticality.cpp
  src/combat/attack-criticality.h
  src/combat/shoot.cpp
Labels: bug, refactor

#5217 get_tag_floor() のサブルーチンをboolではなくoptional<short>を返すようにした
  src/autopick/autopick-entry.cpp
  src/floor/object-scanner.cpp
  src/floor/object-scanner.h
  src/inventory/floor-item-getter.cpp
  src/inventory/inventory-util.cpp
  src/inventory/inventory-util.h
  src/inventory/item-selection-util.h
  src/inventory/player-inventory.cpp
  src/io/input-key-requester.cpp
  src/target/grid-selector.cpp
  src/target/target-describer.cpp
  src/util/string-processor.cpp
  src/util/string-processor.h
Labels: refactor

#5220 get_rumor_num() をテンプレート化した
  src/store/rumor.cpp
Labels: refactor

#5206 (Interface)[Fix] zを充てられた青魔法が選択できずキャンセルになる。
  src/blue-magic/learnt-power-getter.cpp
  src/cmd-action/cmd-mane.cpp
  src/cmd-action/cmd-pet.cpp
  src/cmd-action/cmd-spell.cpp
  src/cmd-io/cmd-floor.cpp
  src/cmd-item/cmd-magiceat.cpp
  src/core/asking-player.cpp
  src/core/asking-player.h
  src/market/building-monster.cpp
  src/mind/mind-archer.cpp
  src/mind/mind-elementalist.cpp
  src/mind/mind-power-getter.cpp
  src/mind/mind-weaponsmith.cpp
  src/spell-realm/spells-hex.cpp
  src/target/target-getter.cpp
Labels: bug, enhancement

#5223 bolt_pict()の引数をPos2Dに変えた
  src/combat/shoot.cpp
  src/effect/effect-processor.cpp
  src/floor/geometry.cpp
  src/grid/grid.cpp
  src/grid/grid.h
  src/io/cursor.cpp
  src/io/screen-util.cpp
  src/io/screen-util.h
  src/mind/mind-mirror-master.cpp
  src/object-use/throw-execution.cpp
  src/spell-class/spells-mirror-master.cpp
  src/system/floor/floor-info.cpp
  src/system/floor/floor-info.h
  src/term/gameterm.cpp
  src/term/gameterm.h
  src/view/display-map.cpp
Labels: refactor

#5221 異常な死因に殺されないようにした
  src/player/player-damage.cpp
Labels: bug, refactor
