Repository hengband/hengband, pull requests merged in 2025-07, with the labels that each got.

#5180 [Add] ユニーク・モンスター「はらへりじじい」とモンスター「まわるポリゴン」を追加
  lib/edit/MonraceDefinitions.jsonc
  lib/edit/MonsterMessages.jsonc
  src/monster-attack/monster-attack-describer.cpp
  src/mspell/mspell-summon.cpp
  src/mspell/specified-summon.cpp
  src/mspell/specified-summon.h
  src/system/enums/monrace/monrace-id.h
Labels: enhancement

#5182 [Fix] 善良でも邪悪でもないモンスターに変身したカメレオンがその後二度と変身しない
  src/monster/monster-util.cpp
Labels: bug

#5096 Chameleons mimic at-death behavior not related to drops or is_explodable()
  src/monster-floor/monster-death-util.cpp
  src/monster-floor/monster-death-util.h
  src/monster-floor/one-monster-placer.cpp
  src/monster-floor/place-monster-types.h
  src/monster-floor/special-death-switcher.cpp
Labels: enhancement

#5185 [Refactor] MonsterMessage.jsoncの整理
  lib/edit/MonsterMessages.jsonc
Labels: refactor

#5188 jsoncファイルの整形ルールの統一とCIによるチェックの導入
  .github/scripts/check-cpp-format.sh
  .github/scripts/check-json-format.sh
  .github/workflows/pull-request-status-check.yml
  .prettierrc.yaml
  THIRD-PARTY-NOTICES.txt
  lib/edit/ArtifactDefinitions.jsonc
  lib/edit/BaseitemDefinitions.jsonc
  lib/edit/ClassMagicDefinitions.jsonc
  lib/edit/MonraceDefinitions.jsonc
  lib/edit/MonsterMessages.jsonc
  lib/edit/SpellDefinitions.jsonc
  src/Makefile.am
  src/external-lib/include-json.h
  src/external-lib/include/nlohmann/json.hpp
  src/main/info-initializer.cpp
Labels: enhancement

#5175 [Update] readme.md 更新 (WIP)
  readme.md
Labels: documentation
