Repository hengband/hengband, pull requests merged in 2025-06, with the labels that each got.

#5121 tl::optional および tl::expected の導入
  src/Makefile.am
  src/external-lib/include/tl/expected.hpp
  src/external-lib/include/tl/optional.hpp
  src/stdafx.h
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/monrace/monrace-message.cpp
  src/system/monrace/monrace-message.h
Labels: enhancement, refactor

#5123 [Refactor] monrace-message.cpp/h
  src/system/monrace/monrace-message.cpp
  src/system/monrace/monrace-message.h
Labels: refactor

#5124 [Feature] 外部ファイルからモンスターメッセージ読込処理の拡張
  VisualStudio/Hengband/Hengband.vcxproj
  VisualStudio/Hengband/Hengband.vcxproj.filters
  lib/edit/MonraceDefinitions.jsonc
  lib/edit/MonsterMessages.jsonc
  schema/MonsterMessages.schema.json
  src/Makefile.am
  src/info-reader/message-reader.cpp
  src/info-reader/message-reader.h
  src/io-dump/character-dump.cpp
  src/main/angband-headers.cpp
  src/main/angband-headers.h
  src/main/angband-initializer.cpp
  src/main/info-initializer.cpp
  src/main/info-initializer.h
  src/monster/monster-processor.cpp
  src/system/monrace/monrace-message.cpp
  src/system/monrace/monrace-message.h
Labels: enhancement

#5125 [Feature] monspeak関連txtの廃止
  lib/edit/MonsterMessages.jsonc
  lib/file/Makefile.am
  lib/file/mondeath.txt
  lib/file/mondeath_j.txt
  lib/file/monfear.txt
  lib/file/monfear_j.txt
  lib/file/monfrien.txt
  lib/file/monfrien_j.txt
  lib/file/monspeak.txt
  lib/file/monspeak_j.txt
  src/monster-floor/monster-move.cpp
  src/monster/monster-damage.cpp
Labels: enhancement

#5129 [Refactor] MonsterMessage::get_message_chance()を廃止
  src/effect/effect-processor.cpp
  src/monster-floor/monster-move.cpp
  src/monster/monster-damage.cpp
  src/monster/monster-processor.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
  src/system/monrace/monrace-message.cpp
  src/system/monrace/monrace-message.h
Labels: refactor

#5131 [Feature] `str_upcase_first()` の追加
  src/monster/monster-damage.cpp
  src/monster/monster-processor.cpp
  src/util/string-processor.cpp
  src/util/string-processor.h
Labels: enhancement, refactor

#5133 [Refactor] process_speak_sound()の整理
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-move.h
  src/monster/monster-processor.cpp
Labels: refactor

#5141 [Refactor] モンスター固有のブレスメッセージのJSON化
  lib/edit/MonraceDefinitions.jsonc
  schema/MonraceDefinitions.schema.json
  schema/MonsterMessages.schema.json
  src/info-reader/race-info-tokens-table.cpp
  src/monster-race/race-speak-flags.h
  src/mspell/mspell-attack/mspell-breath.cpp
Labels: refactor

#5148 Update hengband.spec for 3.0.1.28
  hengband.spec
Labels: release

#5107 Include libcurl's files in archives generated by 'make dist'
  Makefile.am
Labels: enhancement

#5149 [Refactor] ユニーク感知時のメッセージを外部読込化
  lib/edit/MonraceDefinitions.jsonc
  schema/MonraceDefinitions.schema.json
  schema/MonsterMessages.schema.json
  src/info-reader/race-info-tokens-table.cpp
  src/monster-race/race-speak-flags.h
  src/object-activation/activation-others.cpp
Labels: refactor

#5150 [Feature] モンスターの死亡時召喚をJSONで定義可能とする
  lib/edit/MonraceDefinitions.jsonc
  schema/MonraceDefinitions.schema.json
  src/info-reader/parse-error-types.h
  src/info-reader/race-reader.cpp
  src/system/monrace/monrace-definition.cpp
  src/system/monrace/monrace-definition.h
Labels: enhancement

#5152 [Fix] カメレオンの王が化けているユニークモンスターの名称表記
  src/monster/monster-describer.cpp
Labels: bug

#5154 [Feature] デバッグ召喚でカメレオンの変身先を指定する
  src/wizard/wizard-spells.cpp
  src/wizard/wizard-spells.h
Labels: enhancement

#5159 [Refactor] ベースアイテム生成の制約処理
  src/dungeon/quest-completion-checker.cpp
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/grid/object-placer.cpp
  src/grid/object-placer.h
  src/monster-floor/special-death-switcher.cpp
  src/room/rooms-special.cpp
  src/system/baseitem/baseitem-allocation.cpp
  src/system/baseitem/baseitem-allocation.h
  src/system/floor/floor-info.cpp
  src/system/system-variables.cpp
  src/system/system-variables.h
Labels: refactor

#5161 [Refactor] make_object()のシグネチャ
  src/dungeon/quest-completion-checker.cpp
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/grid/object-placer.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/special-death-switcher.cpp
  src/specific-object/chest.cpp
  src/spell-kind/spells-floor.cpp
  src/spell/spells-object.cpp
  src/system/item-entity.cpp
  src/system/item-entity.h
  src/wizard/wizard-item-modifier.cpp
Labels: bug, refactor

#5167 [Refactor] projectableのシグネチャから p_pos を削除
  src/blue-magic/blue-magic-caster.cpp
  src/cmd-action/cmd-mane.cpp
  src/effect/effect-player.cpp
  src/effect/effect-processor.cpp
  src/floor/floor-leaver.cpp
  src/floor/floor-object.cpp
  src/floor/floor-util.cpp
  src/floor/geometry.cpp
  src/grid/trap.cpp
  src/melee/melee-spell-flags-checker.cpp
  src/mind/mind-force-trainer.cpp
  src/mind/mind-mirror-master.cpp
  src/monster-floor/monster-direction.cpp
  src/monster-floor/monster-generator.cpp
  src/monster-floor/monster-move.cpp
  src/monster-floor/monster-runaway.cpp
  src/monster-floor/monster-safety-hiding.cpp
  src/monster-floor/monster-sweep-grid.cpp
  src/monster/monster-processor.cpp
  src/monster/monster-status-setter.cpp
  src/monster/monster-update.cpp
  src/mspell/mspell-checker.cpp
  src/mspell/mspell-judgement.cpp
  src/mspell/mspell-lite.cpp
  src/object-activation/activation-others.cpp
  src/object/warning.cpp
  src/realm/realm-hissatsu.cpp
  src/spell-kind/spells-fetcher.cpp
  src/spell-kind/spells-sight.cpp
  src/spell-kind/spells-world.cpp
  src/spell-realm/spells-chaos.cpp
  src/spell/range-calc.cpp
  src/spell/spells-summon.cpp
  src/target/projection-path-calculator.cpp
  src/target/projection-path-calculator.h
  src/target/target-preparation.cpp
  src/target/target-setter.cpp
Labels: refactor

#5169 [Fix] SPEAK_ALLの扱いを正常化
  lib/edit/MonsterMessages.jsonc
  src/system/monrace/monrace-message.cpp
Labels: bug

#5172 [Refactor] drop_near()から矢弾の破壊処理を分離
  src/artifact/fixed-art-generator.cpp
  src/cmd-item/cmd-eat.cpp
  src/combat/shoot.cpp
  src/dungeon/quest-completion-checker.cpp
  src/effect/effect-monster.cpp
  src/floor/floor-object.cpp
  src/floor/floor-object.h
  src/inventory/inventory-object.cpp
  src/inventory/pack-overflow.cpp
  src/mind/mind-chaos-warrior.cpp
  src/mind/mind-hobbit.cpp
  src/mind/mind-ninja.cpp
  src/monster-floor/monster-death.cpp
  src/monster-floor/monster-object.cpp
  src/monster-floor/special-death-switcher.cpp
  src/object-use/throw-execution.cpp
  src/object/object-broken.cpp
  src/realm/realm-nature.cpp
  src/specific-object/chest.cpp
  src/spell/spells-object.cpp
  src/spell/spells-status.cpp
  src/wizard/wizard-item-modifier.cpp
  src/wizard/wizard-special-process.cpp
Labels: refactor

#5173 [Refactor] アイテム消失処理の共通化
  src/floor/floor-object.cpp
Labels: refactor
