Repository hengband/hengband, pull requests merged in 2025-08, with the labels that each got.

#5193 [Fix] 繰り返しコマンドで床置きアイテムを壊した時の不具合
  src/floor/floor-object.cpp
  src/inventory/floor-item-getter.cpp
  src/system/floor/floor-info.h
Labels: bug

#5186 [Add] 水棲系モンスター投稿案４種を追加。以下の通りに調整。
  lib/edit/MonraceDefinitions.jsonc
Labels: enhancement

#5194 [Release] 3.0.1.29-Beta
  configure.ac
  doxygen/Hengband.doxyfile
  src/system/angband-version.h
Labels: release

#5198 [Fix] SPEAK_FIRENDの挙動の修正
  lib/edit/MonsterMessages.jsonc
Labels: bug
